- [vulkan-loader] fix clang-cl
conan-io/conan-center-index pull request #10007
Opened 2022-03-29 15:00 UTC by SSE4

closes: #9964

Specify library name and version:  **vulkan-loader/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-03-29 15:19 UTC, SpaceIm requested changes
You can remove /WX unconditionally.

2022-03-29 15:19 UTC, SpaceIm commented on recipes/vulkan-loader/all/conanfile.py
> +
```suggestion
```

2022-03-29 15:19 UTC, SpaceIm commented on recipes/vulkan-loader/all/conanfile.py
> +            tools.replace_in_file(os.path.join(self._source_subfolder, "CMakeLists.txt"), '/WX', '')
```suggestion
        # No warnings as errors
        tools.replace_in_file(os.path.join(self._source_subfolder, "CMakeLists.txt"), '/WX', '')
```

2022-03-29 15:23 UTC, SSE4 commented
> You can remove /WX unconditionally.

yes, it shouldn't break anyone

2022-03-29 15:27 UTC, SpaceIm commented
> > You can remove /WX unconditionally.
> 
> yes, it shouldn't break anyone

I would even say that it could avoid build errors of old vulkan-loader versions with recent msvc. `/WX` & `-Werror` should always be disabled/removed in conan-center recipes.

2022-03-30 07:40 UTC, AndreyMlashkin approved these changes

2022-03-30 10:45 UTC, SpaceIm approved these changes

2022-03-30 12:46 UTC, AndreyMlashkin approved these changes

2022-03-30 13:45 UTC, uilianries approved these changes

2022-04-01 15:07 UTC, uilianries approved these changes

2022-04-04 08:40 UTC, danimtb approved these changes

2022-04-04 08:44 UTC, merged