autoconf: fix test_package for compiler=msvc
conan-io/conan-center-index pull request #10368
Opened 2022-04-18 20:15 UTC by maksim-0

Specify library name and version:  **autoconf/any**

fixes #10366

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-04-18 21:13 UTC, Croydon requested changes
Increase the minimum Conan version to 1.45.0

2022-04-18 22:06 UTC, Croydon approved these changes

2022-04-19 08:43 UTC, ericLemanissier approved these changes

2022-04-19 10:29 UTC, uilianries approved these changes

2022-04-19 10:46 UTC, merged