systemc-cci: enable CMake builds
conan-io/conan-center-index pull request #10597
Opened 2022-05-03 13:31 UTC by staskau

Specify library name and version:  **systemc-cci/1.0.0**

Add CMakeLists.txt to enable cmake-based build, which among other things enables Windows build.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-05-07 09:26 UTC, madebr approved these changes

2022-05-07 09:26 UTC, madebr commented on recipes/systemc-cci/1.0.0/conanfile.py
> +        cmake.verbose = True
```suggestion
```

2022-06-10 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=10597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=10597) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: staskau<br/>:x: eyck<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=10597) it.</sub>

2022-06-15 07:29 UTC, uilianries commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +set(POSITION_INDEPENDENT_CODE ON)
```suggestion
```
It's automatically managed by fPIC option

2022-06-15 07:29 UTC, uilianries commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +project(cci)
```suggestion
project(systemc CXX)
```
enforce the language

2022-06-15 07:29 UTC, uilianries commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +conan_basic_setup()
```suggestion
conan_basic_setup(KEEP_RPATHS)
```
better compatibility on Mac

2022-06-15 07:29 UTC, uilianries commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +set_property(TARGET ${LIBRARY_NAME} PROPERTY POSITION_INDEPENDENT_CODE ON)
```suggestion
```
automatically managed by fPIC option in the recipe

2022-06-15 07:29 UTC, uilianries commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +  EXPORT ${PROJECT_NAME}Targets            # for downstream dependencies
```suggestion
```
do not generated cmake files, it should be provided by conan

2022-06-15 08:06 UTC, staskau commented on recipes/systemc-cci/1.0.0/CMakeLists.txt
> +conan_basic_setup()
Mac build is currently not supported

2022-06-17 09:15 UTC, uilianries requested changes
@staskau consider the follow PR as a fix and improvement. 

https://github.com/Minres/conan-center-index/pull/1

This recipe is outdated, so I updated some important parts.

2022-06-20 10:34 UTC, uilianries approved these changes

2022-06-20 20:32 UTC, prince-chrismc approved these changes

2022-06-20 20:43 UTC, merged