Add tllist
conan-io/conan-center-index pull request #10763
Opened 2022-05-12 16:16 UTC by danimtb

From #8588 and the changes proposed in the reviews of such PR (including https://github.com/aacebedo/conan-center-index/pull/1)

closes #8588

2022-05-12 16:51 UTC, SSE4 submitted a review, later dismissed

2022-05-12 20:55 UTC, SpaceIm requested changes

2022-05-12 20:55 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +required_conan_version = ">=1.43.0"
```suggestion
required_conan_version = ">=1.36.0"
```

2022-05-12 20:55 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +    def package_info(self):
```suggestion
    def package_info(self):
        self.cpp_info.set_property("pkg_config_name", "tllist")
```

2022-05-12 20:55 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +    def package_info(self):
https://codeberg.org/dnkl/tllist/src/tag/1.0.5/meson.build#L11-L16

2022-05-13 08:18 UTC, danimtb commented on recipes/tllist/all/conanfile.py
> +            raise ConanInvalidConfiguration("Only Linux supported")
```suggestion
```

2022-05-13 08:19 UTC, danimtb commented on recipes/tllist/all/conanfile.py
> +        self.cpp_info.includedirs.append(os.path.join("include"))
"include" is the default value, so this shouldn't be needed
```suggestion
        self.cpp_info.includedirs.append(os.path.join("include"))
```

2022-05-13 08:33 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +from conans.errors import ConanInvalidConfiguration
```suggestion
from conans import ConanFile, tools
```

2022-05-13 08:39 UTC, SpaceIm approved these changes

2022-05-17 15:46 UTC, danimtb commented on recipes/tllist/all/conanfile.py
> +
No idea why it fails on windows and I don't have the time to figure it out. It fails on the test_package side. As the original PR was restricting build different from Linux, I am ok restricting them now only for windows and adding a proper fix later.
```suggestion
    def validate(self):
        # FIXME: Fails in test_pacakge with the Windows configuration
        if self.settings.os == "Windows":
            raise ConanInvalidConfiguration("Windows not supported")

```

2022-05-17 15:47 UTC, danimtb commented on recipes/tllist/all/conanfile.py
> +    def validate(self):
```suggestion
        return "source_subfolder"

    def validate(self):
```

2022-05-17 15:51 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +            raise ConanInvalidConfiguration("Windows not supported")
only Visual Studio

2022-05-18 07:39 UTC, uilianries approved these changes

2022-05-18 12:13 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +from conan import ConanFile
what is the requirement in terms of conan version?

2022-05-18 14:20 UTC, danimtb commented on recipes/tllist/all/conanfile.py
> +required_conan_version = ">=1.36.0"
```suggestion
required_conan_version = ">=1.43.0"
```

2022-05-18 16:01 UTC, SpaceIm commented on recipes/tllist/all/conanfile.py
> +        # FIXME: Fails in test_pacakge with the Visual Studio compiler
```suggestion
        # tllist relies on __typeof__, not implemented in Visual Studio
```

2022-05-19 08:04 UTC, SpaceIm approved these changes

2022-05-19 08:54 UTC, uilianries approved these changes

2022-05-19 09:25 UTC, merged