Update conanfile.py
conan-io/conan-center-index pull request #10804
Opened 2022-05-15 20:03 UTC by gpbcom

### Enable the tests building from the Conan package

gRPC versions:  **from grpc/1.38.0 to grpc/1.45.2**

The testing components of the gRPC framework are not built by default (gRPC_BUILD_TESTS = False) and it is not possible to modify if from the Conan package. The option I added aims to make this parameter configurable.

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-05-15 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=10804) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=10804) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=10804) it.</sub>

2022-05-16 23:47 UTC, SpaceIm commented
`Update conanfile.py` is not very meaningful.

By design, conan-center recipes don't build test, and don't provide options to build test.

2022-05-17 07:15 UTC, gpbcom commented
> 

Why ? I don't understand the aim of not building the test and other packages manager do it

2022-05-17 08:53 UTC, SpaceIm commented
> Why ? I don't understand the aim of not building the test and other packages manager do it

https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-conancenter-does-not-build-and-execute-tests-in-recipes

2022-05-19 10:25 UTC, jgsogo requested changes
Yes, please. Do not add this `build_tests` option.


Conan v2 will provide some mechanism for opting-in to building (and running tests) based on [config file](https://docs.conan.io/en/latest/reference/config_files/global_conf.html#global-conf). I think there is no documentation specific to testing yet, probably you can get more information in the Conan repository (please link back, so we can also track it).

The rationale behind this is to move to _conf_ everything that shouldn't modify resulting binaries (like cpu_count, for example) and isolate recipes from this logic. Only things that modify the binaries should go into options.


Thanks!

2022-10-21 01:21 UTC, closed without merging