edlib: add version 1.2.7 and modernize
conan-io/conan-center-index pull request #10831
Opened 2022-05-17 16:29 UTC by toge

Specify library name and version:  **edlib/1.2.7**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-05-18 07:02 UTC, SpaceIm requested changes
`_create_cmake_module_alias_targets` is useless, imported target is namespaced in upstream config file, and nothing was done in `package_info()` with the file generated by this function anyway.

2022-05-18 07:02 UTC, SpaceIm commented on recipes/edlib/all/conanfile.py
>          self.cpp_info.names["pkg_config"] = "edlib-{}".format(tools.Version(self.version).major)
```suggestion
        self.cpp_info.set_property("cmake_file_name", "edlib")
        self.cpp_info.set_property("cmake_target_name", "edlib::edlib")
        self.cpp_info.set_property("pkg_config_name", "edlib-{}".format(tools.Version(self.version).major))
        self.cpp_info.names["pkg_config"] = "edlib-{}".format(tools.Version(self.version).major)
```

2022-05-18 07:02 UTC, SpaceIm commented on recipes/edlib/all/conanfile.py
> +required_conan_version = ">=1.33.0"
```suggestion
required_conan_version = ">=1.43.0"
```

2022-05-18 15:27 UTC, SpaceIm approved these changes

2022-05-27 16:08 UTC, SSE4 approved these changes

2022-05-28 04:05 UTC, merged