fix SyntaxWarning: "is not" with a literal
conan-io/conan-center-index pull request #10837
Opened 2022-05-18 09:49 UTC by sify21

Specify library name and version:  **diligent-core/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): Fix syntax warning in conan file.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-05-18 09:54 UTC, MartinDelille commented
Please add the recipe name in the title.

2022-05-18 09:55 UTC, MartinDelille requested changes
Please add the recipe name in the PR title

2022-05-18 10:33 UTC, ericLemanissier approved these changes

2022-05-20 08:10 UTC, AndreyMlashkin approved these changes

2022-05-23 07:28 UTC, uilianries approved these changes

2022-05-23 08:05 UTC, merged