qt - don't set QT_PLUGIN_PATH for buildenv, as package dir doesn't exist
conan-io/conan-center-index pull request #11626
Opened 2022-07-11 08:41 UTC by paulharris

Follow up to #11475 
I don't think we should be setting QT_PLUGIN_PATH for the buildenv,
as it points to a packaged folder that doesn't exist during the build.

2022-07-12 09:47 UTC, paulharris commented
> Changes not allowed in build 1:
> 
> ```
> [.github/workflows/linter-conan-v2.yml, linter/.pylintrc, recipes/qt/6.x.x/conanfile.py]
> ```
> 
> Split them in several pull requests if you are making changes in more than one folder..

What should I do?  I only changed one file ...

2022-07-23 12:43 UTC, paulharris commented
I'll rebase when #11853 has been merged.

2022-08-02 05:26 UTC, ericLemanissier approved these changes

2022-08-02 05:35 UTC, ericLemanissier requested changes
Actually, buildenv_info is used when building dependants of qt, not qt itself, so this path exists , and it can be usefull if any qt program is run during build.

2022-08-05 01:27 UTC, paulharris commented
Oh ok, well then I'll cancel this PR, thanks @ericLemanissier  !

2022-08-05 01:27 UTC, closed without merging