quill: add version 2.1.0
conan-io/conan-center-index pull request #11650
Opened 2022-07-12 15:50 UTC by toge

Specify library name and version:  **quill/2.1.0**

- add version 2.1.0
- remove versions 1.2.3, 1.3.3, 1.4.0, 1.7.0, 1.7.2
- remove if expression for removed versions
- update fmtlib version

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-07-13 13:37 UTC, jwillikers requested changes

2022-07-13 13:37 UTC, jwillikers commented on recipes/quill/all/conanfile.py
> +            # self.requires("fmt/8.1.1")
Should this comment be removed?

2022-07-13 15:47 UTC, toge commented on recipes/quill/all/conanfile.py
> +            # self.requires("fmt/8.1.1")
sorry I forgot to remove it.

2022-07-13 16:52 UTC, jwillikers approved these changes

2022-07-18 07:30 UTC, uilianries approved these changes

2022-07-18 08:20 UTC, ericLemanissier approved these changes

2022-07-18 08:42 UTC, merged