[boost] Revert scm.Version usage
conan-io/conan-center-index pull request #12131
Opened 2022-08-10 10:39 UTC by uilianries

Specify library name and version:  **boost/1.79.0**

- Remove `scm.Version` and use the legacy `conan.tools.Version`
- We will have a hotfix for Conan, but so far, that's the best move.

Related to https://github.com/conan-io/conan-center-index/pull/12119 (read all the discussion there)

/cc @lasote @jcar87

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-08-10 11:06 UTC, lasote commented
Why don't use the old Version model from `conans` even if the linter complains? or is the idea is upgrading with the new `patch` of Conan as soon as it arrives?

2022-08-10 11:07 UTC, jgsogo requested changes
Let's wait for `1.52` and backported changes to `1.50` and `1.51` to see exactly what should we use here.

2022-08-10 11:11 UTC, uilianries commented
I did a new homemade parse, it will be compatible and we can update in the future, after 1.52 or any other patch.

2022-08-10 11:18 UTC, uilianries commented
BTW libtiff also uses `scm.Version(version)[0]` to collect the major.

2022-08-10 12:51 UTC, jcar87 commented
The intended interface of `conan.tools.scm.Version` was to actually preserve the `major`, `minor`, `patch` properties as they were being already used. However, due to a bug this was not functional. The issue has been identified and patch releases will be issued for the `1.50` and `1.51` series, as well as in the upcoming `1.52.0`. 

This means that the changes as they were in https://github.com/conan-io/conan-center-index/pull/12024 would work as intended once the patched versions are released.

The risk of leaving the current state any longer (changes introduced in https://github.com/conan-io/conan-center-index/pull/12119) is that `as_list` was never intended to be an interface for this and will indeed be broken for the patched releases and `1.52.0`.

With the goal of avoiding any further disruption, I agree with the suggestion of going back to `conans.tools.Version()`: we know this is compatible with existing releases. If the linter is a concern, this morning we discussed the possibility of removing that specific check (`conans.tools.Version` -> `conan.tools.scm.Version`) until we are comfortable the situation is addressed.

2022-08-10 13:34 UTC, jgsogo commented
Don't worry about the linter. Once the CI is green we can do different things: remove the check, force the merge,... in any case, first we need here whatever we want to have. It will take the CI several hours to build all these versions. Maybe, during that time, all new versions have been released and we prefer to upgrade Conan and look to the future.

So, first, please, decide what lines we want here and let the CI work. And let's be clear as well about the source we want once `1.50.2` is released with the upcoming interface from `1.52.0`.

2022-08-10 13:42 UTC, jcar87 commented
`conans.tools.Version` as it was _before_ this PR was merged: https://github.com/conan-io/conan-center-index/pull/12024, as this would work in existing versions irrespective of `1.50.2` or `1.52.0` being released with the fix and we can decouple this from those patch releases.

The situation I'd like to avoid is `1.50.2` or `1.52.0` being released, and users downloading the _current_ revision of the recipe, as calling `.as_list` as it currently is will cease working (and was never intended to).

2022-08-10 14:02 UTC, jgsogo commented
This PR doesn't have those changes.

I'll deal with the linter, don't worry about it. Just be sure first that all the changes are prepared and ready to be merged in this or other PR. Maybe it is worth having a look at other recipes that might have the same issue and propose the same changes to them. This rule has been running for several weeks.

In any case, let's keep in mind that once 1.50.x is released and CCI is updated, the linter will recover the rule and these changes (or equivalent) will be introduced again... breaking whatever is broken right now one more time (TBH, I still don't know what the actual problem is here). Maybe this recipe just needs `required_conan_version = ">=1.47.0,<1.52"` and everyone will be happy forever?

2022-08-10 14:03 UTC, uilianries commented
Yes, users will be able to download and be broken as soon as 1.52 is available. That's why this PR is independent from any version so we can update it after having 1.52 or whatever running on CCI.

2022-08-11 05:27 UTC, SSE4 requested changes
need to discuss it first

2022-08-11 10:22 UTC, uilianries commented
@jgsogo @jcar87 @SSE4 I just reverted to use `conans.tools.Version` as previously. I also added a comment to update in the future.

2022-08-11 10:27 UTC, jgsogo approved these changes
Thanks! If CI is happy, we are happy too 😺

2022-08-11 11:47 UTC, SSE4 approved these changes

2022-08-11 12:25 UTC, jcar87 approved these changes

2022-08-12 09:22 UTC, merged