Point 4.10.0 to github/marcus/clipper-archive
conan-io/conan-center-index pull request #12291
Opened 2022-08-17 08:42 UTC by marcusl

Older versions are removed from Sourceforge's archive, so previous link is no longer valid

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [z] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-08-17 08:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=12291) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=12291) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=12291) it.</sub>

2022-08-17 09:02 UTC, marcusl commented
First time contributing, so I'm trying to figure out how to create/test. Will undraft once tested.

2022-08-17 11:08 UTC, jgsogo requested changes
We only get sources from official repositories. If those sources are now missing, we can upload them to our internal Artifactory, as we did with `gsoap` (https://github.com/conan-io/conan-center-index/blob/master/recipes/gsoap/all/conandata.yml)

2022-08-17 12:15 UTC, marcusl commented
If anyone is interested, the error I got when building 5.1.6 with `conan create . clipper/5.1.6@demo/testing` in recipes/clipper/all was:

```
clipper/5.1.6@demo/testing: Calling build()
WARN: patches/0001-include-install-directory-5.x.patch: file 1/1:        b'cpp/CMakeLists.txt'
WARN: patches/0001-include-install-directory-5.x.patch:  hunk no.1 doesn't match source file at line 11
WARN: patches/0001-include-install-directory-5.x.patch:   expected: b'# The header name clipper.hpp is too generic, so install in a subdirectory'
WARN: patches/0001-include-install-directory-5.x.patch:   actual  : b'SET(BUILD_SHARED_LIBS ON CACHE BOOL'
patches/0001-include-install-directory-5.x.patch: source file is different - b'cpp/CMakeLists.txt'
clipper/5.1.6@demo/testing:
clipper/5.1.6@demo/testing: ERROR: Package 'f26537b056c9ff213dcc2874372b233408a3e04e' build failed
clipper/5.1.6@demo/testing: WARN: Build folder C:\Users\marcu\.conan\data\clipper\5.1.6\demo\testing\build\f26537b056c9ff213dcc2874372b233408a3e04e
ERROR: clipper/5.1.6@demo/testing: Error in build() method, line 63
        tools.patch(**patch)
        ConanException: Failed to apply patch: patches/0001-include-install-directory-5.x.patch
```

2022-08-17 14:49 UTC, uilianries commented
@marcusl patch is incompatible. Usually, it's end-of-file: CRLF vs LF. Otherwise, the patch is really incompatible.

2022-08-17 14:52 UTC, marcusl commented
> @marcusl patch is incompatible. Usually, it's end-of-file: CRLF vs LF. Otherwise, the patch is really incompatible.

Yeah. I'm thinklng to skip that part as I didn't need it, so someone who needs 5.6.1 can find the right source that matches the patch or fix the patch or what not, since the original zip that worked for both 4.10.0 and 5.6.1 is lost (see the linked issue's discussion)

Anyway, I'm closing this as the zip file has been restored to sourceforge, but from my little archive repo. So I made some contribution at last. :)

2022-08-18 06:34 UTC, marcusl commented
Need to update the SHA256. Reopening.

2022-08-18 06:39 UTC, jgsogo commented
We will be adding new contributors in the following days and your PR will be triggered again 😸

2022-08-23 07:55 UTC, uilianries commented
Okay, now I remember it's totally related to https://github.com/conan-io/conan-center-index/issues/12064

2022-08-23 13:02 UTC, marcusl commented
It's just a sha change now.

2022-08-23 13:09 UTC, uilianries approved these changes

2022-08-24 15:21 UTC, prince-chrismc approved these changes

2022-08-29 10:42 UTC, marcusl commented
@jgsogo pokepoke! :)

2022-08-29 15:40 UTC, prince-chrismc commented
Can you please update the title so it matches the changes?

"clipper: update checksum sha256" or something similar please 🙏

2022-08-30 07:29 UTC, jgsogo approved these changes

2022-08-30 07:30 UTC, marcusl commented
@prince-chrismc It doesn't seem as if your approval counted?

2022-08-30 07:37 UTC, jgsogo commented
> @prince-chrismc It doesn't seem as if your approval counted?

It does count, but I was blocking the merge. If some member of the team requests changes in a PR, it is blocked regardless of other approvals or changes (this logic is managed by the bot that is performing the actual merges)

2022-08-30 08:23 UTC, marcusl commented
> > @prince-chrismc It doesn't seem as if your approval counted?
> 
> It does count, but I was blocking the merge. If some member of the team requests changes in a PR, it is blocked regardless of other approvals or changes (this logic is managed by the bot that is performing the actual merges)

I get that your changed-requested blockedf things. However, now it requires 3 approvals with write access, but github says there are only two, and @prince-chrismc 's marks are green as yours and @uilianries are.

2022-08-30 08:24 UTC, merged

2022-08-30 08:24 UTC, marcusl commented
Huh, now it passed. Yay. :)

2022-08-30 08:25 UTC, marcusl commented
Thanks guys! :)

2022-08-30 09:29 UTC, jgsogo commented
> > > @prince-chrismc It doesn't seem as if your approval counted?
> > 
> > 
> > It does count, but I was blocking the merge. If some member of the team requests changes in a PR, it is blocked regardless of other approvals or changes (this logic is managed by the bot that is performing the actual merges)
> 
> I get that your changed-requested blocked things. However, now it requires 3 approvals with write access, but github says there are only two, and @prince-chrismc 's marks are green as yours and @uilianries are.

(Just trying to explain the process)

The green/grey for the approvals are from Github and it depends on the permissions people have inside the Conan organization and this repo. We have also configured the repository to require 3 approvals with write access before merging a PR, but this is just to prevent ourselves from accidentally merging a PR manually. 

![image](https://user-images.githubusercontent.com/1406456/187401782-c33869b0-d600-43b3-836c-8403ce5beeda.png)


Our bot only takes into account what is written in this file (https://github.com/conan-io/conan-center-index/blob/master/.c3i/reviewers.yml), two approvals from people in that list are required, at least one of them from a team member. The bot has elevated permissions so it can merge PRs even if Github still says that "3 approvals with write permissions are required".

2022-08-30 11:50 UTC, marcusl commented
Ah. Got it. Thanks for the detailed explanation, and for conan in general. It's 100% awesomesauce! 🤩

2022-08-30 14:26 UTC, prince-chrismc commented
👋 doc writer here...

We have docs here https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#automatic-merges
An I am curious if you looked for them or just relied on GitHub status?

(trying to see what improvements i could make 🙏 )

2022-08-30 15:21 UTC, marcusl commented
I had not seen that. I scanned the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) as mentioned/linked in the issue template though. 

Maybe link to the review process doc from the guide or as a separate note in the issue template?

2022-08-31 03:46 UTC, prince-chrismc commented
Thanks! those are good suggestion 👍 
It's linked, it's the 3️⃣ but it't not clear enough... template sounds like a sure win

I appreciate the feedback!