[libhal] Add library to conan center index
conan-io/conan-center-index pull request #12389
Opened 2022-08-19 14:47 UTC by kammce

Specify library name and version:  **libhal/0.0.0**

New addition to ConanCenter.
I am the author of the project.
Will be the dependency of future libraries.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-08-19 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=12389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=12389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=12389) it.</sub>

2022-08-22 07:19 UTC, uilianries commented
@kammce thank you for your contribution, please, don't forget to sign the CLA on this PR and request your access on the issue #4. After that, the CI bot should run your recipe. In case of doubt of the review process, please, read https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md. For better recipe quality, you can use this guide: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md

2022-08-24 10:55 UTC, uilianries reviewed
@libhal consider https://github.com/libhal/conan-center-index/pull/1

2022-08-24 14:21 UTC, kammce commented
@uilianries I added myself to the #4 a while back. When can I expect access?

2022-08-24 14:22 UTC, kammce commented
> @libhal consider [libhal#1](https://github.com/libhal/conan-center-index/pull/1)

Thank you! I will!

2022-08-24 14:45 UTC, kammce commented
@uilianries when I run `conan create . --version=0.0.0` using conan I get:

```
ERROR: libhal/0.0.0: Error in validate() method, line 45
        if self.settings.compiler.get_safe("cppstd"):
        ConanException: 'self.settings' access in 'validate()' method is forbidden
```

Whats the correct way to get the settings for conan v2? 
My version is `Conan version 2.0.0-beta2`

2022-08-24 15:02 UTC, uilianries commented
@kammce You need to run conan 1.51.3

   pip install -U conan

or 

   pip install conan==1.51.3

2022-08-24 15:24 UTC, kammce commented
> @kammce You need to run conan 1.51.3
> 
> pip install -U conan
> 
> or
> 
> pip install conan==1.51.3

Oh yes, it works with 1.51.3, but I thought the point of preparing for 2.0 was such that 2.0 would work? Or should we ignore running this on conan 2.0 because it is still in beta?

2022-08-24 17:53 UTC, kammce commented
Anything else I need or am I just waiting on approval?

2022-08-25 07:17 UTC, uilianries commented
@kammce The idea is be compatible for both. To access self.settings in validate(), you should use `self.info.settings` same for options. More info: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-validate-method

2022-08-26 07:49 UTC, uilianries commented
> @uilianries self.info.settings doesn't work for me on Conan 1.51.3

Does not work how? It's supported since previous versions. Do you have a log? Anyway, you can keep `self.settings` only for now.

2022-08-26 14:26 UTC, kammce commented
@uilianries 

```
$ conan --version
Conan version 1.51.3
```

I get this error:

```
ERROR: libhal/0.0.0: Error in validate() method, line 41
        if self.info.settings.compiler.get_safe("cppstd"):
        AttributeError: 'NoneType' object has no attribute 'get_safe'
```
if I comment that section out I get this

```
ERROR: libhal/0.0.0: Error in validate() method, line 50
        version = str(self.info.settings.compiler.version)
        AttributeError: 'NoneType' object has no attribute 'version'
```

printing `self.info` results in `<conans.model.info.ConanInfo object at 0x102b43310>`

```
ERROR: libhal/0.0.0: Error in validate() method, line 41
        print(self.info.compiler)
        AttributeError: 'ConanInfo' object has no attribute 'compiler'
```

2022-08-29 11:35 UTC, uilianries commented
@kammce It's `self.settings.get_safe("compiler.cppstd")`

2022-08-29 17:01 UTC, uilianries approved these changes
LGTM!

2022-08-29 17:05 UTC, kammce commented
WOOT! Looks like I need two more reviewers? How do I get more reviewers?

2022-08-29 18:17 UTC, SpaceIm requested changes

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +            "msvc": "19.22",
```suggestion
            "msvc": "193",
```

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +                f"{self.name} {self.version} requires C++20, which your compiler ({compiler}-{version}) does not support")
```suggestion
        if minimum_version and lazy_lt_semver(version, minimum_version):
            raise ConanInvalidConfiguration(
                f"{self.name} {self.version} requires C++{self._min_cppstd}, which your compiler ({compiler}-{version}) does not support")
```

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +                f"{self.name} {self.version} requires C++20, which your compiler ({compiler}-{version}) does not support")
don't raise when you don't know the compiler.

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +
```suggestion
```

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +
```suggestion

    def source(self):
        get(self, **self.conan_data["sources"][self.version],
            destination=self.source_folder, strip_root=True)

```

source() here to understand the flow of execution when reading the recipe

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/conanfile.py
> +             "include"), src=os.path.join(self.source_folder, "include"))
```suggestion
             "include"), src=os.path.join(self.source_folder, "include"))
 
    def package_info(self):
        self.cpp_info.bindirs = []
        self.cpp_info.frameworkdirs = []
        self.cpp_info.libdirs = []
        self.cpp_info.resdirs = []
```

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1.)
```suggestion
cmake_minimum_required(VERSION 3.8)
```

2022-08-29 18:17 UTC, SpaceIm commented on recipes/libhal/all/test_v1_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1.)
```suggestion
cmake_minimum_required(VERSION 3.8)
```

2022-08-29 19:04 UTC, SpaceIm approved these changes

2022-08-29 21:02 UTC, prince-chrismc approved these changes

2022-08-29 21:04 UTC, merged