migrate inja to conan v2
conan-io/conan-center-index pull request #12754
Opened 2022-09-01 08:41 UTC by AndreyMlashkin

This conan v2 migration PR was generated by automatoc script version 10.
It uses simple find and replace technics. Feel free to extend it.

2022-09-02 06:09 UTC, jgsogo approved these changes

2022-09-03 06:29 UTC, prince-chrismc commented
Fixing the imports is a great first step but I would not exactly call this v2 migration new generators + test_package is really the bench mark... also the min conan version needs to be bumped to ~1.45 when the tools.files was added

2022-09-04 09:08 UTC, SpaceIm commented on recipes/inja/all/conanfile.py
> +from conan import ConanFile, tools
No, it's not recommended to import tools directly

2022-09-04 09:08 UTC, SpaceIm commented on recipes/inja/all/test_package/conanfile.py
> +        if not tools.build.cross_building(self, self.settings):
wrong signature

2022-09-04 09:08 UTC, SpaceIm commented on recipes/inja/all/conanfile.py
>  required_conan_version = ">=1.28.0"
wrong required_conan_version

2022-09-04 09:09 UTC, SpaceIm commented
Please read my review. Anyway I've submitted https://github.com/conan-io/conan-center-index/pull/12811. I don't trust this automated script, not reliable enough for the moment.

2022-09-09 22:34 UTC, prince-chrismc requested changes
Same as https://github.com/conan-io/conan-center-index/pull/12753#pullrequestreview-1093226611 🙏  which is what space wrote above

2022-09-12 13:42 UTC, uilianries commented
Closing as superseded by #12811

2022-09-12 13:42 UTC, closed without merging