migrate influxdb-cpp to conan v2
conan-io/conan-center-index pull request #12753
Opened 2022-09-01 08:41 UTC by AndreyMlashkin

This conan v2 migration PR was generated by automatoc script version 10.
It uses simple find and replace technics. Feel free to extend it.

2022-09-01 11:30 UTC, uilianries requested changes
Please, take into account the tools guidelines for your script

[docs.conan.io/en/latest/reference/conanfile/tools.html](https://docs.conan.io/en/latest/reference/conanfile/tools.html)

2022-09-02 16:34 UTC, intelligide submitted a review, later dismissed

2022-09-14 14:30 UTC, danimtb submitted a review, later dismissed

2022-09-20 08:20 UTC, danimtb commented on recipes/influxdb-cpp/all/conanfile.py
> +from conan import ConanFile, tools
```suggestion
from conan import ConanFile
from conan.tools.files import get
```

2022-09-20 08:22 UTC, danimtb commented on recipes/influxdb-cpp/all/test_package/conanfile.py
> +from conans import CMake
```suggestion
from conan import ConanFile
from conan.tools.build import cross_building
from conan.tools.cmake import CMake, CMakeToolchain
```

2022-09-20 08:23 UTC, danimtb commented on recipes/influxdb-cpp/all/test_package/conanfile.py
> +        if not tools.build.cross_building(self, self.settings):
```suggestion
        if not cross_building(self, self.settings):
```

2022-09-26 09:15 UTC, uilianries commented on recipes/influxdb-cpp/all/test_package/conanfile.py
>  import os
The test package is mixing V1 with V2, also, self.setting should not be passed to cross_building anymore.

2022-11-28 02:20 UTC, closed without merging