Contribute biflags
conan-io/conan-center-index pull request #12986
Opened 2022-09-17 14:10 UTC by robomics

Specify library name and version:  **bitflags/1.5.0**

Contribute recipe for [m-peko/bitflags](https://github.com/m-peko/bitflags), a header-only library for easily managing set of auto-generated type-safe flags.

I am not the author of this library, but some of my projects depend on it.
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-09-17 15:47 UTC, SpaceIm requested changes

2022-09-17 15:47 UTC, SpaceIm commented on recipes/bitflags/all/conanfile.py
> +        self.cpp_info.names["cmake_find_package_multi"] = "bitflags"
```suggestion
```

not needed

2022-09-17 15:47 UTC, SpaceIm commented on recipes/bitflags/all/conanfile.py
> +
```suggestion
```

2022-09-17 15:47 UTC, SpaceIm commented on recipes/bitflags/all/conanfile.py
> +
```suggestion

    def package_id(self):
        self.info.clear()

```

2022-09-17 15:47 UTC, SpaceIm commented on recipes/bitflags/all/conanfile.py
> +                raise ConanInvalidConfiguration(f"{self.name} requires a compiler that supports C++{self._minimum_cpp_standard}. {self.settings.compiler}, {self.settings.compiler.version}")
```suggestion
                raise ConanInvalidConfiguration(f"{self.ref} requires a compiler that supports C++{self._minimum_cpp_standard}.)
```

2022-09-17 15:47 UTC, SpaceIm commented on recipes/bitflags/all/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "bitflags::bitflags")
```suggestion
        self.cpp_info.set_property("cmake_target_name", "bitflags::bitflags")
        self.cpp_info.bindirs = []
        self.cpp_info.libdirs = []
        self.cpp_info.resdirs = []
```

2022-09-17 17:05 UTC, SpaceIm approved these changes

2022-09-17 18:32 UTC, toge approved these changes

2022-09-19 10:29 UTC, uilianries approved these changes
LGTM

2022-09-19 10:45 UTC, merged