[libuuid] Cross support for Conan v1 and v2
conan-io/conan-center-index pull request #13155
Opened 2022-09-26 10:56 UTC by uilianries

Specify library name and version:  **libuuid/1.0.3**

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-09-26 14:01 UTC, jwillikers requested changes

2022-09-26 14:29 UTC, uilianries commented on recipes/libuuid/all/conanfile.py
> +        autotools.make
Yes, but, still it's duplicated with https://github.com/conan-io/conan-center-index/pull/13130 I gonna close this PR.

2022-09-26 14:29 UTC, uilianries commented on recipes/libuuid/all/test_package/CMakeLists.txt
>  cmake_minimum_required(VERSION 3.1)
Good catch, 3.8 is the correct one.

2022-09-26 14:29 UTC, uilianries commented
Duplicated with https://github.com/conan-io/conan-center-index/pull/13130

2022-09-26 14:29 UTC, closed without merging

2022-09-30 08:47 UTC, michalwidera commented
dup has commited. Can we resolve this?