nspr: generate gcc11 binaries
conan-io/conan-center-index pull request #13202
Opened 2022-09-28 16:28 UTC by ericLemanissier

Specify library name and version:  **nspr/***

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-09-28 16:46 UTC, jwillikers approved these changes

2022-09-28 17:20 UTC, ericLemanissier commented
Blocked by
- https://github.com/conan-io/conan-center-index/pull/13199

2022-09-29 14:53 UTC, ericLemanissier commented
blocks:
- https://github.com/conan-io/conan-center-index/pull/13106

2022-09-29 16:33 UTC, jwillikers approved these changes

2022-09-29 17:32 UTC, jwillikers requested changes
Should probably fix the Conan hooks and link to `rt` as necessary.

2022-09-29 18:41 UTC, jwillikers submitted a review, later dismissed

2022-09-30 13:22 UTC, uilianries commented on recipes/nspr/all/conanfile.py
> +required_conan_version = ">=1.52.0"
```suggestion
required_conan_version = ">=1.47.0"
```
Version() does not use .major or .minor here, so 1.47.0 is enough

2022-09-30 13:43 UTC, jwillikers approved these changes

2022-09-30 15:27 UTC, prince-chrismc approved these changes

2022-09-30 16:04 UTC, merged