docs: explain why no pdb is useful
conan-io/conan-center-index pull request #13209
Opened 2022-09-29 09:22 UTC by prince-chrismc

This was Diego answer to me which made a lot of sense

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-09-29 20:46 UTC, jwillikers requested changes

2022-09-29 20:46 UTC, jwillikers commented on docs/faqs.md
> +No. The PDBs are only needed to debug dependency code. By providing the libraries you are able to link and build you application and debug your own code.
Minor typo.

```suggestion
No. The PDBs are only needed to debug dependency code. By providing the libraries you are able to link and build your application and debug your own code.
```

2022-09-29 20:46 UTC, jwillikers commented on docs/faqs.md
> +### Doesn't this make debug build useless?
Slightly correct the grammar here.

```suggestion
### Doesn't this make debug builds useless?
```

2022-09-29 20:46 UTC, jwillikers commented on docs/faqs.md
> +difficult to understand [linter errors](v2_linter.md), please, comment on your pull request about, then the community will help you.
```suggestion
difficult to understand [linter errors](v2_linter.md), please comment on your pull request about the problem to receive help from the community.
```

2022-10-01 19:19 UTC, jwillikers approved these changes

2022-10-01 20:09 UTC, jwillikers approved these changes

2022-10-03 01:26 UTC, toge approved these changes

2022-10-03 13:41 UTC, uilianries approved these changes
LGTM

2022-10-03 13:46 UTC, merged