c-ares: fix cross building on mac os
conan-io/conan-center-index pull request #13227
Opened 2022-09-30 07:32 UTC by vvarma

Specify library name and version:  **c-ares/1.18.1**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

Support for cross-building on Mac OS was broken recently, adding back the relevant bit to support the same.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-09-30 12:47 UTC, jwillikers approved these changes

2022-09-30 14:31 UTC, uilianries commented
@vvarma Is there an issue link related or do you have an error log which is able to show your error without that fix?

2022-09-30 15:17 UTC, SpaceIm commented on recipes/c-ares/all/conanfile.py
> +        tc.blocks["rpath"].skip_rpath=True
No, don't do that. It makes shared lib non-relocatable. I can cross-build c-ares on macOS, please open an issue.

2022-09-30 16:53 UTC, uilianries requested changes
Waiting for comments, avoid using block.rpath

2022-10-13 02:38 UTC, vvarma commented
@SpaceIm @uilianries Apologies for the delay, i created [this issue ](https://github.com/conan-io/conan-center-index/issues/13251) capturing the issue i face

2022-10-17 10:00 UTC, uilianries commented
I think it deserves a question to https://github.com/conan-io/conan, as this approach is not good and this case is very particular.

2022-10-17 10:19 UTC, SpaceIm commented
yes, this fix shouldn't be accepted. The root cause is likely different.

2022-10-20 07:03 UTC, closed without merging