restinio: update to conan v2
conan-io/conan-center-index pull request #13338
Opened 2022-10-06 22:42 UTC by prince-chrismc

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-07 00:03 UTC, prince-chrismc commented
2.0 pipeline is failing for a few reasons https://github.com/conan-io/docs/pull/2778#issuecomment-1270854860

2022-10-07 07:55 UTC, uilianries reviewed
Doing good, only small points

2022-10-07 07:55 UTC, uilianries commented on recipes/restinio/all/conanfile.py
>      def package_id(self):
could please rearrange methods order? There is a good order here: https://docs.conan.io/en/latest/reference/commands/creator/create.html#methods-execution-order

2022-10-07 14:50 UTC, prince-chrismc commented on recipes/restinio/all/conanfile.py
> +required_conan_version = ">=1.50.0"
https://github.com/conan-io/conan-center-index/blob/master/docs/v2_linter.md#import-tools-from-conan

it was check_min_cppstd that I used

2022-10-07 14:52 UTC, prince-chrismc commented on recipes/restinio/all/conanfile.py
>              "Visual Studio": "15"
Are the docs wrong? https://docs.conan.io/en/2.0/reference/tools/microsoft/helpers.html#check-min-vs

2022-10-07 14:54 UTC, prince-chrismc commented on recipes/restinio/all/conanfile.py
>      def package_info(self):
https://docs.conan.io/en/latest/reference/conanfile/tools/layout.html?highlight=build

Hmm 🤔 good catch

2022-10-07 14:55 UTC, jwillikers commented on recipes/restinio/all/conanfile.py
> +required_conan_version = ">=1.50.0"
`self.info.clear()` also requires `1.50.0`.

2022-10-07 14:56 UTC, jwillikers commented on recipes/restinio/all/conanfile.py
> +required_conan_version = ">=1.50.0"
I think `self.info.` used in the validate method requires `1.51.0`, right?

2022-10-07 14:58 UTC, jwillikers requested changes

2022-10-07 14:58 UTC, jwillikers commented on recipes/restinio/all/conanfile.py
> +        if self.settings.get_safe("compiler.cppstd"):
```suggestion
        if self.info.settings.get_safe("compiler.cppstd"):
```

2022-10-07 16:35 UTC, jwillikers commented on recipes/restinio/all/conanfile.py
>              "Visual Studio": "15"
You have to check the v1 docs: https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#check-min-vs

2022-10-07 18:39 UTC, prince-chrismc commented on recipes/restinio/all/conanfile.py
>              "Visual Studio": "15"
I did not know they existed 🙃 https://docs.conan.io/en/latest/reference.html?highlight=microsoft

2022-10-07 18:48 UTC, jwillikers commented on recipes/restinio/all/conanfile.py
>              "Visual Studio": "15"
They are kind of buried in there...

2022-10-07 19:11 UTC, jwillikers approved these changes

2022-10-10 07:26 UTC, uilianries commented on recipes/restinio/all/conanfile.py
> +required_conan_version = ">=1.50.0"
self.info is much older. but if need to use get_safe, it will require 1.51.1: https://docs.conan.io/en/latest/changelog.html#id63

2022-10-10 07:27 UTC, uilianries approved these changes
LGTM

2022-10-10 08:05 UTC, merged