ffmpeg: add version 4.4.3
conan-io/conan-center-index pull request #13387
Opened 2022-10-10 07:30 UTC by kambala-decapitator

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

Tested locally:
- macOS Intel (native)
- iOS arm64 (cross) with `with_libx264` and `avdevice` off as they result in build error

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-10 07:47 UTC, kambala-decapitator commented
I see there's #13235 for v2 changes. Or should I still fix v2 linter errors in this PR?

2022-10-10 09:23 UTC, MartinDelille commented
> I see there's https://github.com/conan-io/conan-center-index/pull/13235 for v2 changes. Or should I still fix v2 linter errors in this PR?

No

2022-10-12 02:31 UTC, jwillikers requested changes

2022-10-12 02:31 UTC, jwillikers commented on recipes/ffmpeg/all/conanfile.py
> +            if Version(self.version) >= "5.0" and tools.is_apple_os(self.settings.os):
```suggestion
            if Version(self.version) >= "5.0" and is_apple_os(self):
```

2022-10-12 02:31 UTC, jwillikers commented on recipes/ffmpeg/all/conanfile.py
> +from conan.tools.build import cross_building
```suggestion
from conan.tools.apple import is_apple_os
from conan.tools.build import cross_building
```

2022-10-12 11:14 UTC, jwillikers approved these changes

2022-10-12 22:41 UTC, prince-chrismc approved these changes

2022-10-13 16:45 UTC, merged