docs: add a copy of the CLA for new contributors
conan-io/conan-center-index pull request #13405
Opened 2022-10-10 22:19 UTC by prince-chrismc

https://gist.githubusercontent.com/lasote/317ecbdfc8e011cc8a24c3d6cf40051f/raw/2b34f09dcb4e790ae8f5367aa7bb173b3fba70eb/conan-center-index_CLA.md is the source that's being used by cla-assistant.io to fill the web page

Docs!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-10 22:37 UTC, memsharded approved these changes

2022-10-11 09:42 UTC, uilianries submitted a review, later dismissed
LGTM

2022-10-11 11:02 UTC, toge approved these changes

2022-10-11 17:39 UTC, jwillikers requested changes

2022-10-11 17:39 UTC, jwillikers commented on CONTRIBUTING.md
> +3. Get setup by following [Developing Recipes](docs/developing_recipes_locally.md) guide and learn the basic commands.
```suggestion
3. Get setup by following the [Developing Recipes](docs/developing_recipes_locally.md) guide and learn the basic commands.
```

2022-10-11 17:39 UTC, jwillikers commented on CONTRIBUTING.md
> +2. Make sure to [request access](docs/how_to_add_packages.md#request-access) and be aware there is a [CLA](docs/CONTRIBUTOR_LICENSE_AGREEMENT.md)
```suggestion
2. Make sure to [request access](docs/how_to_add_packages.md#request-access) and be aware there is a [CLA](docs/CONTRIBUTOR_LICENSE_AGREEMENT.md).
```

2022-10-11 17:39 UTC, jwillikers commented on CONTRIBUTING.md
> +4. Check the [How To Add Packages](docs/how_to_add_packages.md) for the break down ConanCenterIndex specific conventions and practices.
```suggestion
4. Check the [How To Add Packages](docs/how_to_add_packages.md) page for the break down of ConanCenterIndex specific conventions and practices.
```

2022-10-11 17:39 UTC, jwillikers commented on docs/how_to_add_packages.md
> +When submitting a pull request for the first time you will be promted to sign the [CLA](CONTRIBUTOR_LICENSE_AGREEMENT.md) for your code contributions.
```suggestion
When submitting a pull request for the first time, you will be prompted to sign the [CLA](CONTRIBUTOR_LICENSE_AGREEMENT.md) for your code contributions.
```

2022-10-11 19:08 UTC, jwillikers approved these changes

2022-10-14 07:39 UTC, uilianries approved these changes

2022-10-14 09:04 UTC, merged