[freetype] update toolchain and add layout
conan-io/conan-center-index pull request #13451
Opened 2022-10-13 08:10 UTC by planetmarshall

Specify library name and version:  **freetype/1.0**

* Update to new toolchain
* Add layout method

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-14 13:29 UTC, jwillikers requested changes

2022-10-14 13:29 UTC, jwillikers commented on recipes/freetype/all/conanfile.py
> +        replace_in_file(self,freetype_config, r"export LC_ALL", textwrap.dedent("""\
Just need to add a space between the first and second arguments here.

2022-10-14 13:29 UTC, jwillikers commented on recipes/freetype/all/test_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} freetype)
```suggestion
target_link_libraries(${PROJECT_NAME} PRIVATE freetype)
```

2022-10-14 13:29 UTC, jwillikers commented on recipes/freetype/all/test_v1_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} Freetype::Freetype)
```suggestion
target_link_libraries(${PROJECT_NAME} PRIVATE Freetype::Freetype)
```

2022-10-14 13:29 UTC, jwillikers commented on recipes/freetype/all/test_package/conanfile.py
> +            self.run("{} {}".format(bin_path, font_path), env="conanrun")
```suggestion
            self.run(f"{bin_path} {font_path}", env="conanrun")
```

2022-10-15 12:52 UTC, jwillikers approved these changes

2022-10-17 10:33 UTC, uilianries approved these changes

2022-10-17 11:04 UTC, merged

2022-10-17 21:51 UTC, prince-chrismc commented on recipes/freetype/all/conanfile.py
> +        basic_layout(self, src_folder="src")
This should be using hte `cmake_layout`

2022-10-17 21:57 UTC, prince-chrismc commented on recipes/freetype/all/conanfile.py
> +        basic_layout(self, src_folder="src")
https://github.com/conan-io/conan-center-index/pull/13557