jxrlib: conan v2 support
conan-io/conan-center-index pull request #13525
Opened 2022-10-16 17:35 UTC by SpaceIm

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-17 12:05 UTC, jwillikers requested changes

2022-10-17 12:05 UTC, jwillikers commented on recipes/jxrlib/all/conanfile.py
> +        if is_msvc(self) and self.options.shared:
Is it possible to use `self.info.options.shared` here?

```suggestion
        if is_msvc(self) and self.info.options.shared:
```

2022-10-17 12:11 UTC, jwillikers approved these changes

2022-10-17 15:21 UTC, uilianries approved these changes

2022-10-17 20:11 UTC, prince-chrismc commented
V2 pipeline is not passing 

Error running command `conan graph info --requires jxrlib/cci.20170615@#a23c9807b12818ff7a73fae89e58ce6a -f json  -pr:h /home/conan/w/prod-v2_cci_PR-13525/4/56f4d13e-dfb8-45e9-8631-ed5e0ac70f4a/profile_linux_11_libstdcpp11_gcc_release_64.-shared-False.txt -pr:b /home/conan/w/prod-v2_cci_PR-13525/4/56f4d13e-dfb8-45e9-8631-ed5e0ac70f4a/profile_linux_11_libstdcpp11_gcc_release_64.-shared-False.txt`:
   ```
   -------- Input profiles --------
   Profile host:
   [settings]
   arch=x86_64
   build_type=Release
   compiler=gcc
   compiler.libcxx=libstdc++11
   compiler.version=11
   os=Linux
   [options]
   */*:shared=False
   
   Profile build:
   [settings]
   arch=x86_64
   build_type=Release
   compiler=gcc
   compiler.libcxx=libstdc++11
   compiler.version=11
   os=Linux
   [options]
   */*:shared=False
   
   
   -------- Computing dependency graph --------
   Graph root
       virtual
   Requirements
       jxrlib/cci.20170615#a23c9807b12818ff7a73fae89e58ce6a - Cache
   
   -------- Computing necessary packages --------
   ERROR: jxrlib/cci.20170615: Error in validate() method, line 56
   	if is_msvc(self) and self.info.options.shared:
   	ConanException: 'self.settings' access in 'validate()' method is forbidden
   ```

2022-10-17 20:14 UTC, prince-chrismc approved these changes

2022-10-17 20:37 UTC, SpaceIm commented
> V2 pipeline is not passing
> 
> Error running command `conan graph info --requires jxrlib/cci.20170615@#a23c9807b12818ff7a73fae89e58ce6a -f json -pr:h /home/conan/w/prod-v2_cci_PR-13525/4/56f4d13e-dfb8-45e9-8631-ed5e0ac70f4a/profile_linux_11_libstdcpp11_gcc_release_64.-shared-False.txt -pr:b /home/conan/w/prod-v2_cci_PR-13525/4/56f4d13e-dfb8-45e9-8631-ed5e0ac70f4a/profile_linux_11_libstdcpp11_gcc_release_64.-shared-False.txt`:
> 
> ```
> -------- Input profiles --------
> Profile host:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=11
> os=Linux
> [options]
> */*:shared=False
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=11
> os=Linux
> [options]
> */*:shared=False
> 
> 
> -------- Computing dependency graph --------
> Graph root
>     virtual
> Requirements
>     jxrlib/cci.20170615#a23c9807b12818ff7a73fae89e58ce6a - Cache
> 
> -------- Computing necessary packages --------
> ERROR: jxrlib/cci.20170615: Error in validate() method, line 56
> 	if is_msvc(self) and self.info.options.shared:
> 	ConanException: 'self.settings' access in 'validate()' method is forbidden
> ```

likely a conan v2 bug

2022-10-18 00:24 UTC, merged

2022-10-18 00:28 UTC, prince-chrismc commented
> likely a conan v2 bug

The validate and self settings is the biggest reason why most recipes aren't passing that I know of