libexif: add 0.6.24 + conan v2 support
conan-io/conan-center-index pull request #13587
Opened 2022-10-18 18:28 UTC by theirix

Specify library name and version:  **libexif/0.6.24**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-20 08:07 UTC, uilianries approved these changes

2022-10-20 13:22 UTC, jwillikers requested changes

2022-10-20 13:22 UTC, jwillikers commented on recipes/libexif/all/conanfile.py
> +        if is_msvc(self) and Version(self.settings.compiler.version) >= "12":
Need to account for `msvc` here.

```suggestion
        if (self.settings.compiler == "Visual Studio" and Version(self.settings.compiler.version) >= "12") or \
                (self.settings.compiler == "msvc" and Version(self.settings.compiler.version) >= "180"):
```

2022-10-20 19:17 UTC, jwillikers approved these changes

2022-10-21 09:49 UTC, toge approved these changes

2022-10-21 13:22 UTC, uilianries approved these changes
LGTM

2022-10-21 13:29 UTC, merged