libgsasl: add ligbsasl/2.2.0
conan-io/conan-center-index pull request #13711
Opened 2022-10-24 02:22 UTC by kexianda

**ligbsasl/2.2.0**

[gsasl](https://www.gnu.org/software/gsasl/) is widely used.
add a recipe for it.

https://github.com/conan-io/conan-center-index/issues/13710

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-24 11:27 UTC, jwillikers requested changes

2022-10-24 11:27 UTC, jwillikers commented on recipes/libgsasl/all/conanfile.py
> +        copy(self, "THANKS", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
This should just be the licenses, I believe.

```suggestion
        copy(self, "COPYING", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
        copy(self, "COPYING.LIB", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
```

2022-10-24 13:58 UTC, uilianries commented on recipes/libgsasl/all/conanfile.py
> +from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, rm, rmdir
```suggestion
from conan.tools.files import copy, get, rm, rmdir
```
NO patches needed

2022-10-24 13:58 UTC, uilianries commented on recipes/libgsasl/all/conanfile.py
> +required_conan_version = ">=1.52.0"
```suggestion
required_conan_version = ">=1.50.0"
```
1.51.3 more than enough without export_conandata_patches

2022-10-24 13:58 UTC, uilianries commented on recipes/libgsasl/all/conanfile.py
> +        "shared": [True, False],
no fPIC?

2022-10-24 13:58 UTC, uilianries commented on recipes/libgsasl/all/conandata.yml
> +  "1.8.0":
Do you need both versions? Otherwise, keep only the latest. We try to avoid extra versions which are not directly requested by users.

2022-11-07 11:14 UTC, uilianries commented
> [HOOK - conan-center.py] pre_export(): ERROR: [TEST V1 PACKAGE FOLDER (KB-H073)] The test_package seems be prepared for Conan v2, but test_v1_package is missing. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H073) 

Please, add a test_v1_package based on https://github.com/conan-io/conan-center-index/tree/master/docs/package_templates/autotools_package/all/test_v1_package

2023-01-16 19:06 UTC, closed without merging