Bump spirv-cross/1.3.231.0
conan-io/conan-center-index pull request #13735
Opened 2022-10-24 20:41 UTC by SpaceIm

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-25 12:59 UTC, uilianries submitted a review, later dismissed
LGTM

2022-10-28 09:13 UTC, uilianries submitted a review, later dismissed

2022-10-28 12:56 UTC, jwillikers requested changes

2022-10-28 12:56 UTC, jwillikers commented on recipes/spirv-cross/all/conanfile.py
> +        export_conandata_patches(self)
The minimum conan version needs to be bumped to 1.52.0.

2022-10-28 13:35 UTC, jwillikers approved these changes
Thanks!

2022-10-28 15:31 UTC, uilianries approved these changes

2022-10-29 10:44 UTC, merged