picosha2: add recipe
conan-io/conan-center-index pull request #13807
Opened 2022-10-27 11:40 UTC by toge

Specify library name and version:  **picosha2/***

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-28 13:23 UTC, uilianries submitted a review, later dismissed
LGTM

2022-10-28 21:26 UTC, prince-chrismc requested changes
This limitation will be fixed in an upcomming release of the client, we like to limit itis usage 

[(there was a PR for this)](https://github.com/conan-io/conan-center-index/pull/13754) puts it back to 1.x syntax and the beta 5 will be improved

2022-10-28 21:26 UTC, prince-chrismc commented on recipes/picosha2/all/conanfile.py
> +from conan import ConanFile, conan_version
```suggestion
from conan import ConanFile
```

2022-10-28 21:26 UTC, prince-chrismc commented on recipes/picosha2/all/conanfile.py
> +    def validate(self):
```suggestion
    def validate(self):
```

2022-10-28 21:26 UTC, prince-chrismc commented on recipes/picosha2/all/conanfile.py
> +        if self._info.settings.compiler.get_safe("cppstd"):
```suggestion
        if self.info.settings.compiler.get_safe("cppstd"):
```

2022-10-31 00:14 UTC, prince-chrismc approved these changes

2022-11-03 14:50 UTC, uilianries approved these changes

2022-11-03 15:52 UTC, merged