qt 5.15.7
conan-io/conan-center-index pull request #13837
Opened 2022-10-28 11:55 UTC by ericLemanissier

Specify library name and version:  **qt/5.15.7**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-28 13:00 UTC, jwillikers requested changes

2022-10-28 13:00 UTC, jwillikers commented on recipes/qt/5.x.x/conanfile.py
> +        export_conandata_patches(self)
Need to bump 'required_conan_version' to 1.52.0 for this function.

2022-10-28 13:36 UTC, jwillikers approved these changes

2022-10-29 22:23 UTC, prince-chrismc approved these changes

2022-10-29 22:24 UTC, merged