Use new Conan 1.53 features
conan-io/conan-center-index pull request #13848
Opened 2022-10-28 21:49 UTC by prince-chrismc

since it's now available #13753 🚀

2022-10-28 22:01 UTC, SpaceIm requested changes

2022-10-28 22:01 UTC, SpaceIm commented on docs/package_templates/autotools_package/all/conanfile.py
> +        self.options.rm_safe("cppstd")
```suggestion
        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")
```

2022-10-28 22:01 UTC, SpaceIm commented on docs/package_templates/cmake_package/all/conanfile.py
> +        self.options.rm_safe("cppstd")
```suggestion
        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")
```

2022-10-28 22:01 UTC, SpaceIm commented on docs/package_templates/meson_package/all/conanfile.py
> +        self.options.rm_safe("cppstd")
```suggestion
        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")
```

2022-10-28 22:01 UTC, SpaceIm commented on docs/package_templates/msbuild_package/all/conanfile.py
> +        self.options.rm_safe("cppstd")
```suggestion
        self.settings.rm_safe("compiler.libcxx")
        self.settings.rm_safe("compiler.cppstd")
```

2022-10-29 22:25 UTC, prince-chrismc commented
Good catch! Dangerous copy past strikes again

2022-11-01 17:08 UTC, jwillikers approved these changes

2022-11-02 10:56 UTC, uilianries approved these changes

2022-11-02 11:22 UTC, merged

2022-11-02 12:35 UTC, SpaceIm commented
So 1.53.0 is deployed?

2022-11-03 04:36 UTC, prince-chrismc commented
It was with the other config pr!