openh264/* upgrade to conan v2
conan-io/conan-center-index pull request #13849
Opened 2022-10-28 22:48 UTC by Nomalah

Specify library name and version:  **openh264/\***

Upgrade openh264 to conan v2

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-10-29 00:03 UTC, Nomalah commented
(also added v2.3.1)

2022-10-29 11:57 UTC, SpaceIm requested changes

2022-10-29 11:57 UTC, SpaceIm commented on recipes/openh264/all/conanfile.py
>              self.build_requires("nasm/2.15.05")
```suggestion
            self.tool_requires("nasm/2.15.05")
```

2022-10-29 11:57 UTC, SpaceIm commented on recipes/openh264/all/conanfile.py
> +        # src_folder must use the same source folder name the project
```suggestion
```

2022-10-29 11:57 UTC, SpaceIm commented on recipes/openh264/all/test_v1_package/conanfile.py
> +
```suggestion
```

2022-10-29 11:58 UTC, SpaceIm commented on recipes/openh264/all/test_v1_package/conanfile.py
> +
not required anymore

2022-10-31 00:21 UTC, prince-chrismc commented on recipes/openh264/all/conandata.yml
> +      patch_type: "conan"
Would portability be a better fit?

Maybe set these to upstream so we don't have to keep applying it?

2022-10-31 00:23 UTC, prince-chrismc commented on recipes/openh264/all/conandata.yml
> +      patch_type: "conan"
Sorry for being picky but id like to make sure these are correct so we can measure the types and reasons 

https://github.com/conan-io/conan-center-index/blob/master/docs/conandata_yml_format.md#patch_type

```suggestion
      patch_type: "portability"
```

Would be a better fit based on  the description

2022-10-31 00:24 UTC, prince-chrismc reviewed
Thank you so much for adding the patch fields just would like to change them to match the docs.

I believe they are all about fixes for different system and they should be type portability 

Please let me know if that's not correct:)

2022-10-31 18:45 UTC, prince-chrismc submitted a review, later dismissed

2022-11-03 11:57 UTC, uilianries commented on recipes/openh264/all/conanfile.py
> +    return None
```suggestion
```

Please, use https://docs.conan.io/en/latest/reference/tools.html#tools-stdcpp-library instead and add a `TODO` to be updated after 1.54.0. Try avoiding duplicated code from Conan tools.

2022-11-09 08:57 UTC, MartinDelille requested changes

2022-11-09 08:57 UTC, MartinDelille commented on recipes/openh264/all/conanfile.py
> +                pass
Since 1.52.0, you can use `self.options.rm_safe("fPIC")` to avoid this warning.

2022-11-10 08:12 UTC, MartinDelille approved these changes

2022-11-10 16:10 UTC, prince-chrismc approved these changes

2022-11-10 16:11 UTC, uilianries approved these changes

2022-11-10 16:30 UTC, merged