libpqxx: add version 6.4.8, support conan v2, remove older versions
conan-io/conan-center-index pull request #14371
Opened 2022-11-22 17:43 UTC by toge

Specify library name and version:  **libpqxx/***

- add version 6.4.8 (last C++14 version)
- remove older versions
- suppor conan v2

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-11-22 17:44 UTC, toge commented
Try to close https://github.com/conan-io/conan-center-index/issues/14117.

2022-12-01 13:58 UTC, jwillikers requested changes

2022-12-01 13:58 UTC, jwillikers commented on recipes/libpqxx/all/conanfile.py
> +        if is_msvc(self) and self.options.shared and self.settings.compiler.runtime == "MTd":
`compiler.runtime` is specific to `Visual Studio`. Can you use [conan.tools.microsoft.msvc_runtime_flag()](https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html#conan-tools-microsoft-msvc-runtime-flag) which supports both `Visual Studio` and `msvc` to check against the `MTd` flag here?

2022-12-01 22:35 UTC, prince-chrismc approved these changes

2022-12-02 21:25 UTC, merged