[libtool] use new toolchain
conan-io/conan-center-index pull request #14466
Opened 2022-11-28 14:21 UTC by planetmarshall

Specify library name and version:  **libtool**

Update to new toolchain. Should fix #9002

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-04 12:01 UTC, planetmarshall commented
Marking as draft as test packages need some work.

2022-12-09 20:18 UTC, jwillikers commented
@planetmarshall Thanks for working on this. Your PR fixes cross-compilation for me on Linux.

2022-12-09 20:18 UTC, jwillikers commented
@planetmarshall Thanks for working on this. Your PR fixes cross-compilation for me on Linux.

2023-01-14 03:05 UTC, samuel-emrys commented
@planetmarshall thanks for your work on this. What still needs to be included in the test packages?

2023-01-15 22:52 UTC, planetmarshall commented
> @planetmarshall thanks for your work on this. What still needs to be included in the test packages?

The test packages are quite complex - they just need ported over to the new toolchains. I will look at this tomorrow.

2023-01-22 17:38 UTC, SpaceIm requested changes

2023-01-22 17:38 UTC, SpaceIm commented on recipes/libtool/all/conanfile.py
> +from conan.tools.apple import is_apple_os
```suggestion
from conan.tools.apple import fix_apple_shared_install_name, is_apple_os
```

2023-01-22 17:38 UTC, SpaceIm commented on recipes/libtool/all/conanfile.py
>                                method_pass_all)
```suggestion
                              method_pass_all)
        fix_apple_shared_install_name(self)
```

2023-01-23 18:34 UTC, SpaceIm commented on recipes/libtool/all/test_package/conanfile.py
> +from conan.tools.env import VirtualBuildEnv, VirtualRunEnv, Environment
I'm not sure it's a good idea to mix up two different build systems, conan v2 doesn't seem to be robust to this case. I would create a test package for Autotools, and another one to test link to libltdl.

2023-04-11 09:54 UTC, closed without merging