soundtouch: add recipe
conan-io/conan-center-index pull request #14519
Opened 2022-12-01 16:36 UTC by toge

Specify library name and version:  **soundtouch/2.3.2**

Try to close https://github.com/conan-io/conan-center-index/issues/14201.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-02 10:22 UTC, MartinDelille submitted a review, later dismissed

2022-12-06 13:23 UTC, jwillikers requested changes
Oops, hit the wrong button.

2022-12-06 15:38 UTC, jwillikers submitted a review, later dismissed

2022-12-12 10:34 UTC, 9cvele3 submitted a review, later dismissed

2022-12-12 11:01 UTC, MartinDelille approved these changes

2022-12-12 11:44 UTC, uilianries commented on recipes/soundtouch/all/conanfile.py
> +        self.cpp_info.components["_soundtouch"].set_property("pkg_config_name", "SoundTouch")
```suggestion
        self.cpp_info.components["_soundtouch"].set_property("pkg_config_name", "soundtouch")
```
I built without Conan and cmake install provided soundtouch.pc

```
% cmake --build . --target install 
[ 78%] Built target SoundTouch
[100%] Built target soundstretch
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/install/include/soundtouch/BPMDetect.h
-- Installing: /tmp/install/include/soundtouch/FIFOSampleBuffer.h
-- Installing: /tmp/install/include/soundtouch/FIFOSamplePipe.h
-- Installing: /tmp/install/include/soundtouch/STTypes.h
-- Installing: /tmp/install/include/soundtouch/SoundTouch.h
-- Installing: /tmp/install/include/soundtouch/soundtouch_config.h
-- Installing: /tmp/install/lib/libSoundTouch.a
-- Installing: /tmp/install/bin/soundstretch
-- Installing: /tmp/install/lib/pkgconfig/soundtouch.pc
-- Installing: /tmp/install/lib/cmake/SoundTouch/SoundTouchTargets.cmake
-- Installing: /tmp/install/lib/cmake/SoundTouch/SoundTouchTargets-release.cmake
-- Installing: /tmp/install/lib/cmake/SoundTouch/SoundTouchConfig.cmake
-- Installing: /tmp/install/lib/cmake/SoundTouch/SoundTouchConfigVersion.cmake
```

2022-12-12 17:09 UTC, jwillikers approved these changes

2022-12-13 00:38 UTC, MartinDelille approved these changes

2022-12-13 08:25 UTC, merged