read-excel: prepare Conan v2 support, add version 1.2.8.
conan-io/conan-center-index pull request #14578
Opened 2022-12-05 05:30 UTC by igormironchik

Specify library name and version:  **read-excel/1.2.8**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

I'm the author of this library.

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-05 12:34 UTC, SpaceIm requested changes

2022-12-06 00:52 UTC, SpaceIm approved these changes

2022-12-06 13:08 UTC, jwillikers approved these changes

2022-12-13 08:42 UTC, uilianries approved these changes
LGTM

2022-12-13 13:46 UTC, merged