added flags for redboltz mqtt project
conan-io/conan-center-index pull request #14591
Opened 2022-12-05 18:05 UTC by MateuszMiekicki

Specify library name and version:  **redboltz-mqtt_cpp/13.1.0**

Hi, I noticed that this particular library is wrongly added comparing with the original repo, plus the flags for cmake are missing during the build. I've done this on the fly, taking examples from other projects. All comments welcome.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-05 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=14591) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=14591) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=14591) it.</sub>

2022-12-06 17:46 UTC, jwillikers requested changes

2022-12-06 19:23 UTC, jwillikers commented
> @jwillikers Thank you very much for your comments, I will try to improve everything in the final version. For the time being, I am struggling to create a package at all.
> 
> conan create . 13.1.0@
> 
> > redboltz-mqtt_cpp/13.1.0: Aggregating env generators
> > [HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
> > [HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
> > redboltz-mqtt_cpp/13.1.0: Calling build()
> > redboltz-mqtt_cpp/13.1.0: CMake command: cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\source"
> > CMake Error: The source directory "C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/source" does not appear to contain CMakeLists.txt.
> > Specify --help for usage, or press the help button on the CMake GUI.
> > redboltz-mqtt_cpp/13.1.0:
> > redboltz-mqtt_cpp/13.1.0: ERROR: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' build failed
> > redboltz-mqtt_cpp/13.1.0: WARN: Build folder C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
> > ERROR: redboltz-mqtt_cpp/13.1.0: Error in build() method, line 64
> > cmake.configure()
> > ConanException: Error 1 while executing cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\source"
> 
> After running this command, unfortunately the package fails to build. Do you know where the problem lies? I know it can't find the CMakeList, but why? As far as I know, this library is in cmak as an interface, not as shared or static.

@MateuszMiekicki I think you're missing the necessary `source` method to actually grab the project's source code.

2022-12-06 20:42 UTC, MateuszMiekicki commented
> > @jwillikers Thank you very much for your comments, I will try to improve everything in the final version. For the time being, I am struggling to create a package at all.
> > conan create . 13.1.0@
> > > redboltz-mqtt_cpp/13.1.0: Aggregating env generators
> > > [HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
> > > [HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
> > > redboltz-mqtt_cpp/13.1.0: Calling build()
> > > redboltz-mqtt_cpp/13.1.0: CMake command: cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\source"
> > > CMake Error: The source directory "C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/source" does not appear to contain CMakeLists.txt.
> > > Specify --help for usage, or press the help button on the CMake GUI.
> > > redboltz-mqtt_cpp/13.1.0:
> > > redboltz-mqtt_cpp/13.1.0: ERROR: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' build failed
> > > redboltz-mqtt_cpp/13.1.0: WARN: Build folder C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
> > > ERROR: redboltz-mqtt_cpp/13.1.0: Error in build() method, line 64
> > > cmake.configure()
> > > ConanException: Error 1 while executing cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/haven/.conan/data/redboltz-mqtt_cpp/13.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\haven.conan\data\redboltz-mqtt_cpp\13.1.0__\source"
> > 
> > 
> > After running this command, unfortunately the package fails to build. Do you know where the problem lies? I know it can't find the CMakeList, but why? As far as I know, this library is in cmak as an interface, not as shared or static.
> 
> @MateuszMiekicki I think you're missing the necessary `source` method to actually grab the project's source code.

It helped, I was able to build what I wanted. I just don't know why it doesn't pass CI, I don't have access to the details.

2022-12-06 20:47 UTC, jwillikers commented
@MateuszMiekicki It says too many blank lines are in `conandata.yml`.

2022-12-06 20:49 UTC, MateuszMiekicki commented
> @MateuszMiekicki It says too many blank lines are in `conandata.yml`.

Thanks, it has been corrected

2022-12-06 20:54 UTC, MateuszMiekicki commented
> @MateuszMiekicki It says too many blank lines are in `conandata.yml`.

Another problem xD Without your help I unfortunately cannot see the details.

2022-12-13 08:57 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "cpp17": [True, False],
Correct. @MateuszMiekicki please, remove it. Any configuration related to the supported c++ standard should be managed by settings.compiler.cppstd

2022-12-13 08:58 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "fPIC": [True, False],
@MateuszMiekicki Could you please check if this library offers shared/static support?

2022-12-13 08:59 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "with_static_openssl": [True, False],
Correct. It should be removed, please. All those options are part of dependencies options, not managed by this package.

2022-12-13 09:00 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +            openssl.shared = True
```suggestion
            openssl = self.dependencies["boost"]
            openssl.shared = True
```
It's read-only, you can't force it. Please, remove it.

2022-12-13 09:01 UTC, uilianries requested changes
Thank you for your contribution. Please, check the review, there are important points which are not allowed in CCI and should be removed/updated

2022-12-13 17:16 UTC, MateuszMiekicki commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "cpp17": [True, False],
Isn't that enough?  https://github.com/conan-io/conan-center-index/blob/56f06c3fb4e56981ef088a5eaee25adbbd514ff6/recipes/redboltz-mqtt_cpp/all/conanfile.py#L69
Simply the project contains such a flag in CMakeLists and thanks to it we know in which version of c++ to build the project.

2022-12-13 17:21 UTC, MateuszMiekicki commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "fPIC": [True, False],
https://github.com/redboltz/mqtt_cpp/blob/master/include/CMakeLists.txt#L7 The library is as header only

2022-12-13 18:41 UTC, MateuszMiekicki commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        tc.variables["MQTT_USE_STATIC_BOOST"] = self.options.with_static_boost
Actually looks better, corrected.

2022-12-13 18:43 UTC, MateuszMiekicki commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        if self.options.get_safe("cpp17"):
This is where I would like to check the flag, the standard I check earlier

2023-01-29 20:36 UTC, MateuszMiekicki commented
@jwillikers @uilianries Hey, can I have some comments so I can merge this?

2023-03-06 13:05 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        "cpp17": [True, False],
@MateuszMiekicki please use the template approach for cppstd version: https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/cmake_package/all/conanfile.py#L77

2023-04-22 22:06 UTC, MateuszMiekicki commented
> Thank you for your contribution. Please, check the review, there are important points which are not allowed in CCI and should be removed/updated

Hi, could you point me to this place? Somehow it has eluded me.

2023-06-20 10:18 UTC, SSE4 commented
> Thank you for your contribution. Please, check the review, there are important points which are not allowed in CCI and should be removed/updated

@uilianries could you possible be more specific? what are these "important points"? what exactly should be "removed" or "updated"? it's a bit unclear what exactly do you mean...

2023-06-21 06:38 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +                "Visual Studio": "16",
```suggestion
                "Visual Studio": "16",
                "msvc": "1923",
```
Conan 2.x does not use Visual Studio, but msvc only as compiler name.

2023-06-21 06:38 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +                "Visual Studio": "15",
```suggestion
                "Visual Studio": "15",
                "msvc": "1916",
```
Conan 2.x does not use Visual Studio, but msvc only as compiler name.

2023-06-21 06:38 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        self.requires("boost/1.81.0")
```suggestion
        self.requires("boost/1.82.0")
```

2023-06-21 06:38 UTC, uilianries commented on recipes/redboltz-mqtt_cpp/all/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "mqtt_cpp_iface::mqtt_cpp_iface")
```suggestion
        self.cpp_info.set_property("cmake_file_name", "mqtt_cpp_iface")
        self.cpp_info.set_property("cmake_target_name", "mqtt_cpp_iface::mqtt_cpp_iface")
```
Why did it change now? These targets were wrong or is just a new name from the latest version?

2023-06-21 13:22 UTC, uilianries commented
@MateuszMiekicki Please, don't forget to sign the CLA attached to this PR. It's listed in the first comment of this PR.

2023-10-13 20:24 UTC, closed without merging