unordered_dense: add version 2.0.2, improve recipe
conan-io/conan-center-index pull request #14618
Opened 2022-12-07 06:21 UTC by toge

Specify library name and version:  **unordered_dense/***

- add version 2.0.2
- use `check_min_vs`
- remove wrong `pkg_config_name`
- simplify test_v1_package/CMakeLists.txt

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-12 12:55 UTC, jwillikers submitted a review, later dismissed

2022-12-13 01:40 UTC, toge commented on recipes/unordered_dense/all/conanfile.py
> +                raise ConanInvalidConfiguration(f"{self.ref} requires C++{self._minimum_cpp_standard}, which your compiler does not support.")
reverted

2022-12-13 08:29 UTC, SpaceIm requested changes
this is what I meant

2022-12-13 08:29 UTC, SpaceIm commented on recipes/unordered_dense/all/conanfile.py
> +from conan.tools.microsoft import is_msvc, check_min_vs
```suggestion
```

2022-12-13 08:29 UTC, SpaceIm commented on recipes/unordered_dense/all/conanfile.py
> +        check_min_vs(self, 192)
```suggestion
```

2022-12-13 08:29 UTC, SpaceIm commented on recipes/unordered_dense/all/conanfile.py
>              "gcc": "7",
```suggestion
            "Visual Studio": "15.7",
            "msvc": "191",
            "gcc": "7",
```

2022-12-13 08:52 UTC, toge commented
@SpaceIm 
Thanks a lot!
Now I understand you mean.

2022-12-13 12:24 UTC, uilianries approved these changes
LGTM

2022-12-19 09:34 UTC, SpaceIm approved these changes

2022-12-19 13:20 UTC, jwillikers approved these changes

2022-12-19 13:56 UTC, uilianries approved these changes
LGTM

2022-12-19 14:07 UTC, merged