Add --enable-strmax configuration option support
conan-io/conan-center-index pull request #14612
Opened 2022-12-06 17:13 UTC by psmitsu

Specify library name and version:  **libsafec/3.6.0**

Hello! This PR enables setting "--enable-strmax" configure flag through Conan package option, as described in #14611 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-06 17:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=14612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=14612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=14612) it.</sub>

2022-12-06 20:36 UTC, jwillikers requested changes

2022-12-06 20:36 UTC, jwillikers commented on recipes/libsafec/all/conanfile.py
> +            "--enable-strmax={}".format(self.options.strmax),
What happens when `self.options.strmax` is `None`?

2022-12-07 13:59 UTC, jwillikers submitted a review, later dismissed
LGTM

2022-12-13 12:17 UTC, uilianries commented
@psmitsu Thank you for your contribution, please, consider https://github.com/psmitsu/conan-center-index/pull/1

2022-12-18 06:06 UTC, psmitsu commented
@jwillikers @uilianries thank you for your feedback! I've merged that PR: it had "del rm_safe()" typos which I've fixed. I've also added a commit which allows to set "--enable-memmax" option similarly to "--enable-strmax". Is it okay to do that in the same PR? I thought that it's better to pack changes in one PR, based on @uilianries PR.

2022-12-19 13:56 UTC, uilianries commented
@psmitsu It's. BTW have you asked for access on the issue #4 already? It's mandatory to the CI run your PR.

2022-12-19 14:29 UTC, jwillikers approved these changes

2023-01-14 03:44 UTC, prince-chrismc approved these changes
There a few things for the 2.0 migration which would be a great follow up PR :)

but this looks really good start!

2023-01-14 03:46 UTC, prince-chrismc commented
> Is it okay to do that in the same PR? 

The less PRs the better for the most part, any update to the same recipe can be in the same PR :)

2023-01-14 04:06 UTC, merged