boost: Add configure options
conan-io/conan-center-index pull request #14625
Opened 2022-12-07 13:36 UTC by Sil3ntStorm

Specify library name and version:  **boost/all**

This adds the configuration options beast_use_std_string_view, asio_disable_eventfd, asio_disable_serial_port, asio_no_experimental_string_view.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-07 15:21 UTC, SpaceIm commented
Do they change binaries? If they are just interface definitions not affecting compiled libraries, I don't see any interest to add these options.

2022-12-27 10:57 UTC, uilianries approved these changes
LGTM

2022-12-27 21:22 UTC, prince-chrismc commented on recipes/boost/all/conanfile.py
> +            flags.append("define=BOOST_BEAST_USE_STD_STRING_VIEW=1")
My concern here is these change really quickly and managing them with each version is a pain https://github.com/boostorg/beast/commit/7300ef463bbc702ac5659f42fa3b8b528ae575e3

This one is already deprecated 🙊

2023-01-25 03:43 UTC, toge approved these changes

2023-01-25 09:14 UTC, SpaceIm commented
> Do they change binaries? If they are just interface definitions not affecting compiled libraries, I don't see any interest to add these options.

No opinion from anybody on this?

2023-01-25 16:30 UTC, prince-chrismc requested changes
This is under discussion so I am blocking i for now

2023-01-27 06:54 UTC, prince-chrismc commented
The team discussed this issue and I've capture that decision in https://github.com/conan-io/conan-center-index/pull/15494.

These options of options are generally not very beneficial as they can easily be set from profiles or downstream recipes. It might be possible that a define is too generic and must be set in a recipe to avoid propagation which would be a good technical reason to add these. The other practical reason is to much the upstream consumption model, assuming these are installed options.

These options are expected to be injected by the consumer for the boost project so not going to be permitted in this particular.

Hopefully that's a helpful explanation.

2023-01-27 06:55 UTC, prince-chrismc commented
Since is does not meet the criteria I will close this PR, feel free to reply if there's more information that was missed

2023-01-27 06:55 UTC, closed without merging

2023-01-27 06:56 UTC, prince-chrismc commented
> No opinion from anybody on this?

There's an official position in the PR mentioned above (finally) 🚀 should be pretty close to the status quo 😄