Revert "(#14525) Add Boost.LEAF to Conan Center"
conan-io/conan-center-index pull request #14660
Opened 2022-12-09 14:44 UTC by uilianries

Reverting Boost Leaf.

https://github.com/conan-io/conan-center-index/pull/14525#pullrequestreview-1211744714

/cc @grafikrobot 

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-09 15:09 UTC, RubenRBS submitted a review, later dismissed

2022-12-09 15:21 UTC, RubenRBS submitted a review, later dismissed

2022-12-09 15:37 UTC, prince-chrismc requested changes
This is not a boost library

2022-12-09 15:38 UTC, prince-chrismc commented
The title does not match the bots output

2022-12-10 03:38 UTC, prince-chrismc commented
IMO it's too late, we have boost Hana too if we decide to go that road... so I dont think rejecting an accepted project is in good taste on this one.

I'd rather see a FAQ for why we don't accept individual boost library then explain the exceptions.

Let's right down conventions so it's more clear :) then we can avoid things like this hopefully

2022-12-10 11:32 UTC, uilianries commented
Fixed!

2022-12-10 11:37 UTC, uilianries commented
> I dont think rejecting an accepted project is in good taste on this one.

It's not good indeed, but it's needed to avoid separated maintenance, patches, discussions, etc ... 

We already tried to separate Boost modules in the past, took months and was a nightmare.

2022-12-10 14:55 UTC, prince-chrismc approved these changes

2022-12-10 14:57 UTC, prince-chrismc commented
Also do https://github.com/conan-io/conan-center-index/blob/389926e2dd9292703937fbbfd94819b470706354/recipes/hana/all/conandata.yml#L3
Please

2022-12-10 19:27 UTC, uilianries commented
@prince-chrismc  Do you mean deprecate Boost.Hana package, right?

2022-12-11 03:51 UTC, prince-chrismc commented
> @prince-chrismc Do you mean deprecate Boost.Hana package, right?

Yes :) sorry vacation wifi sucks, typing is slow since work predicting and autocorrect don't work

2022-12-11 16:54 UTC, prince-chrismc approved these changes

2022-12-12 08:14 UTC, uilianries commented
Hana deprecation: https://github.com/conan-io/conan-center-index/pull/14690

2022-12-12 14:17 UTC, jwillikers approved these changes

2022-12-12 16:27 UTC, merged

2022-12-12 20:24 UTC, zajo commented
It is entirely incorrect to cite Hana deprecation as a reason to remove LEAF also.

Hana is a Level 9 library in the Boost Dependency Report, it depends on `config`, `core`, `fusion`, `mpl`, `tuple`. Most of those sit at the top of a complex dependency tree themselves (see https://pdimov.github.io/boostdep-report/master/module-levels.html).

LEAF is a Level 0 library, it depends on nothing. A single header with no deps.

2022-12-12 21:30 UTC, prince-chrismc commented
🤔 I think you misunderstood, but we are on the same page

> It seems like a mismatch to cite Hana deprecation as a reason to remove LEAF also

My grip, was that we deprecated the leaf package so we must also deprecated hana.

If we don't allow leaf standalone then we shouldn't have hana - hence the conversation above.

So yes, we have the same reasons just think it was not obvious since there was outside threads.