shapelib: Disable SO versioning
conan-io/conan-center-index pull request #14826
Opened 2022-12-19 18:13 UTC by jwillikers

The SO versioning creates symlinks that complicate the recipe. This PR disables generating these symlinks with a CMake variable. This simplifies the recipe to only include `libshp.so`.

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-19 18:32 UTC, jcar87 requested changes
Hi @jwillikers  - thanks for raising this PR.

I'm wondering, in what way does the default behaviour complicate the recipe?
From what I can see, shared object versioning for shapelib is done in a fairly conventional way: 
https://github.com/OSGeo/shapelib/blob/master/CMakeLists.txt#L135-L138 

and CMake is following convention accordingly. I can't see anything unusual and pretty sure the vast majority of Conan Center recipes do result in symlinks like this.

This change would cause a single `libshp.so` to be generated, which would have a _different_ `DT_SONAME` than before. This, in itself, is a major breaking change.

A potential package that depends on `shapelib` with `shared=True`, would have a dependency recorded against `libshp.so.1`. After this change (but without rebuilding a binary on the other end), consumers would be faced with an error like this:


```
error while loading shared libraries: libshp.so.1: cannot open shared object file: No such file or directory
```

(or worse, the runtime linker may fallback to finding this file on the system if it exists, potentially loading a different version).


It would help if you could provide details of a specific issue that is fixed with this change, so that we can try and find a solution.

2022-12-19 18:49 UTC, jwillikers commented
@jcar87 I ran into some trouble extracting the location of library via CMake. Instead of the `LOCATION` property of the target `CONAN_LIB::shapelib_shapelib_shp_shp` pointing at the library, it instead points to the symlink `libshp.so` and not the actual library file. I know this is a internal Conan target, but I don't care. I'm using the CMake target information to install dependencies and this is the best way to get that.

I was trying to find if there was a policy for soversioning on CCI, but coulding find any details. It would be great if we had one.

I'll mark this is a draft so it doesn't get merged. I wouldn't wish to break compatibility with existing packages without proper warrant.

2022-12-19 18:55 UTC, jwillikers commented
Aw, I see Qt uses SO versioning. I wasn't aware what the majority of CCI recipes did for shared libraries.

2022-12-19 19:01 UTC, jcar87 commented
> @jcar87 I ran into some trouble extracting the location of library via CMake. Instead of the `LOCATION` property of the target `CONAN_LIB::shapelib_shapelib_shp_shp` pointing at the library, it instead points to the symlink `libshp.so` and not the actual library file. I know this is a internal Conan target, but I don't care. I'm using the CMake target information to install dependencies and this is the best way to get that.
> 
> I was trying to find if there was a policy for soversioning on CCI, but coulding find any details. It would be great if we had one.
> 
> I'll mark this is a draft so it doesn't get merged. I wouldn't wish to break compatibility with existing packages without proper warrant.

Thanks for providing more details!

From what you're explaining, I believe you would face the same exact situation with every single shared library dependency you bring from Conan or even any other package manager. Perhaps the only exception would be CMake generated config files that also preserve the version information as properties on the imported targets (I'd have to check).

Your binaries that consume these shared libraries will encode a dependency on whatever the `DT_SONAME` flag is of the files provided to the linker at link time - this is irrespective of whether those files were a symlink or not.

So without this PR, your resulting binaries will have a dependency on `libshp.so.1` and that's what the _runtime_ linker will look for. That file is overwhelmingly likely to be a symlink pointing to `libshp.so.1.y.z`. Having been in this situation before, if you have custom logic to copy these files - my advise would be to amend the rule to copy the found file, and copy all that match `libshp.so*` - so that the symlinks are preserved. 

Aside from a warning that these internal Conan targets may change name at any time or may not exist at all, we do have some ways in Conan that would allow you to copy all the .so/dylib/dll files if needed. Let me know if you'd like more information on this.

2022-12-19 19:10 UTC, jcar87 commented
> Aw, I see Qt / Boost use SO versioning. I wasn't aware what the majority of CCI recipes did for shared libraries, as most of the time I'm building them statically.

Indeed - it's all done implicitly by the underlying build systems that follow platform conventions - CCI doesn't do anything specific. When a library changes the soname it's typically because there's an API breaking change, so the "major" version in the recipe version would change and forcing a rebuild at the very least.  On the other hand, you're more likely to find libraries that have stricter soname/soversion promises if they are packaged by Linux distros (which tend to have rather strict conventions to prevent unnecessary rebuilds but also breakages experienced by downstream consumers).

2022-12-19 19:19 UTC, SpaceIm commented
I agree with @jcar87.

so/dylib versioning shouldn't be disabled.

2022-12-19 19:21 UTC, jwillikers commented
@SpaceIm No worries, I'm closing this.

2022-12-19 19:21 UTC, closed without merging

2022-12-19 19:29 UTC, jwillikers commented
@jcar87 I know about the deploy methods, but that seems somewhat less viable during the Conan V2 transition. Regardless of that, it seems like a lot of unnecessarily duplicating files around the filesystem when using CMake / CPack to generate specific packages. I'd have to have Conan "deploy", i.e. copy, the binaries to a specific directory within the build directory only to have CMake then copy these to another directory where it builds the final package. This can substantially increase the disk usage of projects with dependencies on large libraries such as Qt, etc. Aside from runtime plugins which are harder to track in the build system alone, it makes much more sense to have CMake just handle bundling dependencies when taking advantage of CMake's ability to create tarballs and installers using the standard install logic.

2022-12-20 17:34 UTC, jcar87 commented
> @jcar87 I know about the deploy methods, but that seems somewhat less viable during the Conan V2 transition. Regardless of that, it seems like a lot of unnecessarily duplicating files around the filesystem when using CMake / CPack to generate specific packages. I'd have to have Conan "deploy", i.e. copy, the binaries to a specific directory within the build directory only to have CMake then copy these to another directory where it builds the final package. This can substantially increase the disk usage of projects with dependencies on large libraries such as Qt, etc. Aside from runtime plugins which are harder to track in the build system alone, it makes much more sense to have CMake just handle bundling dependencies when taking advantage of CMake's ability to create tarballs and installers using the standard install logic.
> 
> Fyi, I found that [file(INSTALL)](https://cmake.org/cmake/help/latest/command/file.html#install) has the option `FOLLOW_SYMLINK_CHAIN` to install symlinks in this kind of situation. Additionally, if `IMPORT_SONAME` is set for a target, installing the library as part of a runtime dependency set will automatically install at least one level of SO symlinks, according to [this issue comment](https://gitlab.kitware.com/cmake/cmake/-/issues/23249#note_1147163).

Hi @jwillikers  - oh, I understand your concerns! 
My past experience with CMake functionality to perform this kind of operation (along the lines of "given an executable, grab the shared libraries and put them in a bundle") is that there are a lot of corner cases to take into account. If I'm not mistaken, we have:
* the now deprecated `BundleUtilities` module (https://cmake.org/cmake/help/latest/module/BundleUtilities.html)
* The `file(... GET_RUNTIME_DEPENDENCIES` https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies that is also the basis of `install(RUNTIME_DEPENDENCY_SET ` https://cmake.org/cmake/help/latest/command/install.html#installing-runtime-dependencies 
* The `$<TARGET_RUNTIME_DLLS:tgt>` generator expression: https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS


In theory, any of the above should only need you to provide the executable, and CMake should be able to "do the rest". The problem is that depending on the methodology CMake doesn't always have the ability to do this, and my past experience is that there isn't a single of this tools that covers all the bases in a robust, cross-platform, generic way (although `GET_RUNTIME_DEPENDENCIES` should get close).

I've also seen users trying to traverse the dependency graph in CMake themselves (at configure time) - and sometimes sort of soft-harcoding a dependency graph (library wise) in the scripts themselves (which is not robust when dependencies between libraries change).

If you could provide more details of which method you are using, we can try and help from our side, especially if we can identify improvements in the `CMakeDeps `generator.


>  I'd have to have Conan "deploy", i.e. copy, the binaries to a specific directory within the build directory only to have CMake then copy these to another directory where it builds the final package.

You could potentially avoid this - you could define a variable in `CMakeToolchain` that contains a list to all the lib dirs (or bin dirs, if this is windows) - then use this variable in CMake to do the copying yourself. 

 This can substantially increase the disk usage of projects with dependencies on large libraries such as Qt, etc. Aside from runtime plugins which are harder to track in the build system alone, it makes much more sense to have CMake just handle bundling dependencies when taking advantage of CMake's ability to create tarballs and installers using the standard install logic.

>  Aside from runtime plugins which are harder to track in the build system alone, 
These are always harder -  as neither CMake nor the runtime linker now about this statically. Qt has its own set of tools for this (`macdeployqt` and `windeployqt` at least), with the correct logic. In some cases and with the right information, those Qt tools can actually take care of non-Qt libraries as well (at least from memory I think this was the case on macOS).

2022-12-20 19:50 UTC, jwillikers commented
@jcar87 Thanks for following up. I have used `windeployqt`, but I've had lots of issues with Qt's tooling around build systems in general and tend to avoid it. The `windeployqt` functionality also works out-of-band with CMake, which isn't ideal.

The method I'm using is manual right now, though I'm planning on eventually migrating to using `GET_RUNTIME_DEPENDENCIES` when we no longer need to support some older versions of CMake. Automating the bundling of runtime dependencies can be very dangerous since it can unknowingly pull in things with incompatible licenses. I've used `BundleUtilities` in the past, but had to implement lots of CMake code to verify everything pulled in was in an allowlist. From that experience, I've found its better to just explicitly bundle everything necessary for runtime in order to be deterministic.

So currently, I use `find_package` and the `LOCATION` / `LOCATION_<CONFIG>` target properties to find the runtime libraries to bundle with the application. It does require some digging to get the name that Conan uses internally for the target, since the necessary target properties are not defined on the publicly exposed target. Right now, I'm able to get away with the following function to do this, though it's a somewhat naive implementation. It doesn't currently handle special characters in the library names and would probably be better written to work backwards from the public target's name to determine the name of the backing internal target.

The function is called like this:

```cmake
install_conan_libraries(
    PACKAGE libiconv 
    LIBRARIES iconv charset 
    COMPONENT MyProject_Runtime
)
```

```cmake
function(install_conan_libraries)
  set(options)
  set(one_value_args COMPONENT DESTINATION PACKAGE)
  set(multi_value_args LIBRARIES)
  cmake_parse_arguments(
      INSTALL_CONAN_LIBRARIES "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN}
  )

  set(required_args LIBRARIES PACKAGE)
  foreach(required_arg IN LISTS required_args)
    if(${required_arg} IN_LIST INSTALL_CONAN_LIBRARIES_UNPARSED_ARGUMENTS)
      message(FATAL_ERROR "Missing the required argument ${required_arg}")
    endif()
  endforeach()

  set(required_value_args ${one_value_args} ${multi_value_args})
  foreach(required_value_arg IN LISTS required_value_args)
    if(${required_value_arg} IN_LIST INSTALL_CONAN_LIBRARIES_KEYWORDS_MISSING_VALUES)
      message(FATAL_ERROR "Missing argument for ${required_value_arg}")
    endif()
  endforeach()

  include(GNUInstallDirs)
  get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
  if(NOT isMultiConfig)
    string(TOUPPER ${CMAKE_BUILD_TYPE} config)
  endif()

  foreach(library IN LISTS INSTALL_CONAN_LIBRARIES_LIBRARIES)
    set(library_name ${INSTALL_CONAN_LIBRARIES_PACKAGE}_${library})
    set(library_target CONAN_LIB::${library_name})
    if (NOT TARGET ${library_target})
      string(APPEND library_target _${config})
    endif()

    if (NOT TARGET ${library_target})
      message(FATAL_ERROR "The target ${library_target} does not exist")
    endif()

    get_target_property(${library_name}_LIBRARY_LOCATION ${library_target} LOCATION_${config})
    if (NOT ${library_name}_LIBRARY_LOCATION)
      get_target_property(${library_name}_LIBRARY_LOCATION ${library_target} LOCATION)
    endif()
    if (NOT ${library_name}_LIBRARY_LOCATION)
      message(FATAL_ERROR "Failed to determine the location of the ${library} library from the ${INSTALL_CONAN_LIBRARIES_PACKAGE} Conan package.")
    endif()

    # Workaround to prefer installing the provided DLL when a .lib is also provided on Windows.
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
      get_filename_component(${library_name}_LIBRARY_EXTENSION ${${library_name}_LIBRARY_LOCATION} EXT)
      if(${library_name}_LIBRARY_EXTENSION STREQUAL ${CMAKE_SHARED_LIBRARY_SUFFIX})
        get_filename_component(${library_name}_LIBRARY_LOCATION ${${library_name}_LIBRARY_LOCATION} REALPATH)
      else()
        get_filename_component(${library_name}_LIBRARY_DIRECTORY ${${library_name}_LIBRARY_LOCATION} DIRECTORY)
        get_filename_component(${library_name}_LIBRARY_ROOT_DIRECTORY ${${library_name}_LIBRARY_DIRECTORY} DIRECTORY)
        get_filename_component(${library_name}_LIBRARY_FILENAME_WITHOUT_EXTENSION ${${library_name}_LIBRARY_LOCATION} NAME_WE)
        if(EXISTS "${${library_name}_LIBRARY_DIRECTORY}/${${library_name}_LIBRARY_FILENAME_WITHOUT_EXTENSION}${CMAKE_SHARED_LIBRARY_SUFFIX}")
          set(${library_name}_LIBRARY_LOCATION "${${library_name}_LIBRARY_DIRECTORY}/${${library_name}_LIBRARY_FILENAME_WITHOUT_EXTENSION}${CMAKE_SHARED_LIBRARY_SUFFIX}")
        elseif(EXISTS "${${library_name}_LIBRARY_ROOT_DIRECTORY}/bin/${${library_name}_LIBRARY_FILENAME_WITHOUT_EXTENSION}${CMAKE_SHARED_LIBRARY_SUFFIX}")
          set(${library_name}_LIBRARY_LOCATION "${${library_name}_LIBRARY_ROOT_DIRECTORY}/bin/${${library_name}_LIBRARY_FILENAME_WITHOUT_EXTENSION}${CMAKE_SHARED_LIBRARY_SUFFIX}")
        else()
          message(DEBUG "Failed to find the ${library} DLL library from the ${INSTALL_CONAN_LIBRARIES_PACKAGE} Conan package.")
        endif()
      endif()
    endif()

    message(STATUS "Found the ${library} library from the ${INSTALL_CONAN_LIBRARIES_PACKAGE} Conan package: ${${library_name}_LIBRARY_LOCATION}")

    if (DEFINED INSTALL_CONAN_LIBRARIES_DESTINATION)
      set(destination ${INSTALL_CONAN_LIBRARIES_DESTINATION})
    else()
      if (CMAKE_SYSTEM_NAME STREQUAL "Windows" AND ${${library_name}_LIBRARY_LOCATION} MATCHES "\\.dll$")
        set(destination ${CMAKE_INSTALL_BINDIR})
      else()
        set(destination ${CMAKE_INSTALL_LIBDIR})
      endif()
    endif()

    install(CODE "set(library_name ${library_name})" COMPONENT ${INSTALL_CONAN_LIBRARIES_COMPONENT})
    install(CODE "set(${library_name}_LIBRARY_LOCATION ${${library_name}_LIBRARY_LOCATION})" COMPONENT ${INSTALL_CONAN_LIBRARIES_COMPONENT})
    install(CODE "set(destination ${destination})" COMPONENT ${INSTALL_CONAN_LIBRARIES_COMPONENT})
    install(
      CODE  [[
      file(
        INSTALL
        "${${library_name}_LIBRARY_LOCATION}"
        DESTINATION "${CMAKE_INSTALL_PREFIX}/${destination}"
        FILE_PERMISSIONS
          OWNER_READ
          OWNER_WRITE
          OWNER_EXECUTE
          GROUP_READ
          GROUP_EXECUTE
          WORLD_READ
          WORLD_EXECUTE
        FOLLOW_SYMLINK_CHAIN
      )
      ]]
      COMPONENT ${INSTALL_CONAN_LIBRARIES_COMPONENT}
    )
  endforeach()
endfunction()
```