libxshmfence: generate gcc11 binaries
conan-io/conan-center-index pull request #14938
Opened 2022-12-25 22:50 UTC by ericLemanissier

Specify library name and version:  **libxshmfence/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-12-26 00:22 UTC, ericLemanissier commented
Why didn't the bot remove the `failed` label if all builds passed ?

2022-12-27 17:20 UTC, jwillikers requested changes

2022-12-27 17:20 UTC, jwillikers commented on recipes/libxshmfence/all/conanfile.py
> +        self.settings.rm_safe("compiler.cppstd")
Do you need to bump the `required_conan_version` to `1.53.0` for using `rm_safe`?

2022-12-27 22:41 UTC, closed without merging

2023-01-03 20:24 UTC, ericLemanissier commented
closed in favor of https://github.com/conan-io/conan-center-index/pull/14974