libraw: add version 0.21.0, support conan v2
conan-io/conan-center-index pull request #15026
Opened 2022-12-31 05:46 UTC by toge

Specify library name and version:  **libraw/***

- add version 0.21.0
- support conan v2

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-03 15:00 UTC, jwillikers requested changes

2023-01-03 15:00 UTC, jwillikers commented on recipes/libraw/all/conanfile.py
> +    license = "CDDL-1.0/LGPL-2.1-only"
Should these be separated out?

```suggestion
    license = "CDDL-1.0", "LGPL-2.1-only"
```

2023-01-06 19:47 UTC, jwillikers submitted a review, later dismissed

2023-01-08 04:44 UTC, jwillikers approved these changes

2023-01-14 03:52 UTC, prince-chrismc approved these changes

2023-01-14 05:45 UTC, merged