at-spi2-core 2.47.1
conan-io/conan-center-index pull request #15169
Opened 2023-01-09 09:35 UTC by ericLemanissier

Specify library name and version:  **at-spi2-core/2.47.1**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-09 21:36 UTC, prince-chrismc submitted a review, later dismissed

2023-01-10 17:02 UTC, jwillikers requested changes
You should probably add a `test_v1_package`, too.

2023-01-10 17:02 UTC, jwillikers commented on recipes/at-spi2-core/new/conanfile.py
```suggestion

required_conan_version = ">=1.52.0"
```

2023-01-10 17:34 UTC, ericLemanissier commented on recipes/at-spi2-core/new/conanfile.py
> +        self.copy(pattern="COPYING", dst="licenses", src=self.source_folder)
Is self.copy going away in conan 2? Otherwise I see this  change as a net regression. What is better with this new tool in this case ?

2023-01-10 19:40 UTC, jwillikers commented
@ericLemanissier Looking at this build failure:

```
-------- Computing dependency graph --------
ERROR: at-spi2-core/2.45.90: Error in configure() method, line 39
	del self.settings.compiler.libcxx
	ConanException: 'settings.compiler.libcxx' doesn't exist for 'msvc'
'settings.compiler' possible configurations are ['cppstd', 'runtime', 'runtime_type', 'toolset', 'update', 'version']
```

I wonder if using `self.info` for the settings and options in the `validate()` method would help. Might be worth a try.

2023-01-10 21:57 UTC, jwillikers submitted a review, later dismissed

2023-01-11 04:36 UTC, prince-chrismc commented
The v2 pipeline line is not running beta7 AFAIK so I will ask you to remove self.info from validate please :)

2023-01-11 04:36 UTC, prince-chrismc commented on recipes/at-spi2-core/new/conanfile.py
> +required_conan_version = ">=1.52.0"
With rm safe

```suggestion
required_conan_version = ">=1.53.0"
```

2023-01-11 04:38 UTC, prince-chrismc commented
Other wise this looks good 👍

2023-01-11 14:10 UTC, jwillikers approved these changes

2023-01-13 05:48 UTC, prince-chrismc approved these changes

2023-01-13 06:07 UTC, merged