bear 3.0.21
conan-io/conan-center-index pull request #15309
Opened 2023-01-16 16:24 UTC by ericLemanissier

Specify library name and version:  **bear/3.0.21**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-18 13:41 UTC, jwillikers requested changes
I think you should remove some of the comments, but otherwise looks good.

2023-01-18 13:41 UTC, jwillikers commented on recipes/bear/all/conanfile.py
> +    topics = ("compilation", "database")
```suggestion
    topics = ("clang", "compilation", "database", "llvm")
```

2023-01-18 13:41 UTC, jwillikers commented on recipes/bear/all/conanfile.py
> +        # BUILD_SHARED_LIBS and POSITION_INDEPENDENT_CODE are automatically parsed when self.options.shared or self.options.fPIC exist
I think you can remove these comments.

2023-01-18 13:41 UTC, jwillikers commented on recipes/bear/all/test_package/conanfile.py
> +# It will become the standard on Conan 2.x
I think this comment can be removed.

2023-01-18 13:51 UTC, ericLemanissier commented on recipes/bear/all/conanfile.py
> +        # BUILD_SHARED_LIBS and POSITION_INDEPENDENT_CODE are automatically parsed when self.options.shared or self.options.fPIC exist
```suggestion
```

2023-01-18 13:51 UTC, ericLemanissier commented on recipes/bear/all/test_package/conanfile.py
> +# It will become the standard on Conan 2.x
```suggestion
```

2023-01-18 17:35 UTC, jwillikers approved these changes

2023-01-20 04:44 UTC, prince-chrismc commented on recipes/bear/all/conandata.yml
> +    - patch_file: "patches/7de12540948cd5e0ee5f966b5cc383bc0c0e5fe9.diff"
I love patch fields 😍 hint hint

2023-01-20 04:46 UTC, prince-chrismc approved these changes

2023-01-20 05:11 UTC, merged

2023-05-13 13:37 UTC, SpaceIm commented
There is something wrong in this recipe. It let upstream CML downloads stuff at build time like fmt:

```
-- Looking for fmt dependency -- not found
-- Looking for spdlog dependency
-- Conan: Component target declared 'spdlog::spdlog'
-- Conan: Component target declared 'fmt::fmt'
-- Looking for spdlog dependency -- found
-- Looking for gRPC::grpc++ dependency
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'protobuf>=3.11;grpc++>=1.26'
--   Found protobuf, version 3.21.4
--   Found grpc++, version 1.50.1
-- Looking for gRPC::grpc++ dependency -- found
-- Looking for protoc
-- Looking for protoc -- found
-- Looking for grpc_cpp_plugin
-- Looking for grpc_cpp_plugin -- found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release
bear/3.0.21: CMake command: cmake --build "/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release" '--' '-j3'

----Running------
> . "/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/generators/conanbuild.sh" && cmake --build "/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release" '--' '-j3'
-----------------
Scanning dependencies of target grpc_dependency
Scanning dependencies of target googletest_dependency
Scanning dependencies of target nlohmann_json_dependency
[  0%] Built target grpc_dependency
[  0%] Built target googletest_dependency
[  0%] Built target nlohmann_json_dependency
Scanning dependencies of target fmt_dependency
Scanning dependencies of target spdlog_dependency
[  5%] Creating directories for 'fmt_dependency'
[  5%] Built target spdlog_dependency
[ 11%] Performing download step (download, verify and extract) for 'fmt_dependency'
-- Downloading...
   dst='/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release/subprojects/Download/fmt_dependency/9.1.0.tar.gz'
   timeout='none'
-- Using src='https://github.com/fmtlib/fmt/archive/9.1.0.tar.gz'
-- verifying file...
       file='/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release/subprojects/Download/fmt_dependency/9.1.0.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release/subprojects/Download/fmt_dependency/9.1.0.tar.gz'
     dst='/home/conan/w/prod/BuildSingleReference/.conan/data/bear/3.0.21/_/_/build/394f545e9cc458ec75d78c70083d1b2301255007/build/Release/subprojects/Source/fmt_dependency'
```