binutils: conan v2 support & v2.39 + v2.40
conan-io/conan-center-index pull request #15352
Opened 2023-01-18 23:39 UTC by StellaSmith

2023-01-19 00:18 UTC, StellaSmith commented
I don't know why ` continuous-integration/jenkins/pr-merge` fails without giving a reason.
And the linter is giving an error about an unknown kwarg when it does exist.
🤔

2023-01-19 22:29 UTC, StellaSmith commented
Interesting, `self.options.xxx == None` has different behavior in V1 & V2.
I should've used `not self.options.xxx` anyway.

2023-01-20 15:17 UTC, StellaSmith commented
Decided to drop the addition of the new versions as I don't know how to fix the build error.
They can be added as a separate pull request later on.

2023-01-24 03:08 UTC, StellaSmith commented
```
binutils/2.38 (test package): Calling build()
ERROR: binutils/2.38 (test package): Error in build() method, line 49
	if not os.path.isfile(self._test_package_assembly_source):
while calling '_test_package_assembly_source', line 37
	part_arch = self._target_arch
while calling '_target_arch', line 22
	return str(self.dependencies.build[self.tested_reference_str].options.target_arch)
	AttributeError: 'NoneType' object has no attribute 'dependencies'
```
@SpaceIm any idea as to what is happening here?

2023-01-24 08:44 UTC, SpaceIm commented
> ```
> binutils/2.38 (test package): Calling build()
> ERROR: binutils/2.38 (test package): Error in build() method, line 49
> 	if not os.path.isfile(self._test_package_assembly_source):
> while calling '_test_package_assembly_source', line 37
> 	part_arch = self._target_arch
> while calling '_target_arch', line 22
> 	return str(self.dependencies.build[self.tested_reference_str].options.target_arch)
> 	AttributeError: 'NoneType' object has no attribute 'dependencies'
> ```
> 
> @SpaceIm any idea as to what is happening here?

I know that `conanfile.dependencies` is  undefined in several methods of test package like test() at least.

2023-01-24 15:08 UTC, StellaSmith commented
> I know that `conanfile.dependencies` is undefined in several methods of test package like test() at least.

Even if that's the case, the stacktrace says that `self` is `None` if i understand it right

2023-02-02 15:12 UTC, StellaSmith commented
@ericLemanissier @prince-chrismc
Linter seems to be failing here too. It does not recognize the `stdout` kwarg of `ConanFile.run`.

2023-02-02 15:36 UTC, StellaSmith commented
Since it seems that its impossible to use `ConanFile.dependencies` inside a `test_package` in cci, I would just simplify the tests for v2.

2023-02-03 15:13 UTC, uilianries commented
> Since it seems that its impossible to use ConanFile.dependencies inside a test_package in cci, I will just simplify the tests for v2.

@StellaSmith It's possible, but needs a trick:

https://github.com/conan-io/conan-center-index/blob/master/recipes/catch2/2.x.x/test_package/conanfile.py#L37

2023-02-03 15:20 UTC, StellaSmith commented
> > Since it seems that its impossible to use ConanFile.dependencies inside a test_package in cci, I will just simplify the tests for v2.
> 
> @StellaSmith It's possible, but needs a trick:
> 
> https://github.com/conan-io/conan-center-index/blob/master/recipes/catch2/2.x.x/test_package/conanfile.py#L37

I can't say i like this solution. This is just a hack to go around the fact that v2 tests are ran using a v1 runner.

I would prefer just having it this way as this is what most tests do for packaged build tools.

If you think otherwise just tell me and I will add it.

2023-02-04 17:16 UTC, prince-chrismc commented
> Since it seems that its impossible to use `ConanFile.dependencies` inside a `test_package` in cci, I will just simplify the tests for v2.

Not its possible  the new attribute is just limited to the methods where the complete graph is know.

2023-02-04 17:17 UTC, prince-chrismc commented
I've been meaning to try this https://github.com/conan-io/conan-center-index/pull/15091#issuecomment-1372798369 which should look much better then the current saving a file

2023-02-04 17:18 UTC, prince-chrismc commented
There's no v2 test... just  a general one... and the new generators are designed to work by saving a file. It's just hidden by the helpers and provided toolchain

2023-02-04 17:28 UTC, SpaceIm commented
There is a far more elegant solution in boost recipe.

2023-02-04 18:46 UTC, SpaceIm requested changes

2023-02-04 18:46 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
>              self.build_requires("msys2/cci.latest")
```suggestion
        if self._settings_build.os == "Windows":
            self.win_bash = True
            if not self.conf.get("tools.microsoft.bash:path", check_type="str"):
                self.tool_requires("msys2/cci.latest")
```

2023-02-04 18:46 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
> +        get(self, **self.conan_data["sources"][self.version], strip_root=True, destination=self.source_folder)
```suggestion
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
```

2023-02-04 18:46 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
> +        tc.configure_args.append(f"--with-zlib={self.dependencies['zlib'].package_folder}")
```suggestion
        tc.configure_args.append(f"--with-zlib={unix_path(self, self.dependencies['zlib'].package_folder)}")
```

2023-02-04 18:46 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
> +        self.buildenv_info.append_path("PATH", absolute_target_bindir)
```suggestion
```

2023-02-04 18:51 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
> +        self.conf_info.define("user.binutils:recipe_path",  os.path.realpath(__file__))
Honestly, is it really used in any downstream recipe? Maybe user_info stuff have not been translated to conf because it was useless?

2023-02-04 18:57 UTC, SpaceIm commented on recipes/binutils/all/conanfile.py
>  required_conan_version = ">=1.52.0"
```suggestion
required_conan_version = ">=1.54.0"
```

1.53 for rm_safe, 1.54 for autotools install on Windows

2023-02-08 05:24 UTC, prince-chrismc approved these changes

2023-02-10 03:56 UTC, prince-chrismc approved these changes

2023-02-10 03:56 UTC, prince-chrismc commented
v2 passing 🚀

2023-02-10 14:38 UTC, merged