[rtmidi] conan v2 migration
conan-io/conan-center-index pull request #15376
Opened 2023-01-20 11:47 UTC by MartinDelille

Specify library name and version:  **rtmidi**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-02-13 11:56 UTC, uilianries approved these changes
LGTM

2023-02-13 13:51 UTC, jwillikers requested changes
Looks good.

2023-02-13 13:51 UTC, jwillikers commented on recipes/rtmidi/all/conanfile.py
>              self.build_requires("pkgconf/1.7.4")
Github won't let me suggest changing the previous line here, too, but could you change it to this to only require `pkgconf` when it's not configured directly in Conan?

```suggestion
        if self._with_alsa and not self.conf.get("tools.gnu:pkg_config", default=False, check_type=str):
            self.tool_requires("pkgconf/1.9.3")
```

2023-02-13 13:51 UTC, jwillikers commented on recipes/rtmidi/all/test_package/conanfile.py
> +# It will become the standard on Conan 2.x
Can you remove this comment?

2023-02-14 15:08 UTC, jwillikers approved these changes

2023-02-16 12:50 UTC, uilianries approved these changes
LGTM

2023-02-16 13:08 UTC, merged