aaf: conan v2 support
conan-io/conan-center-index pull request #15441
Opened 2023-01-23 21:19 UTC by SpaceIm

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-25 14:05 UTC, jwillikers approved these changes

2023-01-29 09:59 UTC, MartinDelille requested changes

2023-01-29 09:59 UTC, MartinDelille commented on recipes/aaf/all/conanfile.py
> +        tc = CMakeToolchain(self)
```suggestion
        tc = CMakeToolchain(self)
        arch = "x86_64"
```

2023-01-29 09:59 UTC, MartinDelille commented on recipes/aaf/all/conanfile.py
> +            tc.cache_variables["PLATFORM"] = "apple-clang"
```suggestion
            tc.cache_variables["PLATFORM"] = "apple-clang"
            if self.settings.arch == "armv8":
                arch = "arm64"
```

2023-01-29 09:59 UTC, MartinDelille commented on recipes/aaf/all/conanfile.py
> +            tc.cache_variables["PLATFORM"] = "vc"
```suggestion
            tc.cache_variables["PLATFORM"] = "vc"
            arch = "x64"
```

2023-01-29 09:59 UTC, MartinDelille commented on recipes/aaf/all/conanfile.py
> +        tc.cache_variables["ARCH"] = "x86_64"  # ARCH is used only for setting the output directory. So itsvalue does not matter here.
```suggestion
        tc.cache_variables["ARCH"] = arch
```

2023-01-29 09:59 UTC, MartinDelille commented on recipes/aaf/all/conanfile.py
>              raise ConanInvalidConfiguration("ARM v8 not supported")
Apple Silicon is supported since 1.2.0 RC1: https://sourceforge.net/p/aaf/code2/ci/master/tree/

2023-01-29 10:57 UTC, SpaceIm commented
@MartinDelille it's out of scope of this PR, but I've added macOS M1 support.

2023-01-31 14:22 UTC, uilianries approved these changes
LGTM

2023-01-31 14:25 UTC, jwillikers approved these changes

2023-02-01 10:02 UTC, franramirez688 approved these changes

2023-02-01 10:27 UTC, MartinDelille approved these changes

2023-02-01 12:35 UTC, merged