openssl: fix libdir for Android
conan-io/conan-center-index pull request #15483
Opened 2023-01-26 13:34 UTC by kletoz

Specify library name and version: **openssl/1.x.x**

When building libcurl it cannot find lcrypto and lssl because they installed over lib64 and not lib.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-26 13:41 UTC, kletoz commented
Here is the log:

<details>
<summary>conan install libcurl/7.87.0@ -pr:b default -pr:h android --build missing</summary>

```
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=c++_static
compiler.version=9
os=Android
os.api_level=24
[options]
[build_requires]
*: android-ndk/r21d
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: libcurl/7.87.0
Requirements
    libcurl/7.87.0 from 'conancenter' - Cache
    openssl/1.1.1s from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
Packages
    libcurl/7.87.0:a08ea9e1dd879beff551ed2dd7864467a6dababf - Build
    openssl/1.1.1s:7e07587cf845759043ce7a953a8a9093b20c238d - Build
    zlib/1.2.13:7e07587cf845759043ce7a953a8a9093b20c238d - Build
Build requirements
    android-ndk/r21d from 'conancenter' - Cache
    autoconf/2.71 from 'conancenter' - Cache
    automake/1.16.5 from 'conancenter' - Cache
    libtool/2.4.7 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    pkgconf/1.9.3 from 'conancenter' - Cache
Build requirements packages
    android-ndk/r21d:4db1be536558d833e52e862fd84d64d75c2b3656 - Cache
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.5:258f6f05ca54813b3d7180161753df7f9ccf7e1d - Cache
    libtool/2.4.7:00ffeae55ec276f0fef26ad0ed5cd0191ca724ce - Cache
    m4/1.4.19:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    pkgconf/1.9.3:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
Cross-build from 'Linux:x86_64' to 'Android:x86_64'
Installing (downloading, building) binaries...
android-ndk/r21d: Already installed!
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: /root/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
pkgconf/1.9.3: Already installed!
pkgconf/1.9.3: Appending PATH env var: /root/.conan/data/pkgconf/1.9.3/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
pkgconf/1.9.3: Setting PKG_CONFIG env var: /root/.conan/data/pkgconf/1.9.3/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/pkgconf
pkgconf/1.9.3: Appending AUTOMAKE_CONAN_INCLUDES env var: /root/.conan/data/pkgconf/1.9.3/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/aclocal
autoconf/2.71: Already installed!
autoconf/2.71: Defining AC_MACRODIR environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/res/autoconf
autoconf/2.71: Defining autom4te_perllibdir environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/res/autoconf
autoconf/2.71: Defining AUTOCONF environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoconf
autoconf/2.71: Defining AUTORECONF environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoreconf
autoconf/2.71: Defining AUTOHEADER environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoheader
autoconf/2.71: Defining AUTOM4TE environment variable: /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autom4te
openssl/1.1.1s: Applying build-requirement: android-ndk/r21d
Downloading conan_sources.tgz completed [0.41k]
Decompressing conan_sources.tgz completed [0.00k]
openssl/1.1.1s: Configuring sources in /root/.conan/data/openssl/1.1.1s/_/_/source/src
Downloading openssl-1.1.1s.tar.gz completed [9637.68k]                                   openssl/1.1.1s: enssl/1.1.1s:
openssl/1.1.1s:
openssl/1.1.1s: Copying sources to build folder
openssl/1.1.1s: Building your package in /root/.conan/data/openssl/1.1.1s/_/_/build/7e07587cf845759043ce7a953a8a9093b20c238d
openssl/1.1.1s: Generator txt created conanbuildinfo.txt
openssl/1.1.1s: Calling generate()
openssl/1.1.1s: Aggregating env generators
openssl/1.1.1s: Calling build()
openssl/1.1.1s: Apply patch (portability): TVOS and WatchOS don't like fork()
openssl/1.1.1s: gen_info = {'CFLAGS': ['-fPIC', '--sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot', '-O3'], 'CXXFLAGS': ['-fPIC', '--sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot', '-O3'], 'DEFINES': ['NDEBUG'], 'LDFLAGS': ['--sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot']}
openssl/1.1.1s: using target: conan-Release-Android-x86_64-clang-9 -> linux-x86_64-clang
openssl/1.1.1s: my %targets = (
    "conan-Release-Android-x86_64-clang-9" => {
        inherit_from => [ "linux-x86_64-clang" ],
        cflags => add("-fPIC --sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot -O3"),
        cxxflags => add("-fPIC --sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot -O3"),
        defines => add(["NDEBUG"]),
        includes => add(),
        lflags => add("--sysroot /root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot"),



        cc => "/root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang",
        cxx => "/root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang++",
        ar => "/root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar",
        ranlib => "/root/.conan/data/android-ndk/r21d/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ranlib",
        perlasm_scheme => "elf",
    },
);

openssl/1.1.1s: ['"conan-Release-Android-x86_64-clang-9"', 'no-shared', '--prefix=/', '--openssldir="res"', 'no-unit-test', 'threads', 'PERL=perl', 'no-tests', '--release', ' -D__ANDROID_API__=24', '-fPIC', 'no-md2']
Configuring OpenSSL version 1.1.1s (0x1010113fL) for conan-Release-Android-x86_64-clang-9
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

... (OpenSSL build log) ...

install libcrypto.a -> /root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/libcrypto.a
install libssl.a -> /root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/libssl.a
created directory `/root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/pkgconfig'
install libcrypto.pc -> /root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/pkgconfig/libcrypto.pc
install libssl.pc -> /root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/pkgconfig/libssl.pc
install openssl.pc -> /root/.conan/data/openssl/1.1.1s/_/_/package/7e07587cf845759043ce7a953a8a9093b20c238d//lib64/pkgconfig/openssl.pc
openssl/1.1.1s package(): Packaged 104 '.h' files
openssl/1.1.1s package(): Packaged 3 files: LICENSE, c_rehash, openssl
openssl/1.1.1s package(): Packaged 2 '.a' files: libcrypto.a, libssl.a
openssl/1.1.1s package(): Packaged 3 '.pc' files: libcrypto.pc, libssl.pc, openssl.pc
openssl/1.1.1s package(): Packaged 1 '.cmake' file: conan-official-openssl-variables.cmake
openssl/1.1.1s: Package '7e07587cf845759043ce7a953a8a9093b20c238d' create [...]

2023-01-26 14:06 UTC, kletoz commented
@uilianries @danimtb @RubenRBS @SpaceIm @prince-chrismc

could help me to understand what is the error in the Conan v1 pipeline, build 1?

```
Error running command conan upload openssl/1.1.1q@#473763efe7852f9f18f9a2890a2cdecf -r c3i_PR-15483
```

2023-01-27 13:48 UTC, uilianries approved these changes

2023-01-27 13:49 UTC, uilianries commented
@kletoz It should be an internal error, like bad networking. I just restart the CI job. Thank you for reporting us!

2023-01-27 13:50 UTC, uilianries commented
> When building libcurl it cannot find lcrypto and lssl because they installed over lib64 and not lib.

@kletoz Do you have an associated issue or a build log which can prove that error? It would be nice to illustrate for future cases. Could you please paste here your build log error?

2023-01-27 14:18 UTC, kletoz commented
> @kletoz Do you have an associated issue or a build log which can prove that error? It would be nice to illustrate for future cases. Could you please paste here your build log error?

The logs I posted here https://github.com/conan-io/conan-center-index/pull/15483#issuecomment-1405023138 have the build error.

2023-01-27 16:35 UTC, prince-chrismc submitted a review, later dismissed

2023-01-27 17:31 UTC, SpaceIm requested changes
It should be `lib` regardless of settings.

2023-01-27 17:31 UTC, SpaceIm commented on recipes/openssl/1.x.x/conanfile.py
> +        if self.settings.os in ["Linux", "Android"] and self.settings.arch == "x86_64":
```suggestion
```

2023-01-27 17:31 UTC, SpaceIm commented on recipes/openssl/1.x.x/conanfile.py
>              args.append("--libdir=lib") # See https://github.com/openssl/openssl/blob/master/INSTALL.md#libdir
```suggestion
        args.append("--libdir=lib") # See https://github.com/openssl/openssl/blob/master/INSTALL.md#libdir
```

2023-01-27 17:36 UTC, kletoz commented
> It should be `lib` regardless of settings.

Is it safe for all? I was trying to follow the previous pattern for Linux.

2023-01-27 18:06 UTC, SpaceIm commented
> > It should be `lib` regardless of settings.
> 
> Is it safe for all? I was trying to follow the previous pattern for Linux.

Yes it is safe for all, it must be `lib` for all.

2023-01-30 13:21 UTC, kletoz commented
@SpaceIm could you help me to understand why `continuous-integration/jenkins/pr-merge` is failing? I cannot see the logs.

2023-02-01 07:56 UTC, SpaceIm approved these changes

2023-02-01 10:41 UTC, uilianries approved these changes
@kletoz now it passed.

2023-02-01 15:30 UTC, merged