[sentry-breakpad/0.5.4] Bump version
conan-io/conan-center-index pull request #15491
Opened 2023-01-26 19:47 UTC by MartinDelille

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-01-27 11:19 UTC, RubenRBS requested changes
Quick fix for this

2023-01-27 11:19 UTC, RubenRBS commented on recipes/sentry-breakpad/all/conanfile.py
> +            tools.check_min_cppstd(self, tools.Version(self.version) < "0.5.4" ? 11 : 17)
Oops :) Python's way is:

```suggestion
            tools.check_min_cppstd(self, 11 if tools.Version(self.version) < "0.5.4" else 17)
```

2023-02-02 08:05 UTC, SpaceIm commented on recipes/sentry-breakpad/all/conanfile.py
> +        return 11 if Version(self.version < "0.5.4") else 17
```suggestion
        return 11 if Version(self.version) < "0.5.4" else 17
```

2023-02-02 08:06 UTC, SpaceIm commented on recipes/sentry-breakpad/all/conanfile.py
> +        return {} if Version(self.version < "0.5.4") else {
```suggestion
        return {} if Version(self.version) < "0.5.4" else {
```

2023-02-02 08:06 UTC, SpaceIm commented on recipes/sentry-breakpad/all/conanfile.py
> +            "apple-clang": "10",
```suggestion
            "apple-clang": "10",
            "Visual Studio": "15",
            "msvc": "191",
```

2023-02-02 08:10 UTC, SpaceIm commented on recipes/sentry-breakpad/all/conanfile.py
> +from conan.tools.microsoft import check_min_vs, is_msvc
```suggestion
```

2023-02-02 13:09 UTC, SpaceIm approved these changes

2023-02-02 14:02 UTC, jwillikers approved these changes

2023-02-03 15:26 UTC, MartinDelille commented
@RubenRBS Is it fine for you ?

2023-02-06 11:04 UTC, SSE4 approved these changes

2023-02-06 13:23 UTC, RubenRBS commented
Sorry about the delay, lgtm :)

2023-02-06 13:31 UTC, merged