libbpf: add version 0.7.0, support conan v2
conan-io/conan-center-index pull request #15683
Opened 2023-02-02 16:55 UTC by toge

Specify library name and version:  **libbpf/***

- add version 0.7.0 (there are API problem after 0.8.0)
- support conan v2

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-02-03 13:43 UTC, jwillikers requested changes

2023-02-03 13:43 UTC, jwillikers commented on recipes/libbpf/all/conanfile.py
> +    license = "LGPL-2.1", "BSD-2-Clause"
```suggestion
    license = "LGPL-2.1-only", "BSD-2-Clause"
```

2023-02-03 13:43 UTC, jwillikers commented on recipes/libbpf/all/conanfile.py
> +    topics = ("bpf", "ebpf", "berkeley-packet-filter")
```suggestion
    topics = ("berkeley-packet-filter", "bpf", "ebpf", "network", "tracing")
```

2023-02-12 04:42 UTC, prince-chrismc approved these changes

2023-02-12 06:26 UTC, merged