Add Eric's pr Status page
conan-io/conan-center-index pull request #15727
Opened 2023-02-04 22:00 UTC by prince-chrismc

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-02-06 08:12 UTC, ericLemanissier commented on docs/community_resources.md
> +- (Pull Request In Progress Status)[https://ericlemanissier.github.io/conan-center-pr-status/in_progress_jobs]
```suggestion
- [Pull Request In Progress Status](https://ericlemanissier.github.io/conan-center-pr-status/in_progress_jobs)
```

2023-02-06 12:32 UTC, ericLemanissier requested changes
link needs to be fixed

2023-02-06 16:32 UTC, ericLemanissier approved these changes

2023-02-06 17:27 UTC, Hopobcn approved these changes

2023-02-13 08:27 UTC, SSE4 approved these changes

2023-02-13 12:46 UTC, uilianries approved these changes
Amazing! 👏

2023-02-13 13:50 UTC, merged