xorg-proto: Add compatibility to v2
conan-io/conan-center-index pull request #15881
Opened 2023-02-10 14:39 UTC by RubenRBS

Specify library name and version:  **xorg-proto/all**

Needed by imake in #15880 for v2

2023-02-12 05:15 UTC, prince-chrismc commented on recipes/xorg-proto/all/conanfile.py
> +        if self._settings_build.os == "Windows" and not os.environ["CONAN_BASH_PATH"]:
🤔 should be a conf check now AFAIK

2023-02-12 05:16 UTC, prince-chrismc commented on recipes/xorg-proto/all/test_package/conanfile.py
> +    generators = "CMakeDeps", "AutotoolsDeps"
Autotools Deps but no CMakeToolchian?

2023-02-12 05:17 UTC, prince-chrismc commented on recipes/xorg-proto/all/conanfile.py
>          del self.info.settings.build_type
Should probably be package type application?

2023-02-13 16:39 UTC, prince-chrismc commented on recipes/xorg-proto/all/conanfile.py
> +        autotools.configure(build_script_folder=self.source_folder)
Should be n the build method :)

2023-02-13 16:40 UTC, prince-chrismc commented on recipes/xorg-proto/all/conanfile.py
> +        if self._settings_build.os == "Windows" and not os.environ["CONAN_BASH_PATH"]:
https://github.com/conan-io/conan-center-index/blob/044e188e95c82b9ff0e9bb71fdc9e1c9618b15c7/recipes/gumbo-parser/all/conanfile.py#L55-L58

2023-02-17 15:20 UTC, StellaSmith requested changes

2023-02-17 15:20 UTC, StellaSmith commented on recipes/xorg-proto/all/conanfile.py
> +            self.tool_requires("msys2/cci.latest")
```suggestion
        if self._settings_build.os == "Windows":
        self.win_bash = True
        if not self.conf.get("tools.microsoft.bash:path", check_type=str):
            self.tool_requires("msys2/cci.latest")
```

2023-02-17 19:19 UTC, StellaSmith approved these changes

2023-02-17 22:07 UTC, jcar87 approved these changes

2023-02-17 23:25 UTC, prince-chrismc approved these changes

2023-02-17 23:36 UTC, merged