libcurl: support for with-ca-fallback option
conan-io/conan-center-index pull request #16175
Opened 2023-02-20 14:41 UTC by PodnimatelPingvinov

Just one more option for libcurl package.

2023-02-20 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=16175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=16175) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=16175) it.</sub>

2023-02-20 15:13 UTC, SpaceIm requested changes
Prefer to have full control over options instead of relying implicitly on default upstream values.

2023-02-20 15:13 UTC, SpaceIm commented on recipes/libcurl/all/conanfile.py
> +            tc.cache_variables["CURL_CA_FALLBACK"] = True
```suggestion
        tc.cache_variables["CURL_CA_FALLBACK"] = self.options.with_ca_fallback
```

2023-02-20 15:37 UTC, PodnimatelPingvinov commented
> Prefer to have full control over options instead of relying implicitly on default upstream values.

Sure, that's make sense!

2023-03-21 10:57 UTC, Hopobcn approved these changes

2023-03-23 04:05 UTC, prince-chrismc approved these changes

2023-03-24 13:41 UTC, jwillikers approved these changes

2023-03-24 13:54 UTC, SpaceIm commented
PR should be closed/open to trigger CI again. openssl packages were missing, and this recipe must pass v2 pipeline.

2023-03-24 14:37 UTC, PodnimatelPingvinov commented
> PR should be closed/open to trigger CI again. openssl packages were missing, and this recipe must pass v2 pipeline.

I'm not sure about CI pipelines so should I rebase this PR on master and then close/open it or rebase isn't needed?

2023-03-24 15:08 UTC, prince-chrismc commented
No need for a rebase.

2023-03-31 01:04 UTC, merged