[doxygen] Add support for Doxygen version 1.9.6
conan-io/conan-center-index pull request #16310
Opened 2023-02-26 22:55 UTC by datalogics-robb

**doxygen/1.9.6**

Add support for the latest Doxygen version 1.9.6

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-03-29 12:00 UTC, samuel-emrys commented
@datalogics-robb could you rebase these changes on master? #16243 brought in some changes that will resolve your build errors

2023-03-30 16:27 UTC, datalogics-robb commented
In the Windows build output, I don't see an error, just warnings.

2023-04-04 10:32 UTC, samuel-emrys requested changes

2023-04-04 10:32 UTC, samuel-emrys commented on recipes/doxygen/all/conandata.yml
> +      patch_source: "https://github.com/doxygen/doxygen/commit/5198966c8d5fec89116d025c74934ac03ea511fa"
This is only relevant for 1.9.4 as per the name of the patch
```suggestion
```

2023-04-25 20:38 UTC, closed without merging