[linux-syscall-support] Update Conan v2 recipe
conan-io/conan-center-index pull request #16424
Opened 2023-03-07 14:22 UTC by MartinDelille

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-03-07 16:22 UTC, SpaceIm requested changes

2023-03-07 16:22 UTC, SpaceIm commented on recipes/linux-syscall-support/all/conanfile.py
> +        copy(self, pattern="linux_syscall_support.h", src=self.source_folder, dst="include")
```suggestion
    def _extract_license(self):
```

2023-03-07 16:22 UTC, SpaceIm commented on recipes/linux-syscall-support/all/conanfile.py
> +             "\n".join(license_content))
```suggestion
        return "\n".join(license_content)

    def package(self):
        save(self, os.path.join(self.package_folder, "licenses", "LICENSE"), self._extract_license())
        copy(self, "linux_syscall_support.h", src=self.source_folder, dst=os.path.join(self.package_folder, "include"))

    def package_info(self):
        self.cpp_info.bindirs = []
        self.cpp_info.libdirs = []
```

2023-03-07 16:24 UTC, SpaceIm commented
Could you also:
- remove ` conan` from `topics`
- add `package_type = "header-library"`

2023-03-07 21:06 UTC, SpaceIm approved these changes

2023-03-08 06:42 UTC, prince-chrismc approved these changes

2023-03-08 12:48 UTC, StellaSmith approved these changes

2023-03-10 19:15 UTC, merged