osqp: add recipe
conan-io/conan-center-index pull request #16469
Opened 2023-03-08 16:09 UTC by billyzheli

Specify library name and version:  **osqp/0.6.2**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-03-18 19:25 UTC, StellaSmith requested changes

2023-03-18 19:25 UTC, StellaSmith commented on recipes/osqp/all/conanfile.py
> +class PackageConan(ConanFile):
```suggestion
class OsqpConan(ConanFile):
```

2023-03-18 19:25 UTC, StellaSmith commented on recipes/osqp/all/conanfile.py
> +    name = "osqp"
```suggestion
    name = "osqp"
    package_type = "library"
```

2023-03-21 14:21 UTC, StellaSmith commented
Because you don't comply with two of the selection criteria anymore.
Also, please do not force push, makes reviewing harder. Your commits will be squashed into a single one once when the bots merges the pull request.

2023-03-21 15:34 UTC, danimtb approved these changes

2023-03-23 00:15 UTC, merged