libcurl: Curl with additional url to download certificate
conan-io/conan-center-index pull request #16673
Opened 2023-03-23 16:27 UTC by roalter

* Enable the recipe to download an alternative cacert during creation.
* Make  use of a commited cacert or at least ask the environment for CONAN_CA_BUNDLE, CURL_CA_BUNDLE or REQUESTS_CA_BUNDLE (python)

First attempt.

Specify library name and version:  **libcurl/***

**Question:** Why is the cacert.pem needed at all? Why not use the system certificates? 

the file was not used in any other recipe. 

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-03-23 19:52 UTC, roalter commented
Searched for usages of **ca_cert.pem** but didn't find them. Any ideas?

2023-04-20 10:14 UTC, RubenRBS commented
Hi @roalter thanks for your contribution and your patience while we processed the rest of the PR backlog. I see your idea behind the changes, and I'll send a PR for your branch to get this thru the finish line :)

2023-05-18 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=16673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=16673) before we can accept your contribution.<br/>**2** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: ericLemanissier<br/>:white_check_mark: uilianries<br/>:x: roalter<br/>:x: prince-chrismc<br/>:x: tylerjw<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=16673) it.</sub>

2023-05-19 10:06 UTC, RubenRBS requested changes

2023-05-19 10:06 UTC, RubenRBS commented on recipes/libcurl/all/conanfile.py
> +import shutil
```suggestion
```

2023-05-19 10:06 UTC, RubenRBS commented on recipes/libcurl/all/conanfile.py
> +        #download(self, filename="cacert.pem", **data)
Need to use the global conf

2023-05-19 10:07 UTC, uilianries requested changes
Thank you for your contribution. Indeed makes sense providing an alternative way to pass the certificate, but the current version needs improvements.

Blocking this PR until having a better solution proposed by @RubenRBS

2023-05-19 10:34 UTC, RubenRBS requested changes

2023-05-19 10:34 UTC, RubenRBS commented on recipes/libcurl/all/conanfile.py
> +        #download(self, filename="cacert.pem", **data)
```suggestion
        
        cert_url = self.config.get("user.libcurl.cert:url", check_type=str) or "https://curl.se/ca/cacert-2023-01-10.pem"
        cert_sha256 = self.config.get("user.libcurl.cert:sha256", check_type=str) or "fb1ecd641d0a02c01bc9036d513cb658bbda62a75e246bedbc01764560a639f0" 
        download(self, cert_url, "cacert.pem", verify=True, sha256=cert_sha256)
```

2023-05-19 10:34 UTC, RubenRBS requested changes

2023-05-19 10:34 UTC, RubenRBS commented on recipes/libcurl/all/conanfile.py
> +import shutil
```suggestion
```

2023-05-19 10:46 UTC, RubenRBS commented
Closing in favour of https://github.com/conan-io/conan-center-index/pull/17628 as this has some CLA issues, thanks a lot for the initial idea!

2023-05-19 10:46 UTC, closed without merging