ruy: update to support Conan 2.0
conan-io/conan-center-index pull request #16688
Opened 2023-03-24 17:24 UTC by jcar87

Specify library name and version:  **ruy/all**

Changes in this PR:

* Use newer Conan 2.0 integrations, while maintaining compatibility with Conan 1.x
* Remove older version which has outdated CMake scripts, with limitations. Newer versions are more "conventional modern cmake" - this allows us to remove workarounds to handle the cpuinfo dependency
* Add workaround to ensure that `cmake_minimum_required()` is the first thing called in the project - this is an upstream issue which has been reported: https://github.com/google/ruy/issues/328
* Bump dependency on cpuinfo to latest

2023-03-31 23:22 UTC, SpaceIm requested changes

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/conanfile.py
> +                destination=self.source_folder, strip_root=True)
```suggestion
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_v1_package/conanfile.py
> +    generators = "cmake", "cmake_find_package"
```suggestion
    generators = "cmake", "cmake_find_package_multi"
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_v1_package/CMakeLists.txt
> +set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)
```suggestion
cmake_minimum_required(VERSION 3.1)
project(test_package)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../test_package
                 ${CMAKE_CURRENT_BINARY_DIR}/test_package)
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_v1_package/test_package.cpp
> +#include <cstdint>
file to remove

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_package/conanfile.py
> +    generators = "CMakeDeps", "VirtualRunEnv"
```suggestion
    generators = "CMakeDeps", "CMakeToolchain", "VirtualRunEnv"
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_package/conanfile.py
> +        tc.generate()
```suggestion
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_package/CMakeLists.txt
> +
```suggestion
target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_11)
```

2023-03-31 23:22 UTC, SpaceIm commented on recipes/ruy/all/test_package/CMakeLists.txt
>  find_package(ruy REQUIRED)
```suggestion
find_package(ruy REQUIRED CONFIG)
```

2023-04-11 13:13 UTC, czoido submitted a review, later dismissed

2023-04-12 09:33 UTC, RubenRBS approved these changes

2023-04-12 09:49 UTC, merged