libuvc: add version 0.0.7
conan-io/conan-center-index pull request #17041
Opened 2023-04-16 16:23 UTC by toge

Specify library name and version:  **libuvc/***

- add version 0.0.7
- add package_type

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-04-17 05:02 UTC, prince-chrismc commented on recipes/libuvc/all/patches/0.0.7-0001-fix-cci-packagename.patch
> ++    PRIVATE libusb::libusb ${threads}
We could remove the patches and have CMakeDeps set the correct name in the generate method too 🙏

2023-04-17 05:04 UTC, prince-chrismc reviewed
There's a TODO for PKG_CONFIG that was fixed in 1.55 

https://github.com/conan-io/conan/commit/559bca1bc885f38b5ba8320d0c8d636d32491558

2023-04-17 05:06 UTC, prince-chrismc commented
https://github.com/conan-io/conan-center-index/pull/17043 for v2 🤞

2023-04-30 12:24 UTC, toge commented
@prince-chrismc 
Sorry, I don't know what to do for this PR.
libusb package doesn't provide LibUSB::LibUSB yet.
Please tell me the way to improve this PR.

2023-05-09 15:06 UTC, RubenRBS approved these changes

2023-05-09 15:06 UTC, RubenRBS commented
I had to regenerate libusb packages for this to pass, sorry about that :)

2023-05-09 15:07 UTC, danimtb submitted a review, later dismissed

2023-05-09 15:08 UTC, RubenRBS requested changes

2023-05-09 15:08 UTC, RubenRBS commented on recipes/libuvc/all/conanfile.py
> +            tc.variables["BUILD_EXAMPLE "] = False
Is the extra space here a typo?

2023-05-09 15:09 UTC, RubenRBS approved these changes

2023-05-09 15:09 UTC, danimtb approved these changes

2023-05-09 21:25 UTC, merged