flatbuffers/23.3.3
conan-io/conan-center-index pull request #17313
Opened 2023-04-29 14:05 UTC by ilya-lavrenov

Specify library name and version:  **flatbuffers/23.3.3**

Since this [PR](https://github.com/google/flatbuffers/pull/7801) minimal version is 3.8

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-01 16:35 UTC, jwillikers submitted a review, later dismissed

2023-05-03 20:48 UTC, ilya-lavrenov commented
Let's merge

2023-05-07 20:25 UTC, ilya-lavrenov commented
Hi @SpaceIm 
Could you please help with merging of this PR?

2023-05-08 10:14 UTC, SpaceIm requested changes

2023-05-08 10:14 UTC, SpaceIm commented on recipes/flatbuffers/all/conanfile.py
>          if Version(self.version) >= "2.0.7":
```suggestion
        if Version(self.version) >= "2.0.7" and Version(self.version) < "23.3.3":
```

2023-05-08 10:14 UTC, SpaceIm commented on recipes/flatbuffers/all/conanfile.py
> +            self.tool_requires(f"cmake/[>={required_cmake_version} <4]")
```suggestion
            self.tool_requires("cmake/[>=3.16 <4]")
```

2023-05-08 15:48 UTC, ilya-lavrenov commented on recipes/flatbuffers/all/conanfile.py
>          if Version(self.version) >= "2.0.7":
fixed.

2023-05-08 19:06 UTC, jwillikers submitted a review, later dismissed

2023-05-10 11:55 UTC, SpaceIm approved these changes

2023-05-10 12:58 UTC, jcar87 requested changes
This looks good, but I can't find any context as to why the cmake tool_requirement is only applied until version `23.3.3`? What is it not needed for newer versions?
is there something that we can reproduce that does not work unless these changes are merged? thanks!

2023-05-10 13:23 UTC, jcar87 commented on recipes/flatbuffers/all/conanfile.py
>              self.tool_requires("cmake/[>=3.16 <4]")
```suggestion
        if Version(self.version) >= "2.0.7" and Version(self.version) < "23.3.3":
            # This version range of flatbuffers de-facto required CMake 3.16 or newer.
            # Newer versions of flatbuffers are compatible with CMake 3.8 or newer,
            # so we don't need an explicit tool_requires on cmake
            self.tool_requires("cmake/[>=3.16 <4]")
```

2023-05-10 13:28 UTC, jcar87 submitted a review, later dismissed
Thanks for your contribution @ilya-lavrenov.

I've updated the PR description with more information as provided by @SpaceIm, as well as added comments in the recipe for future maintainers to see.

Please note that in the future, PRs that are introducing changes that are not sufficiently motivated or explained in the PR description will not be considered or prioritized for review by Conan Center maintainers.

2023-05-10 13:34 UTC, ilya-lavrenov commented
> I've updated the PR description with more information as provided by @SpaceIm, as well as added comments in the recipe for future maintainers to see.

I don't know where you have been looking for, but original description contained information about that change in flatbuffers.

2023-05-10 13:36 UTC, jwillikers approved these changes

2023-05-10 13:42 UTC, jcar87 commented
> > I've updated the PR description with more information as provided by @SpaceIm, as well as added comments in the recipe for future maintainers to see.
> 
> I don't know where you have been looking for, but original description contained information about that change in flatbuffers.

HI @ilya-lavrenov - indeed there was a link to a PR in flatbuffers - however, it didn't mention which version was the first to include these changes, nor provided context as to why older versions required version 3.16 (which I appreciate is not part of this PR so that's beyond the scope) nor does it explain what we gain with the removal (even if CMake was listed as a tool_requires, the recipe still builds fine from source). 

It greatly helps us provide speedy reviews if the require context to evaluate the pull request is provided in the description. 

Thanks for your contribution!

2023-05-12 08:21 UTC, jcar87 requested changes
Please add a comment in the recipe clarifying this for future maintainers! thanks
I've left a suggestion on line 63

2023-05-12 13:26 UTC, jcar87 approved these changes

2023-05-13 13:24 UTC, merged