Add Boost 1.82.0
conan-io/conan-center-index pull request #17471
Opened 2023-05-09 12:52 UTC by jhunold

Boost/1.82.0

Bump the supported Boost version to the latest release. Needed by everybody.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-09 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17471) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17471) before we can accept your contribution.<br/><hr/>**Jürgen Hunold** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=17471) it.</sub>

2023-05-09 15:51 UTC, SSE4 submitted a review, later dismissed

2023-05-09 20:05 UTC, gegles submitted a review, later dismissed
LGTM, thanks!

2023-05-13 18:52 UTC, fpelliccioni commented
Guys, what happened with the checks?

2023-05-14 01:01 UTC, RubenRBS requested changes
As mentioned by @jwillikers:

> There's still the need to pull in the official patches 283 and 284 described on the [release page](https://www.boost.org/users/history/version_1_82_0.html).

2023-05-15 00:59 UTC, RubenRBS approved these changes

2023-06-02 11:32 UTC, jcar87 commented
The error is this:
```
/home/conan/w/prod/BuildSingleReference/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build/property.jam:354: in validate1 from module property
error: Invalid property '<boost.locale.iconv.lib>libc': unknown feature 'boost.locale.iconv.lib'.
```

which comes from these lines in the recipe:
https://github.com/conan-io/conan-center-index/blob/1f61f4e73bf2f8cf463f88e0819cefbfe98e45ee/recipes/boost/all/conanfile.py#L1009-L1012

which only work with this patch:
https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/patches/1.81.0-locale-fail-on-missing-backend.patch

I'm not sure the description this particular patch is correct, but I imagine the build cannot be configured with those arguments if this patch is not applied.

2023-06-02 15:29 UTC, jcar87 approved these changes

2023-06-02 15:29 UTC, jcar87 commented
Awesome, that did it. Thanks so much for your contribution @jhunold !

In order for this to be merge, please review the contributor license agreement! https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17471

2023-06-04 13:03 UTC, merged