[qt/6.x.x] V2 migration
conan-io/conan-center-index pull request #17539
Opened 2023-05-12 09:52 UTC by MartinDelille

- Remove qt/6.2.4
- [qt/6.x.x] Conan v2

Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-12 13:29 UTC, jwillikers approved these changes

2023-05-13 15:39 UTC, jwillikers approved these changes

2023-05-17 06:01 UTC, ericLemanissier approved these changes

2023-05-17 13:41 UTC, jwillikers approved these changes

2023-05-18 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17539) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ericLemanissier<br/>:x: MartinDelille<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=17539) it.</sub>

2023-06-01 15:12 UTC, MartinDelille commented
@uilianries Would you have time to review this PR ?

2023-06-06 15:40 UTC, nrbnlulu requested changes
Thanks for the PR hopefully will be merged soon

2023-06-06 15:40 UTC, nrbnlulu commented on recipes/qt/6.x.x/test_v1_package/CMakeLists.txt
> +set(CMAKE_AUTORCC ON)
duplicated

2023-06-06 15:40 UTC, nrbnlulu commented on recipes/qt/6.x.x/test_v1_package/conanfile.py
> +    def _is_mingw(self):
All of these can be `@cached_property`

2023-06-06 15:40 UTC, nrbnlulu commented on recipes/qt/6.x.x/test_v1_package/conanfile.py
> +        if not self._qmake_supported():
I'm not sure why you do this check here and not in `build()`?

2023-06-06 15:40 UTC, nrbnlulu commented on recipes/qt/6.x.x/test_v1_package/conanfile.py
> +        if not self._qmake_supported():
same here, can be done in `test()`...

2023-06-09 07:09 UTC, uilianries reviewed
Thank you for your contribution, but I see as a big losing by not having an embedded generator as before. People needing to manage .conf file with all attributes now, will break current project using Qt package for sure.

2023-06-09 07:09 UTC, uilianries commented on recipes/qt/6.x.x/test_package/conanfile.py
> +        path = self.deps_cpp_info["qt"].rootpath.replace("\\", "/")
```suggestion
        path = self.dependencies["qt"].package_folder.replace("\\", "/")
```
deps_cpp_info is Conan 1.x

2023-06-09 07:09 UTC, uilianries commented on recipes/qt/6.x.x/test_package/conanfile.py
> +Prefix = {path}
why do you need to add this configuration file only now?

2023-06-09 13:25 UTC, MartinDelille commented
> Thank you for your contribution, but I see as a big losing by not having an embedded generator as before. People needing to manage .conf file with all attributes now, will break current project using Qt package for sure.

@uilianries From what I understand it was not possible to add a generator in a conanfile.py with conan v2. I based my work on the qt5 migration here: https://github.com/conan-io/conan-center-index/pull/16404

2023-06-12 10:27 UTC, uilianries commented
@MartinDelille Is it qmake generator or another custom generator? Asking because qmake is not included in Conan 2.x yet, but there is a feature asking for, maybe, that's the best opportunity to implement it.

2023-06-12 14:19 UTC, jwillikers commented
@uilianries Qt 6 migrated to CMake, fyi.

2023-06-12 16:18 UTC, uilianries approved these changes
LGTM

2023-06-12 16:19 UTC, uilianries commented
> @uilianries Qt 6 migrated to CMake, fyi.

Thank you, now it's clear.

2023-06-12 17:43 UTC, merged

2023-06-17 21:39 UTC, rob-avalon commented
```
ERROR: qt/6.5.0: Error in source() method, line 598
	if self.settings.os == "Windows":
	ConanException: 'self.settings' access in 'source()' method is forbidden
```

Found a [discussion](https://cpplang.slack.com/archives/C41CWV9HA/p1683721172937099) on why self.setting is forbidden in sources. 

> because once the sources are downloaded, they are kept in local cache, so they are re-used as-is when building other 
> configurations on the same computer (debug, release, compiler etc.)

> the best way is to download sources in the build method in this case. Like this your are safe, you always download sources
> matching your current settings

Sounds like the work around may be to move [these few lines](https://github.com/conan-io/conan-center-index/blob/b77038bdaee9ac6a67a6585032767d7aeb1b74ca/recipes/qt/6.x.x/conanfile.py#LL598C9-L598C9) into `build()`? Does that make sense to anyone?

Looking in conan center index [it looks like most recipes](https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+apply_conandata_patches&type=code&p=1) call `apply_conandata_patches` in the `build()` method, which also seems to line up with that suggestion.

I don't have any experience writing packages, but maybe that could help someone figure out why 6.5.0 failed in v2

2023-06-18 18:25 UTC, sabelka commented
I think "settings_build" should be used here instead. When cross-compiling eg. on a Linux build system for a Windows target one doesn't need this hack for long paths.

2023-06-19 07:53 UTC, ericLemanissier commented
I added the `settings_build` change in https://github.com/conan-io/conan-center-index/pull/17942