trantor: include cstdint
conan-io/conan-center-index pull request #17647
Opened 2023-05-22 01:17 UTC by toge

Specify library name and version:  **trantor/***

- inclue stdint for uint8_t and intmax_t

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-22 08:58 UTC, RubenRBS requested changes

2023-05-22 08:58 UTC, RubenRBS commented on recipes/trantor/all/conandata.yml
> +      patch_type: "portability"
Adding patch sources helps for future maintenance :)

```suggestion
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
  "1.5.10":
    - patch_file: "patches/1.5.6-0001-include-cstdint.patch"
      patch_description: "include cstdint for uint8_t, intmax_t"
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
  "1.5.8":
    - patch_file: "patches/1.5.6-0001-include-cstdint.patch"
      patch_description: "include cstdint for uint8_t, intmax_t"
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
  "1.5.7":
    - patch_file: "patches/1.5.6-0001-include-cstdint.patch"
      patch_description: "include cstdint for uint8_t, intmax_t"
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
  "1.5.6":
    - patch_file: "patches/1.5.6-0001-include-cstdint.patch"
      patch_description: "include cstdint for uint8_t, intmax_t"
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
  "1.5.5":
    - patch_file: "patches/1.5.5-0001-include-cstdint.patch"
      patch_description: "include cstdint for uint8_t"
      patch_type: "portability"
      patch_source: "https://github.com/an-tao/trantor/commit/e8e3887435dcfb310263c588743be1b3746193be"
```

2023-05-22 12:50 UTC, RubenRBS approved these changes

2023-05-23 05:41 UTC, SSE4 approved these changes

2023-05-23 07:02 UTC, merged