benchmark: add pfm option
conan-io/conan-center-index pull request #17702
Opened 2023-05-25 14:57 UTC by andioz

Specify library name and version:  **benchmark/1.8.0**

Benchmark has an build option for enabling performance counters: https://github.com/google/benchmark/blob/v1.5.4/docs/perf_counters.md

We want to use this feature, therefore I try to add an option which is disabled by default. As far as I have seen this is currently only for Linux supported, and requires the "libpfm4" library, which is available via Conan. This feature was added with version 1.5.4, therefore I include a version check too (even if our supported versions starts with a higher version number). 

Some time past by since I mad my last contribution, and this is my very first in the time of Conan 2.x - I hope I did everything in the right way, please correct me if not.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-25 14:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17702) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=17702) it.</sub>

2023-05-25 16:34 UTC, Hopobcn approved these changes

2023-05-26 06:15 UTC, RubenRBS requested changes
Requesting changes until the linked PR is merged so this gets the latest revision :)

2023-05-26 16:02 UTC, andioz commented
> Requesting changes until the linked PR is merged so this gets the latest revision :)

Do you plan to update the libpfm version too? (4.13.0 is available)

2023-05-26 16:52 UTC, RubenRBS commented
Ah I missed that, yes! Will do

2023-05-29 13:53 UTC, RubenRBS requested changes

2023-05-29 13:53 UTC, RubenRBS commented on recipes/benchmark/all/conanfile.py
> +            self.requires("libpfm4/4.12.0")
```suggestion
            self.requires("libpfm4/4.13.0")
```

2023-05-29 13:55 UTC, RubenRBS approved these changes

2023-05-29 14:22 UTC, jwillikers approved these changes

2023-05-29 16:42 UTC, merged