[sqlpp11] Update library to make it conan v2 compatible
conan-io/conan-center-index pull request #17754
Opened 2023-05-30 11:16 UTC by jwidauer

Specify library name and version:  **sqlpp11/0.61**

This PR updates the `sqlpp11` package to be conan v2 compatible.
The downgrade of the `date/*` version is due to the fact that the original codebase also just depends on version `3.0.0`, as can be seen [here](https://github.com/rbock/sqlpp11/blob/main/dependencies/CMakeLists.txt).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-05-30 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=17754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=17754) it.</sub>

2023-06-02 10:15 UTC, jwidauer commented
The build errors seem to be related to `sqlpp11/0.58` not being compatible with gcc version > 10 and also clang version > 10.
You can find the related PR [here](https://github.com/rbock/sqlpp11/pull/330), that fixed the issue, which first appeared in version 0.59.
What is the recommended way to approach this in conan? Just remove the broken version (0.58)?

2023-06-28 06:31 UTC, CJCombrink commented
It seems like this PR can be closed due to https://github.com/conan-io/conan-center-index/pull/17993 getting merged

2023-06-28 06:32 UTC, CJCombrink requested changes
Can be closed due to https://github.com/conan-io/conan-center-index/pull/17993 getting merged

2023-06-28 11:36 UTC, uilianries commented
Implemented by #17993

2023-06-28 11:36 UTC, closed without merging