Openblas - Conan 2.0
conan-io/conan-center-index pull request #17892
Opened 2023-06-10 15:10 UTC by fcorso2016

Upgraded openblas to work with conan 2.0

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-06-23 11:38 UTC, valgur requested changes
LGTM as an intermediate step before merging the more comprehensive #17173.
Only the `_subfolder` properties and the `CMakeLists.txt` that is no longer needed should be dropped.

2023-06-23 11:38 UTC, valgur commented on recipes/openblas/all/CMakeLists.txt
Can be removed.

2023-06-23 11:38 UTC, valgur commented on recipes/openblas/all/conanfile.py
>      @property
`self._source_subfolder` and `self._build_subfolder` can be simply replaced with `self.source_folder` and `self.build_folder` or even omitted entirely in most cases with Conan 2.

2023-07-02 16:14 UTC, fcorso2016 commented
It seems like there's some kind of issue going on with the build server in regard to the older versions of this package when it tries to build for windows. I'm not sure what exactly the issue is and it's not happening for me locally. Does anyone know what might be causing the issue?

2023-07-02 16:58 UTC, fcorso2016 commented
Okay so it seems to be stemming from some generated .c files adding a `#define RC` at the top of the file which then conflicts with one of the headers in the Windows Developer SDK which uses that as the name of a struct member. I'm trying to figure out what's different between the older and newer versions to see how I can best resolve this issue. Unless there's a way to manually specify to build the older versions with a compatible SDK

2023-07-03 05:29 UTC, valgur commented
Adding [fix_apple_shared_install_name(](https://docs.conan.io/2/reference/tools/apple/other.html) to package() should most likely fix the last warnings.

2023-07-04 17:48 UTC, valgur approved these changes

2023-07-06 06:16 UTC, franramirez688 reviewed
Hi @fcorso2016 - Thanks a lot for this contribution! 👏 

Only one comment about that patch for the `utils.cmake` file.

2023-07-06 06:16 UTC, franramirez688 commented on recipes/openblas/all/conanfile.py
> +                            "list(APPEND obj_defines  \"CR=CR\")\r\n" + "endif ()")
If this is a patch, I think it's worth putting it as a Conan one. Please, have a look at our [Policy about patching](https://github.com/conan-io/conan-center-index/blob/56c1638e25453cc8e2ce4a676604900ebc7b62a2/docs/adding_packages/sources_and_patches.md#policy-about-patching)

2023-07-06 09:09 UTC, czoido approved these changes

2023-07-06 09:20 UTC, franramirez688 approved these changes

2023-07-06 09:21 UTC, franramirez688 commented on recipes/openblas/all/conanfile.py
> +                            "list(APPEND obj_defines  \"CR=CR\")\r\n" + "endif ()")
Let's move forward with that because there are more recipes depending on this migration. Let's add this patch in another iteration 😉

2023-07-06 09:24 UTC, czoido commented on recipes/openblas/all/conanfile.py
> +        tc.variables["USE_THREAD"] = self.options.use_thread
```suggestion
        tc.cache_variables["NOFORTRAN"] = not self.options.build_lapack
        tc. cache_variables["BUILD_WITHOUT_LAPACK"] = not self.options.build_lapack
        tc. cache_variables["DYNAMIC_ARCH"] = self.options.dynamic_arch
        tc. cache_variables["USE_THREAD"] = self.options.use_thread
```

2023-07-06 09:24 UTC, czoido commented on recipes/openblas/all/conanfile.py
> +        tc.variables["USE_LOCKING"] = not self.options.use_thread
```suggestion
        tc. cache_variables["USE_LOCKING"] = not self.options.use_thread
```

2023-07-06 09:25 UTC, czoido commented on recipes/openblas/all/conanfile.py
> +        tc.variables[
```suggestion
        tc. cache_variables[
```

2023-07-06 09:25 UTC, czoido commented on recipes/openblas/all/conanfile.py
> +        tc.variables["ANDROID"] = self.settings.os in ["Linux", "Android"]
```suggestion
        tc.cache_variables["ANDROID"] = self.settings.os in ["Linux", "Android"]
```

2023-07-07 10:18 UTC, franramirez688 approved these changes

2023-07-07 12:06 UTC, merged