jpcre2: migrate to Conan v2
conan-io/conan-center-index pull request #18111
Opened 2023-06-28 20:27 UTC by valgur

Specify library name and version:  **jpcre2/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-06-29 09:03 UTC, RubenRBS requested changes

2023-06-29 09:03 UTC, RubenRBS commented on recipes/jpcre2/all/conanfile.py
>          self.requires("pcre2/10.37")
The readme states that a bump should be ok https://github.com/jpcre2/jpcre2#dependency
```suggestion
        self.requires("pcre2/10.42")
```

2023-06-29 09:22 UTC, franramirez688 approved these changes

2023-07-05 01:03 UTC, RubenRBS approved these changes

2023-07-05 01:04 UTC, RubenRBS commented
I'll check why the v2 pipeline failed tomorrow morning :)

2023-07-05 08:45 UTC, RubenRBS approved these changes

2023-07-05 10:47 UTC, czoido approved these changes

2023-07-05 18:43 UTC, merged