hippomocks: migrate to Conan v2
conan-io/conan-center-index pull request #18113
Opened 2023-06-28 20:39 UTC by valgur

Specify library name and version:  **hippomocks/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-06-29 09:08 UTC, czoido approved these changes

2023-06-29 09:19 UTC, czoido commented on recipes/hippomocks/all/test_package/CMakeLists.txt
> +target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_11)
Please check this comment: https://github.com/conan-io/conan-center-index/pull/18124#discussion_r1246361883

2023-06-29 09:27 UTC, RubenRBS requested changes
Blocking until cppstd is added

2023-07-03 10:13 UTC, czoido submitted a review, later dismissed

2023-07-05 08:42 UTC, RubenRBS approved these changes

2023-07-05 10:46 UTC, czoido approved these changes

2023-07-05 18:23 UTC, merged