aaf: add shared and fPIC, add package_type
conan-io/conan-center-index pull request #18166
Opened 2023-06-30 11:35 UTC by valgur

2023-07-05 20:04 UTC, RubenRBS reviewed
Some build issues in Windows, let us know if you need help sorting them out!

2023-07-05 20:04 UTC, RubenRBS commented on recipes/aaf/all/conanfile.py
> +            self.options.rm_safe("fPIC")
`1.53` again :)

2023-07-06 14:15 UTC, jcar87 requested changes
Hi @valgur - thanks for your contribution.

I have a strong suspicion that this should be a `static-library`, please see the motivation in this PR: https://github.com/conan-io/conan-center-index/pull/18385

Evidence:
* The library's own SDK, which mention that consumers need to link against two static libraries (https://aaf.sourceforge.net/AAFProjectFAQ.html)
* The original build scripts, which:
   * Only package the `.a` files in the `.lib` folder: https://github.com/jhliberty/AAF/blob/master/dist/sdk-files.unix#L8-L14
   * Do not package the `.lib` files for the DLLs on windows: https://github.com/jhliberty/AAF/blob/master/dist/sdk-files.win#L18-L19
   
 This would strongly indicate that for the purposes of building, this is a static library (as it is referred explicitly in the documentation and the build scripts), and the the DLLs are merely runtime loaded modules.

2023-07-06 16:44 UTC, MartinDelille approved these changes

2023-07-06 18:27 UTC, valgur commented
Closing in favor of #18385.

2023-07-06 18:27 UTC, closed without merging