alac: add package_type, tidy
conan-io/conan-center-index pull request #18172
Opened 2023-06-30 11:54 UTC by valgur

2023-07-05 20:02 UTC, RubenRBS requested changes

2023-07-05 20:02 UTC, RubenRBS commented on recipes/alac/all/conanfile.py
> +            self.options.rm_safe("fPIC")
Same here, needs to bump `required_conan_version` to 1.53

2023-07-08 07:15 UTC, valgur commented on recipes/alac/all/conanfile.py
>  required_conan_version = ">=1.52.0"
```suggestion
required_conan_version = ">=1.53.0"
```

2023-07-10 07:10 UTC, RubenRBS approved these changes

2023-07-10 07:22 UTC, valgur commented on recipes/alac/all/conanfile.py
> +        if conan_version.major < 2 and self.options.utility:
```suggestion
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs.append("m")

        if conan_version.major < 2 and self.options.utility:
```

2023-07-10 09:40 UTC, RubenRBS approved these changes

2023-07-10 11:32 UTC, czoido approved these changes

2023-07-10 21:23 UTC, merged