wilzegers-autotest: migrate to Conan v2
conan-io/conan-center-index pull request #18234
Opened 2023-07-01 06:05 UTC by valgur

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-06 12:17 UTC, RubenRBS approved these changes

2023-07-06 12:49 UTC, jwillikers requested changes

2023-07-06 12:49 UTC, jwillikers commented on recipes/wilzegers-autotest/all/conanfile.py
> +            "Visual Studio": "15",
Can you add `msvc` here?

2023-07-08 06:50 UTC, SSE4 approved these changes

2023-07-08 06:57 UTC, valgur commented on recipes/wilzegers-autotest/all/conanfile.py
> +            "Visual Studio": "15",
```suggestion
            "Visual Studio": "15",
            "msvc": "191",
```

2023-07-10 06:12 UTC, RubenRBS approved these changes

2023-07-10 08:23 UTC, czoido approved these changes

2023-07-10 09:43 UTC, merged