rangeless: migrate to Conan v2
conan-io/conan-center-index pull request #18246
Opened 2023-07-01 10:57 UTC by valgur

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-05 09:16 UTC, RubenRBS requested changes

2023-07-05 09:16 UTC, RubenRBS commented on recipes/rangeless/all/conanfile.py
> +        if self.settings.compiler.cppstd:
This is missing the `compiler_minimum_version` checks, like for https://github.com/conan-io/conan-center-index/pull/18250/files#diff-100c2c6de539067c6fb843bd683e38979259f7c5e4e7a3e17bd1defa05b5fedeR30

These kinds of checks will be required until v1 is no longer supported in CCI, as they ensure we have something like cppstd checks for v1 (The v1 profiles do not define cppstd, so we use them as a fall-back)

2023-07-22 20:19 UTC, SSE4 commented
@RubenRBS can you unblock?

2023-08-16 11:10 UTC, RubenRBS approved these changes

2023-08-17 05:30 UTC, czoido approved these changes

2023-08-17 08:30 UTC, merged