tclap: migrate to Conan v2
conan-io/conan-center-index pull request #18251
Opened 2023-07-01 11:59 UTC by valgur

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-05 08:52 UTC, RubenRBS approved these changes

2023-07-05 11:37 UTC, czoido commented on recipes/tclap/all/conanfile.py
> +            check_min_cppstd(self, self._min_cppstd)
Is this really necessary? Checking the sources I could not find any obvious c++11 requirement

2023-07-05 12:47 UTC, czoido requested changes
I'll block this for the moment, until we solve the source problem explained here: https://github.com/conan-io/conan-center-index/pull/18335

2023-07-06 11:20 UTC, RubenRBS commented
Hi @valgur thanks for you contribution. After checking the PR made by @uilianries to fix the sources origin, it seems like this PR is now no longer relevant, as the changes have been implemented already (Except for the C++ 11 check, which @czoido points out that is not needed, please let us know if otherwise!)

So I'm closing this as completed, but thanks a lot for your contiued contributions :)

2023-07-06 11:20 UTC, closed without merging