ccache: add version 4.8.2
conan-io/conan-center-index pull request #18315
Opened 2023-07-04 09:52 UTC by Cogitri

Also update the dependencies

Specify library name and version:  **ccache/4.8.2**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-14 10:23 UTC, jcar87 commented
The build errors appear to be a manifestation of https://github.com/ccache/ccache/issues/1278, for which there is a patch that made it to `4.8.2` - I will backport and reference this.

2023-07-14 10:24 UTC, Cogitri commented
Ah grand, thanks

2023-07-14 10:36 UTC, jcar87 commented
Hi @Cogitri - I did not have permission to push to your branch, so I've opened an independent PR to fix the build issue.

https://github.com/conan-io/conan-center-index/pull/18542

Feel free to cherry-pick the commit from my branch into this PR if you would like this new version and the version bumps to be merged quicker - otherwise once/if my PR is merged first, you can rebase your PR to sync up with the latest changes.

Also thanks for fixing the issue with zstd! very nice catch

2023-07-18 08:29 UTC, jcar87 commented on recipes/ccache/all/conanfile.py
> +        self.tool_requires("pkgconf/1.9.3") # for zstd
This doesn't work properly on Windows from what I can see.

My advice would be to add:
```
deps.set_property("zstd", "cmake_find_mode", "module")
```

further down below (around line 89), which will cause Conan to generate `Findzstd.cmake` which will be used instead, and then pkgconf is no longer needed.

2023-07-18 08:30 UTC, jcar87 requested changes
Thanks for your contribution!

In order to fix the build errors on Windows, please add the following in the `generate()` method:
```
deps.set_property("zstd", "cmake_find_mode", "module")
``` 

which should make the tool_requires on pkgconf unnecessary

2023-07-19 12:14 UTC, jcar87 approved these changes
Thanks a lot for your contribution!

2023-07-20 08:43 UTC, franramirez688 approved these changes

2023-07-20 09:29 UTC, merged