libtool: fix build in macOS
conan-io/conan-center-index pull request #18381
Opened 2023-07-06 11:12 UTC by ylatuya

Fixes #18379

Specify library name and version:  **libtool/2.4.7**

I am not sure about the fix though, I don't understand how this could be None if it's provided by the gnu-config recipe.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-06 11:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=18381) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=18381) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=18381) it.</sub>

2023-07-06 12:54 UTC, jwillikers approved these changes

2023-07-06 14:11 UTC, jcar87 requested changes
Hi @ylatuya, thanks for your contribution.

Have you verified that the revision of `gnu-config` is up-to-date and defines this? `conf_info.get()` behaviour is to return None when the requested configuration is not defined, so there is a chance that you locally have an older revision of that recipe?

I think this recipe should indeed have a better handling of that situation but I wonder if silently not doing nothing may cause issues elsewhere.

2023-07-06 17:17 UTC, ylatuya commented
> Hi @ylatuya, thanks for your contribution.
> 
> Have you verified that the revision of `gnu-config` is up-to-date and defines this? `conf_info.get()` behaviour is to return None when the requested configuration is not defined, so there is a chance that you locally have an older revision of that recipe?
> 
> I think this recipe should indeed have a better handling of that situation but I wonder if silently not doing nothing may cause issues elsewhere.

That seems to be the reason, it's picking an old revision of gnu-config/cci.20210814 from our remote from a revision that didn't define these values.

2023-07-08 14:03 UTC, SSE4 commented
@jcar87 can you unblock? seems like your question was answered.

2023-07-10 08:21 UTC, jcar87 commented
Hi @ylatuya, could you please confirm these changes are no longer necessary when using a recent revision of `gnu-config`, and if so, close this pull request?
Happy to help if there are any other issues.

2023-07-10 08:41 UTC, SSE4 commented
> Hi @ylatuya, could you please confirm these changes are no longer necessary when using a recent revision of `gnu-config`, and if so, close this pull request? Happy to help if there are any other issues.

@jcar87 I suppose changes are still necessary, as they add a sanity check for `gnu-config`. I guess other users may also run into similar issue (e.g. if they are using require-override for older `gnu-config`).

2023-07-11 08:25 UTC, ylatuya commented
> Hi @ylatuya, could you please confirm these changes are no longer necessary when using a recent revision of `gnu-config`, and if so, close this pull request? Happy to help if there are any other issues.

I can confirm that it builds correctly with the latest revision.

2023-07-11 08:38 UTC, jcar87 commented
Hi @ylatuya, I'm happy to hear your issue is resolved.

I will close this pull request, however your issue https://github.com/conan-io/conan-center-index/issues/18379 is very valid and should still be addressed by us - I will set aside some time and raise a new PR to resolve this issue. Thank you so much!

2023-07-11 08:38 UTC, closed without merging

2023-07-11 10:10 UTC, ylatuya commented
> Hi @ylatuya, I'm happy to hear your issue is resolved.
> 
> I will close this pull request, however your issue #18379 is very valid and should still be addressed by us - I will set aside some time and raise a new PR to resolve this issue. Thank you so much!

Thanks for your help! I am new to conan and I would like to understand what other changes could help alleviate this issue other than doing the safety checks. Being the dependency with gnu-config at the version level, if a change of a recipe does not changs the version but it modifies the recipe generating a new revision in a backwards breaking way, how can this be managed in conan?