cpp-httplib: add version 0.13.0
conan-io/conan-center-index pull request #18392
Opened 2023-07-06 23:59 UTC by toge

Specify library name and version:  **cpp-httplib/0.13.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-08 19:54 UTC, RubenRBS requested changes
Thanks a lot @toge! It seems like gcc 5 could be added back, right? The .1 patch release seems to have fixed the original issue

2023-07-09 01:13 UTC, toge commented
@RubenRBS 
You are right!
It works fine again on gcc5 in my local environment.
Thanks!

2023-07-09 01:27 UTC, RubenRBS approved these changes

2023-07-09 19:09 UTC, SSE4 approved these changes

2023-07-09 20:03 UTC, merged