libgit2: add version 1.6.4, support conan v2
conan-io/conan-center-index pull request #18458
Opened 2023-07-10 01:47 UTC by toge

Specify library name and version:  **libgit2/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-26 14:27 UTC, whaliendev commented
Hey, @toge I wonder why boost is needed to built this library? 
when I run `fd -i "boost"`, it shows nothing. It's very strange that libgit2 depends on boost.

2023-08-16 13:47 UTC, toge commented
Um... openssl/3.1.2?
```
WARN: libssh2/1.11.0: requirement openssl/[>=1.1 <4] overridden by libgit2/1.7.0 to openssl/3.1.2 
ERROR: Failed requirement 'openssl/3.1.2' from 'libssh2/1.11.0'
ERROR: Unable to find 'openssl/3.1.2' in remotes
```

2023-09-07 15:52 UTC, uilianries reviewed
Looking good, only small suggestion related to range versions.

2023-09-07 15:52 UTC, uilianries commented on recipes/libgit2/0.27.x/conanfile.py
> +            self.requires("libcurl/8.1.2")
```suggestion
            self.requires("libcurl/[>=X.YY <9]")
```

https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

2023-09-07 15:52 UTC, uilianries commented on recipes/libgit2/0.27.x/conanfile.py
> +        self.requires("zlib/1.2.13")
```suggestion
        self.requires("zlib/[>=1.X.Y <2]")
```

https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

2023-09-07 15:52 UTC, uilianries commented on recipes/libgit2/0.28.x/conanfile.py
> +        self.requires("zlib/1.2.13")
```suggestion
        self.requires("zlib/[>=1.X.Y <2]")
```

https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

2023-09-08 06:45 UTC, toge commented on recipes/libgit2/0.28.x/conanfile.py
> +        self.requires("zlib/1.2.13")
@uilianries 
Thanks!
I fixed.

2023-09-08 07:15 UTC, uilianries approved these changes
Arigatou!!

2023-09-08 07:20 UTC, uilianries commented on recipes/libgit2/0.27.x/conanfile.py
> +        self.requires("zlib/[>=1.X.Y <2]")
```suggestion
        self.requires("zlib/[>=1.2.12 <2]")
```

2023-09-08 07:20 UTC, uilianries commented on recipes/libgit2/0.27.x/conanfile.py
> +            self.requires("libcurl/[>=X.YY <9]")
```suggestion
            self.requires("libcurl/[>=7.83 <9]")
```

2023-09-08 09:11 UTC, uilianries commented
@toge I created the PR https://github.com/conan-io/conan-center-index/pull/19672 to fix the current conflict.

2023-10-05 15:38 UTC, RubenRBS commented
The bot did not want to post the errors, but v2 is failing because of a conflict in zlib, will get fixed once we continue with the port, sorry about the delay

2023-10-31 13:35 UTC, jwillikers approved these changes

2024-01-09 10:11 UTC, AlexandrePTJ commented
Hi, is there any status on this PR ?
We do rely on this package, and this is the last one before we can completly migrate to conan 2.

2024-01-11 11:21 UTC, uilianries commented
I just started new internal build to generate de missing `libssh2/1.11.0` package with `openssl/3.2.0`

2024-01-14 16:27 UTC, toge commented
@uilianries 
There seem to be still missing dependencies.
Cloud you investigate them?

2024-02-09 07:48 UTC, uilianries commented
I just started an internal build to generate 'libssh2/1.11.0', 'openssl/3.2.1'.

2024-02-21 08:31 UTC, uilianries commented
@toge Sorry the incident, I guess it failed during the tapaholes. I just pushed to be built it again. Thank you for reporting!

2024-03-05 11:19 UTC, valgur requested changes
Some minor tweaks are required. I would drop `0.27` as well. Maybe `0.28` also, but it's the latest v0.x version on CCI so it's still marginally useful in that regard, possibly.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/0.27.x/conanfile.py
>  class LibGit2Conan(ConanFile):
`package_type` is missing.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/0.27.x/conandata.yml
Maybe the `0.27` recipe can be dropped altogether.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/0.27.x/conanfile.py
> +        tc.variables["BUILD_EXAMPLES"] = False
Need to set `CMP0077` to `NEW` for `tc.variables`.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/all/conanfile.py
> +        tc.variables["REGEX_BACKEND"] = self.options.with_regex
Needs a `CMP0077` as well.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/0.28.x/conanfile.py
> +        tc.variables["USE_HTTPS"] = self._cmake_https[str(self.options.with_https)]
The `False` value in the dict is not a string.

2024-03-05 11:19 UTC, valgur commented on recipes/libgit2/all/conanfile.py
> +        tc.variables["USE_HTTPS"] = self._cmake_https[str(self.options.with_https)]
Same, `False` should be a string in the dict.

2024-04-29 07:31 UTC, RubenRBS commented
Hi @toge - I'm now trying to come back to this PR, sorry about the delay.

My one main question is if you have any insight into keeping the old 0.x releases, I think we could simplify a lot if only the `all` recipe would be kept! :)

2024-04-29 10:40 UTC, toge commented
@RubenRBS 
I agree with you.
I will try to remove 0.x releases.

2024-04-29 11:08 UTC, RubenRBS commented
Hi! I went ahead and removed them and updated the recipe to use version ranges, sorry I didnt notify you sooner! :)

2024-05-07 08:19 UTC, uilianries commented on recipes/libgit2/all/conanfile.py
> +        # REGEX_BACKEND is SET(), avoid options overriding it
Thank you for commenting the motivation! It helps a lot!

2024-05-07 08:19 UTC, uilianries commented on recipes/libgit2/all/patches/1.7.2-0001-fix-cmake.patch
> +-	find_package(HTTPParser)
We could use CMakeDeps with set_property to change the cmake file name, but variables are still not possible to change, so this change looks okay.

2024-05-07 08:22 UTC, RubenRBS approved these changes
Thanks a lot @toge, sorry this one took so long to get merged :)

2024-05-07 08:23 UTC, uilianries approved these changes

2024-05-07 08:25 UTC, merged