tinyxml: enable with_stl by default
conan-io/conan-center-index pull request #18779
Opened 2023-07-21 15:59 UTC by valgur

Needed for #17347.

Including STL support in a C++ library by default should not be an issue, I assume.

2023-07-22 09:31 UTC, ericLemanissier approved these changes

2023-08-11 11:55 UTC, uilianries requested changes
As this PR changes the default behavior expected by TinyXML project, it needs more discussion first.

2023-08-17 09:13 UTC, RubenRBS approved these changes

2023-08-17 09:24 UTC, uilianries approved these changes
After taking a look into others package managers we found that STL option is enabled by default. So based on that, we are good to go.

Arch Linux: https://gitlab.archlinux.org/archlinux/packaging/packages/tinyxml/-/blob/main/PKGBUILD#L33 (BTW I use Arch)

Homebrew: https://github.com/Homebrew/homebrew-core/blob/055ae78415b61ecf1fa3de32b76b8a149855f903/Formula/t/tinyxml.rb#L25

Debian: https://git.launchpad.net/ubuntu/+source/tinyxml/tree/debian/rules#n8

2023-08-17 09:46 UTC, valgur commented
Oh, wow. Thank you so much for looking into this so thoroughly.

2023-08-17 09:47 UTC, merged