libgpiod: Added version 1.6.4 and 2.0.1
conan-io/conan-center-index pull request #18813
Opened 2023-07-22 12:36 UTC by ashley-b

Specify library name and version:  **libgpiod/1.6.4**
- Added version 1.6.4
- Added new major version 2.0.1 with breaking API change
- Fixed test_package to work with version 1 & 2

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-25 16:07 UTC, jwillikers requested changes

2023-07-25 16:07 UTC, jwillikers commented on recipes/libgpiod/all/conandata.yml
> +    sha256: "b6eda55356160a8e73906e3d48e959ef81296787d764975b10f257e9660668e9"
Can you order these from newest version to oldest version?

2023-07-25 16:07 UTC, jwillikers commented on recipes/libgpiod/config.yml
> +    folder: all
Same here.

2023-07-25 18:39 UTC, jwillikers approved these changes
Thanks! LGTM!

2023-08-20 06:10 UTC, ashley-b commented
Just a follow up of this PR.

Thanks

2023-10-15 13:36 UTC, ashley-b commented
@jwillikers Just a follow up of this PR.

Thanks

2023-10-15 14:09 UTC, jwillikers approved these changes

2023-10-15 14:13 UTC, jwillikers commented
> @jwillikers Just a follow up of this PR.
> 
> Thanks

I've approved, but a Conan team member still needs to provide approval by review.

@RubenRBS  could review or assign a Conan member to review? I noticed  that one wasn't assigned automatically.

2023-11-22 10:14 UTC, uilianries approved these changes
LGTM

2023-11-22 11:00 UTC, ericLemanissier approved these changes

2023-11-22 14:19 UTC, jwillikers approved these changes

2023-11-22 22:45 UTC, merged