Makes crc_cpp compatible with conan 2.x
conan-io/conan-center-index pull request #18924
Opened 2023-07-27 08:57 UTC by Xav83

Specify library name and version:  **crc_cpp/1.2.0**

Hello conan devs 🙂 

When trying to use the crc_cpp package with the latest version of conan (`2.0.9` at the moment), the following issue is raised:
```
ERROR: crc_cpp/1.2.0: Error in package_id() method, line 53
        self.info.header_only()
        AttributeError: 'ConanInfo' object has no attribute 'header_only'
```

This commit should correct this error, and is based on the elements mentionned in this [GitHub issue](https://github.com/conan-io/conan/issues/12689)

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-07-27 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=18924) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=18924) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=18924) it.</sub>

2023-08-24 15:39 UTC, valgur requested changes

2023-08-24 15:39 UTC, valgur commented on recipes/crc_cpp/all/conanfile.py
>          self.copy(pattern="LICENSE", dst="licenses", src=self._source_subfolder)
You will need to use full paths like dst=os.path.join(self.package_folder, "licenses") in Conan 2.x.

2023-08-25 07:32 UTC, uilianries reviewed
@Xav83 Thank you for your contribution! Please, consider my PR https://github.com/Xav83/conan-center-index/pull/1 as an improvement over your changes!

2023-09-19 08:58 UTC, uilianries commented on recipes/crc_cpp/all/test_v1_package/conanfile.py
> +    generators = "cmake"
```suggestion
    generators = "cmake", "cmake_find_package_multi"
```

Add missing cmake deps generator for Conan 1.x

2023-09-19 13:28 UTC, Xav83 commented
@uilianries , since #19912 has been merge, is the work in this Pull Request still relevant ?

2023-09-19 13:55 UTC, closed without merging

2023-09-19 13:55 UTC, uilianries commented
@Xav83 I don't think so 😞 I'll close this PR, but thank so much for contributing. Please, file an issue in case you find something in that merged PR.