objectbox-generator: migrate to Conan v2
conan-io/conan-center-index pull request #18940
Opened 2023-07-28 11:12 UTC by valgur

2023-08-10 07:49 UTC, RubenRBS submitted a review, later dismissed

2023-08-10 12:13 UTC, uilianries requested changes
Thank you for your contribution, some important consideration about packaging pre-built binaries.

2023-08-10 12:13 UTC, uilianries commented on recipes/objectbox-generator/all/test_package/conanfile.py
> +from conan import ConanFile
```suggestion
from conan import ConanFile
from conan.tools.build import can_run
```

2023-08-10 12:13 UTC, uilianries commented on recipes/objectbox-generator/all/test_package/conanfile.py
> +        self.run("objectbox-generator -help")
```suggestion
        if can_run(self):
            self.run("objectbox-generator -help")
```
When cross-building, we will not be able to test it.

2023-08-10 12:13 UTC, uilianries commented on recipes/objectbox-generator/all/conanfile.py
>      def source(self):
```suggestion
    def build(self):
```
When packaging pre-built binaries, the common senses is downloading to the build folder directly, it's can be removed after building as it does not contain sources: 

https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#downloading-and-packaging-pre-built-binaries

2023-08-10 12:13 UTC, uilianries commented on recipes/objectbox-generator/all/conanfile.py
> +        pass
```suggestion
```

2023-08-10 12:13 UTC, uilianries commented on recipes/objectbox-generator/all/conanfile.py
> +    no_copy_source = True
```suggestion
```
no_copy_source can be removed as binaries should be downloaded to the build folder directly, so there is nothing to copy from source to build folder.

2023-08-18 09:03 UTC, uilianries approved these changes
LGTM

2023-08-19 07:48 UTC, SSE4 approved these changes

2023-08-19 17:09 UTC, merged