Add QuickPrivate module
conan-io/conan-center-index pull request #19082
Opened 2023-08-07 06:45 UTC by bog-dan-ro

**qt/6.x.x**

Qt6 conan recipe exports many xxxxPrivate modules but QuickPrivate was missing.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-08-07 06:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=19082) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=19082) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=19082) it.</sub>

2023-08-07 07:11 UTC, ericLemanissier approved these changes

2023-08-14 05:17 UTC, bog-dan-ro commented
is there anything I need to do?

2024-03-24 14:00 UTC, valgur requested changes
Need to merge changes from `master`. LGTM otherwise.

2024-07-26 12:57 UTC, jcar87 approved these changes

2024-07-26 14:16 UTC, perseoGI approved these changes
LGTM

2024-07-26 14:22 UTC, merged