libspatialite: bump dependencies
conan-io/conan-center-index pull request #19111
Opened 2023-08-09 07:05 UTC by SpaceIm

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-08-09 10:21 UTC, SpaceIm commented
v2 pipeline:

```
The v2 pipeline failed. Please, review the errors and note this will be required for pull requests to be merged in the near future.

See details:
Changes not allowed in build 1:

[libmysqlclient, libspatialite]
Only one library can be changed in the same PR.
```

?

2023-08-09 12:19 UTC, SpaceIm commented
waiting for https://github.com/conan-io/conan-center-index/pull/19117

2023-08-10 13:11 UTC, jwillikers approved these changes

2023-10-06 17:46 UTC, RubenRBS commented
Any update on this one @SpaceIm?

2023-10-06 18:38 UTC, SpaceIm commented
It's related to https://github.com/conan-io/conan/issues/13603 I think.

2023-10-13 13:36 UTC, jwillikers approved these changes

2023-10-18 21:03 UTC, RubenRBS commented
I've added a zlib range to the PR

2023-10-19 05:35 UTC, czoido approved these changes

2023-10-19 12:32 UTC, jwillikers approved these changes

2023-10-21 07:51 UTC, ericLemanissier commented
The conflict should be resilved now, with the latest commit merged in master. Can we retrigger this one?

This pr blocks:
- #20616

2023-10-24 13:55 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6627845767)

2023-10-24 13:57 UTC, ericLemanissier requested changes

2023-10-24 13:57 UTC, ericLemanissier commented on recipes/libspatialite/all/conanfile.py
> +        self.requires("sqlite3/3.42.0", transitive_headers=True)
```suggestion
        self.requires("sqlite3/3.42.2", transitive_headers=True)
```
Fixes conflict with proj

2024-03-01 08:45 UTC, closed without merging