boost: add version 1.83.0, remove older versions
conan-io/conan-center-index pull request #19175
Opened 2023-08-13 17:11 UTC by toge

Specify library name and version:  **boost/***

boost/1.71.0 and boost/1.72.0 are not required in any packages.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-08-14 07:22 UTC, fpelliccioni commented
I suggest to split the PR in 2, one the 1.83.0 upgrade, the other one for old version removal. I guess you will have less troubles.

2023-08-16 11:06 UTC, RubenRBS approved these changes
The diff got a bit crazy, but this looks good!

2023-08-16 11:43 UTC, RubenRBS requested changes
After discussing it, let's keep the old boost versions around for a while still. It's one of those libraries that people pin for long streches of time :)

2023-08-16 12:08 UTC, toge commented
@fpelliccioni  @RubenRBS  
Thank you for your comments!
I will revert these versions.

2023-08-17 07:58 UTC, jcar87 approved these changes

2023-08-17 12:11 UTC, jwillikers approved these changes

2023-08-17 14:20 UTC, valgur commented
I managed to miss this PR and opened a semi-duplicate one #19251, sorry. You can ignore the version bump aspect of my PR and merge this one first.

2023-08-17 14:21 UTC, valgur commented on recipes/boost/all/patches/1.83.0-locale-iconv-library-option.patch
This patch is identical to the one for 1.82.0. Why not simply reuse that one?

2023-08-17 15:07 UTC, toge commented on recipes/boost/all/patches/1.83.0-locale-iconv-library-option.patch
@valgur 
You are right!
Thank you for your review.
I fixed.

2023-08-17 15:11 UTC, toge commented on recipes/boost/all/dependencies/dependencies-1.83.0.yml
> +  - iconv
I think iconv requirement is still necessary.

Boost.Locale has the options to switch backend library.
```
"i18n_backend": ["iconv", "icu", None, "deprecated"],
"i18n_backend_iconv": ["libc", "libiconv", "off"],
"i18n_backend_icu": [True, False],
```

2023-08-17 19:15 UTC, jwillikers approved these changes

2023-08-18 08:40 UTC, jcar87 approved these changes

2023-08-18 10:06 UTC, RubenRBS approved these changes

2023-08-18 13:17 UTC, merged