libselinux: bump deps
conan-io/conan-center-index pull request #19231
Opened 2023-08-16 14:58 UTC by valgur

Really just to confirm that the `shared=True` build works ok in isolation. 
`libselinux` seems to be causing issues in the shared build for `cairo` in #18883.

2023-08-16 16:02 UTC, RubenRBS submitted a review, later dismissed

2023-08-16 16:02 UTC, RubenRBS commented
Thanks for investigating :)

2023-09-14 08:43 UTC, RubenRBS submitted a review, later dismissed

2023-09-18 11:25 UTC, ericLemanissier requested changes
file 0001-fix-fno-common-3.0.patch needs to be restored

2023-09-18 13:52 UTC, ericLemanissier approved these changes

2023-09-25 14:24 UTC, danimtb submitted a review, later dismissed

2023-09-29 13:02 UTC, valgur commented on recipes/libselinux/all/conanfile.py
> +        "LGPL-2.1",
Good catch. Thanks!

2023-09-29 13:12 UTC, jwillikers approved these changes
Thanks! Appreciate these license corrections.

2023-10-03 22:02 UTC, merged