zlib: add version 1.3, add patch_desscriptions
conan-io/conan-center-index pull request #19274
Opened 2023-08-18 15:50 UTC by toge

Specify library name and version:  **zlib/1.3**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-08-21 22:00 UTC, RubenRBS requested changes
Thanks a lot! We are taking this chance to add zlib to our range allowed recipes, blocking so it does not get merged before intended.

Also, please check the comment about the unneeded patch :)

2023-08-22 00:21 UTC, toge commented on recipes/zlib/all/patches/1.3/0002-gzguts-xcode12-compile-fix.patch
@RubenRBS 
Thanks!
I will follow your comments.

2023-08-22 02:40 UTC, toge commented on recipes/zlib/all/patches/1.3/0002-gzguts-xcode12-compile-fix.patch
@RubenRBS 
I found the related issues:
https://github.com/conan-io/conan-center-index/issues/2986
https://github.com/madler/zlib/pull/509

Now I understand this patch is not necessary for all versions because `_patch_sources()` already solve this issue.

I am going to remove `0002-gzguts-xcode12-compile-fix.patch`.

2023-08-22 04:24 UTC, toge commented on recipes/zlib/all/patches/1.3/0002-gzguts-xcode12-compile-fix.patch
fixed

2023-09-04 14:47 UTC, RubenRBS approved these changes
Thanks for the patience, let's get this merged now :)

2023-09-04 14:48 UTC, uilianries approved these changes
LGTM

2023-09-04 14:51 UTC, merged