qt/6.5.x: Only output a warning when using GCC 9
conan-io/conan-center-index pull request #19339
Opened 2023-08-22 15:45 UTC by jwillikers

Fail explicitly for GCC 9.1 or 9.2 which won't work. Users using any version of GCC 9 may be using newer versions of GCC 9. A warning should suffice in this case, without requiring users to change their settings model to incorporate minor version numbers of the compiler. For details, see https://bugreports.qt.io/browse/QTBUG-112920

Specify library name and version:  **qt/6.5.x**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-08-24 13:21 UTC, MartinDelille approved these changes

2023-11-16 10:53 UTC, RubenRBS approved these changes
We're checking the possibility of updating to gcc >=9.3 in the CI machines, but some issues arose - let's get this in and check back once an updated version (if any) is added :)

2023-11-16 19:49 UTC, ericLemanissier requested changes
we should be able to build with any version of gcc 9 by applying this patch on qt 6.5.0 to 6.6.0 : https://bugreports.qt.io/secure/attachment/148895/148895_0001-Fix-FTBFS-qt-6.5.0-on-gcc-9.patch
The patch has been reviewed upstream : https://bugreports.qt.io/browse/QTBUG-112920?focusedId=757912&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-757912

2023-11-16 20:48 UTC, RubenRBS commented
Thanks for the insight @ericLemanissier! Let's do that :)

2023-11-16 22:19 UTC, ericLemanissier requested changes
Thanks. You should also remove the exceptions and warning triggered when the profile has gcc 9

2023-11-16 22:41 UTC, jwillikers commented
> Thanks. You should also remove the exceptions and warning triggered when the profile has gcc 9

Duh! Thanks!

2023-11-16 23:16 UTC, ericLemanissier approved these changes

2023-11-17 06:23 UTC, ericLemanissier requested changes
The patch must also be applied to 6.6.0

2024-01-18 14:36 UTC, jwillikers commented
Closing as it looks as though this check was removed entirely.

2024-01-18 14:36 UTC, closed without merging