Add an option to support QUIC protocol to wolfssl
conan-io/conan-center-index pull request #19490
Opened 2023-08-30 01:21 UTC by cjbradfield

Specify library name and version:  **wolfssl/[>=5.5.0]**

WolfSSL supports the QUIC protocol (a dependency of http3) for all versions above and including 5.5.0. Expose an option to enable it.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-23 13:23 UTC, valgur requested changes

2024-02-23 13:23 UTC, valgur commented on recipes/wolfssl/all/conanfile.py
> +            self.options.tls13 = True
```suggestion
```
This has no effect, unfortunately.

2024-02-23 13:23 UTC, valgur commented on recipes/wolfssl/all/conanfile.py
> +            self.options.tls13 = True
You can do
```python
"--enable-tls13={}".format(yes_no(self.options.tls13 or self.options.quic)),
```
instead.

2024-06-13 15:47 UTC, perseoGI commented on recipes/wolfssl/all/conanfile.py
> +            self.options.tls13 = True
Thanks Valgur! You are right

2024-06-14 10:29 UTC, perseoGI approved these changes
Hi @cjbradfield thank you for your contribution.
We've tuned a little bit the changes to make it more "conanic"!

2024-06-21 17:04 UTC, cjbradfield commented
> Hi @cjbradfield thank you for your contribution. We've tuned a little bit the changes to make it more "conanic"!

@perseoGI Thanks for the tweaks!

2024-06-22 21:58 UTC, RubenRBS approved these changes
Successful compilation logs:

<details>

```
$ conan create . --version=5.7.0 -b=missing -o="&:with_quic=True"

======== Exporting recipe to the cache ========
wolfssl/5.7.0: Exporting package recipe: /Users/ruben/coding/conan-center-index/recipes/wolfssl/all/conanfile.py
wolfssl/5.7.0: exports: File 'conandata.yml' found. Exporting it...
wolfssl/5.7.0: Copied 1 '.py' file: conanfile.py
wolfssl/5.7.0: Copied 1 '.yml' file: conandata.yml
wolfssl/5.7.0: Exported to cache folder: /Users/ruben/.conan2/p/wolfse83f0820bdab4/e
wolfssl/5.7.0: Exported: wolfssl/5.7.0#4a85c321bc3f0f7c76f81e88c146ccc7 (2024-06-22 21:53:59 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[options]
&:with_quic=True
[platform_tool_requires]
cmake/3.29.1
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[platform_tool_requires]
cmake/3.29.1
[conf]



======== Computing dependency graph ========
Graph root
    cli
Requirements
    wolfssl/5.7.0#4a85c321bc3f0f7c76f81e88c146ccc7 - Cache
Build requirements
    autoconf/2.71#f9307992909d7fb3df459340f1932809 - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Cache
    gnu-config/cci.20210814#dc430d754f465e8c74463019672fb97b - Cache
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Cache

======== Computing necessary packages ========
Requirements
    wolfssl/5.7.0#4a85c321bc3f0f7c76f81e88c146ccc7:733627afde5ab3f21989117de9821a5ef6f3687a - Build
Build requirements
    autoconf/2.71#f9307992909d7fb3df459340f1932809:da39a3ee5e6b4b0d3255bfef95601890afd80709#5b77f70c17ad1741f5845d4e468a347e - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50:9e5323c65b94ae38c3c733fe12637776db0119a5#53e724e4596a55dd2b2a3931d36256dc - Cache
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b:2ee39e692ca4177b4b689b15bc1f2cfdf8f83706#0cc3761c3a78f0ff97c096d3c8db7075 - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2:617cae191537b47386c088e07b1822d8606b7e67#af3bb664b82c4f616d3146625c5b4bd5 - Cache
Skipped binaries
    gnu-config/cci.20210814

======== Installing packages ========
m4/1.4.19: Already installed! (1 of 5)
autoconf/2.71: Already installed! (2 of 5)
automake/1.16.5: Already installed! (3 of 5)
libtool/2.4.7: Already installed! (4 of 5)
libtool/2.4.7: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
libtool/2.4.7: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
wolfssl/5.7.0: Calling source() in /Users/ruben/.conan2/p/wolfse83f0820bdab4/s/src
wolfssl/5.7.0: Source https://github.com/wolfSSL/wolfssl/archive/v5.7.0-stable.tar.gz retrieved from local download cache

-------- Installing package wolfssl/5.7.0 (5 of 5) --------
wolfssl/5.7.0: Building from source
wolfssl/5.7.0: Package wolfssl/5.7.0:733627afde5ab3f21989117de9821a5ef6f3687a
wolfssl/5.7.0: Copying sources to build folder
wolfssl/5.7.0: Building your package in /Users/ruben/.conan2/p/b/wolfsbbe6b715b6fca/b
wolfssl/5.7.0: Calling generate()
wolfssl/5.7.0: Generators folder: /Users/ruben/.conan2/p/b/wolfsbbe6b715b6fca/b/build-release/conan
wolfssl/5.7.0: Generating aggregated env files
wolfssl/5.7.0: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
wolfssl/5.7.0: Calling build()
wolfssl/5.7.0: RUN: autoreconf --force --install
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:22: installing 'build-aux/compile'
configure.ac:24: installing 'build-aux/config.guess'
configure.ac:24: installing 'build-aux/config.sub'
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'

wolfssl/5.7.0: RUN: "/Users/ruben/.conan2/p/b/wolfsbbe6b715b6fca/b/src/configure" --disable-shared --enable-static --prefix=/ '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --disable-examples --disable-crypttests --enable-harden --enable-debug=no --enable-opensslall=no --enable-opensslextra=no --enable-sslv3=no --enable-alpn=no --enable-des3=no --enable-tls13=yes --enable-certgen=no --enable-dsa=no --enable-ripemd=no --enable-sessioncerts=no --enable-sni=no --enable-testcert=no --enable-shared=no --enable-static=yes --enable-quic 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking build system type... aarch64-apple-darwin23.5.0
checking host system type... aarch64-apple-darwin23.5.0
checking target system type... aarch64-apple-darwin23.5.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /Users/ruben/.conan2/p/b/wolfsbbe6b715b6fca/b/src/build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking how to convert aarch64-apple-darwin23.5.0 file names to aarch64-apple-darwin23.5.0 format... func_convert_file_noop
checking how to convert aarch64-apple-darwin23.5.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd.. [...]

2024-07-03 07:04 UTC, franramirez688 approved these changes

2024-07-03 09:03 UTC, merged