Bump vtu11's zlib requirement to [>=1.2.11 <2] range
conan-io/conan-center-index pull request #19683
Opened 2023-09-08 16:09 UTC by RubenRBS

Specify library name and version:  **lib/1.0**

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-09-19 13:25 UTC, czoido submitted a review, later dismissed

2023-09-20 14:45 UTC, RubenRBS commented
I've removed the C++17 patch in favour of defining `/Zc:__cplusplus` in msvc. Thanks to @czoido and @jellespijker for the input :)

2023-09-21 06:06 UTC, czoido approved these changes

2023-09-21 06:09 UTC, jellespijker requested changes
Since the zlib headers are used in the public header of this project the visibility of zlib should be transitive imo

2023-09-25 14:09 UTC, closed without merging

2023-09-25 15:35 UTC, RubenRBS commented on recipes/vtu11/all/conanfile.py
> +            self.requires("zlib/[>=1.2.11 <2]")
Hi! Thanks a lot for reviewing: You're totally correct. The important point to note here is that I've added the `package_type = "header-library"` attribute, which makes the traits infer the =True value in this case :) ([Docs here](https://docs.conan.io/2/reference/conanfile/methods/requirements.html?highlight=inferring#package-type-trait-inferring))