audiowaveform: add initial recipe for 1.8.1
conan-io/conan-center-index pull request #19695
Opened 2023-09-09 12:08 UTC by Nekto89

Specify library name and version:  **audiowaveform/1.8.1**

Recipe can't be used on conanv2 because of dependencies (libid3tag).

Resolves #9371

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-09-09 12:08 UTC, Nekto89 commented
TODO: check after #18987 is merged

2024-03-26 07:16 UTC, valgur commented on recipes/audiowaveform/all/conanfile.py
Needs a `package_id()` with `del self.settings.compiler`.

2024-03-26 07:17 UTC, valgur commented on recipes/audiowaveform/all/patches/1.9.1-disable_documentation.patch
Just delete them after `cmake.install()`. Easier to maintain.

2024-03-26 07:19 UTC, valgur commented on recipes/audiowaveform/all/test_v1_package/conanfile.py
`test_v1_package` should no longer be included in new recipes.

2024-03-26 07:23 UTC, valgur requested changes
Needs a `package_id()`, otherwise LGTM.

I'm not sure if CCI is the best place for this package, though, since it's not really a library or a build tool.

2024-03-26 08:08 UTC, Nekto89 commented on recipes/audiowaveform/all/patches/1.9.1-disable_documentation.patch
documentation requires "gzip" in PATH. In my opinion it's easier to just disable it.

2024-03-26 09:06 UTC, valgur commented on recipes/audiowaveform/all/patches/1.9.1-disable_documentation.patch
Ah, ok. Makes sense.

2024-09-24 07:02 UTC, valgur approved these changes

2024-09-24 07:48 UTC, perseoGI approved these changes

2024-09-24 07:49 UTC, AbrilRBS approved these changes

2024-09-24 08:05 UTC, merged