libmysqlcient: Disable doxxygen generation
conan-io/conan-center-index pull request #19873
Opened 2023-09-15 15:57 UTC by RubenRBS

Closing #19757 in favour of this one

(Thanks to @oleurodecision for bringing up a good reason not to remove the .25 version!)

Closes #19654

2023-09-15 16:28 UTC, ericLemanissier requested changes
You should be able to disable doxygen by doing something like `        tc.cache_variables["CMAKE_DISABLE_FIND_PACKAGE_Doxygen"] = True` in `generate(self)`, which I find more elegant than patching the sources
cf https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html

2023-09-15 20:08 UTC, ericLemanissier approved these changes

2023-09-15 20:08 UTC, ericLemanissier requested changes
Well, actually, one of these changes is redundant 😉

2023-09-25 16:09 UTC, ericLemanissier approved these changes

2023-09-27 14:26 UTC, uilianries approved these changes

2023-09-28 13:32 UTC, danimtb approved these changes

2023-09-28 13:34 UTC, merged