spirv-cross: add new versions, remove old ones
conan-io/conan-center-index pull request #19982
Opened 2023-09-20 11:09 UTC by valgur

Kept only versions from the past year.

2023-10-01 17:58 UTC, RubenRBS submitted a review, later dismissed

2023-10-02 08:01 UTC, ericLemanissier requested changes
Could you also please remove the unused patches in this one ? thanks!

2023-10-06 13:50 UTC, danimtb commented on recipes/spirv-cross/config.yml
> -    folder: all
Please keep this option as it is an active requirement of "shaderc" recipe at https://github.com/conan-io/conan-center-index/blob/91e67bdec23d59d4e2a104a3343762142b300058/recipes/shaderc/all/conanfile.py#L71

2023-10-06 13:50 UTC, danimtb commented on recipes/spirv-cross/config.yml
> -  "1.3.224.0":
Please keep this version as it is a requirement for "diligent-core" recipe https://github.com/conan-io/conan-center-index/blob/91e67bdec23d59d4e2a104a3343762142b300058/recipes/diligent-core/all/conanfile.py#L116

2023-10-06 17:48 UTC, RubenRBS requested changes
As @danimtb pointed out, there are some used versions still - we should either keep those or bump their dependencies

2023-10-23 15:03 UTC, RubenRBS approved these changes
Thanks! I know it can be frustrating to have to keep old versions around

2023-10-23 15:21 UTC, ericLemanissier approved these changes

2023-10-23 17:01 UTC, merged