at-spi2-core: enable non-linux
conan-io/conan-center-index pull request #20101
Opened 2023-09-25 08:23 UTC by ericLemanissier

Specify library name and version:  **at-spi2-core/***

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-09-25 09:57 UTC, ericLemanissier commented
all green in https://github.com/eirikb/proof-of-conan/actions/runs/6297646874

2023-09-25 15:47 UTC, RubenRBS submitted a review, later dismissed
Wow, nice! Thanks :)

2023-09-29 09:49 UTC, ericLemanissier commented
blocked by:
- https://github.com/conan-io/conan-center-index/pull/19935

2023-10-01 09:11 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590)

2023-10-01 09:13 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590)

2023-10-01 09:18 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590)

2023-10-01 09:21 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590)

2023-10-01 09:23 UTC, ericLemanissier commented
Help me SIP gods https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590/job/17289904484#step:8:804

```
Command line: `clang -I/Users/runner/.conan2/p/dbus4f34f5e5d3656/p/include -I/Users/runner/.conan2/p/dbus4f34f5e5d3656/p/include/dbus-1.0 -I/Users/runner/.conan2/p/dbus4f34f5e5d3656/p/lib/dbus-1.0/include -I/Users/runner/.conan2/p/expat2fe1b057146dc/p/include /Users/runner/.conan2/p/b/at-spcfa401f930b9e/b/build-release/meson-private/tmpy3ej8zhj/testfile.c -o /Users/runner/.conan2/p/b/at-spcfa401f930b9e/b/build-release/meson-private/tmpy3ej8zhj/output.exe -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -O0 -Werror=implicit-function-declaration /Users/runner/.conan2/p/dbus4f34f5e5d3656/p/lib/libdbus-1.dylib -lpthread /Users/runner/.conan2/p/expat2fe1b057146dc/p/lib/libexpat.dylib` -> 0
Program stdout:


Program stderr:

dyld: Library not loaded: @rpath/libdbus-1.3.dylib
  Referenced from: /Users/runner/.conan2/p/b/at-spcfa401f930b9e/b/build-release/meson-private/tmpy3ej8zhj/output.exe
  Reason: image not found


../src/meson.build:179:23: ERROR: Could not run alignment test binary.
```

2023-10-02 10:20 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/6296777590)

2023-10-03 04:52 UTC, ericLemanissier commented
Let's go! Wtyt @SpaceIm ?

2023-10-03 13:04 UTC, jwillikers approved these changes

2023-10-04 11:39 UTC, RubenRBS requested changes
Thanks! We should remove the excepting printing for the final merge - I'll merge the commit once the CI queue clears a bit :)

2023-10-04 11:39 UTC, RubenRBS commented on recipes/at-spi2-core/new/conanfile.py
> +            self.output.info(open("meson-logs/meson-log.txt", 'r').read())
```suggestion
        meson.configure()
```

2023-10-04 11:41 UTC, ericLemanissier commented on recipes/at-spi2-core/new/conanfile.py
> +            self.output.info(open("meson-logs/meson-log.txt", 'r').read())
Why should we remove it?

2023-10-05 12:37 UTC, jwillikers approved these changes

2023-10-05 16:44 UTC, SpaceIm approved these changes

2023-10-05 16:58 UTC, RubenRBS commented on recipes/at-spi2-core/new/conanfile.py
> +            self.output.info(open("meson-logs/meson-log.txt", 'r').read())
Oh, good to know!

2023-10-06 09:31 UTC, RubenRBS approved these changes

2023-10-06 09:59 UTC, merged