tensorflow-lite: add version 2.14.0
conan-io/conan-center-index pull request #20173
Opened 2023-09-27 19:14 UTC by Wawha

Library name and version:  **tensorflow-lite/2.14.0**

Add new version 2.14.0 of Tensorflow lite.
Modifications compare to tensorflow repo:
- Add by headers files of library `ml_dtypes` to be able to compile.

Conan package modification:
- Add Android support in `test_package`.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-09-27 19:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=20173) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=20173) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=20173) it.</sub>

2024-03-24 21:18 UTC, valgur commented on recipes/tensorflow-lite/all/conandata.yml
> +      patch_type: "conan"
This patch can probably be replaced with simply setting [`FETCHCONTENT_FULLY_DISCONNECTED`](https://cmake.org/cmake/help/latest/module/FetchContent.html#variable:FETCHCONTENT_FULLY_DISCONNECTED).

2024-03-24 21:20 UTC, valgur commented on recipes/tensorflow-lite/all/patches/dependencies.patch
> ++find_package(fft REQUIRED)
You can probably do `deps = ConanDeps(self); deps.set_property("fft", "cmake_file_name", "fft2d")` instead.

2024-03-24 21:20 UTC, valgur commented on recipes/tensorflow-lite/all/patches/dependencies.patch
> ++find_package(fft REQUIRED)
The same goes for xnnpack.

2024-03-24 21:22 UTC, valgur commented on recipes/tensorflow-lite/all/patches/dependencies.patch
> ++    gemmlowp::eight_bit_int_gemm
```
deps.set_property("farmhash", "cmake_target_name", "farmhash")
deps.set_property("gemmlowp", "cmake_target_name", "gemmlowp::gemmlowp")

2024-03-24 21:24 UTC, valgur commented on recipes/tensorflow-lite/all/patches/ml_dtypes.patch
At this point I would rather `download()` it from GitHub instead. That's a bit excessive for a patch.

2024-03-24 21:25 UTC, valgur requested changes
The full header file is a tad excessive for a patch. Patching can probably simplified slightly. Otherwise LGTM.

Thanks!

2024-03-26 11:18 UTC, Wawha commented
> The full header file is a tad excessive for a patch. Patching can probably simplified slightly. Otherwise LGTM.
> 
> Thanks!

Thank you for the review. Unfortunately I'm not working anymore on that project, so I do not have the setup to test the modification I could make with you remarks.
Perhaps I should close the pull request

2024-10-07 06:41 UTC, closed without merging