boost: remove `b2-default` value of `layout` option
conan-io/conan-center-index pull request #20336
Opened 2023-10-03 23:22 UTC by SpaceIm

logic of this value in configure() can't work in conan v2, it raises a ConanException (see https://cpplang.slack.com/archives/C41CWV9HA/p1696374024080289)

If folks want default layout for Windows, they can set layout to versioned instead of this removed b2-layout, so this value was more or less useless.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-10-05 08:00 UTC, SpaceIm commented
See also https://github.com/conan-io/conan/issues/14868 for explanations

2023-10-06 09:29 UTC, RubenRBS requested changes
This is going to change moving forward - We'll need to validate the options instead of forcing them, as per your conversation in the Conan repo issue, this is no longer valid in v2

2023-10-06 12:18 UTC, SpaceIm commented
I don't understand. As explained, this value was a mistake actually. Users can still change layout, so what's the point of this value?

2023-10-16 13:10 UTC, jwillikers approved these changes
Yeah, that looks like it's effectively a dead value for that option.

2023-11-03 02:43 UTC, SSE4 commented
@RubenRBS can you unblock?

from my point of view, `b2-default` may produce missed expectations. e.g. if you build for Android on Windows host vs on Linux host, you will get different library names for the same package ID (which is kinda weird).

2024-02-28 14:37 UTC, valgur approved these changes

2024-07-24 11:25 UTC, uilianries reviewed
It looks good, considering:

The `b2-default` is a virtual auto value for Boost project, the same does not exist in Boost project, only `system`, `versioned` and `tagged` are available: https://github.com/boostorg/boost/blob/e4b2e2d6a11c9596a022ddfaa49c7a3c6261e297/boostcpp.jam#L64

It's true in Windows, Boost uses `versioned` by default, but in this recipe we have been enforced the `system` by default to any platform.

Plus, I'm not confident in auto values, as the upstream may change in future and we miss it when reviewing. 

I just talked to @AbrilRBS first, so I'll wait her thoughts first.

2024-07-30 17:20 UTC, AbrilRBS approved these changes

2024-07-31 06:07 UTC, uilianries approved these changes

2024-07-31 15:25 UTC, merged