resiprocate: add master snapshot
conan-io/conan-center-index pull request #20465
Opened 2023-10-09 14:04 UTC by gjasny

Specify library name and version:  **resiprocate/cci.20231009**

Only the resiprocate master branch can cope with OpenSSL 3 and modern C++. Unfortunately, no `1.13` release is in sight: https://github.com/resiprocate/resiprocate/discussions/232

This PR could close the gap between the 1.12 release and a future 1.13. We use the code in production since many months, now.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-10-09 14:30 UTC, RubenRBS commented
Thanks for the extra info in the link @gjasny, those are super appreciated :)

2023-11-23 09:03 UTC, valgur requested changes

2023-11-23 09:03 UTC, valgur commented on recipes/resiprocate/cmake/conanfile.py
> +
```suggestion

    @property
    def _minimum_cpp_standard(self):
        return 11

    @property
    def _minimum_compiler_version(self):
        return {
            "gcc": "7",
            "clang": "6",
            "apple-clang": "10",
            "msvc": "191",
            "Visual Studio": "15",
        }

```
I determined the minium GCC and Clang versions by building in a container. apple-clang is based on LLVM 6 version. MSVC is just a guess based on similar recipes.

2023-11-23 09:03 UTC, valgur commented on recipes/resiprocate/cmake/conanfile.py
> +    def validate(self):
```suggestion
    def validate(self):
        if self.info.settings.compiler.cppstd:
            check_min_cppstd(self, self._minimum_cpp_standard)
        minimum_version = self._minimum_compiler_version.get(str(self.info.settings.compiler), False)
        if minimum_version and Version(self.info.settings.compiler.version) < minimum_version:
            raise ConanInvalidConfiguration(
                f"{self.ref} requires C++{self._minimum_cpp_standard}, which your compiler does not support."
            )
```

2023-11-23 09:03 UTC, valgur commented on recipes/resiprocate/cmake/conanfile.py
> +from conan.tools.microsoft import is_msvc
```suggestion
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.env import VirtualBuildEnv
from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, rm, rmdir
from conan.tools.gnu import PkgConfigDeps
from conan.tools.microsoft import is_msvc
from conan.tools.scm import Version
```
Imports for the version checks.

2023-11-23 09:03 UTC, valgur commented on recipes/resiprocate/cmake/conandata.yml
> +    sha256: "0f463c642034d18f98d4ff595f44a1fc3db1e29fc9e12ed2e8fbdc51b4284f98"
```suggestion
  "cci.20231120":
    url: "https://github.com/resiprocate/resiprocate/archive/6b21271c121981e4bae8bb0b5d445081f776c78d.tar.gz"
    sha256: "764381136ef35e7f28cc5d77b8b39a80c49bad99b45b756d2f1af75fab9a2ad8"
```
Can be bumped.

2023-11-23 09:03 UTC, valgur commented on recipes/resiprocate/config.yml
> +  "cci.20231020":
```suggestion
  "cci.20231120":
```

2024-02-23 14:07 UTC, valgur approved these changes
LGTM

Updating the snapshot version before this gets merged would not hurt.

2024-11-12 09:13 UTC, AbrilRBS commented on recipes/resiprocate/cmake/conandata.yml
> +  "cci.20231127":
This should be `1.12.0.cci.20xxxx` to align with the new scheme

2025-01-20 12:19 UTC, jcar87 commented
cc @franramirez688

2025-01-24 13:44 UTC, franramirez688 commented
Hi @gjasny 

> Since the 1 and a half years that this PR is open (😢) a new stable release happened. The PR has been updated accordingly.

I'm so sorry for the terribly long time in reviewing this PR 😭 I'll prioritize this PR into my list to be reviewed ASAP.
Thank you so much for the effort of opening this PR and keeping it up-to-date till the end 👏

2025-01-27 15:32 UTC, franramirez688 commented on recipes/resiprocate/cmake/conanfile.py
> +        tc.generate(scope="build")
If I'm not missing anything, can we remove it?

```suggestion
```

2025-01-27 15:32 UTC, franramirez688 commented on recipes/resiprocate/cmake/conanfile.py
> +from conan.tools.env import VirtualBuildEnv
```suggestion
```

2025-01-28 08:23 UTC, franramirez688 submitted a review, later dismissed
LGTM! 👏 

Thanks @gjasny

2025-01-28 09:35 UTC, franramirez688 commented on recipes/resiprocate/cmake/conanfile.py
> +        self.cpp_info.libs = [resiprocate_lib, "rutil", "dum"]
@AbrilRBS is working on this to split these libraries into several components. She'll update the PR soon

2025-01-28 11:44 UTC, franramirez688 commented on recipes/resiprocate/cmake/conanfile.py
> +            raise ConanInvalidConfiguration(f"{self.ref} can not be built as shared on msvc, it does not export required symbols.")
@AbrilRBS and I were trying to compile it as shared and we saw those export symbol errors, that's why we updated the message. @gjasny Is this the real problem? Are there any open issues related to this?

2025-01-28 12:53 UTC, AbrilRBS submitted a review, later dismissed

2025-01-28 12:54 UTC, franramirez688 approved these changes

2025-02-03 12:16 UTC, merged