pcre2: fix invalid pcre2-config output for static libs
conan-io/conan-center-index pull request #20586
Opened 2023-10-16 08:16 UTC by valgur

`pcre2` includes a `pcre2-config` executable that outputs necessary compiler and linker flags to link against `pcre2`. However, it currently outputs invalid library names for static versions of the libraries.

This is a blocker for #19058, as this causes linking against `pcre2` to fail.

2023-11-13 08:40 UTC, uilianries commented
I just launched an internal CI build to generate pcre2/10.32

2023-11-20 14:54 UTC, jwillikers approved these changes

2023-12-20 10:29 UTC, ptc-rgrasset commented
Any update on this CR?

We are waiting on it for some of our dependencies.

2024-05-28 16:07 UTC, danimtb requested changes
this fix looks ok but I think there is no need to add that complexity to the test_package. Please remove the test_package changes

2024-06-12 15:00 UTC, danimtb reviewed
no need to add that complexity to test_package

2024-06-12 15:00 UTC, danimtb commented on recipes/pcre2/all/test_package/conanfile.py
> +from conan.tools.scm import Version
```suggestion
```

2024-06-12 15:00 UTC, danimtb commented on recipes/pcre2/all/test_package/conanfile.py
> +from io import StringIO
```suggestion
```

2024-06-12 15:00 UTC, danimtb commented on recipes/pcre2/all/test_package/conanfile.py
> +
```suggestion
```

2024-06-12 15:00 UTC, danimtb commented on recipes/pcre2/all/test_package/conanfile.py
> +
```suggestion
```

2024-06-12 15:00 UTC, danimtb commented on recipes/pcre2/all/test_package/conanfile.py
> +                        assert flag[2:] in libs, f"Invalid library target '{flag[2:]}' output by pcre2-config. Not found in {libs}."
```suggestion
```

2024-06-13 11:32 UTC, danimtb approved these changes

2024-06-13 12:52 UTC, jwillikers approved these changes

2024-06-13 13:04 UTC, merged