icu/73.2 recipe, #19340 cc setting respected during build
conan-io/conan-center-index pull request #20779
Opened 2023-10-26 11:06 UTC by hegyizs

cc setting respected during build
Specify library name and version:  **icu/73.2**

fixes #19340

2023-10-26 11:31 UTC, SpaceIm commented
It seems excessive if it's not "fixed" upstream (not even sure we can consider this as a bug). When someone has several compiler installed, it has to define tools.build:compiler_executables.

2023-10-26 11:36 UTC, hegyizs commented
FYI: https://github.com/conan-io/conan-center-index/issues/19340#issuecomment-1779247344

2023-10-26 12:23 UTC, jwillikers commented
@SpaceIm I've opened the issue [ICU-22556](https://unicode-org.atlassian.net/browse/ICU-22556) upstream to see if we can get this fixed there.

2023-11-17 09:29 UTC, uilianries commented
> So far, this is the only package I've seen that requires tools.build.compiler_executables to be defined to use the correct compiler on Linux systems with both GCC and Clang installed.

The `settings.compiler` does not guarantee the compiler that should be used, it's used to generate the Package ID. The correct way should be using compiler_executables always (I use locally).

2023-11-17 09:36 UTC, uilianries requested changes
@hegyizs Thank you for your report.

This PR concerns more about a build configuration than a recipe problem. I see the issue https://unicode-org.atlassian.net/browse/ICU-22556 the right way in a long term to fix your situation.

Please, use the configuration `compiler_executables` always to define which compiler should be used. You can more references here:

- https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html
- https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conf
- https://docs.conan.io/2/reference/config_files/global_conf.html?highlight=compiler_executables

2023-11-17 09:39 UTC, closed without merging