libarchive: patch to include getopt.h when required
conan-io/conan-center-index pull request #20799
Opened 2023-10-28 11:37 UTC by klausholstjacobsen

libarchive 3.7.1

Including getopt.h when HAVE_GETOPT_OPTRESET is defined.

Upstream PR: https://github.com/libarchive/libarchive/pull/2007
---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-10-28 12:47 UTC, jwillikers requested changes

2023-10-28 12:47 UTC, jwillikers commented on recipes/libarchive/all/conandata.yml
> +      patch_type: "portability"
@klausholstjacobsen Thanks for making a PR upstream! If you could add a `patch_source` field like below, that will help us keep track of when the patch has been upstreamed.

```suggestion
      patch_type: "portability"
      patch_source: "https://github.com/libarchive/libarchive/pull/2007"
```

2023-10-29 13:09 UTC, jwillikers approved these changes

2023-10-30 16:49 UTC, uilianries approved these changes
Thank you! Not only for opening this PR, but mainly for sending it to the upstream!

2023-10-30 17:18 UTC, merged