structopt: update magic_enum/0.9.5
conan-io/conan-center-index pull request #21207
Opened 2023-11-18 03:57 UTC by toge

Specify library name and version:  **structopt/***

magic_enum/0.9.5 changed include path from `"magic_enum.hpp"` to `magic_enum/magic_enum.hpp`.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-11-20 13:35 UTC, jwillikers approved these changes

2023-11-22 08:36 UTC, uilianries requested changes
waiting for Ruben review

2023-11-22 09:59 UTC, uilianries commented
I just pushed a PR to the upstream: https://github.com/p-ranav/structopt/pull/24

It should fix the current state by using patches.

2023-11-23 09:40 UTC, RubenRBS commented
If the upstream PR does not get merged after this goes stale, we'll merge here as-is. The library seems not to be getting too many updates lately so they might take a bit

2024-02-28 14:18 UTC, valgur approved these changes

2024-08-12 17:41 UTC, toge commented
It is not necessary modification.
Please refer https://github.com/conan-io/conan-center-index/pull/24894

2024-08-12 17:41 UTC, closed without merging