jemalloc: migrate to Conan v2
conan-io/conan-center-index pull request #21509
Opened 2023-11-30 12:33 UTC by valgur

Continues #17722.

2023-12-18 14:14 UTC, jwillikers requested changes

2023-12-18 14:14 UTC, jwillikers commented on recipes/jemalloc/all/conanfile.py
> +        self.build_requires("automake/1.16.5")
```suggestion
        self.tool_requires("automake/1.16.5")
```

2023-12-18 15:13 UTC, valgur commented on recipes/jemalloc/all/conanfile.py
> +        self.build_requires("automake/1.16.5")
Thanks!

2023-12-26 16:24 UTC, jwillikers approved these changes

2024-01-15 14:50 UTC, RubenRBS approved these changes

2024-01-15 15:20 UTC, merged