glib/2.78.x: Add patch to support Python 3.12
conan-io/conan-center-index pull request #21535
Opened 2023-12-01 17:04 UTC by jwillikers

Specify library name and version:  **glib/2.78.x**

The distutils module was removed in Python 3.12, requiring at least Meson 1.2.3 and a patch for glib. See the upstream PR [here](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3740).

Requires conan-io/conan-docker-tools#554

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2023-12-01 17:24 UTC, ericLemanissier approved these changes

2023-12-04 22:19 UTC, jwillikers commented
Oh yes, actually need to install the Python `packaging` module for this to work...

2024-02-21 21:39 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/7995808868/attempts/1)

2024-03-14 08:05 UTC, uilianries requested changes
Backporting the feature is not a good idea as the upstream no longer support it so there is no guarantee about the behavior. Let's keep trying a solution with packaging first. Thank you for checking this possibility.

2024-03-28 13:31 UTC, stevenwdv commented
FYI, this is preventing `glib` from building on our macOS builder, see https://github.com/conan-io/conan-center-index/issues/23029#issuecomment-2017442481

2024-07-11 15:30 UTC, jcar87 commented
closed in favour of https://github.com/conan-io/conan-center-index/pull/24591  (which backports a glib fix for this that requires no additional dependency)

2024-07-11 15:30 UTC, closed without merging