frugally-deep: add v0.15.27, drop old versions, fix version naming
conan-io/conan-center-index pull request #21637
Opened 2023-12-06 08:17 UTC by valgur

Frugally deep uses `0.15.x-p0` for all of its version names. I assume the `-p0` suffix is meant to effectively be a patch version there, but afaik it gets interpreted as a pre-release version by Conan due to the hyphen. I converted the version names to a more standard semver format without the suffix.

2023-12-07 15:27 UTC, uilianries requested changes
@valgur Please, revert it. The `p0` is for patch, like you said, but Poco C++ also follows it and use -px. Plus, the project officially uses -p0 even in the release: https://github.com/Dobiasd/frugally-deep/releases

2023-12-07 16:28 UTC, valgur commented
@uilianries Buut... this breaks the semantic versioning support in Conan? https://docs.conan.io/2.0/tutorial/versioning/version_ranges.html#semantic-versioning

You would have to use the somewhat obscure `self.requires("frugally-deep/[>0.15 <1, include_prerelease]")` for proper version ranges support. Plus, it's somewhat semantically confusing in isolation.

2023-12-07 17:02 UTC, uilianries commented
@valgur I understand your point, but it's out of Conan's scope how the upstream uses their versions. It would be better if you open a ticket to the upstream asking about not using the suffix instead. This project is just another in the middle of others that does not follow the version schematic proposed by Conan's feature.

2023-12-26 16:24 UTC, Dobiasd commented
Hi, and sorry for the trouble. I did not know the `-p0` would cause these issues. :pray:

Since I can't even remember why we introduced this suffix back in 2018, I just pushed [a new tag](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.15.29) without such a suffix. :heavy_check_mark:

2023-12-27 08:57 UTC, valgur commented
Oh, wow. That was a pleasant surprise. :smile: Thank you, @Dobiasd!

2023-12-27 08:57 UTC, closed without merging