xmlsec-1.2.38: Fix OpenSSL engine headers install on Windows
conan-io/conan-center-index pull request #21833
Opened 2023-12-20 16:55 UTC by gureedo

Specify library name and version:  **xmlsec/1.2.38**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-06 03:32 UTC, RubenRBS commented
Hi! Can I get some logs of the fixed bug, and how this addresses it. Has this been reported upstream?

2024-01-06 18:22 UTC, gureedo commented
It was just a bug in install script.
https://github.com/lsh123/xmlsec/pull/736

2024-01-10 11:12 UTC, ericLemanissier requested changes
Please use this patch instead https://github.com/lsh123/xmlsec/commit/6e0649b49b8d3f51d4f443bc526beed3f2d96c64 and mark it as a backport of https://github.com/lsh123/xmlsec/pull/511

2024-01-10 11:14 UTC, ericLemanissier approved these changes

2024-03-24 14:46 UTC, valgur commented on recipes/xmlsec/all/patches/1.2.38-fix-openssl-engine-headers-install-on-windows.patch
> ++	if exist $(BASEDIR)\include\$(XMLSEC_NAME) copy $(BASEDIR)\include\$(XMLSEC_NAME)\*.h $(INCPREFIX)\$(XMLSEC_NAME)
```suggestion
 	if exist $(BASEDIR)\include\$(XMLSEC_NAME) copy $(BASEDIR)\include\$(XMLSEC_NAME)\*.h $(INCPREFIX)\$(XMLSEC_NAME)	
```
Just a suggestion to keep the patch slightly clearer.

2024-03-24 14:47 UTC, valgur approved these changes

2024-05-02 10:22 UTC, closed without merging