libsigcpp: add v3.6.0, v2.12.1
conan-io/conan-center-index pull request #21954
Opened 2023-12-26 19:21 UTC by valgur

2024-01-06 02:50 UTC, RubenRBS requested changes
Thanks! Small comment about the packaged contents

2024-01-06 02:50 UTC, RubenRBS commented on recipes/libsigcpp/3.x.x/conanfile.py
Check the hook errors, we might want to remove the uncessary doc packaging

2024-01-07 09:43 UTC, valgur commented on recipes/libsigcpp/3.x.x/conanfile.py
It's 'long paths' warning for the source folder, but I removed it nevertheless, since it's not required for building.

2024-02-28 14:05 UTC, RubenRBS commented
@valgur repinging @uilianries - im on holiday this week :)

2024-08-07 17:42 UTC, valgur commented
Could use another review.

2025-03-09 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=21954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=21954) before we can accept your contribution.<br/><hr/>**Martin Valgur** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=21954) it.</sub>

2025-03-17 09:36 UTC, closed without merging