jom: add v1.1.4
conan-io/conan-center-index pull request #21971
Opened 2023-12-27 09:22 UTC by valgur

2024-01-06 02:40 UTC, RubenRBS requested changes
Thanks! Minor change

2024-01-06 02:40 UTC, RubenRBS commented on recipes/jom/all/conandata.yml
> +      url: "https://code.qt.io/cgit/qt-labs/jom.git/plain/LICENSE.GPL?h=v1.1.2"
```suggestion
      url: "https://code.qt.io/cgit/qt-labs/jom.git/plain/LICENSE.GPL?h=v1.1.3"
```

2024-01-10 11:02 UTC, ericLemanissier approved these changes

2024-03-22 17:27 UTC, jcar87 approved these changes

2024-03-22 17:28 UTC, RubenRBS approved these changes

2024-03-22 17:45 UTC, merged