libpsl: add v0.21.2, bump deps, simplify patching
conan-io/conan-center-index pull request #22029
Opened 2023-12-28 17:03 UTC by valgur

2023-12-31 08:37 UTC, eli-schwartz commented
How does this "simplify patching"? Patch files can be cleanly verified to still apply, doing the equivalent of a sed will appear to work but potentially do nothing or potentially break things without providing any feedback that it didn't do what's expected.

2023-12-31 10:51 UTC, valgur commented
@eli-schwartz It does not, from the perspective of the package consumer, at least. But it achieves the exact same result with a much lower maintenance burden. The changes here are relatively trivial and easy to re-apply, but re-applying such patches really adds up across hundreds of packages, when trying to keep most of them up to date.

> doing the equivalent of a sed will appear to work but potentially do nothing or potentially break things without providing any feedback that it didn't do what's expected

It's a valid concern, but the `replace_in_file` method accounts for this and defaults to `strict=True`, which results in an error being raised in case of the replacement not being applied.

2023-12-31 13:09 UTC, eli-schwartz commented
That's the "or potentially break things" case I mentioned. Seds have a distressing tendency to break due to upstream changes that move code around so the sed still does *something*, just not, well, the thing you originally intended it to do.

2023-12-31 13:14 UTC, eli-schwartz commented
Anyways, upstream has already changed this to support `-Dtests=false` which will disable this without any form of replacements or patching. Which is proof that you should NOT use a sed. The modifications are only needed for one version, and the next release tag, a patch will stop applying (but a sed will still apply) and you ***want*** to be notified that the patch stops applying, because it is your notification that you should stop modifying the file and start passing a build option instead.

This is a small part of why I hate seds, whether they are implemented in python with strict parameters or not.

2023-12-31 13:16 UTC, valgur commented
> Anyways, upstream has already changed this to support -Dtests=false which will disable this without any form of replacements or patching. Which is proof that you should NOT use a sed.

It's still working as expected.

2024-11-22 09:40 UTC, danimtb approved these changes

2024-11-27 22:33 UTC, AbrilRBS approved these changes

2024-11-27 22:33 UTC, AbrilRBS commented on recipes/libpsl/all/conanfile.py
> +            self.requires("libunistring/1.1")
Podofo is the only library that uses this too, we should bring it in-line with this in a follow-up PR @danimtb @valgur

2024-11-28 06:49 UTC, franramirez688 approved these changes

2024-11-28 06:53 UTC, franramirez688 requested changes
Sorry, I need to check the new variable `tests` upstream.

2024-11-28 07:02 UTC, franramirez688 commented on recipes/libpsl/all/conanfile.py
> +        self._patch_sources()
```suggestion
```

2024-11-28 07:04 UTC, franramirez688 approved these changes
I just added the new meson option upstream `tests` so we avoid introducing the replace-in-file pattern.

Looking good to me!

2024-11-28 08:27 UTC, AbrilRBS approved these changes

2024-11-28 08:28 UTC, merged