autoconf: add v2.72
conan-io/conan-center-index pull request #22048
Opened 2023-12-28 23:28 UTC by valgur

2024-01-02 10:04 UTC, jcar87 requested changes
Thanks for your contribution!

I can see that the implementation of the relocatability is different than how it's currently done for the existing versions: https://github.com/conan-io/conan-center-index/blame/master/recipes/autoconf/all/patches/2.71-0001-relocatable-autoconf.patch

Please ensure that these changes are motivated and explained  in the pull request descriptions. The existing implementation was tested thoroughly on several systems before it was merged, and to my knowledge no issues have been reported in the past several months.  
I do remember testing different alternatives, but don't remember the specifics of why findbin was discarded.

I would err on the side of caution and use the same implementation as before, unless problems are reported.

2024-01-02 18:25 UTC, valgur commented
@jcar87 I only touched these patches due to them needing rebasing and extending to one additional file for the new version. The standard function seemed like a slightly better tool for the job in a vacuum, but I agree that it's not worth the potential breakage. I reverted them back to the old logic.

2024-01-30 13:30 UTC, jwillikers approved these changes

2024-02-08 15:11 UTC, jcar87 approved these changes
Thanks @valgur !

2024-02-08 15:28 UTC, merged