qt/5.x.x: Fix opengl/system dependency to not be required when using es2
conan-io/conan-center-index pull request #22132
Opened 2024-01-03 17:22 UTC by jwillikers

The opengl/system dependency is very misleading.
For Linux, it is a requirement for the legacy gl interface used for X11.
This is not necessarily required when using the es2 OpenGL backend and likely Wayland.

This PR only requires `opengl/system` on Linux when `with_x11` is enabled.

Fixes #22116.

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-04-19 06:01 UTC, ericLemanissier requested changes
Thanks, but it looks to me that the package_info is incomplete: egl is never added to the requirements of a module.
I wish I had the time to refactor the requirements(self) and package_info(self) methods to use a single method defining both components and requirements, instead of duplicating everything :(

2024-07-25 14:13 UTC, jcar87 commented
would it not make sense to make depending on `egl/system` conditional on the value of `self.options.opengl`?

right now it is:
``
        if self.options.get_safe("opengl", "no") != "no":
            self.requires("opengl/system")
```

but it could possibly be:
```
        if self.options.get_safe("opengl", "no") == "desktop":
            self.requires("opengl/system")
        elif self.options.get_safe("opengl", "no")  == "es2":
           self.requires("egl/system") 
```

seems a bit odd to just sort of ignore the value given to the option and do it depending on a particular combination of other options and settings - may as well be a True/False or not an option at all in that case

assuming that `with_x11=False` and `opengl=es2` might work just with the above

2024-07-25 19:33 UTC, jwillikers commented
> would it not make sense to make depending on `egl/system` conditional on the value of `self.options.opengl`?
> 
> right now it is:
> 
> ```
>         if self.options.get_safe("opengl", "no") != "no":
>             self.requires("opengl/system")
> ```
> 
> but it could possibly be:
> 
> ```
>         if self.options.get_safe("opengl", "no") == "desktop":
>             self.requires("opengl/system")
>         elif self.options.get_safe("opengl", "no")  == "es2":
>            self.requires("egl/system") 
> ```
> 
> seems a bit odd to just sort of ignore the value given to the option and do it depending on a particular combination of other options and settings - may as well be a True/False or not an option at all in that case
> 
> assuming that `with_x11=False` and `opengl=es2` might work just with the above

That seems like it should work to me.

2024-11-22 11:33 UTC, uilianries commented on recipes/qt/5.x.x/conanfile.py
> +                self.requires("opengl/system")
```suggestion
            if self.options.get_safe("opengl", "no") == "desktop":
                self.requires("opengl/system")
            elif self.options.get_safe("opengl", "no")  == "es2":
                self.requires("egl/system") 
```

2024-11-22 11:38 UTC, uilianries commented
Suggestion https://github.com/conan-io/conan-center-index/pull/22132#issuecomment-2250429768 applied in the commit [d69889f](https://github.com/conan-io/conan-center-index/pull/22132/commits/d69889f97689a0c1e46bf79215468a8190fa0a99)

2025-03-18 06:41 UTC, closed without merging

2025-04-19 19:47 UTC, franramirez688 commented
Not stale.