minhook: add minhook/1.3.3 recipe
conan-io/conan-center-index pull request #22165
Opened 2024-01-05 02:49 UTC by wu-vincent

Specify library name and version:  **minhook/1.3.3**

[**minhook**](https://github.com/TsudaKageyu/minhook) is a x86/x64 API Hooking Library for Windows. It is a lightweight alternative to the Detours library. Although I am not the original author, providing a Conan recipe for this useful library will benefit the community with easier integration and broader usage.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-05 02:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22165) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22165) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22165) it.</sub>

2024-01-05 23:54 UTC, RubenRBS commented
Maybe we could ask the maintainers to also create a new release? The last one is from 2017!

2024-01-08 10:11 UTC, wu-vincent commented
Hi, thank you for your suggestion. I completely agree that having the latest releases in Conan Center is ideal for ensuring the most up-to-date and stable versions are available. Someone raised an [issue](https://github.com/TsudaKageyu/minhook/issues/113) back in April to request a new release. Unfortunately, there hasn't been a response from the maintainer yet.

In light of this, I propose creating a cci version of the package (e.g., minhook/cci.20240108). This would enable users to benefit from the recent improvements while we await an official release. This approach has been adopted for other libraries in similar situations, such as [detours/cci.20220630](https://conan.io/center/recipes/detours?version=cci.20220630).

I'd appreciate your thoughts on this approach or any alternative suggestions you might have.

2024-01-11 00:16 UTC, RubenRBS commented
@wu-vincent let's do that!

2024-03-24 15:34 UTC, valgur requested changes
LGTM. Just one minor change required.

2024-03-24 15:34 UTC, valgur commented on recipes/minhook/all/patches/cci.20240114-0001-increase-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
```suggestion
+cmake_minimum_required(VERSION 3.15)
```
Might as well make it 3.15, which avoids `shared` and `fPIC` issues and is required by Conan anyway.

2024-03-24 21:39 UTC, wu-vincent commented
@valgur Thank you for the suggestion! I've made the change accordingly.

2024-03-24 22:50 UTC, valgur approved these changes

2024-07-29 11:08 UTC, memsharded reviewed
This is looking good, I'll try to give it a final push to get it merged.
Thanks for your contribution, and I apologize for the delays in reviewing, the load is simply overwhelming and prioritizing is very challenging.

2024-07-29 11:08 UTC, memsharded commented on recipes/minhook/all/conandata.yml
> +  "cci.20240114":
We will be updating this versioning scheme, to be more future-proof. I'll do it myself and contribute.

2024-07-29 17:35 UTC, AbrilRBS approved these changes

2024-07-29 21:46 UTC, memsharded approved these changes

2024-07-29 22:06 UTC, merged