Upgrading C++ DataFrame to version 2.3.0
conan-io/conan-center-index pull request #22172
Opened 2024-01-05 18:38 UTC by hosseinmoein

Specify library name and version:  **lib/1.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-05 18:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22172) it.</sub>

2024-01-05 19:59 UTC, hosseinmoein commented
> ### Conan v1 pipeline ❌
> Failure in build 1 (`5a4675c03a139897472b05397ff837ed6d193670`):

Fixed

2024-01-05 23:22 UTC, RubenRBS requested changes
Thanks! All good, but will wait until C++23 is supported, thanks!

2024-01-05 23:22 UTC, RubenRBS commented on recipes/dataframe/all/conanfile.py
> +            return "23"
Im going to block merging this until we support C++23 in CCI, I'll push for it next week, thanks a lot for your patience

(Else no binaries for the new version will be generated)

2024-01-09 16:40 UTC, RubenRBS approved these changes

2024-01-09 16:42 UTC, uilianries approved these changes
LGTM

2024-01-09 18:40 UTC, merged