speedb: add recipe
conan-io/conan-center-index pull request #22209
Opened 2024-01-08 12:22 UTC by toge

Specify library name and version:  **speedb/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-29 16:40 UTC, uilianries reviewed
I did not understand very this project, is it a wrapper to Rocksdb or is it vendorized in the project? I just build Rocksdb and the generated headers files are the same! So or this recipe should use `provide = "rocksdb"` or check is using rocksdb as vendor and we could (or not) separate it.

2024-02-29 16:40 UTC, uilianries commented on recipes/speedb/all/conanfile.py
> +        # to avoid wrong CPU detection, modify not to use "-march=native" in apple-clang
@toge Is it to be able to compiler in Mac M1? If yes, could you please report the upstream about the case?

2024-02-29 16:40 UTC, uilianries commented on recipes/speedb/all/conanfile.py
> +        self.cpp_info.set_property("pkg_config_name", "speedb")
```suggestion
        self.cpp_info.set_property("pkg_config_name", "speedb")
        self.cpp_info.set_property("cmake_file_name", "Speedb")
        self.cpp_info.set_property("cmake_target_name", "Speedb::speedb")
```

https://github.com/speedb-io/speedb/blob/main/CMakeLists.txt#L1287
https://github.com/speedb-io/speedb/blob/main/CMakeLists.txt#L1337

2024-03-01 17:23 UTC, toge commented
@uilianries 
Since speedb has become a library featuring 100% compatibility with rocksdb, it seems that the header file names are unified. Although it features compatibility, it does not seem to be a wrapper for rocksdb.

2024-03-24 22:17 UTC, valgur commented on recipes/speedb/all/conanfile.py
> +        tc.variables["ROCKSDB_BUILD_SHARED"] = self.options.shared
```suggestion
        tc.variables["ROCKSDB_BUILD_SHARED"] = self.options.shared
        tc.cache_variables["CMAKE_POLICY_DEFAULT_CMP0077"] = "NEW"
```

2024-03-24 22:18 UTC, valgur commented on recipes/speedb/all/patches/2.8.0-0001-use-cci.patch
Can be avoided by using `CMakeDeps.set_property()` on `cmake_file_name` and `cmake_target_name` properties.

2024-03-24 22:19 UTC, valgur requested changes
CMP0077 is required, otherwise LGTM.

2024-04-04 09:51 UTC, uilianries approved these changes
LGTM

2024-04-05 22:43 UTC, RubenRBS approved these changes

2024-04-05 22:48 UTC, merged