Update to h5pp/1.11.1
conan-io/conan-center-index pull request #22271
Opened 2024-01-12 09:35 UTC by DavidAce

**h5pp/1.11.1**

Bump version

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-12 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22271) it.</sub>

2024-01-14 12:21 UTC, DavidAce commented
The build fails because hdf5/1.14.13 (the latest) is missing binaries for armv8. These binaries exist for hdf5/1.14.2 though.

I'm not sure how to resolve this type of issue. Any help is appreciated.

2024-01-15 07:58 UTC, uilianries commented
I just started an internal CI build to generate the missing hdf5/1.14.3 package. Sorry the inconvenience.

2024-01-15 09:44 UTC, franramirez688 submitted a review, later dismissed

2024-01-15 13:02 UTC, uilianries requested changes
avoid ranged versions for any packages. It will result in missing dependency in future PRs.

2024-01-15 13:05 UTC, franramirez688 reviewed
Absolutely @uilianries 
I approved it, but I didn't realize about those version ranges

2024-01-15 13:09 UTC, DavidAce commented on recipes/h5pp/all/conanfile.py
> +        self.requires("hdf5/[>=1.10.0 <1.15]", transitive_headers=True, transitive_libs=True)
Fixed! Thanks!

2024-01-15 16:03 UTC, uilianries approved these changes
LGTM

2024-01-15 18:29 UTC, franramirez688 approved these changes

2024-01-15 18:40 UTC, merged