g2o: new recipe
conan-io/conan-center-index pull request #22337
Opened 2024-01-14 22:04 UTC by valgur

Adds `g2o`: https://github.com/RainerKuemmerle/g2o

g2o: A General Framework for Graph Optimization

It's currently missing important, but optional, SuiteSparse and CSparse solver dependencies, which are not yet available on CCI.

- Resolves #10931

[![Packaging status](https://repology.org/badge/tiny-repos/g2o.svg)](https://repology.org/project/g2o/versions)

2024-03-25 12:03 UTC, jwillikers requested changes

2024-11-20 08:40 UTC, metalMajor commented
Hello, I have added a PR to your fork to be able to disable the opengl option:

https://github.com/valgur/conan-center-index/pull/10

2024-11-30 14:20 UTC, valgur commented
@rettichschnidi The g2o recipe is blocked by SuiteSparse support on CCI (#23546), which in turn is blocked by the limited OpenMP support on CCI (#22360, #24577), as it relies solely on OpenMP for parallelization support. It currently cannot be built on CCI and potentially many Linux-based consumer machines due to missing OpenMP runtimes.
You can join the discussion on the OpenMP issues, if you feel like it, to help show that the need for improvements is not just a weird obsession of mine and that users on macOS do actually wish to use linear algebra libraries relying on OpenMP, despite Apple's attempts to force its native frameworks (Accelerate and GCD) on its users.

2024-11-30 14:26 UTC, valgur commented
Also, in the mean time, you can use my CCI fork that has support for g2o and many other CV/robotics libraries: https://github.com/valgur/conan-center-index

2025-03-09 09:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22337) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: metalMajor<br/>:x: Martin Valgur<br/><hr/>**Martin Valgur** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22337) it.</sub>

2025-03-17 09:35 UTC, closed without merging