[fix] Fix DuckDB extension build
conan-io/conan-center-index pull request #22361
Opened 2024-01-15 19:54 UTC by Taepper

Specify library name and version:  **duckdb/0.9.2**

Resolves #22347

The duckdb makefile is the only reference how to specify build flags. That has deteriorated for extensions as of version >=0.9

I have not tried it with a conan center hook, but would be interested to learn how that would be done.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-15 19:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22361) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22361) it.</sub>

2024-01-16 09:34 UTC, uilianries requested changes
@Taepper Thank you for your hotfix. Your change only works to duckdb >= 0.9, resulting in breaking change for who is using older versions of this package:

https://github.com/duckdb/duckdb/blob/v0.8.1/CMakeLists.txt

Please, add some condition to exclude or not option and cmake definition according to your package version. As real example you could use https://github.com/conan-io/conan-center-index/blob/master/recipes/qcbor/all/conanfile.py

Regards.

2024-01-16 09:37 UTC, uilianries commented
> I have not tried it with a conan center hook, but would be interested to learn how that would be done.

@Taepper Please, read the follow documentation:

https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md

It's instructed how to use ConanCenter hooks. It only works with Conan 1.x for now. Regards.

2024-01-16 09:38 UTC, uilianries commented
@Taepper Please, ask for CI authorization in the issue #4. Otherwise, the CI build will not run your PR. Regards!

2024-01-23 10:41 UTC, uilianries submitted a review, later dismissed
LGTM

2024-01-23 12:05 UTC, Taepper commented
Just cleaned up the commit history without changing the change-list. Sorry for not doing so earlier

2024-01-23 13:13 UTC, uilianries commented
> Just cleaned up the commit history without changing the change-list. Sorry for not doing so earlier

@Taepper this is not needed because we squash before merging, but thank you!

2024-01-23 13:14 UTC, uilianries approved these changes
LGTM

2024-01-23 13:26 UTC, franramirez688 approved these changes

2024-01-23 18:00 UTC, merged