gperftools: fix missing libcxx dependency
conan-io/conan-center-index pull request #22380
Opened 2024-01-16 13:12 UTC by valgur

Fixes the build failure in the jxl recipe (#18812):
```
/usr/bin/ld: /home/conan/w/prod-v1/bsr/90439/bedfd/.conan/data/gperftools/2.13.0/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/lib/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.so: error adding symbols: DSO missing from command line
```

I can reproduce it in this recipe as well after switching test_package to pure C and building statically without the libcxx dependency added.

2024-01-18 12:02 UTC, ericLemanissier requested changes
I always prefer function calls to preprocessor macros to test the linking

2024-01-18 12:02 UTC, ericLemanissier commented on recipes/gperftools/all/test_package/test_package.c
> +    puts(TC_VERSION_STRING);
```suggestion
    puts(tc_version(NULL, NULL, NULL));
```

2024-01-18 12:13 UTC, ericLemanissier commented
The build is now finished. You can take a look at the results [here](https://github.com/ericLemanissier/proof-of-conan/actions/runs/7569721259/attempts/1)

2024-01-18 12:14 UTC, ericLemanissier approved these changes

2024-01-22 17:51 UTC, RubenRBS approved these changes

2024-01-22 17:56 UTC, merged