aws-c-cal: fix dependency version conflict
conan-io/conan-center-index pull request #22427
Opened 2024-01-18 15:04 UTC by st9007a

Specify library name and version:  **aws-c-cal/0.6.9**

After adding `was-c-common/0.9.12`, I tried to use this version in `aws-c-io` but got a build failure. It is because the dependency of `aws-c-io`: `aws-c-cal` is hard coded to use `aws-c-common/0.9.6`. So, I filed this PR to adjust the version range of the dependencies.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-24 15:39 UTC, valgur requested changes
Version ranges are only allowed for a limited set of packages. You will have to use a specific version for now.

2024-03-25 06:25 UTC, st9007a commented
> Version ranges are only allowed for a limited set of packages. You will have to use a specific version for now.

Hi valgur,

Thanks for your review. Do you mean there should be a upper bound for `aws-c-common/[>=0.9.7]` ?

2024-03-25 12:35 UTC, st9007a commented
> > Version ranges are only allowed for a limited set of packages. You will have to use a specific version for now.
> 
> Hi @valgur,
> 
> Thanks for your review. Do you mean there should be a upper bound for `aws-c-common/[>=0.9.7]` ?

Following the suggestion from [here](https://github.com/conan-io/conan-center-index/pull/22406), I also updated this pr.

2024-03-25 14:11 UTC, valgur approved these changes

2024-06-03 12:43 UTC, danimtb approved these changes

2024-06-03 12:47 UTC, merged