zlib: add 1.3.1
conan-io/conan-center-index pull request #22504
Opened 2024-01-23 07:12 UTC by Cogitri

Specify library name and version:  **zlib/1.3.1**

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-01-24 07:13 UTC, hoyhoy approved these changes

2024-01-24 07:16 UTC, hoyhoy commented
Closes #22519

2024-01-24 10:13 UTC, RubenRBS approved these changes

2024-01-24 10:14 UTC, RubenRBS requested changes
Waiting for a CI change beforehand

2024-01-25 10:56 UTC, RubenRBS approved these changes

2024-01-25 12:34 UTC, merged