eventpp: new recipe
conan-io/conan-center-index pull request #22611
Opened 2024-02-01 01:18 UTC by RazielXYZ

Specify library name and version:  **eventpp/0.1.3**

[Eventpp](https://github.com/wqking/eventpp) is a C++11 header-only library for thread-safe callbacks, event dispatchers, and event queues.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-01 11:37 UTC, RubenRBS requested changes

2024-02-01 11:37 UTC, RubenRBS commented on recipes/eventpp/all/conanfile.py
> +
No need to call this if the recipe contains no patches :)
```suggestion
```

2024-02-01 11:37 UTC, RubenRBS commented on recipes/eventpp/all/conanfile.py
> +
```suggestion
```

2024-02-01 11:37 UTC, RubenRBS commented on recipes/eventpp/all/test_v1_package/CMakeLists.txt
No need for test_v1_packages for new recipes, but won't hurt if you leave it now that it's here :)

2024-02-01 11:38 UTC, RubenRBS approved these changes
Thanks a lot! The recipe looks great, I've just pushed a few minor changes, otherwise looks great :)

2024-02-01 13:54 UTC, jwillikers approved these changes

2024-02-01 14:08 UTC, merged

2024-02-02 01:38 UTC, wqking commented
Hi, thanks for adding eventpp to Conan. After you finish, can you please create an issue in eventpp repo to give me a piece of instruction on how to use Conan so I can add it to the document?