drogon: Add option to use spdlog
conan-io/conan-center-index pull request #22639
Opened 2024-02-02 13:02 UTC by matthiasbuhl

Library name and version:  **drogon/1.9.2**

As of **version 1.9.2**, drogon integrated the feature to use spdlog as the logging backend. 
The changes of this PR add support to the package to support this new feature.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-02 13:11 UTC, matthiasbuhl commented
The build seems to have failed but I cannot view any output of the build due to access restriction.
Can someone let me know what seems to be failing or how I can reproduce this locally?

2024-02-08 07:23 UTC, matthiasbuhl commented
@ericLemanissier and @prince-chrismc, 
did you have a chance to look at the changes made? Could you let me know why it might not be building according to the Github checks?

2024-02-08 07:51 UTC, ericLemanissier commented
Please read carefully all the messages above (in this PR)

2024-02-09 08:32 UTC, uilianries requested changes
The spdlog is a new feature, only available since 1.9.2. It should not be available as option to older versions. 

https://github.com/drogonframework/drogon/commit/8026790e1a8e1f3baf37bd2ecb822a1872933c55

Something like:

```
def config_options(self):
    if Version(self.version) < "1.9.2":
        del self.options.with_spdlog
```

2024-02-09 09:20 UTC, matthiasbuhl commented
> Thello @matthiasbuhl !! Thank you for your first contribution!
> 
> The spdlog is a new feature, only available since 1.9.2. It should not be available as option to older versions.
> 
> [drogonframework/drogon@8026790](https://github.com/drogonframework/drogon/commit/8026790e1a8e1f3baf37bd2ecb822a1872933c55)
> 
> Something like:
> 
> ```
> def config_options(self):
>     if Version(self.version) < "1.9.2":
>         del self.options.with_spdlog
> ```

Thanks for the feedback, Ill get right on it.

2024-02-09 09:36 UTC, matthiasbuhl commented
> Thello @matthiasbuhl !! Thank you for your first contribution!
> 
> The spdlog is a new feature, only available since 1.9.2. It should not be available as option to older versions.
> 
> [drogonframework/drogon@8026790](https://github.com/drogonframework/drogon/commit/8026790e1a8e1f3baf37bd2ecb822a1872933c55)
> 
> Something like:
> 
> ```
> def config_options(self):
>     if Version(self.version) < "1.9.2":
>         del self.options.with_spdlog
> ```

Should be fixed!

2024-02-09 10:28 UTC, uilianries reviewed
Looking good, only small details for safety.

2024-02-09 10:28 UTC, uilianries commented on recipes/drogon/all/conanfile.py
> +            del self.options.with_spdlog
```suggestion
           self.options.rm_safe("with_spdlog")
```

double deletion is an error in Conan 2.x.

2024-02-09 10:28 UTC, uilianries commented on recipes/drogon/all/conanfile.py
> +        tc.variables["USE_SPDLOG"] = self.options.get_safe("with_spdlog", False)
```suggestion
        if Version(self.version) > "1.9.1":
            tc.variables["USE_SPDLOG"] = self.options.get_safe("with_spdlog", False)
```
So we avoid cmake warnings to older versions.

2024-02-09 13:26 UTC, matthiasbuhl commented
Alright I think it should all be in now. Thanks for the help!

2024-02-09 14:34 UTC, uilianries commented
In terms of recipe it looks really good. Just waiting next authorized users wave to include you, then the CI will build this PR. Regards!

2024-02-09 15:57 UTC, matthiasbuhl commented
> I detected other pull requests that are modifying drogon/all recipe:
> 
> * [drogon: add version 1.9.3 #22730](https://github.com/conan-io/conan-center-index/pull/22730)
> 
> This message is automatically generated by https://github.com/ericLemanissier/conan-center-conflicting-prs so don't hesitate to report issues/improvements there.

Just checked this PR but it is not really conflicting as this PR only updates to the most recent drogon release but still does not bring in the option to activate the spdlog support that drogon introduced with 1.9.2

2024-02-22 11:57 UTC, closed without merging