thorvg: add recipe
conan-io/conan-center-index pull request #22746
Opened 2024-02-11 09:44 UTC by toge

Specify library name and version:  **thorvg/***

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-12 05:34 UTC, toge commented
@RubenRBS 
Would you please assist me as I don't have many recipes that I can refer to regarding meson?
I seem to get an error with the following code when I specify a BACKEND to MensonToolchain.
````python
meson = Meson(self)
meson.install()
````

The error is as follows.
```
... \src\meson.build:1:0: ERROR: Tried modify read only option 'backend'
```

Is there a problem with the way my conanfile.py is written and is there a workaround?

2024-02-12 11:54 UTC, RubenRBS commented
Hi @toge, I've pinged @franramirez688 which is more faimiliar than I am with Meson to take a look into this, thanks for the contribution as always, let's see what they find about your error :)

2024-02-12 13:05 UTC, toge commented
@RubenRBS 
Thanks a lot!

2024-02-15 12:49 UTC, danimtb commented
@toge FYI, I was having a look at this with @franramirez688 and we found a bug for the `backend='vs'` in Meson during the install step in `package()` method. We will report it upstream to get it fixed in new releases.

Meanwhile, we realized that using `backend='vs2022'` worked without issue, so let's try that in the recipe for now 😄 Thank you!

2024-02-16 09:42 UTC, franramirez688 commented
> @toge FYI, I was having a look at this with @franramirez688 and we found a bug for the `backend='vs'` in Meson during the install step in `package()` method. We will report it upstream to get it fixed in new releases.
> 
> Meanwhile, we realized that using `backend='vs2022'` worked without issue, so let's try that in the recipe for now 😄 Thank you!

https://github.com/mesonbuild/meson/issues/12868 cc @toge @RubenRBS @danimtb

2024-02-16 10:47 UTC, toge commented
@danimtb 
Thanks a lot!
I will try to fix it.

2024-02-27 11:07 UTC, franramirez688 commented
Hi @toge 

I've been working on this https://github.com/conan-io/conan/pull/15706 
That PR is removing the `reconfigure` process, so we shouldn't have any problem keeping the original `vs` backend. I think we can wait for it and try this PR again using Conan's latest version.

2024-03-01 07:16 UTC, toge commented
@franramirez688 
Thank you for information!
I'm waiting for it.

2024-04-09 12:38 UTC, franramirez688 reviewed
Minor suggestions, otherwise, it looks great.

2024-04-09 12:38 UTC, franramirez688 commented on recipes/thorvg/all/conanfile.py
> +        venv.generate(scope="build")
```suggestion
        venv.generate()
```

2024-04-09 12:38 UTC, franramirez688 commented on recipes/thorvg/all/conanfile.py
> +required_conan_version = ">=1.53.0"
```suggestion
required_conan_version = ">=1.64.0 <2 || >=2.2.0"
```

2024-04-09 12:43 UTC, franramirez688 commented on recipes/thorvg/all/conanfile.py
> +required_conan_version = ">=1.53.0"
This PR needs Conan 1.64 version

cc @danimtb

2024-04-09 12:57 UTC, franramirez688 submitted a review, later dismissed

2024-04-09 14:17 UTC, toge commented
@franramirez688 
Thank you for your review and updating this PR!
I am waiting for updating conan 1.64.0 in CCI.

2024-04-10 07:01 UTC, franramirez688 requested changes

2024-04-10 07:01 UTC, franramirez688 commented on recipes/thorvg/all/conanfile.py
> +            tc = MesonToolchain(self)
@toge I just realized about the available options https://github.com/thorvg/thorvg/blob/main/meson_options.txt
We should take care of them.

2024-04-16 09:22 UTC, franramirez688 approved these changes

2024-04-25 08:29 UTC, franramirez688 approved these changes

2024-04-25 08:30 UTC, RubenRBS approved these changes

2024-04-25 09:05 UTC, merged

2024-04-25 13:12 UTC, toge commented
@franramirez688 
Thanks a lot for lots of improvements!