sentry-breakpad: add version 0.7.0
conan-io/conan-center-index pull request #22759
Opened 2024-02-13 00:27 UTC by toge

Specify library name and version:  **sentry-breakpad/0.7.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-13 04:20 UTC, paulharris commented
Isn't the intent to switch to sentry-native ?

2024-02-13 19:36 UTC, MartinDelille commented
Updating this recipe is indeed not necessary anymore since sentry-native contains already both sentry-breakpad and sentry-crashpad backend.

2024-02-13 19:36 UTC, MartinDelille requested changes
Not applicable

2024-02-16 10:45 UTC, toge commented
@MartinDelille 
THank you for your information.
I don't know the status of sentry-xxx libraries.

I close it.

2024-02-16 10:45 UTC, closed without merging