nghttp3: add version 1.2.0
conan-io/conan-center-index pull request #22802
Opened 2024-02-17 11:58 UTC by toge

Specify library name and version:  **nghttp3/1.2.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-01 13:51 UTC, franramirez688 submitted a review, later dismissed

2024-03-04 08:41 UTC, ericLemanissier requested changes

2024-03-04 08:41 UTC, ericLemanissier commented on recipes/nghttp3/all/conanfile.py
> +from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, replace_in_file, rm, rmdir, copy
```suggestion
from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, rmdir
```

2024-03-04 10:00 UTC, toge commented on recipes/nghttp3/all/conanfile.py
> +from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, replace_in_file, rm, rmdir, copy
@ericLemanissier Thanks!

2024-03-04 10:13 UTC, ericLemanissier approved these changes

2024-03-04 10:22 UTC, franramirez688 approved these changes

2024-03-04 11:08 UTC, merged