Add option to disable xerces-c's network stack.
conan-io/conan-center-index pull request #22821
Opened 2024-02-19 13:38 UTC by ChristianHeinigk

Specify library name and version:  **xerces-c/ALL**

Fixes #22820. I'm using conan to install dependencies. I need to turn off xerces-c's network stack. With this PR, the cmake option will be available within the conanfile.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-02-19 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22821) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22821) it.</sub>

2024-02-19 14:08 UTC, uilianries commented
@ChristianHeinigk Thank you for your contribution. Could you please ask for access in the issue #4. The CI only builds after having people authorized there.

2024-02-19 14:36 UTC, uilianries requested changes

2024-02-19 14:36 UTC, uilianries commented on recipes/xerces-c/all/conanfile.py
> +    version = "3.2.5"
```suggestion
```
Please, do not specify the version in the recipe. It should be passed by command line, so it will be consumed from conandata.yml

2024-02-20 09:09 UTC, uilianries reviewed
@ChristianHeinigk Please, take a look in my PR https://github.com/ChristianHeinigk/conan-center-index/pull/1

Doing a check in the upstream project, I found a dependency between network and network-accessor.

2024-02-21 13:52 UTC, jwillikers approved these changes

2024-02-27 14:04 UTC, jwillikers approved these changes

2024-02-27 14:08 UTC, merged