freeimage/3.18.0: fix build error using msvc 193 with C++20
conan-io/conan-center-index pull request #22942
Opened 2024-03-01 10:25 UTC by elvisdukaj

Trying to build freeimage using MSVC 193 with C++20 results in a buid error. The issue was reported https://github.com/conan-io/conan-center-index/issues/18921.

I am creating a MR for this issue. I submitted also a MR upstream: [issue](https://github.com/WinMerge/freeimage/issues/19) and [MR](https://github.com/WinMerge/freeimage/pull/20).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-01 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=22942) before we can accept your contribution.<br/><hr/>**Elvis Dukaj** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=22942) it.</sub>

2024-03-01 13:06 UTC, uilianries commented on recipes/freeimage/all/conandata.yml
> +    - patch_file: "patches/015_fix_msvc_cpp_20.patch"
```suggestion
    - patch_file: "patches/015_fix_msvc_cpp_20.patch"
      patch_type: "official"
      patch_source: "https://github.com/WinMerge/freeimage/pull/20"
      patch_description: "Fix compilation with MSVC and C++20"
```

Please, always add information about the patch, so we track it.

2024-03-01 13:07 UTC, uilianries reviewed
Thank you for your quick response to this bug.

2024-03-01 13:08 UTC, uilianries commented
@elvisdukaj Could you please ask for access in the issue #4. So the CI can list you as authorized user.

2024-03-01 13:13 UTC, jcar87 requested changes
Hi @elvisdukaj - thank you for your contribution and for looking into this.

Please note that your proposed patch https://github.com/WinMerge/freeimage/pull/20 was *not* submitted to the canonical sources of freeimage, but to an unofficial clone.

Please submit or contact the maintainers at https://freeimage.sourceforge.io/. 

Please note that we will not regularly accept patches fixing problems that are in library code - this should be reported and dealt with upstream. If this library is _not_ maintained anymore, we will not be providing an extended life support in Conan Center. Remember that you can always instruct Conan to install a compatible version.

2024-03-02 16:27 UTC, elvisdukaj commented
Hi @jcar87  thank you for your feedback!

Well if it’s not appropriate the patch in this context we can close this MR then. I’ll keep it only internally to my company! The project seems not maintained anymore indeed. I wasn’t aware that the GitHub wasn’t the official one 😞

2024-03-04 09:50 UTC, jcar87 commented
> Well if it’s not appropriate the patch in this context we can close this MR then. I’ll keep it only internally to my company! The project seems not maintained anymore indeed. I wasn’t aware that the GitHub wasn’t the official one 😞

Thanks so much @elvisdukaj  and thanks for your efforts! Keeping this internal is the way to go in these cases. 
I will close the PR. We have no way of validating the proposed changes: they don't run on our CI, and we are not familiar with the codebase of this library to ascertain that this is compatible and working. For libraries that are no longer maintained by their authors, we will consider them unmaintained and won't be maintaining them ourselves either.

Thanks!

2024-03-04 09:50 UTC, closed without merging