fix gmp/6.3.0:ctest:command not found issue
conan-io/conan-center-index pull request #22980
Opened 2024-03-05 10:39 UTC by crstzh

For gmp/6.3.0, it might show the below error if CMake is not present in the run environment.

```
======== Testing the package: Executing test ========
gmp/6.3.0 (test package): Running test()
gmp/6.3.0 (test package): RUN: ctest --output-on-failure -C Release
/bin/sh: line 1: ctest: command not found
```
we can bypass this by using the `conanbuild` environment on non-Windows platforms.

Specify library name and version:  **gmp/6.3.0**
- [X ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-06 09:20 UTC, jcar87 commented
Hi @crstzh  - a bit confused by this.

Recipes in Conan Center (and by extension the test package) are free to assume that CMake is installed at the system level.

Under what scenarios is this failing? Could you provide a reproducible example.

2024-03-06 09:20 UTC, jcar87 requested changes
waiting for user to provide reproducible example

2024-03-06 12:27 UTC, crstzh commented
> Hi @crstzh - a bit confused by this.
> 
> Recipes in Conan Center (and by extension the test package) are free to assume that CMake is installed at the system level.
> 
> Under what scenarios is this failing? Could you provide a reproducible example.

It's easy to reproduce. 

1. git clone git@github.com:conan-io/conan-center-index.git 
2. cd conan-center-index\recepies\gmp
3. conan create all --version=6.3.0   -pr windows-msvc17.6.0-x86_64 -s build_type=Debug --build=missing

```
======== Testing the package: Executing test ========
gmp/6.3.0 (test package): Running test()
gmp/6.3.0 (test package): RUN: ctest --output-on-failure -C Release
/bin/sh: line 1: ctest: command not found
```

2024-03-06 17:26 UTC, jcar87 commented
Thanks @crstzh 

What are the contents of your  `windows-msvc17.6.0-x86_64` ? Is CMake not installed at a global level? What terminal/console are you using?

Please bear in mind that we _do_ assume but all of conan center that CMake (and by extension, ctest) are installed and discoverable in `PATH`.

2024-03-07 00:34 UTC, crstzh commented
> windows-msvc17.6.0-x86_64
my windows-msvc17.6.0-x86_64 is this:
```
{% set arch="x86_64" %}
{% set runtime="dynamic" %}

{% include "windows-msvc17.6.0" %}
```
and the windows-msvc17.6.0 content:
```
[settings]
os=Windows
arch={{arch}}

{% if build_type is defined %}
build_type={{build_type}}
{% else %}
build_type=Release
{% endif %}

compiler=msvc
compiler.cppstd=20
compiler.version=193
compiler.runtime={{runtime}}


[tool_requires]
#!msvc_desktop|msvc_redists|windows_redists|toolchain|windows_toolchain: msvc_desktop/17.6.0-sdk22h2.755
#!msvc_desktop|msvc_redists|windows_redists|toolchain|windows_toolchain: msvc_redists/17.6.0
#!msvc_desktop|msvc_redists|windows_redists|toolchain|windows_toolchain: windows_redists/17.6.0-sdk22h2.755
#!msvc_desktop|msvc_redists|windows_redists|toolchain|windows_toolchain|cmake|ninja: cmake/3.27.1
#!msvc_desktop|msvc_redists|windows_redists|toolchain|windows_toolchain|cmake|ninja: ninja/1.11.1

[options]
{% if build_profile is defined %}
*:shared = False
{% endif %}

[conf]
# Target Windows 7
tools.build:defines += ["NTDDI_VERSION=0x06010000", "WIN32_WINNT=0x0601"]

{% if build_profile is defined %}

{% else %}

# If any of the below compiler flags are modified we must update this
# flags_version variable to ensure that all conan recipes are compiled again
# with the new flags and that the flags_version contributes to package_id.
user.windows_msvc:flags_version=3
tools.info.package_id:confs=["user.windows_msvc:flags_version"]

# Note: please use the - prefix instead of / for all compile flags to ensure
# compatibility with bash/msys2/autotools/gnu builds on windows

# -EHsc - exception handling model
# -Zi - generate debug information in a .pdb file
# -Qspectre - security: spectre mitigations
# -guard:cf - security: control flow guard
tools.build:cflags += ["-EHsc", "-Zi", "-Qspectre", "-guard:cf"]
tools.build:cxxflags += ["-EHsc", "-Zi", "-Qspectre", "-guard:cf"]

# -DEBUG: Always generate debug information
# -guard:cf: security: Control flow guard
tools.build:sharedlinkflags += ["-DEBUG", "-guard:cf"]
tools.build:exelinkflags += ["-DEBUG", "-guard:cf"]

{% endif %}

```

2024-03-14 06:16 UTC, crstzh reviewed
Hello, cmake.ctest() does not work. Will you follow up this?

2024-03-24 17:37 UTC, valgur commented on recipes/gmp/all/test_package/conanfile.py
> +            cmake.ctest()
```suggestion
            self.run(f"ctest --output-on-failure -C {self.settings.build_type}", env="conanbuild")
```

2024-11-06 18:03 UTC, jcar87 commented
closed as superseded by https://github.com/conan-io/conan-center-index/pull/25859

2024-11-06 18:03 UTC, closed without merging