libffi 3.4.4 -> 3.4.6
conan-io/conan-center-index pull request #23066
Opened 2024-03-11 23:13 UTC by YSaxon

adding urls and hashes for libffi versions 3.4.5 and 3.4.6 (existing is 3.4.4)
I haven't actually figured out how to test it, but it's a pretty simple PR just adding urls and hashes, and I assume you have CI that will test it in any case.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-11 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23066) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23066) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=23066) it.</sub>

2024-03-24 17:44 UTC, valgur requested changes
LGTM, but don't add v3.4.5.

2024-03-24 17:44 UTC, valgur commented on recipes/libffi/all/conandata.yml
> +    sha256: "96fff4e589e3b239d888d9aa44b3ff30693c2ba1617f953925a70ddebcc102b2"
```suggestion
```
Don't add intermediate versions unless there is a specific need for them.

2024-06-12 13:25 UTC, uilianries commented
@YSaxon Thank you for your contribution and effort! 

This PR is now surpassed by the PR #23362 and will be closed.

2024-06-12 13:25 UTC, closed without merging