rocksdb/6.29.5: add patch to ignore thirdparty.inc
conan-io/conan-center-index pull request #23090
Opened 2024-03-14 03:03 UTC by thejohnfreeman

**rocksdb/6.29.5**

RocksDB has [special instructions](https://github.com/facebook/rocksdb/blob/v6.29.5/CMakeLists.txt#L11) for compiling on Windows that asks builders to edit the special file [`thirdparty.inc`](https://github.com/facebook/rocksdb/blob/v6.29.5/thirdparty.inc) to set variables pointing to all of the optional dependencies they want to enable. The main `CMakeLists.txt` follows the best practice of calling `find_package()` and linking to imported targets, but only for non-MSVC generators.

Thus, the latest RocksDB recipe in Conan Center builds with MSVC, but does not correctly link to any optional dependencies that are enabled. `thirdparty.inc` is included with nonsense paths and the build fails when it cannot find third-party headers.

The old RocksDB recipe in Conan Center used a CMake subproject model. It had its own [`CMakeLists.txt`](https://github.com/conan-io/conan-center-index/blob/1a1b7fc7959cdf8fc97cce745fe844e31194db29/recipes/rocksdb/all/CMakeLists.txt) that first called `conan_basic_setup()` before calling `add_subdirectory()` for the project. I don't know how, but it worked.

This patch removes the branch on MSVC that includes `thirdparty.inc` instead of calling `find_package()`, but only for version 6.29.5 (the one I need for now).

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-14 09:28 UTC, RubenRBS commented
Logs after patch:
<details>

```

 conan create . --version=6.29.5 -b=missing -o"&:with_zlib=True" -o"&:with_snappy=True"

======== Exporting recipe to the cache ========
rocksdb/6.29.5: Exporting package recipe: Z:\coding\support\external\thejohnfreeman\recipes\rocksdb\all\conanfile.py
rocksdb/6.29.5: exports: File 'conandata.yml' found. Exporting it...
rocksdb/6.29.5: Calling export_sources()
rocksdb/6.29.5: Copied 1 '.yml' file: conandata.yml
rocksdb/6.29.5: Copied 1 '.py' file: conanfile.py
rocksdb/6.29.5: Copied 2 '.patch' files: 6.29.5-0001-add-include-cstdint-for-gcc-13.patch, 6.29.5-0002-exclude-thirdparty.patch
rocksdb/6.29.5: Exported to cache folder: C:\Users\ruben\.conan2\p\rocks0d514a3e78f40\e
rocksdb/6.29.5: Exported: rocksdb/6.29.5#793fd50634654f9d43bad8ffb0c65f3a (2024-03-14 09:13:16 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[options]
&:with_snappy=True
&:with_zlib=True

Profile build:
[settings]
arch=armv8
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    rocksdb/6.29.5#793fd50634654f9d43bad8ffb0c65f3a - Cache
    snappy/1.1.10#916523630083f6d855cb2977de8eefb6 - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3.1

======== Computing necessary packages ========
rocksdb/6.29.5: Checking 3 compatible configurations
rocksdb/6.29.5: Compatible configurations not found in cache, checking servers
rocksdb/6.29.5: '26ab0ec0bf4c6cfb670c13c928b4f24fe30b1145': compiler.cppstd=17
rocksdb/6.29.5: 'f9d6b7558596023ea54fc2cd50a41dd0506455ed': compiler.cppstd=20
rocksdb/6.29.5: 'eaa981c533e4661cd4134b9733bb85b76711588f': compiler.cppstd=23
Requirements
    rocksdb/6.29.5#793fd50634654f9d43bad8ffb0c65f3a:d3263b7de4815a9ae69f7f082608e1d199c4fefd - Build
    snappy/1.1.10#916523630083f6d855cb2977de8eefb6:94cb4bb25d64f2598a7dec974b5e13052d7d6b49#2eabdc6b764abefb1c9d6c2f0c8f2fea - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:ea5dc84deb25b32a77ec23c39a1811e3f441ee54#1a7395640d8d00eaaf9e6b412c9decf2 - Cache

======== Installing packages ========
snappy/1.1.10: Already installed! (1 of 3)
zlib/1.3.1: Already installed! (2 of 3)
rocksdb/6.29.5: Calling source() in C:\Users\ruben\.conan2\p\rocks0d514a3e78f40\s\src

-------- Installing package rocksdb/6.29.5 (3 of 3) --------
rocksdb/6.29.5: Building from source
rocksdb/6.29.5: Package rocksdb/6.29.5:d3263b7de4815a9ae69f7f082608e1d199c4fefd
rocksdb/6.29.5: Copying sources to build folder
rocksdb/6.29.5: Building your package in C:\Users\ruben\.conan2\p\b\rocks7fe22d9bdd212\b
rocksdb/6.29.5: Calling generate()
rocksdb/6.29.5: Generators folder: C:\Users\ruben\.conan2\p\b\rocks7fe22d9bdd212\b\build\generators
rocksdb/6.29.5: CMakeToolchain generated: conan_toolchain.cmake
rocksdb/6.29.5: CMakeToolchain generated: CMakePresets.json
rocksdb/6.29.5: CMakeToolchain generated: ..\..\src\CMakeUserPresets.json
rocksdb/6.29.5: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(Snappy)
    find_package(ZLIB)
    target_link_libraries(... Snappy::snappy ZLIB::ZLIB)
rocksdb/6.29.5: Generating aggregated env files
rocksdb/6.29.5: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
rocksdb/6.29.5: Calling build()
rocksdb/6.29.5: Apply patch (portability): Fix build with gcc 13 by including cstdint
rocksdb/6.29.5: Apply patch (portability): Do not include thirdparty.inc
rocksdb/6.29.5: Running CMake.configure()
rocksdb/6.29.5: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/ruben/.conan2/p/b/rocks7fe22d9bdd212/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/ruben/.conan2/p/b/rocks7fe22d9bdd212/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\ruben\.conan2\p\b\rocks7fe22d9bdd212\b\src"
-- Using Conan toolchain: C:/Users/ruben/.conan2/p/b/rocks7fe22d9bdd212/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
-- Conan toolchain: C++ Standard 14 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.39.33521.0
-- The C compiler identification is MSVC 19.39.33521.0
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostarm64/arm64/cl.exe
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostarm64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostarm64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Component target declared 'Snappy::snappy'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
-- Could NOT find uring (missing: uring_LIBRARIES uring_INCLUDE_DIR)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Disabling RTTI in Release builds. Always on in Debug.
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Failed
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE - Failed
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP - Failed
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for sched_getcpu
-- Looking for sched_getcpu - not found
-- Looking for getauxval
-- Looking for getauxval - not found
-- Looking for F_FULLFSYNC
-- Looking for F_FULLFSYNC - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- ROCKSDB_PLUGINS:
-- JNI library is disabled
-- Configuring done (6.4s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/ruben/.conan2/p/b/rocks7fe22d9bdd212/b/build

rocksdb/6.29.5: Running CMake.build()
rocksdb/6.29.5: RUN: cmake --build "C:\Users\ruben\.conan2\p\b\rocks7fe22d9bdd212\b\build" --config Release
Versión de MSBuild 17.9.5+33de0b227 para .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/ruben/.conan2/p/b/rocks7fe22d9bdd212/b/src/CMakeLists.txt
  cache.cc
  cache_entry_roles.cc
  cache_key.cc
  cache_reservation_manager.cc
  clock_cache.cc
  lru_cache.cc
  sharded_cache.cc
  arena_wrapped_db_iter.cc
  blob_fetcher.cc
  blob_file_addition.cc
  blob_file_builder.cc
  blob_file_cache.cc
  blob_file_garbage.cc
  blob_file_meta.cc
  blob_file_reader.cc
  blob_garbage_meter.cc
  blob_log_format.cc
  blob_log_sequential_reader.cc
  blob_log_writer.cc
  prefetch_buffer_collection.cc
  builder.cc
  c.cc
  column_family.cc
  compaction.cc
  compaction_iterator.cc
  compaction_picker.cc
  compaction_job.cc
  compaction_picker_fifo.cc
  compaction_picker_level.cc
  compaction_picker_universal.cc
  sst_partitioner.cc
  convenience.cc
  db_filesnapshot.cc
  compacted_db_impl.cc
  db_impl.cc
  db_impl_write.cc
  db_impl_compaction_flush.cc
  db_impl_files.cc
  db_impl_open.cc
  db_impl_debug.cc
  db_impl_experimental.cc
  db_impl_readonly.cc
  db [...]

2024-03-14 13:09 UTC, thejohnfreeman commented
@RubenRBS yes, I think that's right.

2024-03-14 16:46 UTC, thejohnfreeman commented
Why can't I see the error?

2024-03-14 16:56 UTC, uilianries commented
@thejohnfreeman That's was an internal error in the CI, but will be restarted asap. Sorry the inconvenient.

2024-03-24 18:10 UTC, valgur requested changes

2024-03-24 18:10 UTC, valgur commented on recipes/rocksdb/all/patches/6.29.5-0002-exclude-thirdparty.patch
You can get away with a `save(self, os.path.join(self.source_folder, "thirdparty.inc", "")` in `_patch_sources()`, which is more stable across versions and easier to maintain.

Regarding `WITH_GFLAGS`, the recipe needs a `tc.cache_variables["CMAKE_POLICY_DEFAULT_CMP0067"] = "NEW"` for the current `tc.variables` to work correctly for CMake `option()`-s.

2024-03-24 19:36 UTC, thejohnfreeman commented on recipes/rocksdb/all/patches/6.29.5-0002-exclude-thirdparty.patch
That change won't fix the problem. The [branch](https://github.com/facebook/rocksdb/blob/da11a59034584ea2d0911268b8136e5249d6b692/CMakeLists.txt#L105-L182) that calls `find_package()` for each optional dependency will still be skipped because `MSVC` is truthy. My patch effectively removes [the other branch](https://github.com/facebook/rocksdb/blob/da11a59034584ea2d0911268b8136e5249d6b692/CMakeLists.txt#L100-L104) and sends all builds through the path that calls `find_package()`.

I remove [_this_ call](https://github.com/facebook/rocksdb/blob/da11a59034584ea2d0911268b8136e5249d6b692/CMakeLists.txt#L101) to `option(WITH_GFLAGS)` because it is superceded by a [later call](https://github.com/facebook/rocksdb/blob/da11a59034584ea2d0911268b8136e5249d6b692/CMakeLists.txt#L120).

2024-08-21 20:12 UTC, RazielXYZ commented
This patch is still needed, and also needed for newer versions as well. How should we proceed with getting this in and working in general?

2024-11-22 15:00 UTC, franramirez688 commented
Based on this and keeping its commits, I just opened a new one (https://github.com/conan-io/conan-center-index/pull/26009). I was not allowed to push the original branch.

The new one solves that problem for the rest of the versions. Also, I've removed a few ones to avoid having several patches.

2024-11-22 15:49 UTC, thejohnfreeman commented
Closing in favor of the new PR.

2024-11-22 15:49 UTC, closed without merging