binutils: add v2.42, drop vulnerable versions (< 2.40.50)
conan-io/conan-center-index pull request #23250
Opened 2024-03-25 12:37 UTC by valgur

Based on https://repology.org/project/binutils/information

Also switched from .gz to .xz archives.

2024-03-25 16:22 UTC, jwillikers approved these changes

2024-04-09 10:23 UTC, RubenRBS approved these changes
Thanks!

2024-04-09 10:23 UTC, RubenRBS requested changes
Sec

2024-04-09 10:40 UTC, RubenRBS approved these changes
Will need to bump its usages to 2.42 in CCI, thanks for taking the initiative :)

2024-04-09 10:41 UTC, uilianries approved these changes

2024-04-17 08:55 UTC, merged