jasper: add v4.2.2, drop vulnerable versions (< 4.1.2)
conan-io/conan-center-index pull request #23257
Opened 2024-03-25 13:14 UTC by valgur

Based on https://repology.org/project/jasper/information

2024-04-01 21:21 UTC, jwillikers approved these changes

2024-06-12 05:00 UTC, franramirez688 requested changes
Hi @valgur - Thanks for the PR!

I can see all these libs still using `jasper/4.0.0`:

```
gdal/pre_3.5.0/conanfile.py
261:            self.requires("jasper/4.0.0")

opencv/3.x/conanfile.py
89:            self.requires("jasper/4.0.0")

opencv/2.x/conanfile.py
373:            self.requires("jasper/4.0.0")

libraw/all/conanfile.py
61:            self.requires("jasper/4.0.0")
```

So, let's keep that version for now.

2024-06-12 05:06 UTC, franramirez688 reviewed
I just saw the version 4.2.4 released 😁

2024-06-12 05:06 UTC, franramirez688 commented on recipes/jasper/all/conandata.yml
> +    sha256: "5e397570b3110a8edef6d50127e20a2297939809cea25d29068823b442ecdd6d"
```suggestion
  "4.2.4":
    url: "https://github.com/jasper-software/jasper/releases/download/version-4.2.4/jasper-4.2.4.tar.gz"
    sha256: "6a597613d8d84c500b5b83bf0eec06cd3707c23d19957f70354ac2394c9914e7"
```

2024-06-12 05:06 UTC, franramirez688 commented on recipes/jasper/all/conandata.yml
> +  "4.2.2":
```suggestion
  "4.2.4":
```

2024-06-12 05:06 UTC, franramirez688 commented on recipes/jasper/config.yml
> +  "4.2.2":
```suggestion
  "4.2.4":
```

2024-06-12 05:22 UTC, franramirez688 approved these changes

2024-06-12 07:26 UTC, uilianries approved these changes
LGTM. Only versions 4.2.0 and 2.0.0 are used in CCI.

2024-06-12 14:09 UTC, merged