libassert: refactor recipe into v1 and v2 folders
conan-io/conan-center-index pull request #23286
Opened 2024-03-27 04:11 UTC by jeremy-rifkin

Specify library name and version:  **libassert/all**

I'm the library author. I'm refactoring the recipe to clean it up a bit by splitting it into v1 and v2 folders as discussed in #23117.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-27 04:13 UTC, jeremy-rifkin commented
I made two small changes while I was here in addition to the refactor:
- Bumped cpptrace from 0.5.0 to 0.5.1 in the v2 folder
- Updated description and topics metadata in the v2 recipe

2024-04-01 19:03 UTC, RubenRBS approved these changes
Looks great, thanks a lot! :)
The hooks have found one minor issue if you want to fix it, but nothing stopping the PR from getting merged

2024-04-01 19:40 UTC, jeremy-rifkin commented
Thanks for pointing that out, I’ll update tonight

2024-04-01 20:02 UTC, jwillikers approved these changes

2024-04-01 23:01 UTC, jwillikers approved these changes

2024-04-02 00:06 UTC, jwillikers requested changes

2024-04-02 00:06 UTC, jwillikers commented on recipes/libassert/v2/conanfile.py
> +        self.cpp_info.system_libs.append("m")
```suggestion
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs.append("m")
```

2024-04-02 00:08 UTC, jeremy-rifkin commented on recipes/libassert/v2/conanfile.py
> +        self.cpp_info.system_libs.append("m")
Thanks!

2024-04-02 12:22 UTC, jwillikers approved these changes

2024-04-03 15:49 UTC, merged