Add LibRaw 0.22.0-Devel202403 development snapshot with a ton of newl…
conan-io/conan-center-index pull request #23315
Opened 2024-03-30 13:00 UTC by irieger

Specify library name and version:  **libraw/0.22.0-devel202403**

Add LibRaw 0.22.0-Devel202403 development snapshot with a ton of newly supported image file formats. As there is only irregular releases every ~18 Months for LibRaw, development snapshot versions are offered to allow early access to features. As LibRaw is a library to read raw photo image formats and there is often new cameras introduced with slight changes in the image format, regular updates are helpful.

Is it viable to introduce this to cci? Already added it to my local artifactory so not too urgent for me but I'd assume this can also be helpful for other users.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-03-30 20:07 UTC, SpaceIm commented
I don't think it's a good idea to add a version coming from a fork. Nobody reviews your fork, and no offense, it could be malicious.

2024-03-30 20:34 UTC, irieger commented
> I don't think it's a good idea to add a version coming from a fork. Nobody reviews your fork, and no offense, it could be malicious.

The only reason was to trigger a release of a commit from the original repository without any additional changes. However I understand the problem. Sadly the snapshot is not officially tagged & released on the original repository. Would there be a consistent way on github to get a fixed archive URL with fixed checksum to a specific commit properly?

2024-04-01 12:00 UTC, uilianries commented
@irieger Why not just asking the upstream to create a new tag instead?

2024-04-01 12:01 UTC, uilianries requested changes
Blocking for discussion first about the fork.

2024-04-01 18:33 UTC, irieger commented
> @irieger Why not just asking the upstream to create a new tag instead?

On it, just requested the tagging there.

2024-04-01 18:39 UTC, irieger commented
It seems to be a very fluid thing with this "snapshot" so I'll close this MR and just keep my personal conanfile with the current tag or maybe switch it to use newer commits later.

(https://github.com/LibRaw/LibRaw/issues/637#issuecomment-2030324219)

2024-04-01 18:39 UTC, closed without merging