libpcap: add support for dbus, libnl and rdma
conan-io/conan-center-index pull request #23383
Opened 2024-04-05 14:12 UTC by valgur

Build log with all options enabled on Linux: https://gist.github.com/valgur/bb1ff3fd0ca5045a378ddd228c5588b3

2024-04-05 14:12 UTC, valgur commented on recipes/libpcap/all/conanfile.py
> +                "--with-libnl" if self.options.get_safe("enable_libnl") else "--without-libnl",
`--enable-xyz=yes/no` was not supported for most of these options.

2024-04-09 13:01 UTC, jwillikers approved these changes

2024-09-23 15:24 UTC, AbrilRBS submitted a review, later dismissed
Sorry that this took so long to get reviewed, looks good to me! :)

Thanks a lot for also including a full compilation log, truly appreciated!

2024-09-23 16:08 UTC, AbrilRBS submitted a review, later dismissed

2024-09-23 18:43 UTC, uilianries requested changes
Blocking for further review. Thank you for your update! libpcap is a powerful library!

2024-09-24 09:57 UTC, uilianries commented
@valgur I just tried to build locally, but using the official Docker image `conanio/gcc11-ubuntu16.04:2.7.0` and it fails to build:

[libpcap-1.10.4-linux-all-options.log](https://github.com/user-attachments/files/17112240/libpcap-1.10.4-linux-all-options.log)

The error occurred because libpcap was not capable to find those dependencies via pkg-config. The PkgConfigDeps is missing in the recipe. Furthermore, there is a new bug in Conan client that does not allow us renaming the .pc for `libnl::nl-genl` component, so libpcap is not capable to find the expected pc file as well. 

The commit [9271f24](https://github.com/conan-io/conan-center-index/pull/23383/commits/9271f24e12a79e88b8bbb867c837127b6117fa97) fixes the situation by add PkgConfigDeps and renaming the generated .pc file, so we do not patch pcap directly (much cheaper).

[libpcap-1.10.4-linux-pkgconfdeps.log](https://github.com/user-attachments/files/17112323/libpcap-1.10.4-linux-pkgconfdeps.log)

Please, consider using those docker images in the future, when providing the build lob. It did not fail for you, as you system is well configured, having all dependencies installed already.

2024-09-24 13:25 UTC, uilianries commented
Depends on https://github.com/conan-io/conan-center-index/pull/25380 first.

It will fix the correct pkg-config missing for libnl when active with libpcap.

2024-09-24 16:18 UTC, uilianries commented
Need extra PR: https://github.com/conan-io/conan-center-index/pull/25386

2024-09-24 16:19 UTC, valgur commented
LGTM. Thank you for the libnl fix, @uilianries!

2024-09-26 14:12 UTC, AbrilRBS approved these changes

2024-09-27 06:07 UTC, uilianries approved these changes
LGTM. Now libpcap is really consuming Conan dependencies for those new options:

[lipcap-1.10.4-linux-shared.log](https://github.com/user-attachments/files/17159718/lipcap-1.10.4-linux-shared.log)
[lipcap-1.10.4-linux-static.log](https://github.com/user-attachments/files/17159720/lipcap-1.10.4-linux-static.log)

2024-09-27 06:47 UTC, merged