cpp-dump: add recipe
conan-io/conan-center-index pull request #23401
Opened 2024-04-06 16:29 UTC by toge

Specify library name and version:  **cpp-dump/0.5.0**

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-04-06 16:56 UTC, valgur requested changes
LGTM, except for the one typo.

2024-04-06 16:56 UTC, valgur commented on recipes/cpp-dump/all/conanfile.py
> +    topics = ("debug", "dump" "header-only")
```suggestion
    topics = ("debug", "dump", "header-only")
```

2024-04-06 16:56 UTC, valgur commented on recipes/cpp-dump/all/test_package/test_package.cpp
> +#include "dump.hpp"
```suggestion
#include <dump.hpp>

#include <iostream>
#include <ostream>
#include <vector>
```
To verify that no standard library includes are missing in the library.

2024-04-08 09:52 UTC, RubenRBS approved these changes
Thanks!

2024-04-08 14:13 UTC, jwillikers approved these changes

2024-04-08 15:37 UTC, czoido approved these changes

2024-04-08 16:27 UTC, merged