[config] Re-order Mac M1 configuration
conan-io/conan-center-index pull request #23594
Opened 2024-04-17 10:30 UTC by uilianries

This change puts Mac M1 to be listed first when building packages in ConanCenterIndexCI. It does not guarantee the result as builds are execute in parallel, so a test package could ask for package that's not available yet.

Besides this change, Conan team will check for internal options/fix in C3I Jenkins code.

Related to #23558

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2024-04-17 10:31 UTC, RubenRBS approved these changes

2024-04-17 10:45 UTC, jcar87 requested changes
under review

2024-04-17 11:02 UTC, jcar87 commented
having taken the decision to simplify the test_packages, I'm not sure this is worth the effort.

The test_packages should have never reached the level of complexity that some have reached. Guaranteeing a build order "would" fix the issue of test_packages failing when they require two package IDs of the same reference (that are built as part of the same PR), but it has a downside that it serialises what can otherwise be parallel. 

Out of 1743 test_packages in the repository, only the following have a dual requirement against the tested reference:
```
libtool/all/test_package/conanfile.py
mbits-lngs/all/test_package/conanfile.py
mfast/all/test_package/conanfile.py
extra-cmake-modules/all/test_package/conanfile.py
grpc/all/test_package/conanfile.py
tree-gen/all/test_package/conanfile.py
flatcc/all/test_package/conanfile.py
btyacc/all/test_package/conanfile.py
protobuf-c/all/test_package/conanfile.py
qt/5.x.x/test_package/conanfile.py
qt/6.x.x/test_package/conanfile.py
wayland/all/test_package/conanfile.py
pkgconf/all/test_package/conanfile.py
cfgfile/all/test_package/conanfile.py
libtasn1/all/test_package/conanfile.py
ignition-cmake/all/test_package/conanfile.py
gsoap/all/test_package/conanfile.py
flex/all/test_package/conanfile.py
```
that's 18, in addition to `protobuf` and `capnproto` which have already been fixed. Guaranteeing a build order by serialising the creation of the binary packages is not worth it only to support these 18 cases vs the 1743 test packages we have currently. Personally I dont think most of the above are justified in having a complex test package, other than Qt.

I think we should refocus our efforts in ensuring that the very valid PRs against protobuf and the likes that are impacted by the issues can be swiftly merged, while in the background we continue our efforts to bring the test packages back in line with the original intention of the test packages.

If this PR doesn't really guarantee that the test_packages will succeed due to race conditions, I wouldn't bother too much.

2024-04-17 11:09 UTC, ericLemanissier commented
@jcar87 OTOH this change has no adverse effect, and allows easy progress on all the recipes you listed

2024-04-17 11:14 UTC, jcar87 commented
> @jcar87 OTOH this change has no adverse effect, and allows easy progress on all the recipes you listed

All the recipes I've listed will have their test package refactored accordingly, should this become a problem.

2024-04-17 12:34 UTC, jwillikers approved these changes

2024-05-23 19:47 UTC, Croydon approved these changes

2024-05-24 08:48 UTC, closed without merging

2024-05-24 08:49 UTC, uilianries commented
Closing as not planned.

2024-05-24 08:49 UTC, jcar87 commented
After further testing, this did not mitigate the issue.