libosmium: new recipe
conan-io/conan-center-index pull request #23720
Opened 2024-04-23 15:49 UTC by valgur

Adds libosmium: https://github.com/osmcode/libosmium

Fast and flexible C++ library for working with OpenStreetMap data.

[![Packaging status](https://repology.org/badge/tiny-repos/libosmium.svg)](https://repology.org/project/libosmium/versions)

2024-04-23 19:51 UTC, RubenRBS reviewed
Thanks! Can't approve because I ran out of time for a proper review for the day, but from a glance looks good :)

2024-04-23 19:51 UTC, RubenRBS commented on recipes/libosmium/all/test_package/test_package.cpp
> +        const osmium::io::File input_file{"missing_file.pbf"};
Nice idea with passing a missing file, very on topic with the simplification of the test packages :)

2024-04-29 21:56 UTC, RubenRBS reviewed
Thanks! I see a minor issue with zlib, other than that, I have checked that this properly links to gdal locally too, so I think it's good to go :)

2024-04-29 21:56 UTC, RubenRBS commented on recipes/libosmium/all/conanfile.py
> +            self.requires("zlib/1.3.1")
Version range missing here?

2024-04-30 10:39 UTC, valgur commented on recipes/libosmium/all/conanfile.py
> +            self.requires("zlib/1.3.1")
Thanks! Missed that one.

2024-04-30 10:55 UTC, RubenRBS reviewed
Extra question: is the gdalcpp vendorizen library something we should worry about?

2024-04-30 11:17 UTC, valgur commented
@RubenRBS Thanks for pointing it out. I did not notice that it's a vendored external library. I turned it into a separate package: #23829.

2024-07-17 17:36 UTC, nickblock commented
any chance we can get this merged?

2024-10-31 22:25 UTC, AbrilRBS approved these changes

2024-11-04 16:16 UTC, AbrilRBS commented on recipes/libosmium/all/conanfile.py
> +            self.requires("gdalcpp/1.3.0")
is this a typo @valgur? I don't see any `gdalcpp` recipe

2024-11-04 16:19 UTC, AbrilRBS requested changes
When trying to compile with all options set to false, I get this in the test_package:

```
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/abril/coding/conan-center-index/recipes/libosmium/all/test_package/build/apple-clang-16-armv8-gnu17-release

libosmium/2.20.0 (test package): Running CMake.build()
libosmium/2.20.0 (test package): RUN: cmake --build "/Users/abril/coding/conan-center-index/recipes/libosmium/all/test_package/build/apple-clang-16-armv8-gnu17-release" -- -j12
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
In file included from /Users/abril/coding/conan-center-index/recipes/libosmium/all/test_package/test_package.cpp:1:
In file included from /Users/abril/.conan2/p/b/libos33eefa4f13402/p/include/osmium/io/any_input.hpp:48:
In file included from /Users/abril/.conan2/p/b/libos33eefa4f13402/p/include/osmium/io/o5m_input.hpp:42:
/Users/abril/.conan2/p/b/libos33eefa4f13402/p/include/osmium/io/detail/o5m_input_format.hpp:56:10: fatal error: 'protozero/exception.hpp' file not found
   56 | #include <protozero/exception.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/test_package.dir/test_package.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
make: *** [all] Error 2

ERROR: libosmium/2.20.0 (test package): Error in build() method, line 22
	cmake.build()
	ConanException: Error 2 while executing
```

which seems to imply that either `pbf` is non-optional, or that its presence is not properly propagated

2024-11-04 16:20 UTC, AbrilRBS commented on recipes/libosmium/all/conanfile.py
> +            self.requires("gdalcpp/1.3.0")
I just didn't remember, this PR needs https://github.com/conan-io/conan-center-index/pull/23829 for this option to be true-able!

2024-11-04 17:56 UTC, valgur commented
Thank you for the extra checks. :slightly_smiling_face: 

I was using functionality from the optional `io` component in the library, which requires `protozero`.
I simplified `test_package` to only test against objects exposed by the main header as a fix.

2024-11-04 18:42 UTC, AbrilRBS commented
@valgur thanks for fixing the issues!

Right now no PRs are running by default, and we are triggering them by hand at first to get a handle of how the new CI behaves, regardless of how many prs the author has opened :)

I'll launch this one now, thanks!

2024-12-03 15:32 UTC, AbrilRBS requested changes
Sorry for the noise, the required library is not in CCI still

2025-03-09 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23720) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23720) before we can accept your contribution.<br/><hr/>**Martin Valgur** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=23720) it.</sub>

2025-03-17 09:32 UTC, closed without merging