refactor: open62541 test_package
conan-io/conan-center-index pull request #23745
Opened 2024-04-24 11:39 UTC by ErniGH

Simplify the test_package in according to our policies:

- Write the minimal test that tests the package (the compiler can find the correct includes, the static linker can resolve
symbols, the runtime linker can resolve symbols).
- Do not perform heavy logic in CI.
- Remove binary blob - these have not been allowed anywhere in the repository for a while now, it's time to drop them where they exist

2024-04-24 15:19 UTC, jcar87 commented on recipes/open62541/all/test_package/CMakeLists.txt
> -ua_generate_nodeset_and_datatypes(
This check is a little more special
What does it use to "generate"? I'm assuming it generates files from the `csv` and `bsd` files? in that case - we need to identify how they are generated - and attempt to replicate this in the `test_package` as well (like we did recently for protobuf)

2024-04-24 15:20 UTC, jcar87 commented on recipes/open62541/all/test_package/test_package.c
>      UA_Server *server = UA_Server_new();
is there a "delete" function that handles the pointer cleanup? If there is one, I would call it to free the pointer. I think OSs will free the resources upon process termination, but I would still do the minimal thing.

2024-04-29 21:53 UTC, RubenRBS requested changes

2024-04-29 21:53 UTC, RubenRBS commented on recipes/open62541/all/test_package/test_package.c
>      UA_Server *server = UA_Server_new();
```suggestion
    UA_Server *server = UA_Server_new();
    UA_Server_delete(server);
```

2024-04-29 22:08 UTC, RubenRBS commented
The LTO errors I think go outside the scope of the test package changes, I'd focus on the rest of the PRs and we can take a look at it at some point later :)

2025-04-30 11:40 UTC, AbrilRBS commented
Already done in a different PR - the loggin option fix remains to be applied but it can wait until something worthwhile of a new revision arrives

2025-04-30 11:40 UTC, closed without merging