gdalcpp: new recipe
conan-io/conan-center-index pull request #23829
Opened 2024-04-30 11:13 UTC by valgur

Adds gdalcpp: https://github.com/joto/gdalcpp

C++11 wrapper classes for GDAL/OGR

[![Packaging status](https://repology.org/badge/tiny-repos/gdalcpp.svg)](https://repology.org/project/gdalcpp/versions)

Adding it to unvendor the vendored header in
- #23720

2024-04-30 11:22 UTC, RubenRBS approved these changes

2024-04-30 14:26 UTC, RubenRBS commented
Regenerating missing binary

2024-12-03 15:34 UTC, AbrilRBS requested changes
Sorry again for the nopise

2025-03-09 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=23829) before we can accept your contribution.<br/><hr/>**Martin Valgur** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=23829) it.</sub>

2025-03-17 09:31 UTC, closed without merging