Added versions of cuda-api-wrappers: 0.6.9, 0.7.0-b3
conan-io/conan-center-index pull request #23857
Opened 2024-05-03 11:08 UTC by eyalroz

Specify library name and version:  **cuda-api-wrappers/0.6.9**

New version of the library is out; plus a new beta of an upcoming major version, that's based on the new version being released now. No new dependencies.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6). *<- I've only added two version entries*
- [] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated. *<- I'm not exactly sure what I'm supposed to try.*

2024-05-03 12:50 UTC, valgur requested changes
A small error in config.yml, LGTM otherwise.

2024-05-03 12:50 UTC, valgur commented on recipes/cuda-api-wrappers/config.yml
>      folder: all
```suggestion
  "0.7.0-b3":
    folder: all
  "0.7.0-b2":
    folder: all
```

2024-05-03 12:57 UTC, eyalroz commented on recipes/cuda-api-wrappers/config.yml
>      folder: all
Sorry, fixed this.

2024-08-26 04:48 UTC, valgur commented
Can be closed in favor of #25029, probably.

2024-08-26 05:11 UTC, closed without merging