laslib: refactor test package
conan-io/conan-center-index pull request #24140
Opened 2024-05-28 15:26 UTC by ErniGH

Simplify the test_package in according to our policies:

* Write the minimal test that tests the package (the compiler can find the correct includes, the static linker can resolve
symbols, the runtime linker can resolve symbols).
* Do not perform heavy logic in CI.
* Remove binary blob - these have not been allowed anywhere in the repository for a while now, it's time to drop them where they exist

2024-05-28 15:33 UTC, RubenRBS submitted a review, later dismissed

2024-05-29 12:49 UTC, RubenRBS requested changes

2024-05-29 12:49 UTC, RubenRBS commented on recipes/laslib/all/test_package/CMakeLists.txt
> +                ${CMAKE_BINARY_DIR}/test_package.cpp)
You can delete this whole line

2024-05-29 13:46 UTC, RubenRBS submitted a review, later dismissed

2024-06-18 10:47 UTC, RubenRBS approved these changes

2024-06-18 11:13 UTC, uilianries approved these changes
LGTM

2024-06-18 11:30 UTC, merged