opendis6: Update package name
conan-io/conan-center-index pull request #24487
Opened 2024-07-01 18:28 UTC by crhowell3

### Summary
Changes to recipe:  **libdis6/0.1.0**

#### Motivation

I am attempting to get this package published on vcpkg as well, but the current name is too easily confused with another package  that has similar capabilities. I have since updated the repository name and the CMake package name from 'opendis6' to 'libdis6'. As such, the package information that I previously published here will need to be updated for the sake of consistency; also, this change has broken the package information published here to conan, so in order to restore functionality, this change will need to get merged in.

#### Details

See above. This is really just a name change due to conflicts with another package.

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

2024-07-01 18:32 UTC, crhowell3 commented
@conan-io/barbarians 
Let me know as well if this type of change is possible. I'm just renaming my package to be compliant and consistent with changes I had to make to get this package published to `microsoft/vcpkg`.

2024-07-02 06:19 UTC, AbrilRBS commented
Hi @crhowell3 thanks a lot for taking the time to update the library in Conan Center, we appreciate it. I'll talk with the team on how to best deal with this, but as far as I can see, your approach is correct, will let you know more in a bit :)

2024-07-09 17:44 UTC, crhowell3 commented
Hello @AbrilRBS, thanks for the comment! Have there been any updates regarding this issue?

2024-07-10 21:45 UTC, AbrilRBS commented
Hi @crhowell3 sorry for not communicating better, I usually compile some CCI issues for the week and bring them all at once - my next planned meeting is tomorrow, so I'll let you know once we come up with a conclussion :)

2024-07-12 07:40 UTC, uilianries commented
@crhowell3 Hello! After talking with Conan team, including @AbrilRBS we opened 2 PRs to solve your current case. The CI does not allow and is not prepared to rename a project, it may break internally.

- https://github.com/conan-io/conan-center-index/pull/24601

This first PR adds attributes to mark the recipe as deprecated. As effect, anyone consuming the latest recipe revision, will receive a warning message about the deprecation and an advise about to use `libdis6` instead. The CI should not fail to download the tar file, because we use source backup.

- https://github.com/conan-io/conan-center-index/pull/24602

This new PR is based in yours, only a small fix in the test_package.cpp updating the included header name. It will close this PR as soon as it gets merged.

Regards!

2024-07-15 14:42 UTC, crhowell3 commented
@uilianries Thank you for handling this! Before getting these merged in, I may have to make a couple more changes. I received some feedback from the vcpkg team, and they are requesting a different package name altogether. I am working on getting that approved, and when I do, I'll update those PRs with the changes that I have to make. I appreciate you and your team handling this issue!

2024-07-16 11:32 UTC, AbrilRBS requested changes
Requesting changes so this does not get merged by accident - we'll wait for you to decide ona. final name, let us know once that's ready! :)

2025-01-13 05:09 UTC, AbrilRBS commented
Closing in favour of https://github.com/conan-io/conan-center-index/pull/26367 now that the new CI system is up and running, thanks a lot for your patience :)

2025-01-13 05:09 UTC, closed without merging