libyuv: add 1891
conan-io/conan-center-index pull request #24597
Opened 2024-07-11 17:26 UTC by Nerixyz

### Summary
Changes to recipe:  **libyuv/1891**

#### Motivation

Libyuv doesn't have a changelog. The main advancements are for ARM support.

#### Details

- Updates to 1891 (last commit that modified the version: https://chromium.googlesource.com/libyuv/libyuv/+/611806a1559b92c97961f51c78805d8d9d528c08)
- Updates dependencies to the latest version (only patch updates)

Full diff (from a GH mirror): https://github.com/lemenkov/libyuv/compare/fb6341d326846fbbe669ad5173e520f66b339621...611806a1559b92c97961f51c78805d8d9d528c08

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-08-02 09:52 UTC, perseoGI requested changes
Hi @Nerixyz, thanks for your contribution!
Reviewing the diff, the library is now forcing `POSITION_INDEPENDANT_CODE` 
https://github.com/lemenkov/libyuv/compare/fb6341d326846fbbe669ad5173e520f66b339621...4cd90347e78ff76755df2107009e900374aee9cd#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR78

In Conan we have the policy of not forcing that flag unless is strictly necessary. 
I think we could add a `replace_in_file` to remove that line.

2024-08-02 09:53 UTC, perseoGI commented on recipes/libyuv/all/conanfile.py
> +            self.requires("libjpeg-turbo/3.0.3")
Consider using version range for some of this libraries.
I have to discuss with the team

2024-08-05 12:27 UTC, perseoGI commented on recipes/libyuv/all/conanfile.py
> +            self.requires("libjpeg-turbo/[~3.0.3]")
```suggestion
            self.requires("libjpeg-turbo/[>=3.0.3 <4]")
```

2024-08-05 12:32 UTC, perseoGI commented on recipes/libyuv/all/conanfile.py
> +            self.requires("mozjpeg/[~4.1.5]")
```suggestion
            self.requires("mozjpeg/4.1.5")
```

We do not control the compatibility model of `mozjpeg` so having a fixed version is more secure for users.

2024-08-06 07:50 UTC, perseoGI approved these changes

2024-08-06 14:55 UTC, jcar87 approved these changes

2024-08-06 15:14 UTC, merged