opendis6: Deprecate in favor of libdis6
conan-io/conan-center-index pull request #24601
Opened 2024-07-12 07:22 UTC by uilianries

### Summary
Changes to recipe:  **opendis6/0.1.0**

#### Motivation

The author decided to rename the project to avoid name collision.

#### Details

The CI have limitations when renaming packages, so we will first mark this one as deprecated, then, open a second PR only adding a the new recipe.

/cc @crhowell3

Related to #24487

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-07-12 07:25 UTC, AbrilRBS submitted a review, later dismissed
Thanks! :)

2024-07-12 08:02 UTC, uilianries commented
Needed to update the download url to preserve the package url. Otherwise, it would fail, as the project points to another name now to the tag 0.1.0.

2024-07-15 09:19 UTC, jcar87 commented
> Needed to update the download url to preserve the package url. Otherwise, it would fail, as the project points to another name now to the tag 0.1.0.

have we confirmed the contents are the same?

2024-07-15 09:33 UTC, uilianries commented
> have we confirmed the contents are the same?


Yes. The package content is the same as before, the new tag points to the new library name, but repository is the "same", only renamed and continued with new changes. 

/cc @crhowell3

2024-07-15 13:50 UTC, AbrilRBS approved these changes

2024-07-16 11:31 UTC, AbrilRBS requested changes
Waiting for new name from upstream

2025-01-13 05:09 UTC, closed without merging