Nodeeditor: new package
conan-io/conan-center-index pull request #24751
Opened 2024-07-28 22:47 UTC by weatherhead99

### Summary
adds a recipe for the QtNodes / nodeeditor package: https://github.com/paceholder/nodeeditor
nodeeditor/3.0.11

#### Details
New package recipe

---
- [ X ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ X ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ X ] Tested locally with at least one configuration using a recent version of Conan

2024-11-21 16:16 UTC, uilianries reviewed
Hello @weatherhead99 ! Thank you for your PR!

I did few over your current PR, including:

- The requires Conan >=2.0.9
- Added implements attribute to manage fPIC option automatically
- Using Qt6 version range to include the dependency
- Using the exactly same version as tool requirement: host_version
- Added VirtualRunEnv to find shared libs when running Qt tools
- Add USE_QT6 to be able to use Qt 5 too, by replace_requirements
- Copied LICENSE.rst to the package folder
- Removed upstream CMake files installed (e.g QtNodesConfig.cmake) Use CMakeDeps generator instead
- Use the specific library name instead of the collect_libs
- Requires Cmake 3.15 for test package. That's the minimal version supported by Conan 2.x
- Reduced test package to only do a minimal validation and return exit code

2024-11-21 16:18 UTC, uilianries commented
As the Conan Center has no binaries for Qt6 on Linux and MacOS, I'll build locally and post the results later.

2024-11-22 09:03 UTC, uilianries requested changes
Wait for https://github.com/conan-io/conan-center-index/pull/26006 first.

The Qt6 recipe requires a bugfix that will break Mac users when consuming Node Editor. 

As soon as we have #26006 merged, we can re-base this PR to build it again, using the latest revision available, then, merge it.

2025-02-07 09:06 UTC, uilianries commented
I opened an issue to the upstream suggesting updating its CMakeListst.txt and use CMake automoc instead of qt_wrap_cpp macro: https://github.com/paceholder/nodeeditor/issues/460

2025-02-12 07:14 UTC, uilianries commented
The CI can not build on Linux due Qt6, but I built it locally (commit [3a4555f](https://github.com/conan-io/conan-center-index/pull/24751/commits/3a4555f2f3d8165e5e4da419290adc0be0684d50)) to validate the package:

Linux - GCC13 - x86_64 - Release
- Static: [nodeeditor-3.0.11-linux-static.log](https://github.com/user-attachments/files/18763658/nodeeditor-3.0.11-linux-static.log)
- Shared: [nodeeditor-3.0.11-linux-shared.log](https://github.com/user-attachments/files/18763656/nodeeditor-3.0.11-linux-shared.log)

Both packages are valid and no errors were produced.

2025-02-12 07:18 UTC, uilianries approved these changes
LGTM. 

This PR required extra tasks, like adding Metal framework to Qt::Gui module first. The node editor project uses CMake macros qt_wrap_cpp and qt_resource_cpp, which required an extra cmake file to configure a correct path for moc and rcc. 

Thank you for bringing Nodeeditor to Conan Center.

2025-03-13 11:51 UTC, AbrilRBS approved these changes
Thanks a lot for taking the time to implement this

2025-03-13 12:04 UTC, merged