[ffmpeg] Do not use self.dependencis in build
conan-io/conan-center-index pull request #24762
Opened 2024-07-30 09:57 UTC by uilianries

### Summary
Changes to recipe:  **ffmpeg/6.1.1**

#### Motivation

Both Conan 1.x and Conan 2.x are clear about not using `self.dependencies` in `build()`. It may cause unexpected behavior, as it's not documented and may change in the future.

- https://docs.conan.io/1/reference/conanfile/dependencies.html#dependencies-interface
- https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-interface

#### Details

I moved to collect the openssl libraries in generate, then, re-use the same variable later. I tested locally using both Conan 1.64.0 and 2.5.0:

```
cd recipes/ffmpeg/all/
conan install . --version=6.1.1
conan source . --version=6.1.1
conan build . --version=6.1.1
```

fixes #24689

/cc @Drllap

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-07-30 10:26 UTC, AbrilRBS approved these changes

2024-07-30 15:06 UTC, perseoGI approved these changes

2024-07-30 15:19 UTC, memsharded requested changes
I think that this usage is not solving anything, just creating errors for anyone trying to build the recipe locally with the local flow. The options are:

- Let is stay as-is, what real problem is it solving beyond a misalignment with the docs? It is likely that we can relax the docs to allow usage in the ``build()`` method nowadays, it is that way mostly for not breaking too much with Conan 1.
- Make ``generate()`` generate some file that the build of the package could read.

2024-07-30 15:23 UTC, uilianries commented
> Make generate() generate some file that the build of the package could read.

This is something we have done for test_package, as in Conan 1.x we can not preserve the state of a variable. I'll do that, because is easiest.

Relaxing in docs could work, but is a singular case, I guess.

2024-07-31 13:06 UTC, AbrilRBS approved these changes

2024-07-31 14:57 UTC, memsharded approved these changes

2024-07-31 22:03 UTC, merged