tree-gen: add version 1.0.8
conan-io/conan-center-index pull request #24954
Opened 2024-08-15 11:57 UTC by rturrado

### Summary
Changes to recipe:  **tree-gen/1.0.8**

#### Motivation
Just an update of dependencies.

#### Details
`config.yml` and `conandata.yml` point to the newly created `tree-gen/1.0.8`.
`conanfile.py` updates gtest conan package to 1.15.0 and fmt to 11.0.2.

---
- [X] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [X] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [X] Tested locally with at least one configuration using a recent version of Conan

2024-08-16 11:22 UTC, ErniGH requested changes

2024-08-16 11:30 UTC, rturrado commented on recipes/tree-gen/all/conandata.yml
> +    sha256: "85539188350b8a4aebba538f6a51ea7a841ebdfb6d04fa9cc3b96612820d25f5"
Many thanks for letting me know.

Indeed, I took the sha256 from the zip file instead of the tar.gz file.

2024-08-16 11:39 UTC, rturrado commented on recipes/tree-gen/all/conanfile.py
>          self.requires("range-v3/0.12.0", transitive_headers=True)
OK, I have a problem here of understanding what this all/conanfile.py is used for.

This recipe point to a GitHub project. In that GitHub project, versions 1.06 and 1.07 use fmt/10.2.1. Now I've created a version 1.08 that 1) uses fmt/11.0.2, and 2) fixes a compilation error in the source code due to that change to fmt/11.0.2.

Now, the recipe itself has an all/conanfile.py. I thought I should update fmt to 11.0.2 in that file. But that breaks the recipe for package versions 1.06 and 1.07.

So what should I do?
- Just remove versions 1.06 and 1.07?
- Or is there any way to tell all/conanfile.py to just use the fmt version indicated in the GitHub project (fmt/10.2.1 for tree-gen/1.06 and 1.07, and fmt/11.0.2 for tree-gen/1.08)?

Many thanks!

2024-08-19 06:14 UTC, uilianries commented on recipes/tree-gen/all/conanfile.py
>          self.requires("range-v3/0.12.0", transitive_headers=True)
@rturrado You can ase a condition in the recipe to check which version should be used:

```
if Version(self.version) < "1.0.8":
    self.requires("fmt/10.2.1", transitive_headers=True)
else:
	self.requires("fmt/11.0.2", transitive_headers=True)
```

2024-08-19 07:22 UTC, rturrado commented on recipes/tree-gen/all/conanfile.py
>          self.requires("range-v3/0.12.0", transitive_headers=True)
Many thanks @uilianries. I understand this change should only go into all/conanfile.py. Depending on config.yml, a given release of tree-gen will be downloaded, and that release should not conflict with the fmt release indicated here.

I still don't fully understand the following. When a user requests tree-gen Conan package, what recipe is used to build the package: the one in conan-center-io, or the one in tree-gen?

2024-08-19 07:28 UTC, uilianries commented on recipes/tree-gen/all/conanfile.py
>          self.requires("range-v3/0.12.0", transitive_headers=True)
> I still don't fully understand the following. When a user requests tree-gen Conan package, what recipe is used to build the package: the one in conan-center-io, or the one in tree-gen?

Do you mean Conan recipe, right? The one available in Conan Center. It's packaged altogether, so when you run `conan install`, you actually download a package from Conan Center (not this GH repository, but an Artifactory instance), where there is a copy of the recipe revision.

2024-08-19 08:14 UTC, ErniGH approved these changes
It looks pretty good! Thanks ❤️

2024-08-19 08:20 UTC, rturrado commented
> It looks pretty good! Thanks ❤️

Thanks to you!

2024-08-19 09:24 UTC, AbrilRBS approved these changes
Thanks!

2024-08-19 12:31 UTC, merged