Add expat version 2.6.3
conan-io/conan-center-index pull request #25142
Opened 2024-09-04 16:55 UTC by datalogics-robb

Three CVEs have been fixed in this version according to the ChangeLog https://github.com/libexpat/libexpat/blob/R_2_6_3/expat/Changes

### Summary
Changes to recipe:  **expat/2.6.3**

#### Motivation
CVE mitigation

#### Details
Add new version

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

2024-09-04 17:29 UTC, valgur requested changes
No notable changes on the build system end: https://github.com/libexpat/libexpat/compare/R_2_6_2...R_2_6_3

Not directly related to the version bump, but the recipe should include
```cmake
# https://github.com/conan-io/conan/issues/12012
tc.variables["CMAKE_TRY_COMPILE_CONFIGURATION"] = str(self.settings.build_type)
```
due to `try_compile()` calls in the CMake project: https://github.com/libexpat/libexpat/blob/R_2_6_3/expat/ConfigureChecks.cmake#L62

2024-09-04 17:52 UTC, valgur approved these changes
Thank you!

2024-09-04 17:56 UTC, datalogics-robb commented
> Thank you!

no - thank YOU!  I wasn't aware of this issue so this is a big help.

2024-09-05 09:34 UTC, valgur commented
@datalogics-robb Actually, on second thought, that CMake variable is only relevant when `try_compile()` is being used with a dependency from Conan. That is not the case in Expat, so it can be dropped. Sorry about the hassle.

2024-09-06 10:13 UTC, ErniGH commented
Hi @datalogics-robb 👋 , I noticed that you have reverted the changes of 
```
# https://github.com/conan-io/conan/issues/12012
tc.variables["CMAKE_TRY_COMPILE_CONFIGURATION"] = str(self.settings.build_type)
```

I'm not sure if it was a mistake or if those changes are no longer relevant to the new version.

2024-09-06 14:41 UTC, datalogics-robb commented
> Hi @datalogics-robb 👋 , I noticed that you have reverted the changes of
> 
> ```
> # https://github.com/conan-io/conan/issues/12012
> tc.variables["CMAKE_TRY_COMPILE_CONFIGURATION"] = str(self.settings.build_type)
> ```
> 
> I'm not sure if it was a mistake or if those changes are no longer relevant to the new version.

The discussion of this issue is on the PR, it was decided to remove this change.

2024-09-09 07:31 UTC, ErniGH approved these changes
Thank you for your effort 🚀

2024-09-09 07:51 UTC, merged