GDAL: Adds option to rename shapelib's exported symbols
conan-io/conan-center-index pull request #25176
Opened 2024-09-07 19:22 UTC by JustCallMeRay

### Summary
Changes to recipe:  **GDAL/>3.5** to add option to not rename shapelib symbols.

#### Motivation

fixes issue #25175 

#### Details

Adds option `rename_shapelib_symbols` which is forwarded to the cmake option `RENAME_INTERNAL_SHAPELIB_SYMBOLS`

---
- [X] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [X] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

2024-09-07 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=25176) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=25176) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=25176) it.</sub>

2024-09-08 15:53 UTC, valgur commented on recipes/gdal/post_3.5.0/conanfile.py
> +            raise ConanInvalidConfiguration("Must compile with shapelib to have shapelib symbols exported")
Should do
```python
if not self.options.with_shapelib:
    del self.options.rename_shapelib_symbols
```
in `configure()` instead.

2024-09-08 16:00 UTC, valgur requested changes
Looks like a reasonable addition to me.

The usual way of handling vendored dependencies on CCI would be to replace them with an external Conan dependency entirely, but for context to others - the use of the external Shapelib is not recommended by GDAL and also caused compilation errors the last time I tested it. https://github.com/OSGeo/gdal/issues/5711

2024-09-08 17:53 UTC, valgur commented on recipes/gdal/post_3.5.0/conanfile.py
> +
```suggestion

```

2024-09-08 17:53 UTC, valgur commented on recipes/gdal/post_3.5.0/conanfile.py
> +
Leftover whitespace.

2024-09-08 17:54 UTC, valgur approved these changes

2024-09-11 12:51 UTC, JustCallMeRay commented
I don't know what to do here,
Tests fail with MISSING_DEPENDENCIES because of Arrow.
Everything is in the log but for ease of reading: 
`arrow/14.0.2: Compatible package ID 857a79fb7ce8d6c1950524510e775f2f0b738fe6 equal to the default package ID: Skipping it.`  
Followed by:
`arrow/14.0.2#b2e8a6fe3ef6b6a22ffdac9c145ba9a6:857a79fb7ce8d6c1950524510e775f2f0b738fe6 - Missing`
On macos clang

2025-04-04 20:06 UTC, JustCallMeRay commented
Closed as there is a much easier way to do this, see #25175

2025-04-04 20:06 UTC, closed without merging