onetbb: disable tbbind for Apple non-macOS
conan-io/conan-center-index pull request #25361
Opened 2024-09-23 10:21 UTC by kambala-decapitator

hwloc can't be built for these platforms

### Summary
Changes to recipe:  **onetbb/***

#### Motivation

to use the latest version of tbb for iOS, one must explicitly disable tbbind option which is inconvenient

#### Details

hwloc can only be built for macOS among Apple platforms

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-09-23 10:45 UTC, valgur commented on recipes/onetbb/all/conanfile.py
> +        return self.settings.os == "Macos" and Version(self.version) >= "2021.11.0"
```suggestion
        if is_apple_os(self):
            return return self.settings.os == "Macos" and Version(self.version) >= "2021.11.0"
        return True
```
Seems easier to read to me. Just a suggestion.

2024-09-23 11:01 UTC, AbrilRBS submitted a review, later dismissed
Great catch, thanks a lot for taking the time to fix the issue :)

2024-09-23 11:03 UTC, valgur approved these changes
Thanks!

2024-09-23 11:05 UTC, valgur requested changes
Typo

2024-09-23 11:05 UTC, valgur commented on recipes/onetbb/all/conanfile.py
> +        return True
```suggestion
        if is_apple_os(self):
            return self.settings.os == "Macos" and Version(self.version) >= "2021.11.0"
        return True
```

2024-09-23 11:36 UTC, valgur approved these changes

2024-09-24 09:58 UTC, AbrilRBS approved these changes
Thanks!

2024-09-24 10:34 UTC, merged