qxlsx: add v1.4.9, test_package, transitive_headers=True, drop oldest version
conan-io/conan-center-index pull request #25406
Opened 2024-09-25 10:12 UTC by valgur

### Summary
Changes to recipe:  **qxlsx/[*]**

#### Motivation

#### Details
- Closes #24096

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-25 16:29 UTC, AbrilRBS submitted a review, later dismissed

2024-11-25 16:31 UTC, uilianries requested changes
Blocking as it does not have build logs. 

I'll build locally and push them first.

2024-11-25 19:47 UTC, uilianries commented
Full Build Logs (built locally):

#### Linux

- [qxlsx-1.4.4-linux-shared.log](https://github.com/user-attachments/files/17908172/qxlsx-1.4.4-linux-shared.log)
- [qxlsx-1.4.4-linux-static.log](https://github.com/user-attachments/files/17908160/qxlsx-1.4.4-linux-static.log)
- [qxlsx-1.4.5-linux-shared.log](https://github.com/user-attachments/files/17908162/qxlsx-1.4.5-linux-shared.log)
- [qxlsx-1.4.5-linux-static.log](https://github.com/user-attachments/files/17908163/qxlsx-1.4.5-linux-static.log)
- [qxlsx-1.4.9-linux-shared.log](https://github.com/user-attachments/files/17908164/qxlsx-1.4.9-linux-shared.log)
- [qxlsx-1.4.9-linux-static.log](https://github.com/user-attachments/files/17908165/qxlsx-1.4.9-linux-static.log)

#### Windows 

TODO 


#### Macos

TODO

2024-11-26 08:31 UTC, uilianries approved these changes
LGTM. Build logs available in comments.

2024-11-26 08:34 UTC, AbrilRBS approved these changes

2024-11-26 08:34 UTC, merged