Add pvrtc-compressor 20150108
conan-io/conan-center-index pull request #2560
Opened 2020-08-16 23:15 UTC by intelligide

Specify library name and version:  **pvrtc-compressor/cci.20150108**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-08-18 13:44 UTC, uilianries commented on recipes/pvrtc-compressor/all/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1)
```suggestion
cmake_minimum_required(VERSION 3.4)
```

CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS requires 3.4

2020-08-19 21:11 UTC, uilianries commented
Bitbucket is under maintenance right now: https://bitbucket.status.atlassian.com/incidents/hmgnc3x4lfwh

I'll review this tomorrow.

2020-09-11 18:18 UTC, madebr requested changes
None of the bitbucket links are working.
What's going on over there?

2020-09-11 18:24 UTC, intelligide commented
Bitbucket removed Mercurial Support.

2020-09-11 20:32 UTC, intelligide commented
I was able to retrieve the sources from my conan cache. I made a backup of it: https://github.com/FrozenStormInteractive/pvrtc-compressor

2020-09-12 09:13 UTC, madebr commented
> 
> 
> I was able to retrieve the sources from my conan cache. I made a backup of it: https://github.com/FrozenStormInteractive/pvrtc-compressor

That's nice for preservation purposes.

@jthlim
Is there a new way to fetch pvrtc-compressor not bitbucket has retired mercurial support?

2020-12-16 20:58 UTC, jgsogo commented
Wow, the repo is gone (bitbucket remove mercurial repos time ago... ) We need an alternate URL to get the sources. cc/ @danimtb

2020-12-16 21:09 UTC, Croydon commented
Hi @jthlim! If I'm not mistaken you are the author of pvrtc-compressor. The previous pvrtc-compressor mercurial repository got deleted on BitBucket. Could you please consider creating a new git repository on GitHub/GitLab/Bitbucket or so? 

It would be good to have a new official origin for the source code

2021-09-26 10:29 UTC, SSE4 commented
sources are still not found... is there a mirror?

2021-09-27 08:50 UTC, jgsogo commented
We can add sources here (https://github.com/conan-io/cci-sources-backup) and retrieve them from our repo...

2021-09-27 08:55 UTC, SSE4 commented
> We can add sources here (https://github.com/conan-io/cci-sources-backup) and retrieve them from our repo...

yes, but there to retrieve them now? the URL doesn't work:
https://bitbucket.org/jthlim/pvrtccompressor/get/cf7177748ee0dcdccfe89716dc11a47d2dc81af5.tar.gz
```
The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.
```

2021-09-27 09:31 UTC, jgsogo commented
@intelligide did a backup some time ago (https://github.com/FrozenStormInteractive/pvrtc-compressor), and it can also be found in different places like https://github.com/godotengine/godot/tree/master/thirdparty/pvrtccompressor or https://github.com/codywatts/PVRTCCompressor.

2023-05-18 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=2560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=2560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=2560) it.</sub>

2024-02-09 12:46 UTC, jcar87 commented
Closing this PR as the author of the library never reached out, we don't have a canonical location for the source code. Assuming that the library is also unmaintained as well. Please open an issue  to track this if needed!

2024-02-09 12:46 UTC, closed without merging