Add `.conanrunner` & `.conanrc` to gitignored ignored, alongside `conan_home`
conan-io/conan-center-index pull request #25710
Opened 2024-10-24 13:30 UTC by AbrilRBS

`.conanrunner` is a folder created by the runner feature when using it to create packages from docker, and it's helpful if it's already ignored by git

Alongside it `conan_home` is my (maybe in the docs too?) convention for the value of `CONAN_HOME` env var or the `conan_home` variable in `.conanrc` (Files which for now will also be ignored), which is an useful feature when trying to isolate runner builds, for which creating a separate conan_home for the build is usually the best approach

2024-10-24 13:49 UTC, uilianries approved these changes

2024-10-24 16:56 UTC, jcar87 commented on .gitignore
> +conan_home/
Don't think this is a convention - mine is different altogether. If this isn't recommended or mentioned in the Conan client docs, I would remove this from .gitignore.

Remember you can always configure a global gitignore in your profile to achieve the same effect

2024-10-24 16:56 UTC, jcar87 requested changes
see comment

2024-10-24 17:07 UTC, AbrilRBS commented on .gitignore
> +conan_home/
```suggestion
```

2024-10-25 08:04 UTC, jcar87 approved these changes

2024-10-25 09:21 UTC, uilianries approved these changes

2024-10-25 09:41 UTC, merged