libheif: add version 1.19.0
conan-io/conan-center-index pull request #25783
Opened 2024-11-01 00:57 UTC by toge

### Summary
Changes to recipe:  **libheif/1.19.0**

#### Motivation
There are lots of improvements in 1.19.0.

#### Details
https://github.com/strukturag/libheif/compare/v1.18.2...v1.19.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-01 01:01 UTC, toge commented
log with `with_openh264=True`

<details>
> LANG=C conan create  . --build=missing --version=1.19.0 -o "libheif/*:with_openh264=True"

======== Exporting recipe to the cache ========
libheif/1.19.0: Exporting package recipe: src/conan-center-index/recipes/libheif/all/conanfile.py
libheif/1.19.0: exports: File 'conandata.yml' found. Exporting it...
libheif/1.19.0: Calling export_sources()
libheif/1.19.0: Copied 1 '.yml' file: conandata.yml
libheif/1.19.0: Copied 1 '.py' file: conanfile.py
libheif/1.19.0: Exported to cache folder: .conan2/p/libhede5538ade7435/e
libheif/1.19.0: Exported: libheif/1.19.0#3184ac9eaa4acda1077c0e802b961d0b (2024-11-01 00:58:02 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=23
compiler.libcxx=libstdc++11
compiler.version=14
os=Linux
[options]
libheif/*:with_openh264=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=23
compiler.libcxx=libstdc++11
compiler.version=14
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    libde265/1.0.12#6e7cec8c7e3b1c9bfb6761dfc4d1dbb8 - Cache
    libheif/1.19.0#3184ac9eaa4acda1077c0e802b961d0b - Cache
    openh264/2.4.1#f65570895428516317d5236ac3bc5360 - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb - Cache
    meson/1.2.2#21b73818ba96d9eea465b310b5bbc993 - Cache
    meson/1.4.1#43b753adf9a089cadfa17c8034f5c897 - Cache
    nasm/2.16.01#d0aebbd20ccbb6ad9c9c753ab708098c - Cache
    ninja/1.12.0#d3c243aba81b618ec33158a2cfbe55e5 - Cache
    pkgconf/2.2.0#6462942a22803086372db44689ba825f - Cache
Resolved version ranges
    cmake/[>=3.16 <4]: cmake/3.30.1
    ninja/[>=1.10.2 <2]: ninja/1.12.0

======== Computing necessary packages ========
libheif/1.19.0: Main binary package 'cfa16f143bde9344a6bfe09fae78a434b4e076c5' missing
libheif/1.19.0: Checking 9 compatible configurations
libheif/1.19.0: Compatible configurations not found in cache, checking servers
libheif/1.19.0: '2d984f287ef6829e04d39e1e744eea3165e7aa4a': compiler.cppstd=11
libheif/1.19.0: '0562810339ea089024c90a27a1c4a456e44a598f': compiler.cppstd=gnu11
libheif/1.19.0: 'f8fa658dfb7ac56921284932ee446068a56e2472': compiler.cppstd=14
libheif/1.19.0: '127eb1b0ae98a3e9b4836606f0772716800e46ed': compiler.cppstd=gnu14
libheif/1.19.0: 'b7f51b75acaef1d3034e8eb41e2be1855a990ac4': compiler.cppstd=17
libheif/1.19.0: '58000bde55fcd768410d9190fb6daa928f0486ec': compiler.cppstd=gnu17
libheif/1.19.0: '6e4ae7bc1b9978168924c6ca0602b1fd1bb9057e': compiler.cppstd=20
libheif/1.19.0: 'e6d370ff736d08012cc79c49ca6d2c289611595d': compiler.cppstd=gnu20
libheif/1.19.0: '4e450545806907ac8b1af002e492746d48f2fed9': compiler.cppstd=gnu23
Requirements
    libde265/1.0.12#6e7cec8c7e3b1c9bfb6761dfc4d1dbb8:4ecf4462f7308dd366b266629b606effdefad230#007a1ab13e8a734ea6332f98b49a21fe - Cache
    libheif/1.19.0#3184ac9eaa4acda1077c0e802b961d0b:cfa16f143bde9344a6bfe09fae78a434b4e076c5 - Build
    openh264/2.4.1#f65570895428516317d5236ac3bc5360:60d979b0a7d7272ce4719856e16fef14b991f4c9#e3e13e26b9088712e08d75d0ecd2bb3e - Cache
Build requirements
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb:63fead0844576fc02943e16909f08fcdddd6f44b#041a38980949bccd356d9142f4e0a2bf - Cache
Skipped binaries
    meson/1.2.2, meson/1.4.1, nasm/2.16.01, ninja/1.12.0, pkgconf/2.2.0

======== Installing packages ========
cmake/3.30.1: Already installed! (1 of 4)
cmake/3.30.1: Appending PATH environment variable: .conan2/p/cmakefaa1321642d5b/p/bin
libde265/1.0.12: Already installed! (2 of 4)
openh264/2.4.1: Already installed! (3 of 4)
libheif/1.19.0: Calling source() in .conan2/p/libhede5538ade7435/s/src
libheif/1.19.0: Unzipping libheif-1.19.0.tar.gz to .

-------- Installing package libheif/1.19.0 (4 of 4) --------
libheif/1.19.0: Building from source
libheif/1.19.0: Package libheif/1.19.0:cfa16f143bde9344a6bfe09fae78a434b4e076c5
libheif/1.19.0: Copying sources to build folder
libheif/1.19.0: Building your package in .conan2/p/b/libhe0faa1019e0e63/b
libheif/1.19.0: Calling generate()
libheif/1.19.0: Generators folder: .conan2/p/b/libhe0faa1019e0e63/b/build/Release/generators
libheif/1.19.0: CMakeToolchain generated: conan_toolchain.cmake
libheif/1.19.0: CMakeToolchain generated: .conan2/p/b/libhe0faa1019e0e63/b/build/Release/generators/CMakePresets.json
libheif/1.19.0: CMakeToolchain generated: .conan2/p/b/libhe0faa1019e0e63/b/src/CMakeUserPresets.json
libheif/1.19.0: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(LIBDE265)
    find_package(OpenH264)
    target_link_libraries(... de265 openh264::openh264)
libheif/1.19.0: Generating aggregated env files
libheif/1.19.0: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
libheif/1.19.0: Calling build()
libheif/1.19.0: Running CMake.configure()
libheif/1.19.0: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX=".conan2/p/b/libhe0faa1019e0e63/p" -DCMAKE_COMPILE_WARNING_AS_ERROR="OFF" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" ".conan2/p/b/libhe0faa1019e0e63/b/src"
-- Using Conan toolchain: .conan2/p/b/libhe0faa1019e0e63/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Defining architecture flag: -m64
-- Conan toolchain: C++ Standard 23 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Warning: Standard CMAKE_CXX_STANDARD value defined in conan_toolchain.cmake to 23 has been modified to 20 by .conan2/p/b/libhe0faa1019e0e63/b/src/CMakeLists.txt
-- Performing Test has_potentially_evaluated_expression
-- Performing Test has_potentially_evaluated_expression - Failed
-- Conan: Target declared 'de265'
-- Conan: Target declared 'openh264::openh264'

=== Summary of compiled codecs ===
libde265 HEVC decoder           : + built-in
FFMPEG HEVC decoder (HW acc)    : - disabled
x265 HEVC encoder               : - disabled
Kvazaar HEVC encoder            : - disabled
AOM AV1 decoder                 : - disabled
AOM AV1 encoder                 : - disabled
Dav1d AV1 decoder               : - disabled
SVT AV1 encoder                 : - disabled
Rav1e AV1 encoder               : - disabled
JPEG decoder                    : - disabled
JPEG encoder                    : - disabled
OpenH264 decoder                : + built-in
OpenJPEG J2K decoder            : - disabled
OpenJPEG J2K encoder            : - disabled
OpenJPH HT-J2K encoder          : - disabled
uvg266 VVC enc. (experimental)  : - disabled
vvenc VVC enc. (experimental)   : - disabled
vvdec VVC dec. (experimental)   : - disabled

=== Supported formats ===
format        decoding   encoding
AVC             YES        NO 
AVIF            NO         NO 
HEIC            YES        NO 
JPEG            NO         NO 
JPEG2000        NO         NO 
JPEG2000-HT     NO         NO 
Uncompressed    NO         NO 
VVC             NO         NO 

libsharpyuv: disabled
-- Looking for _LIBCPP_VERSION
-- Looking for _LIBCPP_VERSION - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.6.0")
-- Found JPEG: /usr/lib64/libjpeg.so (found version "62")
-- Performing Test HAVE_JPEG_WRITE_ICC_PROFILE
-- Performing Test HAVE_JPEG_WRITE_ICC_PROFILE - Success
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.40")

=== Active input format [...]

2024-11-04 15:39 UTC, AbrilRBS requested changes
@toge the new version is asking for C++ 20 as far as I can tell, so we should update the check accordingly, thanks! :)

2024-11-11 17:56 UTC, AbrilRBS commented on recipes/libheif/all/conanfile.py
> +            "20": {
From now on this should only be used for minimum compiler versions that do not compile with the given cppstd even if they support said flag

2024-11-11 17:56 UTC, AbrilRBS submitted a review, later dismissed

2024-11-11 18:09 UTC, jcar87 approved these changes

2024-11-11 18:26 UTC, AbrilRBS approved these changes

2024-11-11 19:24 UTC, merged