Update conanfile.py
conan-io/conan-center-index pull request #25789
Opened 2024-11-01 21:42 UTC by pya102

Added "s390x" to the  _b2_address_model function to return "64".

### Summary
Changes to recipe:  **lib/all**

#### Motivation
Boost library fails to build on IBM Z and IBM LinuxONE processors due to recipe defaulting to 32-bits architecture due to the following function: 
```
def _b2_address_model(self):
        if self.settings.arch in ("x86_64", "ppc64", "ppc64le", "mips64", "armv8", "armv8.3", "sparcv9"):
             return "64"

        return "32"
```

#### Details
Added "s390x" to the architecture tuple returning "64": 
```
def _b2_address_model(self):
       if self.settings.arch in ("x86_64", "ppc64", "ppc64le", "mips64", "armv8", "armv8.3", "sparcv9", "s390x"):
            return "64"

        return "32"
```

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-01 21:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=25789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=25789) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=25789) it.</sub>

2024-11-05 10:07 UTC, jcar87 requested changes
PR is fine, just double checking something on CI :)

2024-11-06 15:39 UTC, AbrilRBS approved these changes

2024-11-06 15:39 UTC, merged

2024-11-07 04:42 UTC, pya102 commented
Thank you so much for your response. 

If interested, IBM provides access to Virtual Machines using s390x architecture to Open Source projects like this one. You can request access using this link: https://community.ibm.com/zsystems/form/l1cc-oss-vm-request/

I look forward to continuing to contribute to the community.