libpopcnt: add recipe
conan-io/conan-center-index pull request #25857
Opened 2024-11-06 11:44 UTC by toge

### Summary
Changes to recipe:  **libpopcnt/3.1**

#### Motivation
Fast C/C++ bit population count library.

#### Details
https://github.com/kimwalisch/libpopcnt

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-06 12:14 UTC, jcar87 requested changes

2024-11-07 12:16 UTC, toge commented on recipes/libpopcnt/all/conanfile.py
> +
Fixed.

2024-11-07 16:58 UTC, AbrilRBS commented on recipes/libpopcnt/all/test_package/test_package.c
> +  size_t size = 70000;
```suggestion
  size_t size = 42;
```

2024-11-07 17:06 UTC, AbrilRBS submitted a review, later dismissed
Thanks!

2024-11-07 17:09 UTC, AbrilRBS approved these changes
Thanks!

2024-11-11 16:22 UTC, jcar87 approved these changes

2024-11-11 16:23 UTC, AbrilRBS approved these changes

2024-11-11 16:24 UTC, merged