sdl3: WIP implementation
conan-io/conan-center-index pull request #25873
Opened 2024-11-07 17:00 UTC by AbrilRBS

Got this to compile and run the tests and examples, but plenty of work remains to be done

2025-01-12 18:43 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "SDL3::SDL3")
In addition, create a `SDL3::SDL3-static` when creating a static library and
`SDL3::SDL3-shared` when building a shared library.

Also create `SDL3::Headers` for the headers.

2025-01-29 10:17 UTC, elvisdukaj reviewed
When commenting the "hidapi" on Windows I was able to build this package for Windows and msvc shared/static and debug/release

2025-01-29 10:17 UTC, elvisdukaj commented on recipes/sdl/config.yml
> +    folder: 3.x
```suggestion
  "3.2.0":
    folder: 3.x
```

2025-01-29 10:17 UTC, elvisdukaj commented on recipes/sdl/3.x/conanfile.py
> +                    # CMakeLists.txt#L343
```suggestion
                    # CMakeLists.txt#L378
```

On the 3.2.0 this is line 378

2025-01-29 11:00 UTC, skhaz commented
Excuse my ignorance, but how can I help with testing? I’m very interested in having SDL3 in the emsdk.

2025-01-29 11:50 UTC, elvisdukaj commented
> Excuse my ignorance, but how can I help with testing? I’m very interested in having SDL3 in the emsdk.

@skhaz, if you have the project cloned and this PR than you need to run the following command. If you don't you need the [GitHub CLI](https://cli.github.com) tools, autentificate and than `gh pr --checkout 25873` or something similar/

```
cd recipes/sdl
conan create 3.x --version <version> --profile <profile_emsdk> 
```

This PR is actually using a pre-release version, see the config.yml file. I suggested to move on the 3.2.0 instead.

2025-01-29 11:55 UTC, elvisdukaj commented
I am trying to build this recipe for macOS. Let's see how far I can go.

@AbrilRBS should I fork from you and proposing the changes there, suggest changes here, or what is your preferred way? Let me know :)

2025-02-10 11:59 UTC, madebr requested changes

2025-02-10 11:59 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +            "alsa": [None, True, False],
This is missing options for x11, Wayland and probably others.
(Check the summary at the end of configuration)

2025-02-10 11:59 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +            tc.cache_variables["SDL_PULSEAUDIO"] = True
Is there a reason you're not assigning `bool(self.options.get("pulseaudio"))` h

2025-02-10 11:59 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +            self.cpp_info.set_property("cmake_target_aliases", ["SDL3::SDL3-static"])
This logic is inverted.

2025-02-10 11:59 UTC, madebr commented on recipes/sdl/3.x/conandata.yml
> +  "3.2.2":
We're at 3.2.4 already

2025-02-10 12:02 UTC, AbrilRBS commented on recipes/sdl/3.x/conandata.yml
> +  "3.2.2":
Thanks for the heads-up!

2025-02-10 12:03 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +            "alsa": [None, True, False],
Yes, we have yet to implement the rest of the options, we're testing the best approach with these 2 for now :)

2025-02-10 12:03 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +            tc.cache_variables["SDL_PULSEAUDIO"] = True
We still need the conditional for the variable below, as accessing a non existing dependencie errors out, so at that point I think this way is cleaner for both :)

2025-02-10 17:30 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +            del self.options.fPIC
You can remove alsa and pulseaudio here on Android and Apple.

2025-02-10 17:31 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +        if self.options.get("pulseaudio"):
I think you need to use `get_safe` here.

2025-02-14 12:05 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
I'd also throw a ConanException here if the os is Android because without Java classes, the compiled C library is useless.

SDL's CMake script compiles the java classes, so Android can be supported if you provide a jdk and a Android SDK (it needs android.jar).

2025-02-14 17:25 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
No problem. Documenting this, and raising an exception is always useful for the next person.

2025-02-20 13:41 UTC, valgur commented on recipes/sdl/3.x/conanfile.py
> +            tc.cache_variables["SDL_UNIX_CONSOLE_BUILD=ON"] = True
```suggestion
            tc.cache_variables["SDL_UNIX_CONSOLE_BUILD"] = True
```

2025-02-20 13:43 UTC, valgur commented on recipes/sdl/3.x/conanfile.py
> +            "fPIC": False,
```suggestion
            "fPIC": True,
```
Probably wasn't intentional?

2025-02-20 15:39 UTC, valgur commented
@AbrilRBS @perseoGI
I opened a PR for complete X11 support: https://github.com/AbrilRBS/conan-center-index/pull/13

2025-02-20 18:15 UTC, valgur commented on recipes/sdl/3.x/conanfile.py
> +                self.cpp_info.requires.append("xorg::xscrnsaver")
Good point.
It sounds like these dynamically-loaded dependencies should be using `self.requires(..., libs=False, run=True)` or something similar to exclude them from `self.cpp_info.requires`. Which does not work as expected, though, afaik, based on some prior PRs.

2025-02-20 18:21 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +                self.cpp_info.requires.append("xorg::xscrnsaver")
Indeed! I did not know about the conan 2 `libs=xxx run=yyy` feature.

2025-02-20 18:23 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +                self.cpp_info.requires.append("xorg::xscrnsaver")
Also, building a shared SDL3 library needs this. When linking to a shared SDL3 library, you don't have to link to any dependency.

2025-02-27 13:23 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
We have been able to compile Android locally and run the test_package in an emulator, so my current idea is to let users build for Android if they have already set things up properly, but don't expect the recipe to fully provide it. Does that sound good to you?

2025-02-27 13:50 UTC, valgur commented on recipes/sdl/3.x/conanfile.py
> +            "SDL3::Headers"
Could be done with a component that sets `includedirs` and no `libs` or `requires`, no?

2025-02-27 14:13 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +                self.cpp_info.requires.append("xorg::xscrnsaver")
Thanks for the clarification. It's also my understanding that there's no way to have Conan transparently handle this case for now, and that creating the unused component might be the only way, but that also feels iffy.

I'd thus like to understand if the overlinking here causes too much damage to consumers

2025-02-27 14:14 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +    ("hidapi", []),
We have fixed the libusb issues here, which can't be build as shared for now until the new CMakeConfigDeps is generally available in the Conan client, thanks for testing on your end :)

2025-02-27 14:15 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +            "SDL3::Headers"
Yes, that's another approach and I might just go for it after we check that the rest of the recipe looks ok - having only the global component would be better but alas

2025-02-27 14:17 UTC, AbrilRBS commented
We think that the recipe is now mostly there, all our local tests on different configurations seem ok - we additionally tested on Android (@perseoGI will post the logs shortly)

If anyone can take a double look and test the generated package on their end, we'd appreciate it, thanks!

The known issues/limitations for now are:
- Overlinking when shared
- Linking with `SDL3::Headers` will link everything, it's currently an alias for the global library

2025-02-27 14:28 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
No, the test_package is a executable that runs in cli mode only. 
Android gui executables must be built as a shared library, and have the java classes.

I think you can add android support by addind a jdk and android-ndk to the (build) requirements.
If cmake finds those, it'll create a SDL3-3.x.y.jar archive.

2025-02-27 14:42 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
FYI, I added support for building the SDL tests (not the examples) as a single-arch-debug-apk to CMake (if it finds all dependencies, only tested on Linux, and is only for internal SDL use). This was done to avoid Gradle.

2025-02-27 14:47 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +            "SDL3::Headers"
This will cause an issue if you ever add sdl2-compat to cci

2025-02-27 17:00 UTC, perseoGI commented
Android compilation logs:

```sh
$ conan profile show -pr android-packed 

[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=c++_static
compiler.version=17
os=Android
os.api_level=26
[tool_requires]
*: cmake/3.29.7, android-ndk/r27c
[conf]
tools.build:verbosity=verbose
tools.cmake.cmaketoolchain:generator=Ninja
tools.compilation:verbosity=verbose
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=true

```

```sh
$ conan create recipes/sdl/3.x/ --version 3.2.4 --build='&' -pr:h android-packed
```

[sdl-3.2.4-android-compilation.txt](https://github.com/user-attachments/files/19013228/sdl-3.2.4-android-compilation.txt)

And a quick test running on an Android emulator:

```
$ emulator -avd Pixel_8_API_VanillaIceCream -netdelay none -netspeed full
<other terminal>
$ adb push recipes/sdl/3.x/test_package/build/clang-17-armv8-17-release/test_package /data/local/tmp 
$ adb shell file /data/local/tmp/test_package
/data/local/tmp/test_package: ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64), for Android 26, built by NDK r27c (12479018), BuildID=0ce060d23c7564c0d2c3840e3ce4db826110d874, not stripped
$ adb shell
$ [adb] /data/local/tmp/test_package
SDL version 3002004
```

2025-02-27 18:31 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
> I think you can add android support by adding a jdk and android-ndk to the (build) requirements.

This is something that we expect users to add using their profiles instead of having recipes explicitly depend on those

2025-02-27 18:46 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
That's reasonable.
I expect the sdl3 conan recipe to fail in build or package when the java classes are not built.

2025-02-27 18:55 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
The issue is that this might be a bit hard to detect the case where the user has properly configured it on their side and when they have not

2025-02-27 19:00 UTC, madebr commented on recipes/sdl/3.x/conanfile.py
> +    def config_options(self):
You can detect by checking for a few `ANDROID_*` environment variables, and the presence of `javac` and `jar.
But that will break easily.
The pragmatic approach is to fail the build when the jar file is not created.
Don't overcomplicate things.

2025-02-28 10:16 UTC, perseoGI commented
Greetings @madebr,

I'm attaching a short screen record where the execution of different SDL examples can be seen:

https://github.com/user-attachments/assets/36d60bd2-d952-433a-bd10-23bd7c9cdf7b

This is running on a MacOS machine. 
Testing examples o Android will require creating a native application and importing SDL as dependency. 
I have not bandwidth enough to create such examplenright now.

2025-02-28 12:39 UTC, madebr commented
That's great! All I'm asking is to throw an error when building an android package (with a few comments why), so the next dev knows what to do.

2025-03-02 06:19 UTC, madebr commented on recipes/sdl/3.x/conandata.yml
> +  "3.2.4":
3.2.6 :)

2025-03-03 16:34 UTC, AbrilRBS commented on recipes/sdl/3.x/conanfile.py
> +            "SDL3::Headers"
Looks like I was wrong, adding it as a proper component was not quite as involved as I first thought!

2025-03-03 16:35 UTC, AbrilRBS commented
> That's great! All I'm asking is to throw an error when building an android package (with a few comments why), so the next dev knows what to do.

@madebr we have guarded Android builds behind a conf, users that have properly set up their env can set it to build this for Android as needed

2025-03-03 17:02 UTC, perseoGI approved these changes
🐸

2025-03-03 18:07 UTC, madebr approved these changes

2025-03-04 11:43 UTC, jcar87 commented
Thanks everyone for your involvement in this!

2025-03-04 11:43 UTC, merged