opentelemetry-cpp: bump grpc to fix unwanted absl log output
conan-io/conan-center-index pull request #25870
Opened 2024-11-07 12:53 UTC by ArielGMachado

### Summary
Changes to recipe:  **opentelemetry/1.14.2**
fixes #25869

#### Motivation

gRPC/1.65.0 is affected by a change in absl logging that produces unwanted log output to stdout.

#### Details

grpc dependency is bumped from 1.65.0 to 1.67.1

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-07 21:51 UTC, AbrilRBS approved these changes

2024-11-07 21:52 UTC, AbrilRBS requested changes
Checking which conflicts this would generate elsewhere, sorry for the delay!

2024-11-07 21:55 UTC, AbrilRBS approved these changes
Looks good on my end

2024-11-11 11:41 UTC, uilianries approved these changes
LGTM. Just checked other recipes using grpc and opentelemetry-cpp. The risk is same as always, as gRPC may or may not use opentelemetry as well.

2024-11-11 11:43 UTC, merged