gdal: Fix 3.7.3 and 3.8.3 builds by replacing Parquet and ArrowDataset versions with Arrow one
conan-io/conan-center-index pull request #25898
Opened 2024-11-09 18:35 UTC by CommanderCRM

### Summary
Changes to recipe:  **gdal**

#### Motivation
Resolves #25853

#### Details
Introduce new patch for gdal 3.7.3 (forward compatible with 3.8.3) which replaces empty `Parquet_VERSION` and `ArrowDataset_VERSION` variables in CMake with `ARROW_VERSION`. 
Arrow library always [sets](https://github.com/apache/arrow/blob/03c3f8ed41573b611c4c6dfaf1ec166a9b78decb/cpp/src/arrow/arrow-config.cmake#L25) this variable, being the main dependency of gdal.

There [is](https://github.com/apache/arrow/blob/03c3f8ed41573b611c4c6dfaf1ec166a9b78decb/cpp/src/parquet/ParquetConfig.cmake.in#L41) a PARQUET_VERSION var in Arrow source code, but it doesn't work during gdal configuration - probably because it's a template file which is [included](https://github.com/apache/arrow/blob/03c3f8ed41573b611c4c6dfaf1ec166a9b78decb/cpp/src/parquet/CMakeLists.txt#L365) only when Arrow is built from source.

Configuration [file](https://github.com/apache/arrow/blob/03c3f8ed41573b611c4c6dfaf1ec166a9b78decb/cpp/src/arrow/dataset/ArrowDatasetConfig.cmake.in#L20) of ArrowDataset doesn't even handle version variable. 

---
- [X] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [X] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [X] Tested locally with at least one configuration using a recent version of Conan

2024-11-11 08:55 UTC, valgur commented
Thanks!
It's a reasonable fix for now, but it should really be addressed in the custom find_package() as part of #23233 instead.

2024-12-11 07:49 UTC, Luk0r commented
just a little reminder, that this is still relevant, thx

2024-12-18 13:47 UTC, valgur commented
The patching in this recipe can be avoided by passing the necessary vars via CMakeToolchain instead:
```patch
--- a/recipes/gdal/post_3.5.0/conanfile.py
+++ b/recipes/gdal/post_3.5.0/conanfile.py
@@ -445,8 +445,12 @@
         tc.variables["GDAL_USE_ZLIB_INTERNAL"] = False
         tc.variables["GDAL_USE_ZSTD"] = self.options.with_zstd
 
-        tc.variables["Parquet_FOUND"] = self.options.with_arrow and self.dependencies["arrow"].options.parquet
-        tc.variables["ArrowDataset_FOUND"] = self.options.with_arrow and self.dependencies["arrow"].options.dataset_modules
+        if self.options.with_arrow:
+            arrow = self.dependencies["arrow"]
+            tc.variables["Parquet_FOUND"] = arrow.options.parquet
+            tc.variables["Parquet_VERSION"] = str(arrow.ref.version)
+            tc.variables["ArrowDataset_FOUND"] = arrow.options.dataset_modules
+            tc.variables["ArrowDataset_VERSION"] = str(arrow.ref.version)
 
         # General workaround for try_compile() tests in the project
         # https://github.com/conan-io/conan/issues/12180
```

2025-01-08 15:31 UTC, franramirez688 approved these changes
Hi @CommanderCRM 

Thanks a lot for this PR 😁 
I just tested both versions and it works 👏 

LGTM!

2025-01-08 17:15 UTC, perseoGI approved these changes

2025-01-08 17:36 UTC, valgur requested changes
Please avoid patching and pass the necessary variables via CMakeToolchain instead:
https://github.com/conan-io/conan-center-index/pull/25898#issuecomment-2551370637

2025-01-09 09:14 UTC, merged