libftp: add version 1.2.0
conan-io/conan-center-index pull request #25893
Opened 2024-11-09 09:02 UTC by toge

### Summary
Changes to recipe:  **libftp/***

#### Motivation
There are a new features and several improvements in 1.2.0.
Make static-library package type on msvc instead of validation check.

#### Details
https://github.com/deniskovalchuk/libftp/compare/v1.1.0...v1.2.0

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] Tested locally with at least one configuration using a recent version of Conan

2024-11-12 09:10 UTC, ErniGH approved these changes
Thanks!

2024-11-12 16:21 UTC, AbrilRBS requested changes
There are hook warnings that should be addressed

2024-11-14 11:48 UTC, uilianries submitted a review, later dismissed
LGTM. The new minor version install cmake files: https://github.com/deniskovalchuk/libftp/compare/v1.1.0...v1.3.0#files_bucket

I did few changes to this recipe adapting not only to Conan 2.x, but fixing linter and hooks warnings.

2024-11-14 15:55 UTC, perseoGI commented on recipes/libftp/all/conanfile.py
>              self.package_type = "static-library"
Reverting to original due to internal behavior of `auto_shared_fpic`. 
See https://github.com/conan-io/conan-center-index/pull/25940

2024-11-14 15:58 UTC, perseoGI approved these changes
LGTM

2024-11-14 16:23 UTC, uilianries commented
@AbrilRBS The hooks warnings are fixed. Could you please review it again :)

2024-11-14 20:54 UTC, AbrilRBS approved these changes
Thanks!

2024-11-14 20:54 UTC, merged

2024-11-15 15:24 UTC, valgur commented on recipes/libftp/all/conanfile.py
> +required_conan_version = ">=2.0"
@uilianries Should have been `2.0.9` since `implements = ["auto_shared_fpic"]` is being used.