orc: add version 2.0.3 (and other stable releases)
conan-io/conan-center-index pull request #25971
Opened 2024-11-18 02:24 UTC by wgtmac

### Summary
Changes to recipe:  **orc/2.0.3**

#### Motivation
Sync recent releases from Apache ORC.

#### Details
Add several news releases from Apache ORC 2.0.x, 1.9.x and 1.8.x major versions.

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

2024-11-18 05:29 UTC, wgtmac commented
@toge @valgur Could you please take a look? Thanks!

2024-11-18 12:36 UTC, valgur commented
+1 I would suggest keeping only the latest versions for each major release (1.9.5 and 2.0.3)..

2024-11-18 14:03 UTC, wgtmac commented
Make sense! Now I just keep 1.9.5 and 2.0.3. Thanks @ErniGH and @valgur!

2024-11-18 15:20 UTC, valgur approved these changes

2024-11-18 17:00 UTC, valgur requested changes
Keep the old versions. :)

2024-11-21 03:44 UTC, wgtmac commented
To be clear, do you mean that I need to keep 1.9.5, 2.0.0 and 2.0.3. Right? @valgur

2024-11-21 16:52 UTC, perseoGI commented
@wgtmac  

> BTW, if someone is using 1.7.10 or 1.9.3. Does it break anything if these versions are removed?

It is safe to remove versions, they will be kept in CCI. The only difference is that those versions will stop receiving recipe revision updates.

2024-11-25 16:59 UTC, ErniGH approved these changes
LGTM

2024-11-25 17:00 UTC, AbrilRBS approved these changes

2024-11-25 17:04 UTC, merged

2024-12-02 16:18 UTC, jcar87 commented on recipes/orc/all/conanfile.py
> -        if self.version < "1.9.0":
Are we sure about that? From what I can see it worked as intended
The versions in `conandata.yml` previous to this PR were: `2.0.0`, `1.9.3`, `1.9.2`, `1.8.7`, `1.8.6`, `1.7.10`
From what I can see, the pure string comparisons would have been correct for all these versions:

* `"2.0.0" < "1.9.0"`: `False`
* `"1.9.3" < "1.9.0"`: `False`
* `"1.9.2" < "1.9.0"`: `False`
* `"1.8.7" < "1.9.0"`: `True`
* `"1.8.6" < "1.9.0"`: `True`
* `"1.7.10" < "1.9.0"`: `True`

Lexicographical version comparisons are correct when the number of digits across versions is fixed, and the most significant components go from the left to right - 
There are potential issues when you have `1.2.0`, `1.19.0`, `1.20.0` - but they don't apply to this recipe and these versions - so surrounding with `Version()` is to account for that, especially if in the future versions like that are used (or prereleases, etc) - but in this case was not critical enough to be actually a bug.