Add libe57format/3.2.0 release
conan-io/conan-center-index pull request #26146
Opened 2024-12-09 21:24 UTC by EstebanDugueperoux2

### Summary
Changes to recipe:  **libe57format/3.2.0**

#### Motivation
Add 3.2.0 release

2024-12-12 08:00 UTC, jcar87 requested changes
Thanks @EstebanDugueperoux2  - please only make the changes required by the PR objetive (adding 3.2.0) - we've had issues with hasty removals of old logic leading to unintended bugs. For the time being, the team will try to take on these clean ups _after_ the PR has been reviewed and if it doesn't cause delays in merging a useful feature.

2024-12-12 08:18 UTC, EstebanDugueperoux2 commented
> Thanks @EstebanDugueperoux2 - please only make the changes required by the PR objetive (adding 3.2.0) - we've had issues with hasty removals of old logic leading to unintended bugs. For the time being, the team will try to take on these clean ups _after_ the PR has been reviewed and if it doesn't cause delays in merging a useful feature.

Hi @jcar87, the issue is that only adding new release make pipeline failed.
And it seems patch done inside the recipe is no more usefull.

2025-01-28 15:54 UTC, jcar87 commented
> Hi @jcar87, the issue is that only adding new release make pipeline failed.

mmm, we can have a look, what was the CI failure in this case?

> And it seems patch done inside the recipe is no more usefull.

The removal of the `_patch_sources()` method is in effect for all already published versions, so it is introducing regressions for pre-existing versions w.rt. `POSITION_INDEPENDENT_CODE`, and introducing a regression for 3.1.1 by removing the warnings as errors - if this PR were merged, it could cause issues to users of 3.1.1 - 

> And it seems patch done inside the recipe is no more usefull.
We keep asking contributors to avoid these kind of changes because we very often see that they are more invasive and have side effects that are not intended, as it seems to be the case here

2025-01-28 19:09 UTC, EstebanDugueperoux2 commented
Hi @jcar87 I have updated recipe to relax replace_in_file with strict=False because "set_warning_as_error()" doesn't exists anymore in recent release.
It was the cause of previous pipeline failures.

2025-01-30 11:07 UTC, jcar87 approved these changes
Thanks for amending the PR!

2025-01-30 11:08 UTC, merged