libnftnl: add new recipe (#26198)
conan-io/conan-center-index pull request #26200
Opened 2024-12-16 09:57 UTC by nikitasinys

### Summary
Add new recipe:  **libnftnl/[1.2.8]**, fixes #26198

#### Motivation
This library helps to work with nf_tables subsystem

---
- [ ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ ] Tested locally with at least one configuration using a recent version of Conan

2024-12-16 11:50 UTC, valgur requested changes
Thanks! LGTM. The Windows shared validation needs to be moved to `validate()`.

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/conanfile.py
> +            raise ConanInvalidConfiguration("libnftnl is only supported on Linux")
Should move this to `validate()`.

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/conanfile.py
> +    package_type = "library"
```suggestion
    package_type = "library"
    languages = ["C"]
    implements = ["auto_shared_fpic"]
```
Can drop `config_options()` and `configure()` if `auto_shared_fpic` is added.

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/conanfile.py
> +    topics = ("libnftnl", "netlink", "nftables")
```suggestion
    topics = ("netlink", "nftables")
```

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/conanfile.py
> +        self.cpp_info.libs = ["nftnl"]
```suggestion
        self.set_property("pkg_config_name", "libnftnl")
        self.cpp_info.libs = ["nftnl"]
```
The project installs a `libnftnl.pc` file. Although it matches the default .pc name generated by Conan, it's better to list this explicitly, imo.

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/test_package/conanfile.py
> +    test_type = "explicit"
```suggestion
    generators = "CMakeDeps", "CMakeToolchain"
```
No longer needed in Conan v2.

2024-12-16 11:50 UTC, valgur commented on recipes/libnftnl/all/conanfile.py
> +required_conan_version = ">=1.53.0"
```suggestion
required_conan_version = ">=2.0.9"
```
In case `auto_shared_fpic` is used.

2024-12-16 13:29 UTC, nikitasinys commented
> Thanks! LGTM. The Windows shared validation needs to be moved to `validate()`.

Thanks for review!

2025-01-06 08:39 UTC, nikitasinys commented
Hi @conan-io/barbarians,
I have an hanging pre-check for 20 days in two of my PR (this PR and #26204), it's also still hanging after adding new commits
Can you please look at it?

2025-02-03 09:28 UTC, nikitasinys commented
Hi @uilianries 
I have an issues with hanging pre-checks for more than a month in two of my PR, I tried to ping `@conan-io/barbarians` but probably mentioning didn't worked. Can you please look at it?

> Hi @conan-io/barbarians, I have an hanging pre-check for 20 days in two of my PR (this PR and #26204), it's also still hanging after adding new commits Can you please look at it?

2025-02-06 10:56 UTC, uilianries commented
@nikitasinys An internal error occurred when running your PR. I just reported internally to take action. Sorry for the occurrence.

2025-03-13 13:46 UTC, AbrilRBS approved these changes
Looks good on my end 👍

2025-03-13 13:50 UTC, uilianries approved these changes

2025-03-13 17:21 UTC, merged