- docs for KB-H053
conan-io/conan-center-index pull request #2662
Opened 2020-08-26 11:43 UTC by SSE4

docs for https://github.com/conan-io/hooks/pull/226

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-08-26 11:45 UTC, danimtb approved these changes

2020-08-27 03:01 UTC, Croydon commented on docs/error_knowledge_base.md
> +The recipe imports private conan API, this is strongly discouraged - private imports are subjects to breaking changes. Avoid usage of private APIs, request to publically expose needed methods, if nec
```suggestion
The recipe imports private Conan API, this is strongly discouraged - private imports are subjects to breaking changes. Avoid usage of private APIs, request to publically expose needed methods, if necessary.
```

Nit: conan -> Conan

2020-09-20 14:01 UTC, prince-chrismc submitted a review, later dismissed

2020-09-24 18:30 UTC, intelligide submitted a review, later dismissed

2020-10-13 18:05 UTC, jgsogo requested changes

2020-10-13 18:05 UTC, jgsogo commented on docs/error_knowledge_base.md
> +### **<a name="KB-H053">#KB-H053</a>: "PRIVATE IMPORTS"**
```suggestion
#### **<a name="KB-H053">#KB-H053</a>: "PRIVATE IMPORTS"**
```

Ups! We use four here.

2020-10-13 18:32 UTC, jgsogo approved these changes

2020-10-13 20:55 UTC, prince-chrismc approved these changes

2020-10-14 03:49 UTC, Croydon approved these changes

2020-10-14 04:01 UTC, merged