Add TinyXML as a new "cmake_find_package" name for tinyxml
conan-io/conan-center-index pull request #2814
Opened 2020-09-03 23:59 UTC by joxoby

Specify library name and version:  **tinyxml/2.6.2**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

Many CMake projects that include `tinyxml` use the name `TinyXML` instead. See [urdfdom](https://github.com/ros/urdfdom/blob/master/cmake/FindTinyXML.cmake), [dart](https://github.com/dartsim/dart/blob/master/cmake/FindTinyXML.cmake) and [GOTURN](https://github.com/davheld/GOTURN/blob/master/cmake/Modules/FindTinyXML.cmake) for example.

2020-09-03 23:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=2814) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=2814) before we can accept your contribution.<br/><hr/>**Juan Oxoby** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=2814) it.</sub>

2020-09-04 21:53 UTC, uilianries requested changes
Same should be applying for cmake multi (TinyXMLConfig.cmake)

2020-09-04 21:53 UTC, uilianries commented on recipes/tinyxml/all/conanfile.py
> +        self.cpp_info.names["cmake_find_package"] = "TinyXML"
```suggestion
        self.cpp_info.names["cmake_find_package"] = "TinyXML"
        self.cpp_info.names["cmake_find_package_multi"] = "TinyXML"
```

2020-09-09 12:52 UTC, uilianries approved these changes

2020-09-09 17:45 UTC, SSE4 approved these changes

2020-09-10 15:48 UTC, merged