abseil: add components + cache cmake
conan-io/conan-center-index pull request #2928
Opened 2020-09-15 15:23 UTC by SpaceIm

Specify library name and version:  **abseil/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

closes https://github.com/conan-io/conan-center-index/issues/2924

Suggestions are welcome :smile:

2020-09-15 15:33 UTC, SpaceIm commented
Another option would be to:
- parse `abseil-targets.cmake` in package method (before deleting it obviously)
- generate the json file introducted in this PR
- install this json file (or whatever format) in package folder

2020-09-15 16:26 UTC, SpaceIm commented
I can wait conan 1.29.0 in CCI, or maybe using `cmake_find_package` in `test_package` which is less buggy in 1.28.1 I believe.

2020-09-15 16:48 UTC, Croydon commented
Did you generate the JSON files? (I really hope so 🙈)
If yes, how?

2020-09-15 18:29 UTC, prince-chrismc commented on recipes/abseil/all/test_package/CMakeLists.txt
> +conan_basic_setup(TARGETS)
```suggestion
conan_basic_setup()
```

2020-09-15 18:30 UTC, prince-chrismc commented on recipes/abseil/all/conanfile.py
> +conan_basic_setup()""")
Could this be avoided with a top level CMakeLists.txt wrapper?

2020-09-15 18:32 UTC, prince-chrismc commented
> Another option would be to:
> 
> * parse `abseil-targets.cmake` in package method (before deleting it obviously)
> * generate the json file introducted in this PR
> * install this json file (or whatever format) in package folder

I think keeping the parser with the recipe would make maintenance easier!

2020-09-18 09:10 UTC, danimtb approved these changes

2020-09-18 11:59 UTC, Croydon commented
Regarding the new auto-merge feature:

If I would "request changes" now, because I think this should not get merged until we have talked further about the generating of the JSON files - would the bot care about this? Or does the bot exclusively look at the approvals?

2020-09-18 12:00 UTC, Croydon requested changes
How to generate the JSON files?

2020-09-18 14:37 UTC, danimtb commented
@Croydon we are still kind of testing it (now in production), as the automation is configurable. The usage is very basic right now and it counts the reviews from the team and the community and only "blocks" the merge if the latest commit has a red review from any of the team members. We are still doing some changes until we enable it with the proper configuration. The details will be documented as requested in #2857

2020-09-18 20:02 UTC, SpaceIm commented
@Croydon @prince-chrismc
It was partially generated with a small script taking `absl-target.cmake` file as input, but I had to manually fix some parts in generated file (like system libs) and I don't know if input file is consistent across CMake version.

I know that current recipe is far from ideal, but at least it brings all abseil imported targets in cmake_find_package and cmake_find_package_multi. When i have time, I'll try to really automatize creation of this json file at "package" time.

2020-09-20 21:07 UTC, prince-chrismc commented
I think I would prefer if you checked it in, god forbid someone else needs it at least we have a starting point. 
If you do not commit the script, adding a new version would be much more complicated for anyone else.

As long as ur script says "FYI i do not work and you'll need to manually fix some paths" I think we will be miles of head of where we are today.

does that sound reasonable?

2020-09-27 12:44 UTC, SSE4 approved these changes

2020-09-29 05:27 UTC, mathbunnyru commented
lts_2020_09_23 was released (https://github.com/abseil/abseil-cpp/releases/tag/20200923).

May I ask you to generate the JSON file for the new version as well?
Totally fine, if that will be done in another PR.

2020-09-29 17:04 UTC, uilianries approved these changes

2020-09-29 17:05 UTC, uilianries commented
> lts_2020_09_23 was released ([abseil/abseil-cpp@`20200923` (release)](https://github.com/abseil/abseil-cpp/releases/tag/20200923)).
> 
> May I ask you to generate the JSON file for the new version as well?
> Totally fine, if it will be done in another PR.

Another PR please, this one is related to components only.

2020-09-29 20:31 UTC, merged

2020-09-30 04:48 UTC, Croydon commented
@SpaceIm Please provide your script somewhere, even if it is just in a GitHub Gist or whatever. Otherwise we pretty much have a bus factor of 1 for adding new abseil versions and we will always have to annoy you 😄

2020-09-30 12:41 UTC, SpaceIm commented
@Croydon I'm close to provide a PR with last abseil release, where cmake config file is (more or less naively) parsed in `package` method, installed, and read in `package_info`.

2020-09-30 13:07 UTC, mathbunnyru commented
Thanks @SpaceIm, it sounds awesome.

2020-09-30 14:27 UTC, SpaceIm commented
https://github.com/conan-io/conan-center-index/pull/3050