glib: allow MT runtime
conan-io/conan-center-index pull request #2974
Opened 2020-09-21 13:04 UTC by ericLemanissier

it allowed, now that C3I builds shared libraries with MT runtime

Specify library name and version:  **glib/***

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

cc @Croydon

2020-09-21 16:26 UTC, intelligide approved these changes

2020-09-21 22:19 UTC, Croydon approved these changes
Thanks!

2020-09-22 12:13 UTC, madebr requested changes
I'm not sure glib can be built as a **fully functional** shared MT library.
Because it exposes symbols from the c runtime.
See e.g. https://developer.gnome.org/glib/2.66/glib-File-Utilities.html#g-fopen

The `FILE*` token is not shared between dll and application.
This will cause undefined behaviour.

2020-09-22 12:55 UTC, ericLemanissier commented
I'm not sure either, but the possibility of UB in some uses cases should not be enough to prevent building the binary.

2020-09-22 13:09 UTC, madebr commented
> I'm not sure either, but the possibility of UB in some uses cases should not be enough to prevent building the binary.

Maybe. When somebody decides to use shared libraries with MT, he is holding a big foot gun already.
So maybe it's ok.

2020-09-26 14:50 UTC, SSE4 approved these changes

2020-09-26 16:01 UTC, merged