Fix builds for OpenSSL < 1.0.2d
conan-io/conan-center-index pull request #3001
Opened 2020-09-24 16:40 UTC by jheaff1

Enabling "make" parallelisation when building OpenSSL < 1.0.2d
causes errors. This commit modifies the OpenSSL 1.x.x recipe to
disable parallel builds for versions less than 1.0.2d.

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-09-24 18:28 UTC, uilianries commented
Hi @jheaff1 Could you please explain a bit more about the error? Is there any reference about this?

2020-09-25 08:20 UTC, jheaff1 commented
> Hi @jheaff1 Could you please explain a bit more about the error? Is there any reference about this?

Hi @uilianries, I tried building all sub-versions of OpenSSL 1.0.2 with "make -j4" and it would only succeed for versions >= 1.0.2d.

It seems to be a known issue that parallel builds fail for old versions of OpenSSL:

https://github.com/openssl/openssl/issues/298
https://stackoverflow.com/questions/28639207/why-cant-i-compile-openssl-with-multiple-threads-make-j3

2020-09-25 18:13 UTC, uilianries commented
@jheaff1 Thank you for extra details!

2020-09-25 19:35 UTC, jheaff1 commented
@uilianries No problem! It appears that 3 people need to approve it. Whom do I ask for approval?

2020-09-25 19:51 UTC, prince-chrismc requested changes
Can you please add the two links to the comment?

2020-09-25 20:51 UTC, uilianries approved these changes

2020-09-25 20:53 UTC, uilianries commented
I know openssl's build take hours, but 20h ... I'll keep eye open here, maybe the CI job got stuck.

2020-09-27 12:55 UTC, SSE4 approved these changes

2020-09-27 12:55 UTC, SSE4 commented
@danimtb seems like build stucks

2020-09-28 08:47 UTC, jheaff1 commented
> Can you please add the two links to the comment?

Done.

This will be my first ever contribution to an Open Source project, very exciting indeed!

2020-09-28 12:53 UTC, prince-chrismc approved these changes

2020-09-29 13:14 UTC, uilianries approved these changes

2020-09-30 03:48 UTC, Croydon approved these changes

2020-09-30 04:01 UTC, merged

2020-09-30 04:08 UTC, Croydon commented
@jheaff1 Congratulations to your first open source contribution! 🎉