Add libgit2/1.0.1
conan-io/conan-center-index pull request #3070
Opened 2020-10-01 15:27 UTC by intelligide

Specify library name and version:  **libgit2/1.0.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-10-01 17:17 UTC, SSE4 commented on recipes/libgit2/all/conandata.yml
> -  "0.28.5":
please don't remove old versions

2020-10-01 19:38 UTC, uilianries requested changes
dont remove old versions

2020-10-01 20:31 UTC, intelligide commented
> dont remove old versions

https://github.com/conan-io/conan-center-index/pull/3070#discussion_r498409627 ;)

2020-10-01 22:21 UTC, uilianries approved these changes

2020-10-01 22:21 UTC, uilianries commented
@intelligide Thanks! It was a mess!

2020-10-08 15:50 UTC, theirix approved these changes
Looks good

2020-10-21 00:56 UTC, prince-chrismc approved these changes

2020-10-21 02:01 UTC, merged