Sqlitecpp
conan-io/conan-center-index pull request #3114
Opened 2020-10-05 18:00 UTC by prsolucoes

Specify library name and version:  **sqlitecpp/3.1.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-10-05 21:12 UTC, prsolucoes commented
It require C++ 11. How the best way to do it for Conan?

```
1b21c53eeec8b813f1751585329fab099c02755b/include/SQLiteCpp/Exception.h:72:29: error: expected ';' at end of declaration list
    int getErrorCode() const noexcept
                            ^
                            ;
/Users/jenkins/w/cci_PR-3114@3/.conan/data/sqlitecpp/3.1.1/_/_/package/1b21c53eeec8b813f1751585329fab099c02755b/include/SQLiteCpp/Exception.h:38:9: error: delegating constructors are permitted only in C++11
        Exception(aErrorMessage.c_str(), ret)
        ^~~~~~~~~
/Users/jenkins/w/cci_PR-3114@3/.conan/data/sqlitecpp/3.1.1/_/_/package/1b21c53eeec8b813f1751585329fab099c02755b/include/SQLiteCpp/Exception.h:48:9: error: delegating constructors are permitted only in C++11
        Exception(aErrorMessage, -1) // 0 would be SQLITE_OK, which doesn't make sense
        ^~~~~~~~~
/Users/jenkins/w/cci_PR-3114@3/.conan/data/sqlitecpp/3.1.1/_/_/package/1b21c53eeec8b813f1751585329fab099c02755b/include/SQLiteCpp/Exception.h:52:9: error: delegating constructors are permitted only in C++11
        Exception(aErrorMessage.c_str(), -1) // 0 would be SQLITE_OK, which doesn't make sense
        ^~~~~~~~~
```

2020-10-05 21:14 UTC, prsolucoes commented
![image](https://user-images.githubusercontent.com/395096/95132695-91c27200-0736-11eb-9865-5e7e26ad63c8.png)

2020-10-05 21:17 UTC, uilianries requested changes

2020-10-05 21:17 UTC, uilianries commented on recipes/sqlitecpp/all/test_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```suggestion
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)
```

2020-10-05 21:17 UTC, uilianries commented on recipes/sqlitecpp/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1)
```suggestion
cmake_minimum_required(VERSION 3.4)
```

Because CXX_STANDARD is available since 3.4

2020-10-06 12:55 UTC, uilianries commented
Add at line 53:
```python
 and Version(self.version) < "3":
```

2020-10-06 19:03 UTC, uilianries approved these changes

2020-10-09 02:50 UTC, prince-chrismc approved these changes

2020-10-12 10:28 UTC, SSE4 approved these changes

2020-10-12 13:01 UTC, merged