Add trantor/1.0.0
conan-io/conan-center-index pull request #3117
Opened 2020-10-06 03:17 UTC by an-tao

Specify library name and version:  trantor/1.0.0

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-10-06 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=3117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=3117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=3117) it.</sub>

2020-10-06 05:17 UTC, intelligide approved these changes

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    def _source_subfolder(self):
```suggestion

    @property
    def _source_subfolder(self):
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    def _configure_cmake(self):
```suggestion

    def _configure_cmake(self):
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    def build(self):
```suggestion

   def build(self):
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    def package(self):
```suggestion

    def package(self):
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    def package_info(self):
```suggestion

    def package_info(self):
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +        self.copy("License", src=self._source_subfolder(), dst="licenses")
```suggestion
         self.copy("License", src=self._source_subfolder, dst="licenses")
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +        os.rename(extracted_dir, self._source_subfolder())
```suggestion
        os.rename(extracted_dir, self._source_subfolder)
```

2020-10-06 05:17 UTC, intelligide commented on recipes/trantor/all/conanfile.py
> +    license = "https://raw.githubusercontent.com/an-tao/trantor/master/License"
```suggestion
    license = "BSD-3-Clause"
```

2020-10-06 13:13 UTC, uilianries requested changes

2020-10-06 13:13 UTC, uilianries commented on recipes/trantor/all/conanfile.py
> +    topics = ("Network library", "C++14/17", "Non-blocking I/O")
```suggestion
    topics = ("tcp-server", "non-blocking-io", "asynchronous", "networking")
```

2020-10-06 13:13 UTC, uilianries commented on recipes/trantor/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1)
```suggestion
cmake_minimum_required(VERSION 3.4)
```

CXX_STANDARD 14 requires 3.4

2020-10-06 13:13 UTC, uilianries commented on recipes/trantor/all/test_package/test_package.cpp
> +#include <iostream>
```suggestion
```

not used

2020-10-08 13:45 UTC, uilianries commented on recipes/trantor/all/conanfile.py
> +            del self.options.fPIC
```suggestion
            del self.options.fPIC
        if self.settings.compiler == "Visual Studio" and "MT" in self.settings.compiler.runtime and self.options.shared:
            raise ConanInvalidConfiguration("Trantor can not be built by MSVC and MT runtime as shared library.")
```

2020-10-20 13:36 UTC, uilianries commented
@an-tao  The error is caused due Crypt32 missing:

>    libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_open_store [C:\J\w\cci_PR-3117@2.conan\data\trantor\1.0.0__\build\19f67793fecef0b1b6dcb3d7f2815c46a3a040ba\source_subfolder\trantor.vcxproj]

The method CertOpenStore is part of wincrypt.h

2020-12-31 13:24 UTC, closed without merging