libharu: add libharu/2.3.0 recipe
conan-io/conan-center-index pull request #3349
Opened 2020-10-29 18:01 UTC by madebr

Specify library name and version:  **libharu/2.3.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-10-30 13:59 UTC, theirix commented on recipes/libharu/all/conanfile.py
> +    _autotools = None
Not needed

2020-10-30 14:02 UTC, theirix requested changes
One fix and it's ok

2020-11-02 23:51 UTC, SpaceIm approved these changes

2020-11-03 21:11 UTC, uilianries approved these changes

2020-11-04 08:25 UTC, danimtb approved these changes

2020-11-07 00:13 UTC, prince-chrismc approved these changes

2020-11-10 23:29 UTC, SpaceIm commented
This PR was not merged by the bot.

2020-11-15 15:37 UTC, SSE4 approved these changes

2020-11-18 05:55 UTC, theirix approved these changes

2020-11-18 06:31 UTC, merged