Add cppoptparse
conan-io/conan-center-index pull request #3380
Opened 2020-11-02 08:50 UTC by tarc

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-02 23:17 UTC, SpaceIm requested changes

2020-11-02 23:17 UTC, SpaceIm commented on recipes/cpp-optparse/all/conanfile.py
> +
```suggestion
```

2020-11-02 23:17 UTC, SpaceIm commented on recipes/cpp-optparse/config.yml
> +  "2ec0b7aca9a692ff93017ed44ca9d13a8e7d4d00":
```suggestion
  "cci.20171104":
```

2020-11-02 23:17 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +conan_target_link_libraries(OptionParser)
```suggestion
if(MSVC AND BUILD_SHARED_LIBS)
    set_target_properties(OptionParser PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
endif()
```

2020-11-02 23:17 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +endif()
```suggestion
```

2020-11-02 23:19 UTC, SpaceIm commented on recipes/cpp-optparse/all/conanfile.py
> +    topics = ("conan", "utils", "library")
```suggestion
    topics = ("conan", "cpp-optparse", "argument", "parsing")
```

2020-11-02 23:20 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13)
```suggestion
cmake_minimum_required(VERSION 3.4)
```

2020-11-02 23:22 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +        PATTERN "*.h")
```suggestion
install(FILESsource_subfolder/OptionParser.h DESTINATION include)
```

2020-11-02 23:34 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +include(${CMAKE_CURRENT_BINARY_DIR}/../conanbuildinfo.cmake)
```suggestion
include(conanbuildinfo.cmake)
```

2020-11-02 23:34 UTC, SpaceIm commented on recipes/cpp-optparse/all/CMakeLists.txt
> +add_library(OptionParser ${CMAKE_CURRENT_SOURCE_DIR}/source_subfolder/OptionParser.cpp)
```suggestion
add_library(OptionParser source_subfolder/OptionParser.cpp)
```

2020-11-03 08:50 UTC, theirix approved these changes

2020-11-03 14:29 UTC, SSE4 approved these changes

2020-11-03 14:30 UTC, SpaceIm approved these changes

2020-11-03 14:31 UTC, merged