libcurl: add support for c-ares
conan-io/conan-center-index pull request #3383
Opened 2020-11-02 16:37 UTC by timblechmann

c-ares is required for threaded resolvers.

Specify library name and version:  **libcurl**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-02 21:13 UTC, SpaceIm commented on recipes/libcurl/all/conanfile.py
> +            self.requires("c-ares/1.16.1")
why `get_safe`? This option is never removed. Does this option make sense for all versions currently in CCI?

2020-11-02 21:18 UTC, SpaceIm requested changes

2020-11-02 21:18 UTC, SpaceIm commented on recipes/libcurl/all/conanfile.py
> +        if self.options.get_safe("with_c_ares"):
```suggestion
        if self.options.with_c_ares:
```

2020-11-02 21:18 UTC, SpaceIm commented on recipes/libcurl/all/conanfile.py
> +        if self.options.get_safe("with_c_ares"):
```suggestion
        if self.options.with_c_ares:
```

2020-11-03 09:01 UTC, a4z approved these changes

2020-11-03 10:29 UTC, SpaceIm approved these changes

2020-11-03 14:27 UTC, SSE4 approved these changes

2020-11-03 20:52 UTC, uilianries approved these changes

2020-11-03 21:31 UTC, merged