leptonica: Fix turning off options, no memmove on macOS < 13
conan-io/conan-center-index pull request #3440
Opened 2020-11-07 02:38 UTC by datalogics-kam

Specify library name and version:  **leptonica/1.79.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-07 09:28 UTC, theirix requested changes
Good point, thanks!

Variable `CMAKE_DISABLE_FIND_PACKAGE_XXX` does not have effect on `find_library` call which is used for webp and openjp2. Those requirements with their `FindXXX.cmake` files are brought into build directory since libtiff 4.1.0 which depends on libwebp. 

Please remove  `CMAKE_DISABLE_FIND_PACKAGE_webp` and `CMAKE_DISABLE_FIND_PACKAGE_openjp2` too.

2020-11-18 05:57 UTC, theirix approved these changes

2020-11-20 14:10 UTC, uilianries approved these changes

2020-11-20 14:19 UTC, danimtb approved these changes

2020-11-20 14:31 UTC, merged