botan/*: Remove apple_deployment_target_flag
conan-io/conan-center-index pull request #3456
Opened 2020-11-08 19:20 UTC by MartinDelille

Since `apple_deployment_target_flag` is set by conan since version 1.31.0 (https://github.com/conan-io/conan/pull/7862), I removed this specific formula code.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-08 23:17 UTC, prince-chrismc requested changes
Can you please add the minimum conan version at the top with 1.31.0 for this new feature

2020-11-08 23:20 UTC, Croydon commented
According to the changelog the macOS CI does not yet have Conan >= 1.31.0 so this probably has to wait until then

2020-11-09 10:02 UTC, reneme commented
In my setup this fails to automatically add the compiler flag. Maybe I'm doing something wrong?

### conan profile

```
[settings]
os=Macos
os.version=10.13

os_build=Macos

arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=11
compiler.libcxx=libc++
build_type=RelWithDebInfo
[...]
```

### conan --version

```
> conan --version
Conan version 1.31.0
```

### Compiler invocation without this patch (see underlined flag)

```
clang++  -fstack-protector -m64 -pthread -stdlib=libc++ -m64 -std=c++11 -D_REENTRANT  -g -O3 -fPIC -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -isystem /usr/local/opt/llvm11/include/c++/v1 -fvisibility=hidden -D_LIBCPP_DISABLE_AVAILABILITY -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual  -Ibuild/include -Ibuild/include/external -c botan_all.cpp -o build/obj/lib/botan_all.o
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Compiler invocation with this patch

```
clang++  -fstack-protector -m64 -pthread -stdlib=libc++ -m64 -std=c++11 -D_REENTRANT  -g -O3 -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -isystem /usr/local/opt/llvm11/include/c++/v1 -fvisibility=hidden -D_LIBCPP_DISABLE_AVAILABILITY -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual  -Ibuild/include -Ibuild/include/external -c botan_all.cpp -o build/obj/lib/botan_all.o
```

I don't want to rule out that my setup is just misconfigured. Nevertheless, the compiler invocation changes at the crucial location after applying that patch.

2020-11-09 10:05 UTC, reneme commented
Note that Botan uses a homebrew build system and not auto tools.

2020-11-09 14:46 UTC, MartinDelille commented
Ok my mistake: conan-io/conan#7862 only concerns autotools.

2020-11-09 14:46 UTC, closed without merging