cyrus-sasl: fix pkg-config/hooks + bump dependencies + default options shouldn't raise
conan-io/conan-center-index pull request #3466
Opened 2020-11-09 17:44 UTC by SpaceIm

Specify library name and version:  **cyrus-sasl/all**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

default shared value is set to True, otherwise all recipes in CCI depending on this one won't be able to build without overriding this option...
I believe that the default combination of options should never raise (if another combination of options can work for a given triplet, it should be prefered than the one which raise).

2020-11-11 20:28 UTC, uilianries commented
Fair enough https://github.com/conan-io/hooks/pull/250

2020-11-12 14:28 UTC, SpaceIm commented
Maybe it could be fixed in the recipe without tweaking hooks: https://github.com/conan-io/hooks/pull/250#issuecomment-726111185. Some checks are required (when I have time).

2021-01-06 10:14 UTC, mathbunnyru requested changes

2021-01-06 10:14 UTC, mathbunnyru commented on recipes/cyrus-sasl/all/conanfile.py
> +        "shared": True,
```suggestion
        "shared": False,
```

2021-01-06 10:35 UTC, SpaceIm commented
For the moment, I'll disable `with_gssapi` by default and raise if it's True. Indeed, it requires krb5 recipe which is not available. In https://github.com/conan-io/conan-center-index/pull/2094, if you look at build logs, it doesn't find krb5 headers: https://c3i.jfrog.io/c3i/misc/logs/pr/2094/3/cyrus-sasl/2.1.27/5a07691c3da104a2be5c424d4970b723c8bcbbd6/create_stdout.txt

2021-01-06 11:59 UTC, uilianries approved these changes
LGTM

2021-01-06 14:49 UTC, prince-chrismc approved these changes

2021-01-06 22:45 UTC, dmn-star approved these changes

2021-01-07 10:38 UTC, SSE4 approved these changes

2021-01-07 13:01 UTC, merged