gsoap: disallow building tools when crossbuilding
conan-io/conan-center-index pull request #3615
Opened 2020-11-19 14:51 UTC by madebr

Specify library name and version:  **gsoap//all**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-19 15:07 UTC, prince-chrismc approved these changes

2020-12-27 03:41 UTC, prince-chrismc approved these changes

2020-12-27 03:41 UTC, madebr commented
@uilianries @jgsogo 
From the logs, it's unclear to me what build/configuration has failed.
All failed logs in https://github.com/conan-io/conan-center-index/pull/3615#issuecomment-751421884 look fine to me.
Unless I'm missing something...

2021-02-14 09:52 UTC, dmn-star requested changes

2021-02-14 09:52 UTC, dmn-star commented on recipes/gsoap/all/conanfile.py
> +            self.options.tools = False
```suggestion

```

2021-02-14 09:53 UTC, dmn-star commented
The conditional option setting will cause the build to fail on CCI.

2021-03-26 11:34 UTC, memsharded commented
I am trying to build and fix this.
It seems that the upstream source files have been removed, and only latest is available in https://sourceforge.net/projects/gsoap2/files/gsoap-2.8/

2021-05-12 14:40 UTC, jgsogo commented
Hi! As you've seen in #5516 we have stored the sources for existing versions in a public repository. We understand that gSOAP sources will be periodically removed from Sourceforge so we will need to keep adding them to the repository. We are thinking (and working) on a better solution.

Please, fix conflicts and rebase/merge with `master`, time to move this PR ahead 🚀

2021-07-11 17:02 UTC, closed without merging