added recipe for seqan
conan-io/conan-center-index pull request #3679
Opened 2020-11-24 12:34 UTC by boussaffawalid

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-24 14:08 UTC, prince-chrismc commented on recipes/seqan/2.x.x/conanfile.py
> +        )
you can avoid this is you download the sources from github https://github.com/seqan/seqan/archive/seqan-v2.4.0.tar.gz

just a thought, not a requirement

2020-11-24 14:18 UTC, prince-chrismc requested changes

2020-11-24 14:18 UTC, prince-chrismc commented on recipes/seqan/2.x.x/test_package/test_package.cpp
> +
Please try to keep the test_package a minimum to ensure correctness of the package not a sample for the API

```suggestion
```

2020-11-24 14:18 UTC, prince-chrismc commented on recipes/seqan/2.x.x/conanfile.py
> +
There's no components so this is not requires

```suggestion
```

2020-11-24 14:18 UTC, prince-chrismc commented on recipes/seqan/2.x.x/test_package/CMakeLists.txt
> +#SeqAn requires C++14!
```suggestion
```

2020-11-24 19:17 UTC, prince-chrismc reviewed
🚀 LGTM!

2020-11-25 18:38 UTC, uilianries requested changes
Have to filter compiler version according cppstd support.

2020-11-25 18:38 UTC, uilianries commented on recipes/seqan/2.x.x/conanfile.py
> +            tools.check_min_cppstd(self, 14)
@property
    def _compilers_minimum_version(self):
        return {
            "gcc": "5",
            "Visual Studio": "14",
            "clang": "3.4",
            "apple-clang": "3.4",
        }

    def configure(self):
        if self.settings.compiler.cppstd:
            tools.check_min_cppstd(self, 14)
        minimum_version = self._compilers_minimum_version.get(str(self.settings.compiler), False)
        if minimum_version:
            if tools.Version(self.settings.compiler.version) < minimum_version:
                raise ConanInvalidConfiguration("seqan requires C++14, which your compiler does not fully support.")
        else:
            self.output.warn("seqan requires C++14. Your compiler is unknown. Assuming it supports C++14.")

2020-11-25 18:38 UTC, uilianries commented on recipes/seqan/2.x.x/conanfile.py
> +from conans import ConanFile, tools
```suggestion
from conans import ConanFile, tools
from conans.errors import ConanInvalidConfiguration
```

2020-11-26 14:45 UTC, prince-chrismc approved these changes

2020-11-30 09:29 UTC, SSE4 commented on recipes/seqan/2.x.x/conanfile.py
> +SeqAn is an open source C++ library of efficient algorithms and data structures for the analysis of sequences
I'd personally just leave the first sentence. but never mind :)

2020-11-30 09:29 UTC, SSE4 approved these changes

2020-12-01 17:17 UTC, uilianries approved these changes

2020-12-01 19:02 UTC, merged