xorg/system: install libxcb-util0-dev on ubuntu AND debian, libxcb-ut…
conan-io/conan-center-index pull request #3726
Opened 2020-11-28 16:36 UTC by ledocc

…il-dev for other apt based distro

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-11-28 16:48 UTC, Croydon approved these changes
The current dev version of Debian has `libxcb-util-dev` too, this should be included in the condition

https://pkgs.org/search/?q=libxcb-util-dev

2020-11-28 17:04 UTC, ericLemanissier submitted a review, later dismissed

2020-11-28 17:46 UTC, SSE4 approved these changes

2020-11-28 18:39 UTC, Croydon commented
Lol, I have no clue why I approved, I wanted to post this as a comment

2020-11-28 18:40 UTC, Croydon requested changes
The current dev version of Debian has libxcb-util-dev too, this should be included in the condition

https://pkgs.org/search/?q=libxcb-util-dev

2020-11-28 19:06 UTC, Croydon commented on recipes/xorg/all/conanfile.py
> +                if (tools.os_info.linux_distro == "ubuntu" and tools.os_info.os_version < "15") or tools.os_info.linux_distro == "debian" :
```suggestion
                if (tools.os_info.linux_distro == "ubuntu" and tools.os_info.os_version < "15") or (tools.os_info.linux_distro == "debian" and tools.os_info.os_version < "12"):
```

2020-11-29 18:30 UTC, prince-chrismc approved these changes

2020-11-30 07:32 UTC, SSE4 approved these changes

2020-11-30 14:59 UTC, Croydon approved these changes

2020-11-30 15:03 UTC, merged