[docs] Add sources policy
conan-io/conan-center-index pull request #3902
Opened 2020-12-15 15:43 UTC by danimtb

Closes https://github.com/conan-io/conan-center-index/issues/3296

2020-12-15 16:53 UTC, intelligide commented on docs/README.md
> +  + [Packaging policy](packaing_policy.md)
```suggestion
  + [Packaging policy](packaging_policy.md)
```

2020-12-15 17:00 UTC, madebr commented on docs/packaging_policy.md
> +- Library sources that are no publicly available will not be allowed in this repository even if the license allows their redistribution.
```suggestion
- Library sources that are not publicly available will not be allowed in this repository even if the license allows their redistribution.
```

2020-12-15 17:57 UTC, jgsogo requested changes
Right now the policy is that we are not serving sources/binaries that original publishers are not serving themselves. I think this should be clear in this document.

If there is enough pressure to modify this policy we can escalate this petition and it can be reconsidered. So far, I think it is only #2850 the one being affected by this.

2020-12-15 17:57 UTC, jgsogo commented on docs/packaging_policy.md
> +- Library sources that are not publicly available will not be allowed in this repository even if the license allows their redistribution.
IMO these two points are the same: sources that are not accessible. 

We are not storing sources. The recommendation is to contact the publisher and ask them to provide the sources in a way/format that can be consumed programmatically.

2020-12-15 17:57 UTC, jgsogo commented on docs/packaging_policy.md
> +- In the remote case of having to package precompiled libraries, those should come from official sources like release/download webpages.
To add here (maybe reformulate together with the previous point): if binaries are not accessible the CTA is to contact the publisher and ask for a programmatically way to retrieve and consume those binaries.

If these binaries are needed as `build_requires` for some library, then we can write a `<app>/system` recipe and consider making those binaries available in the CI machines (if license let us install them) (#2850)

2020-12-15 18:12 UTC, madebr commented
What would be useful imho, is adding recipes for public sources/binaries, but that do not allow redistribution.
This would allow packaging binaries of Microsoft, which almost always forbid redistribution by some EULA.

c3i can check whether the recipe is correct, but no packages are uploaded to bintray.

2020-12-15 18:30 UTC, jgsogo commented
> What would be useful imho, is adding recipes for public sources/binaries, but that do not allow redistribution.
> This would allow packaging binaries of Microsoft, which almost always forbid redistribution by some EULA.
> 
> c3i can check whether the recipe is correct, but no packages are uploaded to bintray.

I've thought about it and maybe it makes sense to have a new type of recipe that retrieves the sources/binaries only on the consumer machine. A recipe with [`build_policy = always`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#build-policy)... and ConanCenter smart enough to not uploaded packages (but run the tests) for them.

Probably this deserves a new issue, and maybe some alignment with future Conan v2 to know if `build_policy` is the best approach for it or there will be something better.

2020-12-19 03:12 UTC, prince-chrismc commented on docs/packaging_policy.md
> +- Recipes should always build packages from library sources.
The spec writter in me :cursing_face: "should always"

```suggestion
- Recipes should build packages from library sources.
```

2020-12-28 17:11 UTC, danimtb commented
I have updated the policy with some suggestions and clarified the points under sections. I would like to move this forward as we really need to set these points in order to clarify the status of some pull requests. cc/ @SSE4 @uilianries

2020-12-28 17:39 UTC, prince-chrismc approved these changes

2020-12-28 17:50 UTC, madebr approved these changes

2020-12-28 18:13 UTC, SSE4 commented on docs/packaging_policy.md
> +  as a system recipe (`<build_require>/system``) and making those binaries available in the CI machines (if the license allows it).
```suggestion
  as a system recipe (`<build_require>/system`) and making those binaries available in the CI machines (if the license allows it).
```

2020-12-28 18:13 UTC, SSE4 approved these changes
LGTM

2020-12-29 15:56 UTC, prince-chrismc approved these changes

2020-12-29 15:57 UTC, merged