ezc3d: add version 1.3.8
conan-io/conan-center-index pull request #3943
Opened 2020-12-17 21:33 UTC by qchateau

Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-12-18 06:40 UTC, theirix requested changes
Need to export `EZC3D_SHARED` in package_info

2020-12-18 08:54 UTC, SSE4 approved these changes

2020-12-18 08:54 UTC, SSE4 requested changes
please add macro

2020-12-18 08:55 UTC, jgsogo approved these changes
This PR is adding a version, we can modify the `conanfile.py` in the next one.

2020-12-18 11:29 UTC, uilianries approved these changes

2020-12-18 18:25 UTC, madebr approved these changes

2020-12-18 20:30 UTC, theirix submitted a review, later dismissed

2020-12-19 20:32 UTC, intelligide submitted a review, later dismissed

2020-12-20 08:54 UTC, SpaceIm commented
> 
> 
> Need to export `EZC3D_SHARED` in package_info

No, it's already defined in a header file: https://github.com/pyomeca/ezc3d/blob/7d40969ac2ee08ec4092504fc937d5f49e40e745/include/ezc3dConfig.h.in#L4

2020-12-20 08:57 UTC, SpaceIm commented on recipes/ezc3d/all/conandata.yml
> +      base_path: "source_subfolder"
```suggestion
```

2020-12-20 08:59 UTC, SpaceIm commented on recipes/ezc3d/all/conandata.yml
> +      base_path: "source_subfolder"
this patch was submitted to upstream and is included in 1.3.8:
https://github.com/pyomeca/ezc3d/blob/Release_1.3.8/CMakeLists.txt
https://github.com/pyomeca/ezc3d/blob/Release_1.3.8/include/ezc3dConfig.h.in

2020-12-20 09:05 UTC, SpaceIm requested changes

2020-12-20 09:05 UTC, SpaceIm commented on recipes/ezc3d/all/conandata.yml
> +      base_path: "source_subfolder"
```suggestion
```

this patch was submitted to upstream and is included in 1.3.8:
https://github.com/pyomeca/ezc3d/blob/Release_1.3.8/CMakeLists.txt
https://github.com/pyomeca/ezc3d/blob/Release_1.3.8/include/ezc3dConfig.h.in

See those warnings in logs:

```
[1m[33mWARN: patches/fix-export-symbols.patch: file 1/2:	 b'CMakeLists.txt'[0m
[1m[33mWARN: patches/fix-export-symbols.patch:  hunk no.1 doesn't match source file at line 43[0m
[1m[33mWARN: patches/fix-export-symbols.patch:   expected: b'    add_library(${PROJECT_NAME} SHARED ${SRC_LIST})'[0m
[1m[33mWARN: patches/fix-export-symbols.patch:   actual  : b'    set(EZC3D_SHARED TRUE)'[0m
[1m[33mWARN: patches/fix-export-symbols.patch: already patched  b'CMakeLists.txt'[0m
[1m[33mWARN: patches/fix-export-symbols.patch: file 2/2:	 b'include/ezc3dConfig.h.in'[0m
[1m[33mWARN: patches/fix-export-symbols.patch:  hunk no.1 doesn't match source file at line 4[0m
[1m[33mWARN: patches/fix-export-symbols.patch:   expected: b'// dllexport/import declaration'[0m
[1m[33mWARN: patches/fix-export-symbols.patch:   actual  : b'#cmakedefine EZC3D_SHARED'[0m
[1m[33mWARN: patches/fix-export-symbols.patch: already patched  b'include/ezc3dConfig.h.in'[0m
```

I recommend to always check diff between new version and last version in CCI.

2020-12-21 02:39 UTC, prince-chrismc approved these changes
@SpaceIm thank you for fixing upstream :heart:

https://github.com/pyomeca/ezc3d/commit/c7d98d71a088709d79e505b3726151eead2f3efd

2020-12-21 06:48 UTC, SSE4 approved these changes

2020-12-21 10:22 UTC, jgsogo approved these changes

2020-12-21 10:51 UTC, SpaceIm approved these changes

2020-12-21 11:32 UTC, merged