[boost] Allow apple-clang version 10 for nowide and C++ 11
conan-io/conan-center-index pull request #3977
Opened 2020-12-23 18:16 UTC by datalogics-kam

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-12-23 23:51 UTC, prince-chrismc submitted a review, later dismissed

2020-12-24 10:00 UTC, gocarlos submitted a review, later dismissed

2020-12-24 15:32 UTC, mathbunnyru submitted a review, later dismissed

2020-12-25 23:39 UTC, madebr commented
@datalogics-kam 
Can you perhaps take a look at https://github.com/conan-io/conan-center-index/issues/3992?

2020-12-28 10:15 UTC, SSE4 commented
the default mode of apple-clang 12 (and 10) is C++03:
```
lang++ -dM -E -x c++ /dev/null | grep __cplusplus
#define __cplusplus 199711L
```
you have to activate `cppstd` setting in order to use newer C++ standards (such as C++11), thus to get nowide building for apple clang

2020-12-28 10:16 UTC, SSE4 requested changes
this should probably return None for apple-clang instead of 10/12

2020-12-29 17:19 UTC, dmn-star commented
@SSE4 The default C++ language standard in apple clang 12 is gnu++14 (~C++14  with GNU specific extensions).

>man clang 

then search "default C++"

2020-12-29 17:35 UTC, SSE4 commented
> @SSE4 The default C++ language standard in apple clang 12 is gnu++14 (~C++14 with GNU specific extensions).
> 
> > man clang
> 
> then search "default C++"

Does it seem like documentation is lying? I can't compile C++14 code without passing `-std=c++14` explicitly.

2020-12-29 17:47 UTC, dmn-star commented
Trust no one. :-) Maybe Apple means XCode sets the option _gnu++14_ by default.

2021-01-06 07:51 UTC, SSE4 commented on recipes/boost/all/conanfile.py
> +            "apple-clang": 10,
```suggestion
```

2021-01-06 07:51 UTC, SSE4 commented on recipes/boost/all/conanfile.py
> +            "apple-clang": 10,
```suggestion
```

2021-01-06 14:22 UTC, prince-chrismc commented
That's really odd @SSE4 when I was looking into [this boost issue](https://github.com/conan-io/conan-center-index/pull/3999#issuecomment-754896271) I noticed in the logs that apple-clang 12 was the only one which had all of the C++ 11 features in the b2 output.

A developer who forgot the documentation... shocker xD!

2021-01-06 19:08 UTC, datalogics-kam commented
I agree with the changes; thanks @SSE4 and @uilianries!

This still produces a Boost that can use ICU for Boost.Locale for my test case, which results in the configuration listed in the description:

```
 conan create recipes/boost/all boost/1.74.0@kam/testing -o boost:i18n_backend=icu --build missing -pr apple-clang-10.0-macos-10.9 -e DEVELOPER_DIR=/Applications/Xcode-10.3.app/Contents/Developer -s compiler.cppstd=11
```

I see the CI errors have to do with not finding the fiber libraries in version 1.69.0. Perhaps that's fixed by #3999, and #4097 may be related. Shall I do a rebase?

We have a local workaround (prior recipe in our Artifactory), so there's time to coordinate efforts on Boost.

(Thanks for your patience. I was on winter holiday, and am still catching up with things...)

2021-01-07 06:52 UTC, SSE4 commented
I think this code line requires an else branch (to set `without_fiber=True` and others): https://github.com/conan-io/conan-center-index/blob/24d9bf71bfc5e697acd53fc3b35b25f2c2b50a18/recipes/boost/all/conanfile.py#L223
@madebr WDYT?

2021-01-07 12:00 UTC, dmn-star commented
Somehow I don't quite understand what you are trying to achieve. I do not know any compilers with practical relevance  (2021), which do not support c++11. Why not set -std=c++11/14  if it is not set on command line by default?

2021-01-07 12:26 UTC, SSE4 commented
> Somehow I don't quite understand what you are trying to achieve. I do not know any compilers with practical relevance (2021), which do not support c++11. Why not set -std=c++11/14 if it is not set on command line by default?
> 
> cc #4147

this is not about what the compiler supports. given compiler may support c++11 and even c++20. it's more about the default mode of the compiler (when you didn't pass `-std=c++<something>` at all).
IMO our default mode (no `cppstd` specified), should exactly match the compiler's default mode of operation, otherwise, it would be confusing for users (and may cause lots of troubles).
setting `-std=c++11/14` will be active if user passes `cppstd=11/14`.

2021-01-07 12:41 UTC, dmn-star commented
It is much more surprising when I use the conan libs (C++03) with XCode which sets c++14 by default (same for VS). :-)

2021-01-08 14:21 UTC, prince-chrismc commented
There's a few issues related to this topic, can you please restart the build


#4097
#4073
#4084
#3992

2021-01-08 16:08 UTC, dmn-star commented
No reason to hurry.  It still can not be compiled.

2021-01-08 19:55 UTC, dmn-star commented
Ok. ok. So far it "compiles" as expected. 😂 

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : building
    - coroutine                : building
    - date_time                : building
    - exception                : building
    **- fiber                    : not building**
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : building
    **- json                     : not building**
    - locale                   : building
    - log                      : building
    - math                     : building
    - mpi                      : not building
    **- nowide                   : not building**

2021-01-08 23:27 UTC, datalogics-kam commented
@SSE4 I believe this PR now satisfies your review request change.

2021-01-09 02:26 UTC, madebr approved these changes

2021-01-09 06:22 UTC, dmn-star commented
maybe i'm wrong but your changes tell me nowide can't be compiled with any apple compiler anymore.

2021-01-09 15:30 UTC, datalogics-kam commented
> maybe i'm wrong but your changes tell me nowide can't be compiled with any apple compiler anymore.

It can be compiled if you set `compiler.cppstd=11` or higher. Here's the boost configuration with my test case build from above, which has `compiler.cppstd=11` set.

```
Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : building
    - coroutine                : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - mpi                      : not building
    - nowide                   : building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - stacktrace               : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building
```

Part of what the changes do is to remove the pre-emptive "your compiler doesn't support nowide" error, even _if_ cppstd is set to 11.

2021-01-09 16:12 UTC, dmn-star commented
> It can be compiled if you set `compiler.cppstd=11` or higher. Here's the boost configuration with my test case build from above, which has `compiler.cppstd=11` set.

Worked as designed. If there are no opportunities for improvement, we will stop using Conan/CCI for Mac dev.

2021-01-09 16:20 UTC, dmn-star commented on recipes/boost/all/conanfile.py
>              "gcc": 6,
The default mode is C++98 for GCC versions prior to 6.1, and C++14 for GCC 6.1 and above.

2021-01-09 16:20 UTC, dmn-star commented on recipes/boost/all/conanfile.py
> -            "apple-clang": 12,  # guess
"apple-clang": 8,

2021-01-09 16:23 UTC, dmn-star commented on recipes/boost/all/conanfile.py
>              "gcc": 6,
#Minimum compiler version having c++ standard >= 11 at 135

 # Minimum compiler version uses c++ standard >= 11 by default

2021-01-09 20:30 UTC, dmn-star commented
The boost packages on CCI are  without nowide, fiber, numa, json, right?

2021-01-09 22:08 UTC, prince-chrismc commented
> The boost packages on CCI are without nowide, fiber, numa, json, right?

The logs have not be uploaded yet (boost is huge and it takes time)

We'll need to wait before we can check them.

@SSE4 since you are following this PR, do you know if (the community) can pull packages from the internal "conan-upstream" remote?

2021-01-09 22:25 UTC, dmn-star commented
1)  self.settings.compiler.cppstd is not set on CCI
     
 2) version_cxx11_standard_json = self._min_compiler_version_default_cxx11 is null ( apple-clang removed from _min_compiler_version_default_cxx11)

   3)             self.options.without_fiber = True
                self.options.without_json = True
                self.options.without_nowide = True

        # nowide requires a c++11-able compiler + movable std::fstream: change default to not build on compiler with too old default c++ standard or too low compiler.cppstd
        # json requires a c++11-able compiler: change default to not build on compiler with too old default c++ standard or too low compiler.cppstd
        if self.settings.compiler.cppstd:
            if not tools.valid_min_cppstd(self, 11):
                self.options.without_fiber = True
                self.options.without_nowide = True
                self.options.without_json = True
        else:
            version_cxx11_standard_json = self._min_compiler_version_default_cxx11
            if version_cxx11_standard_json:
                if tools.Version(self.settings.compiler.version) < version_cxx11_standard_json:
                    self.options.without_fiber = True
                    self.options.without_json = True
                    self.options.without_nowide = True
            else:
                self.options.without_fiber = True
                self.options.without_json = True
                self.options.without_nowide = True

2021-01-10 05:49 UTC, SSE4 commented
> 1. self.settings.compiler.cppstd is not set on CCI

this is a WIP, we're going to add `cppstd` into CCI. probably not all of them, but only the most used and stable ones. right now, users who need to specify custom `cppstd` will have to build from source (the same as for every custom build settings or options).

2021-01-10 05:50 UTC, SSE4 commented
> @SSE4 since you are following this PR, do you know if (the community) can pull packages from the internal "conan-upstream" remote?

I don't think so, AFAIK this is the only temporary repository that exists for a short period of time, and then removed to avoid wasting CI resources (disk space).

2021-01-10 05:51 UTC, SSE4 commented
> The boost packages on CCI are without nowide, fiber, numa, json, right?

I think so, as well as without MPI, python, stack trace and several other libraries

2021-01-10 05:54 UTC, SSE4 commented
@danimtb @jgsogo can you take a look why the build was marked as failed, while conan center bot reports success?

2021-01-10 09:13 UTC, dmn-star commented
right now, users who need to specify custom `cppstd` will have to build from source (the same as for every custom build settings or options).

you know my point of view #8304. Rethink you "default" choice, not use apple-clang in prehistoric c++003 mode. Set cppstd=14 for apple-clang in boost recipe and the problem is fixed. And this safe, also because no one use apple-clang on command line.

2021-01-10 17:27 UTC, datalogics-kam commented
> Set cppstd=14 for apple-clang (12) in boost recipe and the problem is fixed. And this is safe also because no one use apple-clang on command line.

We're using apple-clang 10 at the moment, and from the command line. And while you _can_ use an IDE to build our code, it's primarily built from the command line, from CMake projects.

Also, I don't think the language standard should be hardcoded in this recipe. Whatever gets passed to B2 should be from `compiler.cppstd`, or something from Conan itself that's also sent to Conan's built-in build helpers. That way, developers can be assured that the compiler is set up the same way for all the requirements in a build.

2021-01-11 11:48 UTC, dmn-star commented
I would wonder if you have not set the same c++ standard in your CMake projects that is set in Xcode 10. But agreed, the default c++ standard should rather be set everywhere by Conan itself.

2021-01-20 12:39 UTC, jgsogo commented
About the `compiler.cppstd`: right now in conan-center-index we use whatever is the default for Conan, the reason is that we expect people installing Conan to be able to consume packages from ConanCenter without modifying anything. You install Conan, you run `conan install boost/1.74.0` and you get a package. This is one value proposition we can't change.

Nevertheless, we talked to the hierarchy, and we are allowed to burn more resources if needed. So the plan is to generate packages for other `compiler.cppstd` values (and this is absolutely needed to fix some recipes, I refer you to [this pull-request to read some dramatization about it](https://github.com/conan-io/examples/pull/73)). It is almost decided to generate those extra packages, but there are some caveats:
 * time: the more packages we generate, the more it takes to the CI to create all the packages, the more a contributor needs to wait for feedback in a pull-request.
 * random failures: from time to time we get a random failure from a build, compilation fails (memory, node failure, restarts,...). The more packages, the more choices of these failures.
 * graph and dependencies: to activate new configurations we need to be sure that all requirements have already been generated for those configurations, otherwise your PR will fail because of missing dependencies. We are already facing this problem trying to generate all the packages for some compilers (apple-clang 12.0 and modern gcc and clang in Linux). It is taking too much time and new references and revisions arrive and we need to start from the beginning again and again. We need to improve this process before adding new configurations.

Maybe the answer is not to generate ALL, but only some of the `compiler.cppstd` combinations. We are starting to gather information about the configurations requested by users in ConanCenter (https://github.com/conan-io/conan/pull/8046), we expect to have some data before taking that decision (we need other teams to provide us with that information).

2021-01-20 12:43 UTC, SSE4 approved these changes

2021-01-20 12:44 UTC, jgsogo approved these changes

2021-01-20 13:01 UTC, merged

2021-01-20 13:30 UTC, dmn-star commented
@jgsogo Yes you will need the packages, but they are not actually consumable  from Xcode. Because Xcode passes c++14 as standard by default.

2021-01-20 13:32 UTC, dmn-star commented
And the next boost version can anyway no longer be in C++03 mode at all.