Update conanfile.py
conan-io/conan-center-index pull request #4018
Opened 2020-12-29 14:40 UTC by ShuangLiu1992

if arch is not x86 and x86_64, the deleted option self.options.enable_fat will cause error

Specify library name and version: gmp/6.2.0

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2020-12-29 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4018) it.</sub>

2020-12-29 16:44 UTC, Croydon commented on recipes/gmp/all/conanfile.py
> +                del self.options.disable_assembly
```suggestion
        if self.options.get_safe("enable_fat"):
            del self.options.disable_assembly
```

2020-12-29 16:45 UTC, uilianries commented on recipes/gmp/all/conanfile.py
> +                del self.options.disable_assembly
```suggestion
        if self.options.get_safe("enable_fat"):
            del self.options.disable_assembly
```

2020-12-29 16:46 UTC, uilianries commented on recipes/gmp/all/conanfile.py
> +                del self.options.disable_assembly
same suggestion, at same time haha

2020-12-29 16:47 UTC, uilianries commented
@ShuangLiu1992 Thank you for your hotfix. Could you please add your name on #4. EAP is a requirement for any PR.

2020-12-29 17:25 UTC, theirix approved these changes

2020-12-31 11:34 UTC, ShuangLiu1992 commented
https://github.com/conan-io/conan-center-index/issues/4#issuecomment-752185317

2021-01-06 14:48 UTC, prince-chrismc requested changes
Please apply a suggestion from above

2021-01-07 11:15 UTC, Croydon approved these changes

2021-01-07 14:45 UTC, prince-chrismc approved these changes

2021-01-07 17:32 UTC, SSE4 approved these changes

2021-01-07 18:02 UTC, merged