Bump dataframe/1.15.0
conan-io/conan-center-index pull request #4051
Opened 2021-01-01 18:21 UTC by theirix

Specify library name and version:  **dataframe/1.15.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-01-01 18:23 UTC, Croydon submitted a review, later dismissed

2021-01-01 22:32 UTC, prince-chrismc approved these changes

2021-01-02 11:17 UTC, dmn-star submitted a review, later dismissed

2021-01-02 15:44 UTC, hosseinmoein approved these changes

2021-01-02 15:54 UTC, hosseinmoein commented
I closed the other conflicting PR

2021-01-05 15:34 UTC, hosseinmoein commented
Is there any resolution as to why this is not building?
Thanks

2021-01-08 13:24 UTC, hosseinmoein commented
@Croydon , @prince-chrismc ,
Is there anything we can do to move this forward?
Thanks

2021-01-08 14:31 UTC, prince-chrismc requested changes

2021-01-08 14:31 UTC, prince-chrismc commented on recipes/dataframe/all/conanfile.py
> +                    self.name, compiler, tools.Version(self.settings.compiler.version.value)
```suggestion
                    self.name, compiler, tools.Version(self.settings.compiler.version)
```

2021-01-08 16:12 UTC, prince-chrismc commented
You'll need to restart it again

2021-01-08 18:04 UTC, theirix commented
> You'll need to restart it again

didn't help

2021-01-08 18:37 UTC, prince-chrismc commented
Status is in progress... it's doing something  now

2021-01-09 14:11 UTC, hosseinmoein approved these changes

2021-01-09 14:28 UTC, prince-chrismc approved these changes

2021-01-09 19:58 UTC, SpaceIm approved these changes

2021-01-10 15:29 UTC, mathbunnyru approved these changes

2021-01-11 21:10 UTC, hosseinmoein commented
@prince-chrismc , @SpaceIm , @mathbunnyru 
Is this mergeable now?
Thanks,

2021-01-11 22:35 UTC, prince-chrismc commented
#2857 Has some details about what's required for merging, but we are missing one for the CCI team...

Please be patient they are doing their best to keep up with all the PRs we get

2021-01-11 23:20 UTC, mathbunnyru commented
Sorry, I'm not official community reviewer, just trying to help the CCI team when I can.

2021-01-12 16:53 UTC, SSE4 approved these changes

2021-01-13 01:32 UTC, merged