(#4248) fix in CPR with WinSSL
conan-io/conan-center-index pull request #4255
Opened 2021-01-14 13:35 UTC by rdeterre

Specify library name and version:  **cpr/1.5.2**

Here is the pull request that follows issue #4248

I moved the validation code to the `validate()` method. Not sure If I got it right though.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-01-14 13:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4255) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4255) before we can accept your contribution.<br/><hr/>**Romain Deterre** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4255) it.</sub>

2021-01-15 03:45 UTC, rdeterre commented
I'm not sure what's the right approach to solve this. Should I just patch CPR v1.3's CMakeLists.txt to add something like `set(ignored ${CMAKE_EXPORT_NO_PACKAGE_REGISTRY})`?

2021-01-16 00:00 UTC, prince-chrismc commented
😖 There's no error in the logs

```txt
cpr/1.3.0 (test package): Running test()

----Running------
> bin\test_package
-----------------
status code: 200
headers:     application/json; charset=utf-8
text:        {
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```

2021-01-16 00:05 UTC, prince-chrismc commented
close the PR wait 10s and re-open... let's see if it was random 🤞

2021-01-16 15:56 UTC, rdeterre commented
It seems to fix v1.3.0 but now v1.4.0 is broken, that seems random indeed ;)

2021-01-16 17:41 UTC, prince-chrismc commented
No I think the order might be inconsistent, it tries to do as many versions at once, it's just reporting the first failure

#4261

It might be related to https://github.com/conan-io/conan-center-index/pull/4255/files#diff-aead6257abe8f2d3a654ab6c01f99d3205fea85e598215f04953b3193f6c0b87R106-R107 being moved 🤔

2021-01-16 17:43 UTC, prince-chrismc requested changes
let's try to revert some changes... I think the new method is a little too new

2021-01-16 17:43 UTC, prince-chrismc commented on recipes/cpr/all/conanfile.py
> +            raise ConanInvalidConfiguration("Visual Studio build for shared library with MT runtime is not supported")
```suggestion
```

2021-01-16 17:43 UTC, prince-chrismc commented on recipes/cpr/all/conanfile.py
```suggestion

        if self.options.get_safe("with_winssl", False) and self.settings.os != "Windows":
            raise ConanInvalidConfiguration("cpr only supports winssl on Windows")

        if self.options.get_safe("with_openssl", False) and self.options.get_safe("with_winssl", False):
            raise ConanInvalidConfiguration("cpr can not be built with both openssl and winssl")

        if self.settings.compiler == "Visual Studio" and self.options.shared and "MT" in self.settings.compiler.runtime:
            raise ConanInvalidConfiguration("Visual Studio build for shared library with MT runtime is not supported")

```

2021-01-16 18:53 UTC, prince-chrismc commented
🤞

2021-01-18 20:45 UTC, rdeterre commented
I tried removing `validate()` completely but the build still breaks. I can't see the details of the error, but is there anything I can try to fix this?

2021-01-18 21:02 UTC, prince-chrismc commented
CCI has issues at times... when theres no message from the bot. Your best best is to restart CI

You can open close... rename title or edit the top level comment

2021-01-18 22:39 UTC, prince-chrismc approved these changes

2021-01-19 05:38 UTC, SSE4 approved these changes

2021-01-20 15:52 UTC, intelligide approved these changes

2021-01-20 20:31 UTC, uilianries approved these changes

2021-01-21 08:31 UTC, merged