Add TCLAP v1.2.3
conan-io/conan-center-index pull request #4389
Opened 2021-01-27 21:54 UTC by xguerin

Specify library name and version:  **tclap/1.2.3**

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-01-27 21:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4389) it.</sub>

2021-01-29 04:39 UTC, prince-chrismc requested changes
Along with all the comments... If you could please take a look at the docs https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#the-version-folders

Please rename the folder from `1.2.3` to `all` since this project is very unlikely to change over time

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +    license = "MIT License"
Please you the SPDX short identifiers

```suggestion
    license = "MIT"
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +    version = "1.2.3"
```suggestion
```

You can set the version at the command line `conan create conanfile.py 1.2.3@`

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +    exports_sources = ["include/*"]
```suggestion

    @property
    def _source_subfolder(self):
        return "source_subfolder"
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +        tools.get(**self.conan_data["sources"][self.version])
```suggestion
        tools.get(**self.conan_data["sources"][self.version])
         os.rename(self.name + "-" + self.version, self._source_subfolder)
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +        self.copy("*.h", "include", src_folder + "/include")
https://github.com/xguerin/tclap/blob/6689a6109700390d61c44298181da7e73fab7dae/tclap.pc.in#L4

```suggestion
        self.copy("COPYING", src=self._source_subfolder, dst="licenses")
        self.copy(pattern="*", src=os.path.join(self._source_subfolder, "include"), dst="include", keep_path=True)

    def package_info(self):
        self.cpp_info.names["pkg_config"] = "tclap"
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/conanfile.py
> +
```suggestion

    def package_id(self):
        self.info.header_only()

```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/test_package/conanfile.py
> +            self.run(os.path.join("bin", "test"), run_environment=True)
```suggestion
        if not tools.cross_building(self.settings):
            bin_path = os.path.join("bin", "test_package")
            self.run(bin_path, run_environment=True)
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/test_package/conanfile.py
> +
```suggestion
```

2021-01-29 04:39 UTC, prince-chrismc commented on recipes/tclap/1.2.3/test_package/CMakeLists.txt
> +set_target_properties(test_tclap PROPERTIES OUTPUT_NAME "test")
```suggestion
add_executable(test_package test.cpp)
target_link_libraries(test_package CONAN_PKG::tclap)
```

2021-01-29 23:15 UTC, prince-chrismc commented
Please try to avoid force pushing it makes reviewing much more difficult

2021-01-29 23:16 UTC, prince-chrismc approved these changes

2021-01-30 06:54 UTC, theirix requested changes

2021-01-30 06:54 UTC, theirix commented on recipes/tclap/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0)
```suggestion
cmake_minimum_required(VERSION 3.1)
```

2021-01-30 14:16 UTC, prince-chrismc approved these changes

2021-01-31 08:29 UTC, SSE4 approved these changes

2021-02-01 17:47 UTC, uilianries approved these changes

2021-02-01 18:02 UTC, merged