Update reviewing.md
conan-io/conan-center-index pull request #4430
Opened 2021-01-31 02:36 UTC by prince-chrismc

Docs!

I've added two bullet points for the test package which I find I repeat fairly often.

Feedback always welcomed!

2021-01-31 08:27 UTC, SSE4 submitted a review, later dismissed

2021-02-01 17:19 UTC, uilianries commented on docs/reviewing.md
> +When components are defined in the `packge_info` in `conanfile.py` tthe following conditions are desired
```suggestion
When components are defined in the `packge_info` in `conanfile.py` the following conditions are desired
```

2021-02-01 17:19 UTC, uilianries reviewed
Great! Thanks @prince-chrismc !

2021-02-01 17:20 UTC, uilianries approved these changes
LGTM

2021-02-01 18:26 UTC, intelligide requested changes

2021-02-01 18:26 UTC, intelligide commented on docs/reviewing.md
> +When components are defined in the `packge_info` in `conanfile.py` the following conditions are desired
```suggestion
When components are defined in the `package_info` in `conanfile.py` the following conditions are desired
```

2021-02-01 19:47 UTC, prince-chrismc commented
I swear when I speak in English it sounds like the words which I can not spell 🗣️

2021-02-02 03:11 UTC, intelligide approved these changes

2021-02-02 08:46 UTC, SSE4 approved these changes

2021-02-03 13:48 UTC, uilianries approved these changes

2021-02-03 14:01 UTC, merged