[zlib] Remove auto tools logic
conan-io/conan-center-index pull request #4502
Opened 2021-02-07 12:54 UTC by anton-dirac

Putting this one out there :)

Makes the recipe possible to use when cross building from Windows.
Also fixes cross build of 1.2.8 on iOS/watchOS/tvOS

If this is not feasible for some reason two things needs to be fixed:

1. `1.2.8` Needs the same fix as `1.2.11`. Use CMake if  `str(self.settings.os) in ["iOS", "watchOS", "tvOS"]`
2. Both recipes need to select CMake/Autotools based on `self.settings_build.os` not `self.settings.os` to work properly when cross building.

If this PR is rejected I can make the two fixes above instead.

Specify library name and version:  **zlib/1.2.8** **zlib/1.2.11**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-10 11:15 UTC, SSE4 commented
let's simplify 1.2.11 only in this PR. then, as a next PR, 1.2.8 may use the same dir as 1.2.11.

2021-02-10 14:17 UTC, dmn-star commented
And I thought I was the only one who tries to cross compile for Android on Windows. :-)

2021-02-11 09:17 UTC, anton-dirac commented
> And I thought I was the only one who tries to cross compile for Android on Windows. :-)

Haha, I hear you 😄!

2021-02-13 06:07 UTC, prince-chrismc submitted a review, later dismissed

2021-02-13 07:02 UTC, SSE4 commented
zlib is kinda vital and fundamental, I gonna test these changes with platforms not covered by CCI (Android, iOS, MinGW, clang-cl, etc.) and report

2021-02-15 18:33 UTC, intelligide approved these changes

2021-02-16 08:00 UTC, SSE4 commented
iOS (armv7/armv8) - OK
Android (armv7/armv8) - OK

2021-02-17 12:15 UTC, dmn-star submitted a review, later dismissed

2021-02-18 08:26 UTC, SSE4 commented
MSYS2 - OK
MSYS2 MinGW32 - OK
MSYS2 MinGW64 - OK
clang-cl - OK
Cygwin - OK
I need someone to test Intel C++, @danimtb , do you still have one?
otherwise, I'd say it's good to be merged.

2021-02-18 08:29 UTC, SpaceIm commented
I guess you can also remove those lines to completly remove autotools logic in this recipe:

```python
        if not tools.os_info.is_windows:
            configure_file = os.path.join(self._source_subfolder, "configure")
            st = os.stat(configure_file)
            os.chmod(configure_file, st.st_mode | stat.S_IEXEC)
```

2021-02-18 08:30 UTC, SSE4 requested changes
hold request changes to prevent accidental merge before we test everything

2021-02-18 09:49 UTC, SpaceIm commented
Maybe not in this PR, but I think that 1.2.8 and 1.2.11 should be merged in the same folder, diff is really anecdotal in terms of build system.

2021-02-18 10:36 UTC, anton-danielsson commented
@SpaceIm 
Thanks! I missed that more stuff could be removed :) Fixed now.

I agree that 1.2.8 should also be fixed and then the recipes can be merged to one folder.
However, CCI doesn't seem to allow that two recipes change in the same PR:
> Only one library can be changed in the same PR: [zlib/1.2.11, zlib/1.2.8]

If this PR is merged I plan to update 1.2.8 as well and merge them to one folder.
But it has to be done in several steps I guess?

2021-02-18 15:50 UTC, danimtb commented
Sorry, I cannot test it with Intel compiler but if CI works then we should be ok.

2021-02-18 15:57 UTC, jgsogo commented
Great to see it works with the new compilers too: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/4502/4/zlib/1.2.11//summary.json

2021-02-18 15:58 UTC, SSE4 approved these changes

2021-02-18 16:45 UTC, prince-chrismc approved these changes

2021-02-19 12:50 UTC, dmn-star approved these changes

2021-02-19 14:14 UTC, intelligide approved these changes

2021-02-19 14:31 UTC, merged