sentry-native: add version 0.4.7
conan-io/conan-center-index pull request #4525
Opened 2021-02-10 04:59 UTC by sotoahsAlto

Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **sentry-native/4.7**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-23 18:12 UTC, mathbunnyru commented
@sotoahsAlto  could you please ask to add you to the EAP here?
#4

2021-02-23 18:12 UTC, mathbunnyru approved these changes

2021-02-23 21:31 UTC, uilianries approved these changes

2021-03-16 16:23 UTC, ericriff commented
This version is already on conan/master. Furthermore this pr https://github.com/conan-io/conan-center-index/pull/4913 adds an even newer version.

This should be closed :)

2021-03-16 17:31 UTC, mathbunnyru requested changes
Thanks, @ericriff. Declined my review (I can't close PRs myself)

2021-05-14 07:56 UTC, closed without merging