Add recipe for libusb/hidapi
conan-io/conan-center-index pull request #4547
Opened 2021-02-12 12:23 UTC by Jihadist

Specify library name and version:  hidapi/0.10.1 hidapi/0.10.0 hidapi/0.9.0

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-12 12:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4547) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4547) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4547) it.</sub>

2021-02-12 15:23 UTC, Jihadist commented
**Windows**: 0.9.0 cannot build with .vcproj directly so I remove this version. 0.10.0 provides full back compability with 0.9.0 so there is no reason to install older library. 

**Unix**: 
```
[Installing package: hidapi/0.10.0
Requirements
    hidapi/0.10.0 from local cache - Cache
    libusb/1.0.24 from 'conan-center' - Cache
Packages
    hidapi/0.10.0:0114ceff673f5254d496d14b2aa6e2022bc465af - Build
    libusb/1.0.24:a19e97fe6b80c9260c53f0624a793ebe3a192404 - Cache]
```
But configure cannot find libusb
checking for libusb... no
```
  Library libusb-1.0 was not found on this system.
  Please install it and re-run ./configure
```
What i did wrong?

2021-02-16 02:31 UTC, prince-chrismc requested changes

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conandata.yml
> +    sha256: "68FEBD416CB6E6E6E205C9DD46A6F86F0D5A9808B7CD8C112906CD229889B8E1"
There no need for older versions

```suggestion
```

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +    license = "BSD-Style"
Yikes this is complicated https://github.com/libusb/hidapi/blob/master/LICENSE.txt

https://spdx.org/licenses/BSD-3-Clause.html https://spdx.org/licenses/GPL-3.0-or-later

```suggestion
    license = "GPL-3.0-or-later", "BSD-3-Clause", "HIDAPI"
```

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +            self.requires("libusb/[~=1.0]")
This needs to be an exact version for CCI

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +            self.requires("libusb/[~=1.0]")
These two do no match

maybe allow FreeBSD above and use `self.options.get_safe("...")` ?

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +        msbuild.build("%s/windows/hidapi.vcxproj" % self._source_subfolder,
Please use `os.path.join`

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +        autotools = self._configure_autotools()
This looks like a conflict 😕

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +        self.copy("*.a", dst="lib", keep_path=False)
```suggestion
    def package(self):
        autotools.install()
        tools.rmdir(os.path.join(self.package_folder, "lib", "pkgconfig"))
        tools.rmdir(os.path.join(self.package_folder, "share"))
        tools.remove_files_by_mask(os.path.join(self.package_folder, "lib"), "*.la")
```

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/all/conanfile.py
> +        if self.settings.os == "Linux":
I see there's a `pkgconfig` file being deleted you need to explicitly set it here

2021-02-16 02:31 UTC, prince-chrismc commented on recipes/hidapi/config.yml
> +    folder: all
```suggestion
  "0.10.1":
    folder: all
```

2021-02-16 10:04 UTC, Jihadist commented on recipes/hidapi/all/conanfile.py
> +        self.copy("*.a", dst="lib", keep_path=False)
Thanx for this, i didn't think about it

2021-02-16 14:31 UTC, prince-chrismc commented
I can not see the failure in the logs, you'll need to test it locally

2021-05-06 22:54 UTC, closed without merging