Replace controversial 'Lena' test image with popular alternative 'peppers'
conan-io/conan-center-index pull request #4619
Opened 2021-02-19 17:29 UTC by ericriff

See https://github.com/conan-io/conan-center-index/issues/4609

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-19 17:37 UTC, ericriff commented
Why does 2 version of the same library count as 2 separate libraries? :(

2021-02-19 18:25 UTC, prince-chrismc commented
it's two different recipes

2021-02-19 18:30 UTC, Croydon commented
Best case scenario would be a test that does not need a binary file in git

2021-02-19 18:32 UTC, ericLemanissier commented
Conan-center-index should allow this situation, because it is really no different than modifying a single conanfile which builds several version. In both case there can be no requirement relation between the packages to build, so the order of build does not matter.

2021-02-19 18:35 UTC, mathbunnyru submitted a review, later dismissed
Let's update the code a little bit, if you're changing the lines.

2021-02-19 18:35 UTC, mathbunnyru commented on recipes/opencv/2.x/test_package/conanfile.py
> +            self.run("%s %s %s" % (bin_path, res_path,peppers), run_environment=True)
```suggestion
            self.run("{} {} {}".format(bin_path, res_path, peppers), run_environment=True)
```

2021-02-19 18:35 UTC, mathbunnyru commented on recipes/opencv/3.x/test_package/conanfile.py
> +            self.run("%s %s %s" % (bin_path, res_path,peppers), run_environment=True)
```suggestion
            self.run("{} {} {}".format(bin_path, res_path, peppers), run_environment=True)
```

2021-02-19 18:57 UTC, ericriff commented
So whatever approach we take, I have to split this into 2 PRs then?

2021-02-19 19:04 UTC, mathbunnyru commented
Yep, I think the fastest way to get this merged is to create 2 different PRs.

2021-02-19 19:04 UTC, mathbunnyru approved these changes

2021-02-19 19:12 UTC, uilianries requested changes
Please, remove png files and keep test more simple.

2021-02-19 20:52 UTC, ericriff commented
I reverted the changes on 3.x (will open another PR later), got rid of the peppers image on 2.x and replaced the test_package with one similar to the one on 4.x, which doesn't use an image.

2021-02-19 20:57 UTC, mathbunnyru submitted a review, later dismissed
test_package is bigger than usual, but that's fine by me.

2021-02-19 20:57 UTC, mathbunnyru commented on recipes/opencv/2.x/test_package/test_package.cpp
> +#define w 400
meh

2021-02-19 21:04 UTC, ericriff commented
> test_package is bigger than usual, but that's fine by me.

I know, I usually include a couple of headers and call a function. Just check for include dirs and linking. But I wanted to be consistent with what we have on 4.x.

This is a copy/pase of openCV official code.

2021-02-19 21:05 UTC, mathbunnyru commented
> > test_package is bigger than usual, but that's fine by me.
> 
> I know, I usually include a couple of headers and call a function. Just check for include dirs and linking. But I wanted to be consistent with what we have on 4.x.
> 
> This is a copy/pase of openCV official code.

Oh, I see.
Yes, having consistent code is a good thing.
Thanks for the reply.

2021-02-22 15:12 UTC, SSE4 approved these changes

2021-02-22 16:37 UTC, uilianries approved these changes
Great! Thank you!!

2021-02-22 17:19 UTC, mathbunnyru approved these changes

2021-02-23 00:01 UTC, merged