cassandra-cpp-driver: fix cpp_info.libs
conan-io/conan-center-index pull request #4621
Opened 2021-02-19 18:13 UTC by ericLemanissier

flagged by conan-io/hooks#273

Specify library name and version:  **lib/1.0**

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-19 18:25 UTC, prince-chrismc submitted a review, later dismissed

2021-02-19 18:52 UTC, uilianries approved these changes

2021-02-19 19:09 UTC, SpaceIm commented
you can also update boost, libuv and http_parser

2021-02-19 19:11 UTC, mathbunnyru requested changes
I do agree with @SpaceIm.
Let's update other libs as well (to not create one more revision later).

2021-02-19 20:53 UTC, prince-chrismc commented
The PR merging is blocked so it's a good time to sneak it in

2021-02-19 20:58 UTC, mathbunnyru approved these changes

2021-02-19 21:11 UTC, SpaceIm approved these changes

2021-02-20 01:06 UTC, prince-chrismc approved these changes

2021-02-20 22:22 UTC, intelligide approved these changes

2021-02-21 05:27 UTC, SSE4 approved these changes

2021-02-21 05:31 UTC, merged