Fix broken armv8 builds my making 32-bit building option explicit
conan-io/conan-center-index pull request #4653
Opened 2021-02-23 14:08 UTC by ralfholly

Specify library name and version:  **lib/1.0**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

# Reason for change
Currently, all builds for armv8 (like Raspberry PI 4, NVIDIA Jetson) fail because of a check that makes no sense for armv8 platforms. The CMake option BENCHMARK_BUILD_32_BITS is automatically set to ON if the settings.arch string doesn't contain the number "64". This can never be the case if settings.arch == "armv8" (which is a 64-bit platform). Hence, on armv8 platforms, BENCHMARK_BUILD_32_BITS is always on, which during compilation leads to the use of the '-m32' compiler switch. This switch is not supported by gcc, so the building with gcc on armv8 is not possible. This is a BIG BIG BIG problem!

# Change
After the fix, the CMake BENCHMARK_BUILD_32_BITS option is not derived from the value of the settings.arch string. If a user wants a 32-bit build, they have to manually set the option "build_32_bits" to set the corresponding CMake option "BENCHMARK_BUILD_32_BITS".

2021-02-23 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4653) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4653) it.</sub>

2021-02-23 14:12 UTC, ralfholly commented
@Croydon We already had a discussion about this on the benchmark repo.

2021-02-23 16:49 UTC, mathbunnyru requested changes
Maybe a better default option would be something like this?

```
        arch64 = ['x86_64', 'sparcv9', 'ppc64', 'ppc64le', 'armv8', 'armv8.3', 'mips64']
        bits = "64" if self.settings.arch in arch64 else "32"
```

2021-02-23 16:49 UTC, mathbunnyru commented on recipes/benchmark/all/conanfile.py
> +    default_options = {"shared": False, "fPIC": True, "enable_lto": False, "enable_exceptions": True, "build_32_bits": False}
```suggestion
    default_options = {
        "shared": False,
        "fPIC": True,
        "enable_lto": False,
        "enable_exceptions": True,
        "build_32_bits": False
    }
```

2021-02-23 16:49 UTC, mathbunnyru commented on recipes/benchmark/all/conanfile.py
>          # See https://github.com/google/benchmark/pull/638 for Windows 32 build explanation
```suggestion
```

2021-02-23 17:45 UTC, ralfholly commented
> Maybe a better default option would be something like this?
> 
> ```
>         arch64 = ['x86_64', 'sparcv9', 'ppc64', 'ppc64le', 'armv8', 'armv8.3', 'mips64']
>         bits = "64" if self.settings.arch in arch64 else "32"
> ```

IMHO, the underlying CMakeLists.txt uses an explicit option to enable 32-bit builds and so should the conanfile. Your solution solves the immediate problem, but the arch64 list needs maintenance.

2021-02-23 17:54 UTC, mathbunnyru commented
> > Maybe a better default option would be something like this?
> > ```
> >         arch64 = ['x86_64', 'sparcv9', 'ppc64', 'ppc64le', 'armv8', 'armv8.3', 'mips64']
> >         bits = "64" if self.settings.arch in arch64 else "32"
> > ```
> 
> IMHO, the underlying CMakeLists.txt uses an explicit option to enable 32-bit builds and so should the conanfile. Your solution solves the immediate problem, but the arch64 list needs maintenance.

Sorry, I chose a very bad explanation.

What I meant is to still add the explicit version (to follow the upstream CMake), like you did, but for the cases, where we know for sure we need 32 bits, we might want to change the default value to True.
To do that, it's possible to add `config_options` method, which will set `build_32_bits` to True, when we are sure that we want 32bits version (for example, "x86" arch).
This will allow building this recipe with default settings under "x86" architecture.

2021-02-24 05:41 UTC, ralfholly commented
> > > Maybe a better default option would be something like this?
> > > ```
> > >         arch64 = ['x86_64', 'sparcv9', 'ppc64', 'ppc64le', 'armv8', 'armv8.3', 'mips64']
> > >         bits = "64" if self.settings.arch in arch64 else "32"
> > > ```
> > 
> > 
> > IMHO, the underlying CMakeLists.txt uses an explicit option to enable 32-bit builds and so should the conanfile. Your solution solves the immediate problem, but the arch64 list needs maintenance.
> 
> Sorry, I chose a very bad explanation.
> 
> What I meant is to still add the explicit version (to follow the upstream CMake), like you did, but for the cases, where we know for sure we need 32 bits, we might want to change the default value to True.
> To do that, it's possible to add `config_options` method, which will set `build_32_bits` to True, when we are sure that we want 32bits version (for example, "x86" arch).
> This will allow building this recipe with default settings under "x86" architecture.

Thanks for your feedback. Honestly, I have no strong opinion on that. To me, and possibly many, many other developers working on armv8-based projects, the most important thing is that we get rid of this nasty build-breaker as soon as possible.

2021-02-24 18:03 UTC, ralfholly commented
This is related to newly created issue #4677

2021-02-24 18:25 UTC, mathbunnyru commented
@ralfholly to get this merged, you will still have to apply to EAP (only after this PRs are tested in the CI).

So, please, ask to be included in EAP here:
https://github.com/conan-io/conan-center-index/issues/4

And, please, apply my review suggestions - this will not slow down the merging of this PR.

2021-02-24 19:00 UTC, SpaceIm commented
I disagree with this modification, while agree that something is wrong in previous revision of this recipe.
I would not add an option, just turn off this CMakeList option unconditionally to not enter in this branch https://github.com/google/benchmark/blob/5c43112eb3d70cec10784d8d1f4373bc7397836b/CMakeLists.txt#L97.
flags related to arch should come from conan profile. We do not have to mimic all upstream options, specially when they violate conan paradigm.

2021-02-25 07:00 UTC, ralfholly commented
> I disagree with this modification, while agree that something is wrong in previous revision of this recipe.
> I would not add an option, just turn off this CMakeList option unconditionally to not enter in this branch https://github.com/google/benchmark/blob/5c43112eb3d70cec10784d8d1f4373bc7397836b/CMakeLists.txt#L97.
> flags related to arch should come from conan profile. We do not have to mimic all upstream options, specially when they violate conan paradigm.

Makes sense to me! How do we go about this? Shall I close this PR and create a new one?

2021-02-28 09:20 UTC, mathbunnyru commented
Please, use this PR (do not create new one), it will be easier.

2021-02-28 16:22 UTC, mathbunnyru approved these changes

2021-03-01 21:25 UTC, SpaceIm approved these changes

2021-03-02 02:13 UTC, prince-chrismc approved these changes
Murdering 32-bit support? Sign me up!

2021-03-03 09:56 UTC, ralfholly commented
Hmm, I do have three approvals, but it looks like the approvers must also have write access.

2021-03-03 14:02 UTC, prince-chrismc commented
> Hmm, I do have three approvals, but it looks like the approvers must also have write access.

I am on my phone but in the docs we have "review process" that has all the details about how it works. It should not be long (theres a lot of prs recently)

2021-03-03 14:34 UTC, mathbunnyru commented
https://github.com/conan-io/conan-center-index/blob/a433dd4cc628384bf6500d73e6f860e35affa49d/docs/review_process.md#rule-of-3-reviews

> but it couldn't be just 3 community reviews

right now there are only 3 community reviewers.

2021-03-03 16:58 UTC, uilianries approved these changes

2021-03-03 17:31 UTC, merged

2021-03-03 18:15 UTC, ralfholly commented
Thanks to everyone helping me getting this done!