new ldns recipe
conan-io/conan-center-index pull request #4667
Opened 2021-02-24 10:47 UTC by fcelda

Specify library name and version:  **ldns/1.7.1**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-03-10 14:35 UTC, prince-chrismc commented on recipes/ldns/all/conanfile.py
> +    version = "1.7.1"
This can be passed at the command line `conan create all/conanfile.py 1.7.1@`

```suggestion
```

2021-03-10 14:39 UTC, prince-chrismc requested changes
A few small comments

2021-03-10 14:39 UTC, prince-chrismc commented on recipes/ldns/all/conanfile.py
> +            os.remove(la_file)
We have a Conan help for this, `tools.remove_file_by_mask`

2021-03-10 14:39 UTC, prince-chrismc commented on recipes/ldns/all/test_package/CMakeLists.txt
> +pkg_check_modules(LDNS REQUIRED "ldns")
there likely needs to be some logic in the `package_info()` to setup the components

2021-04-09 19:03 UTC, uilianries commented on recipes/ldns/all/conanfile.py
> +import os.path
```suggestion
```

2021-07-30 09:13 UTC, fcelda commented
Thank you all for review. I'm gonna close this as there are some build issues related to OpenSSL detection and it just doesn't work cross-platform with Conan. I will work with upstream to get this fixed. Until then, I think it doesn't make sense to keep this open.

2021-07-30 09:13 UTC, closed without merging