gtsam/4.0.3 native fix
conan-io/conan-center-index pull request #4686
Opened 2021-02-25 20:40 UTC by blackliner

Specify library name and version:  **gtsam/4.0.3**

adding a new option `with_march_native` that makes it possible to disable passing `-march=native`. Default behavior is untouched.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-02-25 20:45 UTC, ameysutavani approved these changes
Looks good! Thanks for adding an option for possibility of non-native builds.

2021-02-25 20:47 UTC, parik-lum approved these changes
Looks good!!!

2021-02-25 20:48 UTC, rounakluminar approved these changes
Thanks!

2021-02-25 20:52 UTC, SpaceIm commented
Shouldn't this upstream option be always disabled? Injection of `-march=native` in CFLAGS and CXXFLAGS should come from conan profile, not from a specific option in a recipe.

2021-02-25 21:04 UTC, blackliner commented
> Shouldn't this upstream option be always disabled? Injection of `-march=native` in CFLAGS and CXXFLAGS should come from conan profile, not from a specific option in a recipe.
> Moreover, `-march=native` should never be passed by default to produce pre build binaries in CCI.

fully agree, we are working on a PR there as well.

I thought about disabling it within conan, but did not want to change default behavior. Shall we make it OFF by default in this recipe?

2021-02-25 21:09 UTC, SpaceIm commented
IMOO, yes, this CMakeList option should always be disabled, even if it doesn't honor upstream default behavior. I believe that compilers optimization flags should come from conan profile (expect when underlying build system has more logic than just adding a compiler flag), specially when they can generate non portable binaries !

2021-02-25 21:23 UTC, blackliner commented on recipes/gtsam/all/conanfile.py
> +                        "with_march_native": True,
```suggestion
                        "with_march_native": False,
```

2021-02-25 21:26 UTC, ameysutavani submitted a review, later dismissed

2021-02-25 21:27 UTC, parik-lum approved these changes

2021-02-25 21:28 UTC, SpaceIm requested changes
if consumers want `-march=native` (and it's the only thing that `GTSAM_BUILD_WITH_MARCH_NATIVE` does), they can add it in CFLAGS or CXXFLAGS.

2021-02-25 21:28 UTC, SpaceIm commented on recipes/gtsam/all/conanfile.py
> +               "with_march_native": [True, False],
```suggestion
```

2021-02-25 21:28 UTC, SpaceIm commented on recipes/gtsam/all/conanfile.py
> +                        "with_march_native": False,
```suggestion
```

2021-02-25 21:28 UTC, SpaceIm commented on recipes/gtsam/all/conanfile.py
> +            self._cmake.definitions["GTSAM_BUILD_WITH_MARCH_NATIVE"] = self.options.with_march_native
```suggestion
            self._cmake.definitions["GTSAM_BUILD_WITH_MARCH_NATIVE"] = False
```

2021-02-26 12:25 UTC, SpaceIm approved these changes

2021-02-26 13:00 UTC, SSE4 approved these changes
agree, things like `-march=native` or `-mtune=native` break reproducibility IMO

2021-02-26 16:13 UTC, uilianries approved these changes

2021-02-26 16:28 UTC, parik-lum approved these changes

2021-02-26 18:31 UTC, merged