Bump odbc to 2.3.9
conan-io/conan-center-index pull request #4703
Opened 2021-02-27 07:12 UTC by sourcedelica

Fixes #4702

Specify library name and version:  **odbc/2.3.9**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

The existing patch for 2.3.7 didn't apply and it looks like the fix may have been made upstream but I'm not 100% clear on the intention of the patch.  

@SpaceIm, could you take a look?  The upstream fix is https://github.com/lurcher/unixODBC/commit/ca226e2e94f68ef7eee5ed9b6368f6550e3ecd56#diff-1bf1faa7ca7b442fc9abf362144fb1848e66b29b8849ca9a8e86b85085db93d1R187.  If not could you let me know what the intention is and how to validate a patch for it? (perhaps in the `test_package`).   Thanks!

2021-02-27 08:45 UTC, SpaceIm commented
If 2.3.9 builds with apple-clang 12 without a patch, then it's fine.

2021-02-27 14:10 UTC, mathbunnyru requested changes
@sourcedelica the issue it that you forget to update config.yml:
https://github.com/conan-io/conan-center-index/blob/master/recipes/odbc/config.yml
You need to add version here as well.

2021-02-27 14:11 UTC, mathbunnyru commented
After that we'll see if it works in CI without a patch. If it is, then it's great 👍

2021-02-27 15:42 UTC, sourcedelica commented
Whoops - fixed.  I built is Apple clang 12 locally so it's looking postive.

2021-02-27 15:49 UTC, mathbunnyru approved these changes

2021-02-27 16:25 UTC, SpaceIm approved these changes

2021-02-27 18:06 UTC, prince-chrismc approved these changes

2021-02-27 20:17 UTC, intelligide approved these changes

2021-02-28 05:36 UTC, SSE4 approved these changes

2021-02-28 06:01 UTC, merged

2021-02-28 06:36 UTC, sourcedelica commented
Thanks guys!