nspr: fix apple silicon cross compilation
conan-io/conan-center-index pull request #4770
Opened 2021-03-03 08:16 UTC by timblechmann

conan-1.33 adds `-arch arm64` to the cflags. this breaks the compilation
of nspr, which correctly adds the `-arch` flags

fixes: #4692

Specify library name and version:  **nspr**

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-03-03 15:22 UTC, uilianries approved these changes

2021-03-05 00:22 UTC, prince-chrismc approved these changes

2021-03-05 18:48 UTC, mathbunnyru requested changes
Maybe this should be fixed in conan itself?
`conan-1.33 adds -arch arm64 to the cflags. this breaks the compilation`

2021-03-05 19:24 UTC, timblechmann commented
> Maybe this should be fixed in conan itself?
> `conan-1.33 adds -arch arm64 to the cflags. this breaks the compilation`

maybe not: https://github.com/conan-io/conan-center-index/issues/4692#issuecomment-786707046
🤷

2021-03-06 13:06 UTC, mathbunnyru commented
> > Maybe this should be fixed in conan itself?
> > `conan-1.33 adds -arch arm64 to the cflags. this breaks the compilation`
> 
> maybe not: [#4692 (comment)](https://github.com/conan-io/conan-center-index/issues/4692#issuecomment-786707046)
> 🤷

Oh, I see. It's the build system of the library, which causes the problem, not conan adding some flags.
So, yes, this is the right place to have a fix.

2021-03-06 13:08 UTC, mathbunnyru approved these changes
In general, it would be great to have it fixed in the upstream, to make it future-proof.
So, if you want to, you can send a patch to the upstream which will resolve the issue for future versions.

2021-03-06 13:10 UTC, mathbunnyru commented
I see, that there is already an issue https://bugzilla.mozilla.org/show_bug.cgi?id=1658671
And the status is `RESOLVED FIXED`, so everything seems to be great 👍

2021-03-06 14:31 UTC, merged

2021-03-06 14:53 UTC, timblechmann commented
> I see, that there is already an issue https://bugzilla.mozilla.org/show_bug.cgi?id=1658671
> And the status is `RESOLVED FIXED`, so everything seems to be great 👍

this issue is about apple silicon support (configuring with `--build=x86_64-apple-darwin --host=aarch64-apple-darwin`). but it's not about a frontend injecting architecture flags via CFLAGS.
so this patch is here to stay