ixwebsocket: add version 11.0.8 and 11.0.9
conan-io/conan-center-index pull request #4832
Opened 2021-03-10 04:33 UTC by liboyue

Specify library name and version:  **ixwebsocket/11.0.8** and **ixwebsocket/11.0.9**

@prince-chrismc  I updated the OpenSSL, now you can close https://github.com/conan-io/conan-center-index/pull/4828 and merge this pr. The 11.0.8 is a "major" release according to the author, so I added it too. Thanks!

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-03-10 04:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=4832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=4832) it.</sub>

2021-03-10 13:56 UTC, prince-chrismc requested changes
We try to avoid adding older versions, since they are almost never used.

If you specifically need that version that's acceptable as well!

2021-03-10 13:56 UTC, prince-chrismc commented on recipes/ixwebsocket/all/conandata.yml
> +    sha256: "5d02fa5a23427e07326b4bbd285479aabb18fa2e1d47c05a676523ae4d6a4dca"
```suggestion
```

2021-03-10 13:56 UTC, prince-chrismc commented on recipes/ixwebsocket/config.yml
> +    folder: all
```suggestion
```

2021-03-10 15:39 UTC, liboyue commented
Thanks for the comment. However, as in the release page https://github.com/machinezone/IXWebSocket/releases, 11.0.8 is still labeled as "latest", and I was using 11.0.8 too. So I guess it may be better to add this version.

2021-03-10 18:23 UTC, prince-chrismc commented
If you look at the release history the mainters have been very inconsistent at creating proper GitHub releases but the tags and teh official changlog have all the versions https://machinezone.github.io/IXWebSocket/CHANGELOG/#1109-2021-03-07

I also noticed this going through the repro
https://github.com/machinezone/IXWebSocket/commit/ee5a2eb46ee0e109415dc02b0db85a9c76256090
Please please adjust this in the recipe

2021-03-10 18:57 UTC, liboyue commented
Should I remove this check https://github.com/conan-io/conan-center-index/blob/master/recipes/ixwebsocket/all/conanfile.py#L51 since it does not have a minimum requirement or change it to `11`?

2021-03-10 21:56 UTC, prince-chrismc commented
Maybe?

`tools.check_min_cppstd(self, 14 if tools.Version(self.version) < "11.0.8" else 11)`

2021-03-11 01:03 UTC, prince-chrismc approved these changes

2021-03-11 01:04 UTC, prince-chrismc commented
Once a week new comments on the EAP issue are added automatically so it should not be too long before this can continue =)

2021-03-15 04:26 UTC, closed without merging