Add fake function framework (fff)
conan-io/conan-center-index pull request #5114
Opened 2021-04-01 15:50 UTC by kebadopp

Specify library name and version:  **fff/1.1.0**

This library is a header-only library and is a micro-framework for creating fake C functions for tests.
This library do not have dependencies to other libraries.
I am NOT the author of this library.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-01 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=5114) it.</sub>

2021-04-02 00:53 UTC, prince-chrismc requested changes
Please respect the original version semantics

2021-04-02 00:53 UTC, prince-chrismc commented on recipes/fff/all/conandata.yml
> +  "1.1.0":
```suggestion
  "1.1":
```

2021-04-02 00:53 UTC, prince-chrismc commented on recipes/fff/all/conanfile.py
> +        os.rename(extracted_dir, self._source_subfolder)
```suggestion
        tools.get(**self.conan_data["sources"][self.version], strip_root=True, destination=self._source_subfolder)
```

2021-04-06 12:58 UTC, prince-chrismc approved these changes
LGTM! 🚀

2021-04-06 13:24 UTC, SSE4 approved these changes

2021-04-06 18:02 UTC, uilianries approved these changes

2021-04-06 19:31 UTC, merged