Fix LGPL/BSD3 mismatch
conan-io/conan-center-index pull request #5195
Opened 2021-04-12 02:30 UTC by TobiSchluter

The conan package advertises its license as BSD-3-Clause but with default settings it is in fact LGPL. Fix this by disabling use_eigen_sparse by default. I will see about updating the Ceres documentation which isn't very clear about this.

Specify library name and version:  ceres-solver/2.0.0

I ran into this because the ceres-solver package doesn't compile if Eigen is configured with the MPL2_only option. I've submitted a patch to ceres to clarify the deocumentation with respect to the licensing issues. You can find it here https://ceres-solver-review.googlesource.com/c/ceres-solver/+/18580

I don't think it is desirable nor wise to advertise ceres as BSD-3 if the default build isn't. The other way out would be to update the license information but being more permissive is probably more useful on balance because, as I understand it, eigen_sparse is not used by default even if enabled, so the current default settings pull in LGPL code for no gain.

(I updated the pull request to make the author's email match my github account in order for it to understand that I signed the contributor agreement. In the process I've also rebased it on the current trunk.)

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-12 16:47 UTC, Croydon commented
I think it is better to add both licenses to the license attribute. We don't differentiate finer things like if packages are dual-licensed or if just some parts are under some license etc.

2021-04-13 03:19 UTC, TobiSchluter commented
For the record, the ceres developers acknowledged that the problem exists in the issue I linked to above. It seems to be due to a clerical issue on the Eigen side (where code was relicensed but isn't yet flagged as non-LGPL).

2021-04-13 14:49 UTC, uilianries requested changes
We cannot change it because it follow the project behavior:

https://github.com/ceres-solver/ceres-solver/blob/2.0.0/CMakeLists.txt#L167
https://github.com/ceres-solver/ceres-solver/blob/1.14.0/CMakeLists.txt#L130

Also, if we change it, we will break users, providing a different package behavior by default. If you need a new package, you have to build from sources.

About license, good point.

Version 1.14.0 used BSD-3-Clause only: https://github.com/ceres-solver/ceres-solver/blob/1.14.0/LICENSE

However, 2.0.0 has 3 different licenses (BSD-3-Clause, Apache-2.0 and MIT): https://github.com/ceres-solver/ceres-solver/blob/2.0.0/LICENSE

The only we can do is updating license attribute according Ceres' version:

```python
def configure(self):
    if tools.Version(self.version) >= "2.0.0":
        self.license = "BSD-3-Clause", "Apache-2.0", "MIT"
```

2021-04-14 06:02 UTC, TobiSchluter commented
@uilianries my point about the license is actually is that this doesn't appear to be correct: with default settings ceres-solver includes LGPL parts of Eigen. If you follow through to the request I made to the ceres developers about this (linked above), it seems to be a clerical error on the side of Eigen. Yet, if Eigen says that you are violating the license, I think it's best to err on the side of correctness.

I seem to have not said this, but the way to trigger this error is to use
 ceres-solver/2.0.0
 eigen/3.3.9
with option
 eigen:MPL2_only
and make sure that it actually builds the packages. This is going to fail because ceres references code in Eigen that is disabled by #define EIGEN_MPL2_ONLY

2021-04-14 12:02 UTC, uilianries commented
@TobiSchluter We follow the LICENSE files, we can not change it. Besides that, we import ALL license files, including from their dependencies. If you think it's incorrect, first the upstream should accept it and we will change, but according the version.

2021-04-16 01:50 UTC, TobiSchluter commented
Thank you. I understand that and why the policy is as it is. It is only after I sent this pull request and as the discussion on the ceres side went on that I understood that this seems to be a genuine mistake somewhere between Ceres and Eigen. I also understand why conan-center should rely on what ceres claim their license to be. As someone who cares about correct licensing though, it came as a surprise that the version of my code that I was about to send to my customer suddenly included LGPL stuff after I'd added a BSD3-licensed library.

I don't have a good solution to offer, though I don't see why setting use_eigen_sparse = False by default until these issues are clarified by upstream would be such a bad choice. Yes, changing default behavior is bad, but in this case it fixes a (legal) bug and doesn't affect most users of the library anyway (I believe the eigen_sparse stuff isn't used unless explicitly requested by the user at runtime)

2021-04-16 12:44 UTC, uilianries commented
We don't change default option values because users expect having the exactly same behavior when building package. The only exception is when a option is broken and the default package ID doesn't work. 

We can change it, of course, but first the upstream should do it.

2021-04-18 00:35 UTC, prince-chrismc commented
Their replies match up with the Git history https://github.com/ceres-solver/ceres-solver/commit/ea667ede5c038d6bf3d1c9ec3dbdc5072d1beec6

Technically speaking, one could argue the if ceres was built against a shared eigne 3.3.9 there's no LGPL issues....

CCI has the same issue with boost for example, the default options pull in an LGPL with `libiconv` so an "enterprise" consumer like myself can not use the static version provided by CCI.

This is by no means a rare case, so beware when installing =) OSS licensing it a rough sea.

***

Please follow https://github.com/conan-io/conan-center-index/pull/5195#pullrequestreview-634687781 at the bottom is one thing we can do to improve things (and please update the title)

2021-06-17 05:20 UTC, closed without merging