[open62541] Add version 1.1.6
conan-io/conan-center-index pull request #5211
Opened 2021-04-13 14:09 UTC by wbitesi

Specify library name and version:  **open62541/1.1.6**

New minor release of open62541/1.1.X. Only a minor update to the patch necessary (small CMakeLists.txt change in release 1.1.6 compared to 1.1.5).

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-23 12:31 UTC, prince-chrismc requested changes
Can you please rename the patches such that it's more obvious what the patches are for?

like `1_1_x.patch` --> `0001-fix-cmake-find-deps-1_1_x.patch` and `1_1_5.patch` to `0002-disable-sanitizers.patch`

2021-04-23 23:17 UTC, prince-chrismc approved these changes
Thank you so much!

2021-04-24 09:11 UTC, theirix approved these changes

2021-04-26 20:37 UTC, uilianries approved these changes

2021-04-26 23:31 UTC, merged