Fix Public Domain license for jpeg-compressor
conan-io/conan-center-index pull request #5294
Opened 2021-04-23 15:04 UTC by uilianries

Public Domain is not allowed: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-license-should-i-use-for-public-domain

Related to https://github.com/conan-io/hooks/pull/292

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-23 16:34 UTC, madebr submitted a review, later dismissed

2021-04-24 08:54 UTC, SSE4 approved these changes

2021-04-24 14:02 UTC, prince-chrismc requested changes
There's Intel code here thats MIT that was missed originally

2021-04-24 14:02 UTC, prince-chrismc commented on recipes/jpeg-compressor/all/conanfile.py
> +    license = "Unlicense", "Apache-2.0"
https://github.com/richgel999/jpeg-compressor/blob/aeb7d3b463aa8228b87a28013c15ee50a7e6fcf3/jpgd_idct.h#L1

```suggestion
    license = "Unlicense", "Apache-2.0", "MIT"
```

2021-04-24 20:37 UTC, prince-chrismc approved these changes

2021-04-24 22:21 UTC, madebr approved these changes

2021-04-26 16:06 UTC, SSE4 approved these changes

2021-04-27 15:01 UTC, merged