add soci 4.0.2 package
conan-io/conan-center-index pull request #5313
Opened 2021-04-24 20:38 UTC by spjuanjoc

Library name and version:  **soci/4.0.2**

Add the recently released version 4.0.2 to the existing SOCI package.
---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-25 00:39 UTC, prince-chrismc requested changes
Please try to use the conan tools

https://docs.conan.io/en/latest/reference/tools.html#tools-mkdir-tools-rmdir

2021-04-25 00:39 UTC, prince-chrismc commented on recipes/soci/all/conanfile.py
> +import shutil
```suggestion
```

2021-04-25 00:39 UTC, prince-chrismc commented on recipes/soci/all/conanfile.py
> +        shutil.rmtree(os.path.join(self.package_folder, "lib", "cmake"), ignore_errors=True)
```suggestion
        tools.rmdir(os.path.join(self.package_folder, "lib", "cmake"))
```

2021-04-25 00:43 UTC, prince-chrismc commented
For anyone reviewing after... I did not see any components, its just vendored module files that I found

2021-04-25 15:16 UTC, SSE4 approved these changes

2021-04-26 15:32 UTC, ericLemanissier approved these changes

2021-04-26 17:53 UTC, prince-chrismc approved these changes

2021-04-27 14:11 UTC, uilianries approved these changes

2021-04-27 18:31 UTC, merged