libwebsockets: add version 4.2.0
conan-io/conan-center-index pull request #5321
Opened 2021-04-25 18:07 UTC by prince-chrismc

Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)
Find more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-25 18:28 UTC, prince-chrismc commented
Only GCC-4.9 shared failed =/

2021-04-26 00:14 UTC, prince-chrismc commented
They all fail... did something change in the docker images?

2021-05-05 15:41 UTC, SSE4 approved these changes

2021-05-06 13:18 UTC, ericLemanissier submitted a review, later dismissed

2021-05-06 14:42 UTC, mathbunnyru requested changes

2021-05-06 14:42 UTC, mathbunnyru commented on recipes/libwebsockets/all/conanfile.py
> +                raise ConanInvalidConfiguration("{}/{} with clang>=12 does not build. Please submit a PR with a fix.".format(self.name, self.version))
```suggestion
                raise ConanInvalidConfiguration("{}/{} with apple-clang>=12 does not build. Please submit a PR with a fix.".format(self.name, self.version))
```

2021-05-07 00:04 UTC, mathbunnyru submitted a review, later dismissed

2021-05-07 12:10 UTC, uilianries commented on recipes/libwebsockets/all/conanfile.py
> +        if tools.Version(self.version) == "4.0.15" and self.settings.compiler == "apple-clang" and tools.Version(self.settings.compiler.version) >= "12":
```suggestion
        if tools.Version(self.version) <= "4.0.15" and self.settings.compiler == "apple-clang" and tools.Version(self.settings.compiler.version) >= "12":
```

2021-05-07 12:10 UTC, uilianries commented on recipes/libwebsockets/all/conanfile.py
> +        if self.options.shared and self.settings.compiler == "gcc" and tools.Version(self.settings.compiler.version) < "5":
```suggestion
    def validate(self):
        if self.options.shared and self.settings.compiler == "gcc" and tools.Version(self.settings.compiler.version) < "5":
```

2021-05-07 13:37 UTC, mathbunnyru approved these changes

2021-05-07 16:03 UTC, SSE4 approved these changes

2021-05-07 19:20 UTC, uilianries approved these changes
LGTM

2021-05-07 19:31 UTC, merged