libcurl: fix darwinssl option
conan-io/conan-center-index pull request #5357
Opened 2021-04-28 10:01 UTC by SpaceIm

Specify library name and version:  **lib/1.0**

closes https://github.com/conan-io/conan-center-index/issues/441

Perhaps, if we should also change darwinssl value to secure-transport in `with_ssl` recipe option, but it might break consumers.

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-04-28 10:12 UTC, SpaceIm commented
> Perhaps, we should also change darwinssl value to secure-transport in with_ssl recipe option, but it might break consumers.

I believe we can safely change this value, because darwinssl never worked in this recipe (configure would have failed to understand `--with-darwinssl`).

2021-04-28 13:34 UTC, SpaceIm commented
Actually, it's not really a "fix", with-darwinssl option is still there (for backward compatibility of configure script I guess), but it has the same effect than with-secure-transport option. But only with-secure-transport is documented now.

2021-04-29 16:08 UTC, SSE4 approved these changes

2021-04-29 21:36 UTC, prince-chrismc commented on recipes/libcurl/all/conanfile.py
> +            "--with-secure-transport={}".format(yes_no(self.options.with_ssl == "darwinssl")),
With `schannel` would this disable TLS?

2021-04-30 23:26 UTC, prince-chrismc commented on recipes/libcurl/all/conanfile.py
> +            "--with-secure-transport={}".format(yes_no(self.options.with_ssl == "darwinssl")),
https://github.com/curl/curl/blob/47e169e7a46dd0932ede5225768aa666730820f1/configure.ac#L196

2021-04-30 23:31 UTC, prince-chrismc requested changes
Doubled checked the other options when I saw this 

https://github.com/curl/curl/commit/68d89f242cf9f6326e3b2f6fe119b7c74ef41c66

> Removes: --with-winssl, --with-darwinssl and all --without-* options for
TLS libraries

We'll break on the next release https://github.com/conan-io/conan-center-index/blob/7601c64f15c5ef22f05758a905fab31a3a7d1123/recipes/libcurl/all/conanfile.py#L249

2021-04-30 23:33 UTC, madebr approved these changes

2021-05-02 18:38 UTC, prince-chrismc approved these changes

2021-05-02 19:01 UTC, merged