Add dtl/1.19 and dtl/cci.20210404
conan-io/conan-center-index pull request #5407
Opened 2021-05-03 13:33 UTC by LHLaurini

Specify library name and version:  dtl/1.19 and dtl/cci.20210404

This library is a dependency to one of my projects, which I intend to eventually also submit to the CCI.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-05-03 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=5407) it.</sub>

2021-05-08 16:02 UTC, prince-chrismc requested changes
Very close! great work, just a few minor tweaks

2021-05-08 16:02 UTC, prince-chrismc commented on recipes/dtl/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
```suggestion
cmake_minimum_required(VERSION 3.1)
```

2021-05-08 16:02 UTC, prince-chrismc commented on recipes/dtl/all/conanfile.py
> +        self.copy("dtl/*", dst="include", src="dtl")
Path separator should be cross platform =)

```suggestion
        self.copy(os.path.join("dtl", "*.hpp"), dst="include", src="dtl")
```

2021-05-08 16:09 UTC, LHLaurini commented
> Very close! great work, just a few minor tweaks

Thank you for the review. Changes accepted. Some of these were caused by a lack of attention, sorry for that 😄  (specially the wrong license name, forgot to look it up).

2021-05-08 20:51 UTC, prince-chrismc approved these changes
Sorry about the bad edit :p

2021-05-10 20:00 UTC, uilianries commented on recipes/dtl/all/conandata.yml
> +  "cci.20210404":
thank you.

2021-05-10 20:00 UTC, uilianries approved these changes

2021-05-12 08:42 UTC, SSE4 approved these changes

2021-05-12 11:31 UTC, merged