swig: don't use HAVE_UNISTD_H
conan-io/conan-center-index pull request #5430
Opened 2021-05-04 21:19 UTC by madebr

Specify library name and version:  **swig/all**

Fixes #5068

Don't use `HAVE_UNISTD_H` but use `/proc/self/exe` unconditionally on Linux, Macos and all BSD's.
If `/proc/self/exe` does not exist, then it will use the embedded path.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-05-06 08:03 UTC, SSE4 commented
I am not sure if it is right thing to do. e.g. detecting `unistd.h` existence and using `HAVE_UNISTD_H` should make code way more portable (in theory) to the systems you didn't list in the patch.

2021-05-14 12:38 UTC, datalogics-robb commented
> I am not sure if it is right thing to do. e.g. detecting `unistd.h` existence and using `HAVE_UNISTD_H` should make code way more portable (in theory) to the systems you didn't list in the patch.

AIX and Solaris are two platforms would be broken by this patch, and it seems that no case has been made for it - `unistd.h` is ubiquitous on UNIX and if the test for it is failing it shouldn't be fixed this way.

2021-05-24 07:53 UTC, SSE4 requested changes
sorry, but unfortunately I don't think the fix is correct.
it makes code less portable (as commented, for Solaris, AIX, maybe other platforms not listed, like IRIX or HP-UX). I guess HAVE_UNISTD_H detection should be fixed instead.

2021-05-24 14:47 UTC, madebr commented on recipes/swig/all/conanfile.py
> +                self.run("strings {}".format(os.path.join(self.package_folder, "bin", "swig")), run_environment=True)
Linux logs contain `/proc/self/exe` so everything seems fine.
```suggestion
```

2021-05-24 15:12 UTC, madebr commented
Perhaps the servers contain an outdated binary..

2021-05-24 16:39 UTC, jgsogo approved these changes

2021-05-24 17:29 UTC, uilianries approved these changes

2021-05-24 17:30 UTC, SSE4 approved these changes

2021-05-24 17:31 UTC, merged