Add args-parser library version 6.0.1.0.
conan-io/conan-center-index pull request #5499
Opened 2021-05-10 13:21 UTC by igormironchik

Specify library name and version:  **args-parser/6.0.1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

I'm the author of this library.

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-05-10 13:43 UTC, madebr commented on recipes/args-parser/6.0.0.0/conanfile.py
> +        self.info.header_only()
The settings object is reset by calling `self.info.header_only`.

https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/model/info.py#L575-L578


```suggestion
        self.info.header_only()
```

2021-05-10 13:51 UTC, madebr submitted a review, later dismissed

2021-05-10 13:54 UTC, uilianries submitted a review, later dismissed

2021-05-12 08:26 UTC, igormironchik commented
Please, don't approve this PR. I want to change it a little: add possibility to use `find_package()`. Will do it soon, just a few hours. Thanks.

2021-05-12 08:39 UTC, SSE4 approved these changes

2021-05-12 08:39 UTC, SSE4 requested changes
author asked not to approve

2021-05-12 10:23 UTC, igormironchik commented
@SSE4 Thank you. PR is ready to be reviewed.

2021-05-12 15:55 UTC, SSE4 approved these changes

2021-05-13 12:35 UTC, uilianries approved these changes

2021-05-14 13:32 UTC, czoido approved these changes

2021-05-14 14:01 UTC, merged

2021-05-15 09:04 UTC, SpaceIm commented on recipes/args-parser/6.0.1.0/conanfile.py
> +        )
It doesn't make sense here. This library never had a `args-parser` imported target.
6.0.0.0: `Args`
6.0.0.1: `args-parser::args-parser`

2021-05-15 09:05 UTC, SpaceIm commented on recipes/args-parser/6.0.1.0/test_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} args-parser)
`target_link_libraries(${PROJECT_NAME} args-parse::args-parser)`