sqlcipher: add 4.4.3 and requires openssl/1.1.1k
conan-io/conan-center-index pull request #5508
Opened 2021-05-10 18:48 UTC by shiena

fixed #5056 

Specify library name and version:  sqlcipher/4.4.3

sqlcipher 4.4.2 and below and openssl 1.1.1j and below are vulnerable.

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3119
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3450

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-05-18 22:43 UTC, prince-chrismc approved these changes

2021-05-20 17:03 UTC, mathbunnyru requested changes
Let's reuse patches from 4.4.2 if they don't actually change

2021-05-20 17:46 UTC, shiena commented
@mathbunnyru 
I used `tools.patch` and the `fuzz=True` option but it doesn't patch correctly. Probably there is a problem with https://github.com/conan-io/python-patch-ng/issues/19 .

2021-05-20 17:48 UTC, mathbunnyru approved these changes
Ok, if old patches do not work, then I'm ok with the new ones for the new version.

2021-05-22 14:08 UTC, SSE4 approved these changes

2021-05-22 14:31 UTC, merged