capnproto/0.7.0
conan-io/conan-center-index pull request #5591
Opened 2021-05-21 09:30 UTC by blackliner

Specify library name and version:  **capnproto/0.7.0**

Add support for the older version 0.7.0

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-05-21 17:52 UTC, blackliner commented
@prince-chrismc any advice on that symlink issue? Is this related to the recipe/build or something that might have changed since the introduction of this capnproto recipe?

2021-05-22 01:46 UTC, prince-chrismc commented
No expert here... I think you are missing this https://github.com/capnproto/capnproto/commit/fdbf035619ab2f9e25173bb7361e7e19a52e0fa1

0.7.0 https://github.com/capnproto/capnproto/blame/3f44c6db0f0f6c0cab0633f15f15d0a2acd01d19/c%2B%2B/src/capnp/CMakeLists.txt#L185

0.8.0

2021-05-22 10:05 UTC, SpaceIm commented
What about all the patches of 0.8.0? There is little chance that you could provide 0.7.0 without similar patches.

2021-05-22 18:30 UTC, blackliner commented
> What about all the patches of 0.8.0? There is little chance that you could provide 0.7.0 without similar patches.

It builds fine on my end with clang and gcc, so I wanted to know what the issue might be.

2021-05-23 11:25 UTC, blackliner commented
> No expert here... I think you are missing this [capnproto/capnproto@fdbf035](https://github.com/capnproto/capnproto/commit/fdbf035619ab2f9e25173bb7361e7e19a52e0fa1)
> 
> 0.7.0 https://github.com/capnproto/capnproto/blame/3f44c6db0f0f6c0cab0633f15f15d0a2acd01d19/c%2B%2B/src/capnp/CMakeLists.txt#L185
> 
> 0.8.0
> https://github.com/capnproto/capnproto/blame/57a4ca5af5a7f55b768a9d9d6655250bffb1257f/c%2B%2B/src/capnp/CMakeLists.txt#L189
> 
> The commit above changed the extension for windows.... which is what failed when looking for the file missing an extension ... make sense but I could be wrong

Thanks @prince-chrismc , that was it 👍

2021-05-23 12:55 UTC, prince-chrismc commented
> > What about all the patches of 0.8.0? There is little chance that you could provide 0.7.0 without similar patches.
> 
> It builds fine on my end with clang and gcc, so I wanted to know if that is required at all.

Sometimes build is not enough, we do not test everything so there's a little judgement we need to make... I am not familiar with this library, but naively I think make 1, 2, and 4 are important enough they are required for CCI

2021-06-04 18:18 UTC, blackliner commented
@prince-chrismc I added patch1 and 4, but 2 is not possible, as the compat stuff completely changed, and actually looks similar to how the result of the patch would look like

2021-06-04 20:43 UTC, prince-chrismc commented
Seems like KJ-gzip is just a c file not a library 🤔

2021-06-05 16:58 UTC, blackliner commented
@prince-chrismc I think its dead, Jim

2021-06-05 17:01 UTC, SpaceIm requested changes

2021-06-05 17:05 UTC, SpaceIm commented on recipes/capnproto/all/conanfile.py
> +        if self.options.get_safe("with_openssl"):
```suggestion
        if self.options.with_openssl:
```

2021-06-05 17:06 UTC, SpaceIm commented on recipes/capnproto/all/conanfile.py
>          ]
```suggestion
            "--with-openssl" if self.options.with_openssl else "--without-openssl",
            "--enable-reflection"
        ]
        if tools.Version(self.version) >= "0.8.0":
            args.append("--with-zlib" if self.options.with_zlib else "--without-zlib")
```

2021-06-05 17:06 UTC, SpaceIm commented on recipes/capnproto/all/conanfile.py
> +        if self.options.get_safe("with_openssl"):
```suggestion
        if self.options.with_openssl:
```

2021-06-05 17:24 UTC, prince-chrismc commented
Please do not force push! Github makes us restart reviewing 😭

2021-06-05 17:27 UTC, prince-chrismc reviewed
I assume TLS is important for this project, can you try Space's comments?

2021-06-05 17:56 UTC, SpaceIm commented on recipes/capnproto/all/conanfile.py
> +        self._cmake.definitions["WITH_OPENSSL"] = self.options.get_safe("with_openssl")
```suggestion
        self._cmake.definitions["WITH_OPENSSL"] = self.options.with_openssl
```

2021-06-05 18:34 UTC, blackliner commented
6fba328ef0a51f07737c42491cd37fa127e4502e was the commit where I only disabled zlib, but that was not enough, CI failed with a similar message as with zlib for TLS

2021-06-05 18:53 UTC, prince-chrismc commented
> [6fba328](https://github.com/conan-io/conan-center-index/commit/6fba328ef0a51f07737c42491cd37fa127e4502e) was the commit where I only disabled zlib, but that was not enough, CI failed with a similar message as with zlib for TLS

Well https://github.com/capnproto/capnproto/commit/7da6abf233fdf74a4ad4db56b6e98778b162dd7d

Was added 2 years after this old release.... I don't know why linux and mac pass....

2021-06-05 20:25 UTC, SpaceIm commented
Sure it fails, it requires similar patch than 0.8.0

2021-06-06 08:23 UTC, blackliner commented
> Sure it fails, it requires similar patch than 0.8.0: https://github.com/conan-io/conan-center-index/blob/3df626e745868dfdba5248cf58a3f8190dd157d7/recipes/capnproto/all/patches/0003-kj-tls-windows.patch

I dont need the TLS for 0.7.0, do yo insist on patching it for windows?

2021-06-06 12:16 UTC, prince-chrismc commented
Nope! Just can revert and either 
- add a fix me comment
- or throw when on and windows this way linux gets it

2021-06-06 12:52 UTC, SpaceIm commented
I would prefer to use the same patch than 0.8.0, it's easy and avoids to much complexity and weird logic in conanfile.

2021-06-07 14:36 UTC, prince-chrismc approved these changes

2021-06-07 17:56 UTC, uilianries approved these changes

2021-06-07 19:04 UTC, jgsogo approved these changes

2021-06-07 20:01 UTC, merged