submission to conancenter repository
conan-io/conan-center-index pull request #5785
Opened 2021-06-07 04:21 UTC by rtosman

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-07 04:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=5785) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=5785) it.</sub>

2021-06-08 13:38 UTC, madebr commented on recipes/asionet/config.yml
> +  folder: all
```suggestion
    folder: all
```

2021-06-08 13:40 UTC, madebr requested changes
This is missing a test package.
Please include a small cxx source using the asionet headers + build it.

2021-06-13 01:17 UTC, rtosman commented
> This is missing a test package.
> Please include a small cxx source using the asionet headers + build it.

Sorry, I am new to conancenter. Is the test supposed to be part of the library or part of the recipe?

I have a completely separate project that is the test for this library, but I was going to submit that once this was in, since it has a dependency on this library (obviously).

2021-06-15 23:58 UTC, ruilvo commented
> Sorry, I am new to conancenter. Is the test supposed to be part of the library or part of the recipe?
> 
> I have a completely separate project that is the test for this library, but I was going to submit that once this was in, since it has a dependency on this library (obviously).

My advice is for you to look at the other recipes :) The best place to start is to really use another recipe that's like yours, in this case, any that has "header_only" on it :) You'll see what is expected.

2021-06-30 18:18 UTC, ruilvo requested changes

2021-06-30 18:18 UTC, ruilvo commented on recipes/asionet/all/conanfile.py
> +    version = "1.5.0"
Please remove the version from the python script so that you can reuse it for other versions in the future.

2021-06-30 18:20 UTC, ruilvo commented
Please use more descriptive titles in PR submissions. And please fill out the fields in the PR creation:

> Specify library name and version: lib/1.0
> 
> This is also a good place to share with all of us why you are submitting this PR (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

This is really useful information.

2021-08-30 11:38 UTC, closed without merging