fix libmysqlclient compilation for cpp 17
conan-io/conan-center-index pull request #5823
Opened 2021-06-08 22:34 UTC by AndreyMlashkin

Specify library name and version:  **libmysqlclient/8.0.25**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-08 22:35 UTC, AndreyMlashkin commented
fixes https://github.com/conan-io/conan-center-index/pull/5677

2021-06-09 06:42 UTC, AndreyMlashkin commented
My changes only affect libmysqlclient/8.0.25, has someone a clue, why libmysqlclient/8.0.17 is failing now?
new conan version bug? sporadic issue?

2021-06-09 06:57 UTC, ericLemanissier commented
I have no idea, the build passed 6 days ago, and nothing changed on the recipe or its requirements since then. This is a mystery to me. Maybe just restart the build by closing/reopening the PR?

2021-06-09 10:24 UTC, AndreyMlashkin commented
still the same problem with v8.0.17.
Could someone investigate, what's wrong with the CI?

2021-06-10 11:23 UTC, ericLemanissier requested changes
@AndreyMlashkin I found the problem: by declaring a second "patches" key in conandata.yml, it removed all the patches of 8.0.17

2021-06-10 11:23 UTC, ericLemanissier commented on recipes/libmysqlclient/all/conandata.yml
> +patches:
```suggestion
```

2021-06-10 12:40 UTC, ericLemanissier approved these changes

2021-06-10 13:28 UTC, jgsogo approved these changes

2021-06-10 14:43 UTC, AndreyMlashkin commented
@SpaceIm @prince-chrismc
please, review

2021-06-10 16:31 UTC, prince-chrismc approved these changes

2021-06-10 17:01 UTC, merged