Add libltc 1.3.1
conan-io/conan-center-index pull request #5889
Opened 2021-06-14 13:31 UTC by MartinDelille

Specify library name and version:  **libltc/1.3.1**

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-14 13:32 UTC, MartinDelille commented
@x42 FYI

2021-06-15 16:06 UTC, ruilvo requested changes

2021-06-15 16:06 UTC, ruilvo commented on recipes/libltc/all/conanfile.py
> +        self._autotools = AutoToolsBuildEnvironment(self)
In the `argtable2` recipe (that I choose at random when searching for autotools in CCI), I found this:
```python
self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
```
Try adding that `win_bash=tools.os_info.is_windows` to the constructor too :)

2021-06-15 17:23 UTC, ruilvo commented
You need
```python
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
```

2021-06-15 17:35 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        os.rename(extracted_dir, self._source_subfolder)
```suggestion
    tools.get(**self.conan_data["sources"][self.version],
              destination=self._source_subfolder, strip_root=True)
```

2021-06-15 17:35 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        self._autotools.configure(args=args)
```suggestion
        self._autotools.configure(args=args, configure_dir=self._source_subfolder)
```

So you don't need chdir

2021-06-15 17:35 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +            autotools.make()
```suggestion
        autotools = self._configure_autotools()
        autotools.make()
```

2021-06-15 17:35 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +            autotools.install()
```suggestion
        autotools = self._configure_autotools()
        autotools.install()
```

2021-06-15 17:35 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        self.cpp_info.libs = ["ltc"]
```suggestion
        self.cpp_info.libs = ["ltc"]
        if self.settings.os == "Linux":
            self.cpp_info.system_libs = ["m"]
```

```
$ ldd /tmp/install/lib/libltc.so.11
	linux-vdso.so.1 (0x00007ffd19782000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f46bca4e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f46bc882000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f46bcbc4000)
```

2021-06-15 17:39 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +    def package_info(self):
```suggestion
    def package_info(self):
        self.cpp_info.names["pkg_config"] = "ltc"
```

https://github.com/x42/libltc/blob/v1.3.1/ltc.pc.in

2021-06-16 08:42 UTC, ruilvo commented
> libltc/1.3.1: WARN: Error running `configure --help`: Cannot recognize the Windows subsystem, install MSYS2/cygwin or specify a build_require to apply it

Yap, you'll need MSYS2 as a build dependency

2021-06-16 08:54 UTC, ruilvo requested changes

2021-06-16 08:54 UTC, ruilvo commented on recipes/libltc/all/conanfile.py
> +        if tools.os_info.is_windows and self.settings.compiler != "Visual Studio":
```suggestion
        if tools.os_info.is_windows and not tools.get_env("CONAN_BASH_PATH"):
```
You'll probably need it like this (I copied from other recipes).
And you'll need to set the environment to use the cl compiler,
From automake recipe:
```python
    @contextmanager
    def _build_context(self):
        if self.settings.compiler == "Visual Studio":
            with tools.vcvars(self.settings):
                with tools.environment_append({"CC": "cl -nologo", "CXX": "cl -nologo",}):
                    yield
        else:
            yield
```

2021-06-16 10:02 UTC, ruilvo commented
> checking for gcc... gcc
> checking whether the C compiler works... no
Yap, you have some flags to set :)

2021-06-16 13:25 UTC, MartinDelille commented
Windows debug build is still failing. Here is an extract from the logs:

```
libtool: compile:  /c/j/w/buildsinglereference@2/.conan/data/automake/1.16.2/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -DHAVE_CONFIG_H -I. -I/c/j/w/buildsinglereference@2/.conan/data/libltc/1.3.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/source_subfolder/src -Wall -Zi -Ob0 -Od -MTd -c -showIncludes /c/j/w/buildsinglereference@2/.conan/data/libltc/1.3.1/_/_/build/b2b69efcc79a149e0bc765fb12ba0278d52fc260/source_subfolder/src/decoder.c -o libltc_la-decoder.obj
decoder.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt.h(212): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

2021-06-16 13:35 UTC, ruilvo commented
At least it already started building, you're in the right track. Let's examine the logs.

2021-06-16 13:52 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +            args.extend(["--disable-shared", "--enable-static"])
```suggestion
            args.extend(["--disable-shared", "--enable-static"])
        if self.settings.compiler == "Visual Studio":
            self._autotools.cxx_flags.append("-EHsc")
            self._autotools.flags.append("-FS")
```

It fixes your problem with MTd

2021-06-16 14:55 UTC, uilianries commented
Almost there, the libraries names are different when built by msvc:

> ibltc/1.3.1 package(): Packaged 1 '.dll' file: ltc-11.dll
libltc/1.3.1 package(): Packaged 1 '.h' file: ltc.h
libltc/1.3.1 package(): Packaged 1 '.lib' file: ltc.dll.lib

2021-06-16 16:03 UTC, MartinDelille commented
Shall I rename them or change something in package_info()  ?

2021-06-16 16:36 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        self.cpp_info.libs = ["ltc"]
```suggestion
        self.cpp_info.libs = ["ltc.dll.lib"] if self.settings.compiler == "Visual Studio" and self.options.shared else ["ltc"]
```

2021-06-17 07:51 UTC, ruilvo commented
@MartinDelille can I ask you please to write something in the commit message other than default? I'm receiving notifications for this PR and it's hard to know what happened :)

2021-06-17 08:49 UTC, MartinDelille commented
@ruilvo Yes sorry I'll write more explicit message in the future! Sorry for the noise and thank you for your support with this recipe! 😄

2021-06-17 20:52 UTC, uilianries reviewed
Conan hooks is not happy with that name, let's use a regular library name

2021-06-17 20:52 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        self.cpp_info.libs = ["ltc.dll.lib"] if self.settings.compiler == "Visual Studio" and self.options.shared else ["ltc"]
```suggestion
        self.cpp_info.libs = ["ltc"]
```

2021-06-17 20:52 UTC, uilianries commented on recipes/libltc/all/conanfile.py
> +        os.unlink(os.path.join(self.package_folder, "lib", "libltc.la"))
```suggestion
        os.unlink(os.path.join(self.package_folder, "lib", "libltc.la"))
        if self.settings.compiler == "Visual Studio" and self.options.shared:
            tools.rename(os.path.join(self.package_folder, "lib", "ltc.dll.lib"),
                         os.path.join(self.package_folder, "lib", "ltc.lib")
```

2021-06-18 17:38 UTC, jgsogo approved these changes

2021-06-18 17:50 UTC, uilianries approved these changes
Finally working! :D

2021-06-20 13:53 UTC, prince-chrismc approved these changes

2021-06-20 14:32 UTC, merged

2021-06-20 15:30 UTC, MartinDelille commented
Thank you again for your kind help on this recipe!