gtest: remove obsolete defines and refactor recipe
conan-io/conan-center-index pull request #5898
Opened 2021-06-15 11:01 UTC by Nekto89

I've noticed that new googletest doesn't use GTEST_LANG_CXX11 and GTEST_HAS_TR1_TUPLE so I've decided to slightly improve recipe.

Check conan version for tools.get
Use remove_files_by_mask
Refactor call to patching
Move compiler checks to validate method
Use shorter lines and other small style changes
Remove GTEST_NO_MAIN which was doing nothing
Do not use GREATER_EQUAL - it is not present in CMake 2.8
Remove "conan" from topics

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-15 11:52 UTC, uilianries approved these changes

2021-06-15 13:29 UTC, prince-chrismc requested changes
Amazing work! One tiny detail

2021-06-15 13:29 UTC, prince-chrismc commented on recipes/gtest/all/conanfile.py
> +                if tools.Version(self.settings.compiler.version.value) >= "15":
```suggestion
                if tools.Version(self.settings.compiler.version) >= "15":
```

2021-06-15 14:44 UTC, uilianries approved these changes

2021-06-15 15:11 UTC, prince-chrismc approved these changes

2021-06-15 15:11 UTC, prince-chrismc commented
You'll need to retrigger CI, close the pr wait 10s and then re-open it 🔁

2021-06-16 14:59 UTC, SSE4 approved these changes

2021-06-16 15:02 UTC, merged