confu_json:  parsing  json to user defined type and vice versa
conan-io/conan-center-index pull request #5986
Opened 2021-06-19 11:43 UTC by werto87

Specify library name and version:  **confu_json/0.0.5**

# confu_json
## Helps you with parsing  json to user defined type and vice versa.

## How to:
  Define a boost fusion struct "https://www.boost.org/doc/libs/1_76_0/libs/fusion/doc/html/fusion/adapted/define_struct.html".
  
  Use to_json(object from your type) to create a json with the data from your type.
  
  Use to_object< your type >(json) to create an object from a json.
  
  
## Example:
  ```c++
  #include "confu_json/to_json.hxx"
  #include "confu_json/to_object.hxx"
  #include <boost/fusion/adapted/struct/adapt_struct.hpp>
  #include <boost/json/src.hpp>  // this file should be included only in one translation unit

  BOOST_FUSION_DEFINE_STRUCT((shared_class), Nested, (long, answer)) // used to define a struct

  int main() {
    using namespace confu_json;
    auto nested = shared_class::Nested{};
    nested.answer = 42;
    std::cout << to_json(nested) << std::endl; // converts the struct into json and prints it
    auto nestedTest = to_object<shared_class::Nested>(to_json(nested)); // converts the struct into json and back into an object
    assert(nested.answer == nestedTest.answer);
  }  
  ```
  Exampls for defining types: "https://github.com/werto87/confu_json/blob/main/test/constant.hxx"
  
  Exampls for usage: "https://github.com/werto87/confu_json/blob/main/test/combineToJsonAndToObject.cxx"

## This project builds on:
boost::json -> json handling 

boost::mpl and boost::fusion -> template metaprogramming

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-19 14:46 UTC, prince-chrismc requested changes

2021-06-19 14:46 UTC, prince-chrismc commented on recipes/confu_json/all/conanfile.py
> +    def configure(self):
```suggestion
    def validate(self):
```

2021-06-19 14:46 UTC, prince-chrismc commented on recipes/confu_json/all/conanfile.py
> +        os.rename(extracted_dir, self._source_subfolder)
```suggestion
        tools.get(**self.conan_data["sources"][self.version],
                  destination=self._source_subfolder, strip_root=True)
```

2021-06-19 14:46 UTC, prince-chrismc commented on recipes/confu_json/all/conanfile.py
> +class ConfuJson(ConanFile):
```suggestion
from conans.tools import Version

required_conan_version = ">=1.33.0"


class ConfuJson(ConanFile):
```

2021-06-19 14:46 UTC, prince-chrismc commented on recipes/confu_json/all/conanfile.py
> +        self.options["boost"].header_only = True
Let's not surprises the consumer 

```suggestion

    def configure(self):
        if not self.options["boost"].header_only:
            raise ConanInvalidConfiguration("{} requires a header-only Boost. ".format(self.name))
```

2021-06-19 14:46 UTC, prince-chrismc commented on recipes/confu_json/all/test_package/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
`cxx_Std_20` was added later.... this should be a hook

```suggestion
cmake_minimum_required(VERSION 3.12)
```

2021-06-19 20:32 UTC, prince-chrismc approved these changes

2021-06-20 17:20 UTC, jgsogo approved these changes

2021-06-21 05:58 UTC, SSE4 approved these changes

2021-06-21 09:32 UTC, merged