Initial package for crc_cpp, Version 1.0.0
conan-io/conan-center-index pull request #6086
Opened 2021-06-29 12:17 UTC by AshleyRoll

Specify library name and version:  **crc_cpp/1.0.0**

I am the author of the crc_cpp header only library and I would like to make it easily available for others to use. This is the initial release and I believe the API is stable.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-06-29 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=6086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=6086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=6086) it.</sub>

2021-06-30 16:28 UTC, theirix requested changes

2021-06-30 16:28 UTC, theirix commented on recipes/crc_cpp/all/conanfile.py
> +    def configure(self):
```suggestion
    def validate(self):
```

Those checks are better in `validate` method

2021-07-01 06:35 UTC, theirix approved these changes

2021-07-01 10:16 UTC, SSE4 approved these changes

2021-07-01 23:22 UTC, prince-chrismc approved these changes

2021-07-02 00:02 UTC, merged