add effcee recipe
conan-io/conan-center-index pull request #6133
Opened 2021-07-02 11:32 UTC by AndreyMlashkin

Specify library name and version:  **effcee/v2019.1@**

this lib is needed for creation a recipe for https://github.com/microsoft/DirectXShaderCompiler
---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-02 12:39 UTC, uilianries commented on recipes/effcee/all/conanfile.py
> +    license = "Apache 2.0"
```suggestion
    license = "Apache-2.0"
```

2021-07-02 12:39 UTC, uilianries commented on recipes/effcee/all/test_package/CMakeLists.txt
> +conan_basic_setup()
```suggestion
conan_basic_setup(TARGETS)
```

2021-07-02 12:39 UTC, uilianries commented on recipes/effcee/all/test_package/CMakeLists.txt
> +target_link_libraries(effcee-example ${CONAN_LIBS})
```suggestion
target_link_libraries(effcee-example effcee::effcee)
```

2021-07-04 21:41 UTC, AndreyMlashkin commented
Do someone have a clue, why mac-clang complains about the test package?

the enum is declared like:

namespace effcee {
...
class Result {
 public:
  enum class Status {
    Ok = 0,
    Fail,       // A failure to match
    BadOption,  // A bad option was specified
    NoRules,    // No rules were specified
    BadRule,    // A bad rule was specified
  };
...

Test code:

  auto result = effcee::Match(input_stream.str(), checks_stream.str(),
                              effcee::Options().SetChecksName("checks"));

  // Successful match result converts to true.
  if (result) {
    std::cout << "The input matched your check list!" << std::endl;
  } else {
    // Otherwise, you can get a status code and a detailed message.
    switch (result.status()) {
      case effcee::Result::Status::NoRules:
        std::cout << "error: Expected check rules as command line arguments\n";
        break;
      case effcee::Result::Status::Fail:
        std::cout << "The input failed to match your check rules:\n";
        break;
      default:
        break;
    }

/Users/jenkins/w/BuildSingleReference@2/conan-center-index/recipes/effcee/all/test_package/main.cc:54:12: error: expression is not an integral constant expression
      case effcee::Result::Status::Fail:

2021-07-05 08:01 UTC, AndreyMlashkin commented
What is the best way to force compiler to use at least cpp11 (the higher, the better)?

2021-07-08 19:21 UTC, prince-chrismc commented
> What is the best way to force compiler to use at least cpp11 (the higher, the better)?

conan-io/conan#8002 is my go to

2021-07-08 19:47 UTC, uilianries commented
> What is the best way to force compiler to use at least cpp11 (the higher, the better)?

https://github.com/conan-io/conan-center-index/blob/master/recipes/easyhttpcpp/all/CMakeLists.txt#L8

2021-07-08 19:53 UTC, uilianries commented on recipes/effcee/all/CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8.11)
```suggestion
cmake_minimum_required(VERSION 3.1)
```

The CI complains that you need to use Cmake 3.1 because of CMAKE_CXX_STANDARD

2021-07-08 21:34 UTC, prince-chrismc commented on recipes/effcee/all/conanfile.py
> +    settings = "cppstd", "os", "arch", "compiler", "build_type"
Its complaining about this too

```suggestion
    settings = "os", "arch", "compiler", "build_type"
```

2021-07-09 10:38 UTC, AndreyMlashkin commented
Why windows runtime for test package is not taken from conan?...

2021-07-09 14:25 UTC, prince-chrismc commented
I suspect your culprit is 

https://github.com/google/effcee/blob/2ec8f8738118cc483b67c04a759fee53496c5659/cmake/setup_build.cmake#L46

2021-07-10 01:34 UTC, prince-chrismc commented on recipes/effcee/all/conanfile.py
> +        self._cmake.definitions["EFFCEE_ENABLE_SHARED_CRT"] = True
This needs to be set based on the compiler runtime setting afaik

2021-07-12 09:26 UTC, AndreyMlashkin commented
If I try to reproduce the problem from the CI, I am fetting a different error... does anyone have a clue?

[build_log.txt](https://github.com/conan-io/conan-center-index/files/6800195/build_log.txt)

2021-07-12 10:07 UTC, AndreyMlashkin commented
Ah, I see, I have compiler version 16, not 14.
So, I have the same issue - I've got a *.dll instrad of an *.a file...
Why flag from conan is not applied?

2021-07-13 14:43 UTC, AndreyMlashkin commented
Not sure, what should I change there

2021-07-13 14:47 UTC, prince-chrismc commented
Only put destination the CMake defaults are good enough https://github.com/conan-io/conan-center-index/pull/6273/files#diff-04ec96e4879db2f998fea9295e0cd12ebdf31ee93315c76077e944e70b91db07

2021-07-13 19:23 UTC, prince-chrismc commented
They dont support MT and shared... typical, i'd just block it in validate

https://github.com/conan-io/conan-center-index/blob/f829bb930e4742ddcdc660f42daf2f0911c5a69e/recipes/jpeg-compressor/all/conanfile.py#L43-L44

2021-07-14 13:48 UTC, AndreyMlashkin commented
Strange. the failed configureation should raise an exception... strange

2021-07-15 01:26 UTC, prince-chrismc commented
The raise should be in the validate... that might be the culprit

2021-07-16 19:10 UTC, prince-chrismc commented on recipes/effcee/all/conanfile.py
> +
```suggestion
    def configure(self):
        if self.options.shared:
            del self.options.fPIC
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, "14")

    def validate(self):
        if self.options.shared:
            if self.settings.compiler == "Visual Studio" and "MT" in self.settings.compiler.runtime:
                raise ConanInvalidConfiguration("Visual Studio build for shared library with MT runtime is not supported")

```

2021-07-16 19:17 UTC, prince-chrismc reviewed
In the logs... Visual Studio is passing static but not shared....

I noticed there's no `.lib` created or packaged

```
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  effcee.vcxproj -> C:\J\w\BuildSingleReference@6\.conan\data\effcee\2019.1\_\_\build\2a916f1b72da6433e8f921238b6327abe2155ed9\build_subfolder\bin\effcee.dll
  effcee.vcxproj -> C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/build/2a916f1b72da6433e8f921238b6327abe2155ed9/build_subfolder/bin/effcee.pdb (Full PDB)
  -- Install configuration: "Debug"
  -- Installing: C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/package/2a916f1b72da6433e8f921238b6327abe2155ed9/include/effcee/effcee.h
  -- Installing: C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/package/2a916f1b72da6433e8f921238b6327abe2155ed9/lib/effcee.dll
[HOOK - conan-center.py] post_package(): [PACKAGE LICENSE (KB-H012)] OK
[HOOK - conan-center.py] post_package(): [DEFAULT PACKAGE LAYOUT (KB-H013)] OK
[HOOK - conan-center.py] post_package(): [MATCHING CONFIGURATION (KB-H014)] OK
[HOOK - conan-center.py] post_package(): [SHARED ARTIFACTS (KB-H015)] OK
[HOOK - conan-center.py] post_package(): [PC-FILES (KB-H020)] OK
[HOOK - conan-center.py] post_package(): [CMAKE-MODULES-CONFIG-FILES (KB-H016)] OK
[HOOK - conan-center.py] post_package(): [PDB FILES NOT ALLOWED (KB-H017)] OK
[HOOK - conan-center.py] post_package(): [LIBTOOL FILES PRESENCE (KB-H018)] OK
[HOOK - conan-center.py] post_package(): [MS RUNTIME FILES (KB-H021)] OK
effcee/2019.1 package(): Packaged 1 '.h' file: effcee.h
effcee/2019.1 package(): Packaged 1 '.dll' file: effcee.dll
effcee/2019.1 package(): Packaged 1 file: LICENSE
```

Looking at the code I do not see a single windows DLL export https://github.com/google/effcee/blob/main/effcee/effcee.h

try this suggestions

2021-07-16 19:17 UTC, prince-chrismc commented on recipes/effcee/all/CMakeLists.txt
> +conan_basic_setup()
```suggestion
cmake_minimum_required(VERSION 3.4)
project(cmake_wrapper)

include(conanbuildinfo.cmake)
conan_basic_setup()

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
```

2021-07-17 15:14 UTC, prince-chrismc requested changes
One tiny detail

2021-07-17 15:14 UTC, prince-chrismc commented on recipes/effcee/all/conanfile.py
> +            del self.options.fPIC
There's a duplicate method

```suggestion
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC

    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, "14")
```

2021-07-17 22:38 UTC, AndreyMlashkin commented
> In the logs... Visual Studio is passing static but not shared....
> 
> I noticed there's no `.lib` created or packaged
> 
> ```
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   effcee.vcxproj -> C:\J\w\BuildSingleReference@6\.conan\data\effcee\2019.1\_\_\build\2a916f1b72da6433e8f921238b6327abe2155ed9\build_subfolder\bin\effcee.dll
>   effcee.vcxproj -> C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/build/2a916f1b72da6433e8f921238b6327abe2155ed9/build_subfolder/bin/effcee.pdb (Full PDB)
>   -- Install configuration: "Debug"
>   -- Installing: C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/package/2a916f1b72da6433e8f921238b6327abe2155ed9/include/effcee/effcee.h
>   -- Installing: C:/J/w/BuildSingleReference@6/.conan/data/effcee/2019.1/_/_/package/2a916f1b72da6433e8f921238b6327abe2155ed9/lib/effcee.dll
> [HOOK - conan-center.py] post_package(): [PACKAGE LICENSE (KB-H012)] OK
> [HOOK - conan-center.py] post_package(): [DEFAULT PACKAGE LAYOUT (KB-H013)] OK
> [HOOK - conan-center.py] post_package(): [MATCHING CONFIGURATION (KB-H014)] OK
> [HOOK - conan-center.py] post_package(): [SHARED ARTIFACTS (KB-H015)] OK
> [HOOK - conan-center.py] post_package(): [PC-FILES (KB-H020)] OK
> [HOOK - conan-center.py] post_package(): [CMAKE-MODULES-CONFIG-FILES (KB-H016)] OK
> [HOOK - conan-center.py] post_package(): [PDB FILES NOT ALLOWED (KB-H017)] OK
> [HOOK - conan-center.py] post_package(): [LIBTOOL FILES PRESENCE (KB-H018)] OK
> [HOOK - conan-center.py] post_package(): [MS RUNTIME FILES (KB-H021)] OK
> effcee/2019.1 package(): Packaged 1 '.h' file: effcee.h
> effcee/2019.1 package(): Packaged 1 '.dll' file: effcee.dll
> effcee/2019.1 package(): Packaged 1 file: LICENSE
> ```
> 
> Looking at the code I do not see a single windows DLL export https://github.com/google/effcee/blob/main/effcee/effcee.h
> 
> try this suggestions

I think it is worth submitting upstream

2021-07-18 13:48 UTC, prince-chrismc submitted a review, later dismissed

2021-07-19 13:35 UTC, uilianries commented on recipes/effcee/all/conanfile.py
> +            tools.check_min_cppstd(self, "14")
```suggestion
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC

    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, "11")
        if self.settings.compiler == "Visual Studio" and "MT" in self.settings.compiler.runtime:
            raise ConanInvalidConfiguration("Visual Studio build for shared library with MT runtime is not supported")
```
 Also,

2021-07-19 13:35 UTC, uilianries commented on recipes/effcee/all/test_package/CMakeLists.txt
> +endif()
```suggestion
```

2021-07-19 13:35 UTC, uilianries commented on recipes/effcee/all/test_package/CMakeLists.txt
> +target_link_libraries(effcee-example effcee::effcee)
```suggestion
target_link_libraries(effcee-example effcee::effcee)
set_property(TARGET effcee-example PROPERTY CXX_STANDARD 11)
```

2021-07-19 13:35 UTC, uilianries commented on recipes/effcee/all/test_package/conanfile.py
> +        pass
```suggestion
        if and not tools.cross_building(self.settings):
            bin_path = os.path.join("bin", "effcee-example")
            self.run(bin_path, run_environment=True)
```

2021-07-19 13:35 UTC, uilianries commented on recipes/effcee/all/test_package/main.cc
> +}
```suggestion
#include "effcee/effcee.h"

int main(void) {
  const std::string = effcee::Match("foo bar qux", "foo",
                              effcee::Options().SetChecksName("checks"));
  return 0;
}
```

Simplify!

2021-07-20 08:30 UTC, AndreyMlashkin commented
I don't know, what happened to PR, I needed to rebase and force push.

2021-07-23 13:01 UTC, prince-chrismc approved these changes

2021-07-26 10:14 UTC, SSE4 approved these changes

2021-07-26 15:16 UTC, uilianries approved these changes

2021-07-26 15:34 UTC, merged