Update version to 1.1.0
conan-io/conan-center-index pull request #6214
Opened 2021-07-07 09:13 UTC by a4z

Specify library name and version:  **djinni-support-lib/1.1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-07 11:58 UTC, a4z commented
Close and re-open, since last conan-center-bot message, 1 failure - all successfully, looks like a crash

2021-07-07 11:59 UTC, a4z commented
Please help, what is wrong with the PR ?

2021-07-07 12:04 UTC, ruilvo requested changes

2021-07-07 12:04 UTC, ruilvo commented on recipes/djinni-support-lib/1.x.x/conanfile.py
> +                raise ConanInvalidConfiguration("Python on Windowns is not fully yet supported, please see https://github.com/cross-language-cpp/djinni-support-lib/issues.")
```suggestion
                raise ConanInvalidConfiguration("Python on Windows is not fully yet supported, please see https://github.com/cross-language-cpp/djinni-support-lib/issues.")
```

You have a typo. Commit this change and the bot will rebuild and then we'll see.

2021-07-07 12:42 UTC, SpaceIm commented on recipes/djinni-support-lib/1.x.x/conandata.yml
> +sources:
```suggestion
```

illformed yml

2021-07-07 16:41 UTC, a4z commented on recipes/djinni-support-lib/1.x.x/conandata.yml
> +sources:
thanks!

2021-07-07 18:57 UTC, jothepro approved these changes

2021-07-08 05:44 UTC, SpaceIm approved these changes

2021-07-08 06:35 UTC, SSE4 approved these changes

2021-07-08 08:44 UTC, ruilvo approved these changes

2021-07-08 12:03 UTC, jgsogo approved these changes

2021-07-08 12:31 UTC, merged