Bump miniaudio version
conan-io/conan-center-index pull request #6437
Opened 2021-07-20 19:25 UTC by ruilvo

Specify library name and version:  **miniaudio/0.10.39**

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-07-20 22:19 UTC, madebr requested changes
I think only adding the latest version suffices.

2021-07-20 22:19 UTC, madebr commented on recipes/miniaudio/all/conandata.yml
> +    sha256: 918FD1A458217BFE8D855F4F9C15BF7D62C510F19103FB619BAE01D1ED06681F
```suggestion
```

2021-07-20 22:19 UTC, madebr commented on recipes/miniaudio/config.yml
> +    folder: all
```suggestion
```

2021-07-20 23:20 UTC, madebr approved these changes

2021-07-21 00:25 UTC, ericriff approved these changes

2021-07-21 06:25 UTC, SSE4 approved these changes

2021-07-21 08:46 UTC, merged