aws-c-auth/0.6.0
conan-io/conan-center-index pull request #6775
Opened 2021-08-09 08:59 UTC by MartinDelille

Specify library name and version:  **aws-c-auth/0.6.0**

ref #6346
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-08-09 13:46 UTC, intelligide commented
CCI doesn't contains the prebuilt package for aws-c-http/0.6.5 for Windows.

![image](https://user-images.githubusercontent.com/12529837/128716319-0c052ac9-8ae7-4c79-810b-78f26e0b34e0.png)
(https://conan.io/center/aws-c-http)

It seems that this is a build pipeline error.

2021-08-09 14:14 UTC, jgsogo commented
I'm on it, but builds for `qt` entered before that one... so we need to wait a little bit.

2021-08-09 14:39 UTC, jgsogo commented
Packages built. All those missing ones were really unexpected... https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/237/summary.json

2021-08-09 16:15 UTC, intelligide requested changes

2021-08-09 16:15 UTC, intelligide commented on recipes/aws-c-auth/all/test_package/conanfile.py
> +        if not tools.cross_building(self.settings):
```suggestion
        if not tools.cross_building(self):
```

2021-08-09 18:11 UTC, intelligide submitted a review, later dismissed

2021-08-10 08:04 UTC, jgsogo submitted a review, later dismissed

2021-08-10 09:01 UTC, MartinDelille commented
I added missing requirements after @intelligide [comments](https://github.com/conan-io/conan-center-index/pull/6715#discussion_r684641978).

These libraries are indeed reference in the source code: https://github.com/awslabs/aws-c-auth/blob/main/source/credentials_provider_x509.c#L10-L20

I'm not sure to understand why it is needed since it seems to work without and it may make bumping dependencies version more tricky.

I'm also wondering if there was a simple way to detect these dependencies.

2021-08-10 09:31 UTC, jgsogo approved these changes
It is not required (it builds and works) to add those transitive dependencies, but it is a good practice when the package uses them directly. It can happen that the requirement in some future version stops using that transitive dependency, but the library still needs it. Adding it as a direct requirement ensures that the recipe will keep working if that scenario happens.

For a _framework_ like `aws-c-xxxx` it's very likely that the dependency graph will only grow in complexity, but for other dependency graphs of unrelated libraries the situation has a higher probability.

2021-08-10 12:22 UTC, intelligide approved these changes

2021-08-10 14:16 UTC, SSE4 approved these changes

2021-08-10 19:46 UTC, uilianries approved these changes

2021-08-10 20:02 UTC, merged