aws-c-mqtt/0.7.6
conan-io/conan-center-index pull request #6776
Opened 2021-08-09 09:00 UTC by MartinDelille

Specify library name and version:  **aws-c-mqtt/0.7.6**

ref #6346
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-08-09 16:16 UTC, intelligide requested changes

2021-08-09 16:16 UTC, intelligide commented on recipes/aws-c-mqtt/all/test_package/conanfile.py
> +        if not tools.cross_building(self.settings):
```suggestion
        if not tools.cross_building(self):
```

2021-08-10 12:22 UTC, intelligide approved these changes

2021-08-10 14:16 UTC, SSE4 approved these changes

2021-08-10 17:01 UTC, uilianries commented on recipes/aws-c-mqtt/all/conanfile.py
> +        self.requires("aws-c-http/0.6.5")
There is an option for websocket: MQTT_WITH_WEBSOCKETS It could be added in the future. It seems like only depends on aws-c-http

2021-08-10 17:01 UTC, uilianries approved these changes

2021-08-10 20:32 UTC, merged