#7244 numa option is deleted if Boost fibre is disabled
conan-io/conan-center-index pull request #7248
Opened 2021-09-11 14:43 UTC by wdobbe

Specify library name and version:  **boost/1.77.0**

Resolves issue #7244.

When option `without_fiber` is set to True, option `numa` is deleted in the recipe. But currently the recipe still tries to change it value without checking if the option exists.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-09-12 00:57 UTC, madebr commented
`self.options.numa` is removed in the `configure` method.
https://github.com/conan-io/conan-center-index/blob/011f6e2f952d472473106f74e3899384052b84dc/recipes/boost/all/conanfile.py#L381-L382

The lines you're wanting to change here are in the `config_options` method.
https://github.com/conan-io/conan-center-index/blob/011f6e2f952d472473106f74e3899384052b84dc/recipes/boost/all/conanfile.py#L292-L294

`config_options` is run before `configure`.
So there is no problem.

2021-09-12 00:57 UTC, madebr requested changes
See https://github.com/conan-io/conan-center-index/pull/7248#issuecomment-917516004

I think this pr is invalid.

2021-09-12 10:43 UTC, wdobbe commented
@madebr I was also surprised that I got an error message in the config_options section.

But using the new Boost recipe still broke by build with the following error message (full log in linked issue):
ERROR: boost/1.77.0: Error in config_options() method, line 294
		self.options.numa = False
	ConanException: option 'numa' doesn't exist

Can you explain then why I get that error when 'without_fiber' is True ?

2021-09-12 12:16 UTC, madebr commented
What command is failing for you?
I ran the following commands and conan began building boost without showing an error.
```
conan create . boost/1.77.0@ -o boost:without_fiber=True -o boost:numa=False
conan create . boost/1.77.0@ -o boost:without_fiber=True -o boost:numa=True
conan create . boost/1.77.0@ -o boost:without_fiber=False -o boost:numa=False
conan create . boost/1.77.0@ -o boost:without_fiber=False -o boost:numa=True
```

2021-09-12 14:11 UTC, SSE4 commented
probably, it makes sense to fix boost shared=True + numa build instead.
there are many reports about it:
https://github.com/conan-io/conan-center-index/issues/4339
https://github.com/conan-io/conan-center-index/issues/4950

2021-09-12 14:30 UTC, wdobbe commented
I'll reproduce it tomorrow and copy the exact command I used.

2021-09-12 15:38 UTC, dmn-star commented
> probably, it makes sense to fix boost shared=True + numa build instead.

That would be very nice. Then I could finally get rid of my workaround (https://github.com/conan-io/conan-center-index/issues/4339#issuecomment-766172860).

2021-09-15 15:27 UTC, madebr commented
I'm on Windows now and trying those 4 option combinations.
In all cases, conan began building just fine.

Please post the complete `conan create boost/1.77.0@` command that is failing.

2021-09-15 15:32 UTC, wdobbe commented
Yes, I'm trying to reproduce it myself now.

2021-09-15 15:55 UTC, wdobbe commented
Well, I haven't been able to reproduce the reported problem anymore.
Sorry for the false alarm, I don't know why I got that error, maybe an old recipe in the local cache.

2021-09-15 15:55 UTC, closed without merging