(#7329) Support Gandiva in Arrow 2.0.0
conan-io/conan-center-index pull request #7331
Opened 2021-09-18 12:18 UTC by kexianda

* fix protobuf, re2 and llvm dependencies
* fix compile error since the llvm api changed.

Specify library name and version:  **arrow/2.0.0**

In arrow 2.0.0,  CCI does not support gandiva component since gandiva depends on llvm. Since CCI has llvm recipe now.
Turn on gandiva component support, and fix some compiling errors.

Tested on
MacOS / Clang 12
Debian / GCC 9.3

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-09-18 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=7331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=7331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=7331) it.</sub>

2021-09-27 09:44 UTC, jgsogo requested changes
The comment about version ranges is important for CCI.

Thanks!

2021-09-27 09:44 UTC, jgsogo commented on recipes/arrow/all/conanfile.py
> +            self.requires("llvm-core/[>=11.1.0]")
Do not use version ranges in CCI. It might change packageID and consumers will complain about _missing packages_.

2021-09-27 09:44 UTC, jgsogo commented on recipes/arrow/all/conanfile.py
> +            self.cpp_info.components["libarrow"].requires.append("llvm-core::llvm-core")
Probably we can move this together with the entry for `libarrow` component

2021-11-01 12:35 UTC, uilianries approved these changes
LGTM

2021-12-04 04:32 UTC, prince-chrismc approved these changes

2021-12-09 17:36 UTC, uilianries approved these changes

2021-12-13 13:08 UTC, danimtb approved these changes

2022-01-07 07:49 UTC, SSE4 approved these changes

2022-01-07 18:32 UTC, prince-chrismc commented
@jgsogo your requested changes have been applied! please review when you have the chance!

2022-01-12 07:45 UTC, jgsogo approved these changes

2022-01-12 08:06 UTC, merged