harfbuzz: bump dependencies
conan-io/conan-center-index pull request #7366
Opened 2021-09-21 15:22 UTC by madebr

Specify library name and version:  **harfbuzz/all**

Bump dependencies

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-09-21 15:26 UTC, ericLemanissier commented
Are you based on top of master?

2021-09-21 15:28 UTC, madebr commented
@ericLemanissier 
Oh sorry, I'll rebase

2021-09-21 16:50 UTC, ericLemanissier commented on recipes/harfbuzz/all/conanfile.py
> +    @functools.lru_cache(1)
very nice !

2021-09-21 18:50 UTC, Croydon requested changes
I think that you forgot to delete `example.c` (you copied instead of renamed?)

2021-09-21 18:57 UTC, madebr commented
> I think that you forgot to delete `example.c` (you copied instead of renamed?)

Good catch.

While trying to get a recipe building on MSVC, I made a lot of changes to a few recipes.
After I got finished, I just copied the changes for each recipe on top of current master but forgot to remove those files I renamed earlier.

2021-09-22 04:59 UTC, ericLemanissier approved these changes

2021-09-22 19:42 UTC, uilianries approved these changes

2021-09-23 00:06 UTC, prince-chrismc approved these changes

2021-09-23 01:02 UTC, merged