- add gemmlowp/cci.20211003
conan-io/conan-center-index pull request #7527
Opened 2021-10-04 07:36 UTC by SSE4

Specify library name and version:  **gemmlowp/cci.20211003**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-10-04 07:45 UTC, SSE4 commented on recipes/gemmlowp/all/conanfile.py
> +        self.cpp_info.components["eight_bit_int_gemm"].libs = ["eight_bit_int_gemm"]
```suggestion
        self.cpp_info.components["eight_bit_int_gemm"].libs = ["eight_bit_int_gemm"]
        if self.settings.os == "Linux":
            self.cpp_info.components["eight_bit_int_gemm"].system_libs.extend(["pthread"])
```

2021-10-04 08:26 UTC, SSE4 commented on recipes/gemmlowp/all/conanfile.py
> +
```suggestion

    def validate(self):
        if self.settings.os == "Windows" and self.options.shared:
            raise ConanInvalidConfiguration("shared is not supported on Windows")

```

2021-10-04 08:26 UTC, SSE4 commented on recipes/gemmlowp/all/conanfile.py
> +from conans import ConanFile, CMake, tools
```suggestion
from conans import ConanFile, CMake, tools
from conans.errors import ConanInvalidConfiguration
```

2021-10-04 18:45 UTC, uilianries submitted a review, later dismissed

2021-10-04 18:45 UTC, uilianries commented on recipes/gemmlowp/all/conanfile.py
> +        self.copy("COPYING", dst="licenses", src=self._source_subfolder)
```suggestion
```

Only LICENSE is listed in project's folder

2021-10-04 19:13 UTC, uilianries approved these changes

2021-10-05 14:19 UTC, prince-chrismc submitted a review, later dismissed

2021-10-06 07:44 UTC, jgsogo requested changes

2021-10-06 13:35 UTC, prince-chrismc approved these changes

2021-10-06 16:28 UTC, jgsogo approved these changes

2021-10-06 17:01 UTC, merged

2021-10-07 01:30 UTC, SpaceIm commented
Several issues in this recipe:

- upstream aways build shared lib
- include dir is wrong. In upstream CMake config file:

  ```cmake
  # Create imported target gemmlowp::gemmlowp
  add_library(gemmlowp::gemmlowp INTERFACE IMPORTED)
  
  set_target_properties(gemmlowp::gemmlowp PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gemmlowp"
    INTERFACE_LINK_LIBRARIES "gemmlowp::eight_bit_int_gemm"
  )
  
  # Create imported target gemmlowp::eight_bit_int_gemm
  add_library(gemmlowp::eight_bit_int_gemm SHARED IMPORTED)
  
  set_target_properties(gemmlowp::eight_bit_int_gemm PROPERTIES
    INTERFACE_LINK_LIBRARIES "pthread"
  )
  ```

Less important:
- no share & pkgconfig dir to remove
- generators are useless (except cmake)
- required_conan_version is too high