add inversify-cpp/2.1.0
conan-io/conan-center-index pull request #7881
Opened 2021-10-28 22:38 UTC by mosure

Specify library name and version:  **inversify-cpp/2.1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

New addition to ConanCenter.
Standalone library.
I am the author.

---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-11-02 13:24 UTC, mosure commented
@conan-center-bot remove label

2021-11-05 13:36 UTC, uilianries reviewed
Thank you for contribution, please take a look on my review.

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/conanfile.py
> +    topics = ("conan", "inversify-cpp", "ioc", "container", "dependency", "injection")
```suggestion
    topics = ("ioc", "container", "dependency", "injection")
```

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/conanfile.py
> +        tools.check_min_cppstd(self, "17")
```suggestion
    @property
    def _compilers_minimum_version(self):
        return {
            "gcc": "9",
            "Visual Studio": "15.7",
            "clang": "7",
            "apple-clang": "11",
        }

    def validate(self):
        if self.settings.compiler.cppstd:
            tools.check_min_cppstd(self, 17)
        minimum_version = self._compilers_minimum_version.get(str(self.settings.compiler), False)
        if minimum_version:
            if tools.Version(self.settings.compiler.version) < minimum_version:
                raise ConanInvalidConfiguration("{} requires C++17, which your compiler does not support.".format(self.name))
        else:
            self.output.warn("{} requires C++17. Your compiler is unknown. Assuming it supports C++17.".format(self.name))
```

Need to validate compiler versions

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/conanfile.py
> +        self.cpp_info.includedirs = ['include']
```suggestion
```

Not needed.

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/test_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```suggestion
cmake_minimum_required(VERSION 3.1)
project(test_package CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

find_package(inversify-cpp CONFIG REQUIRED)

add_executable(${PROJECT_NAME} test_package.cpp)
target_link_libraries(${PROJECT_NAME} inversify-cpp::inversify-cpp)
```

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/test_package/conanfile.py
> +    generators = "cmake"
```suggestion
    generators = "cmake", "cmake_find_package_multi"
```

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/test_package/conanfile.py
> +
```suggestion
```

do not validate it on test package.

2021-11-05 13:36 UTC, uilianries commented on recipes/inversify-cpp/all/test_package/conanfile.py
> +        if not tools.cross_building(self.settings):
```suggestion
        if not tools.cross_building(self):
```

self.settings does not work when using build context.

2021-11-08 17:42 UTC, uilianries submitted a review, later dismissed
LGTM

2021-11-12 09:42 UTC, SSE4 submitted a review, later dismissed

2021-11-13 19:22 UTC, prince-chrismc requested changes
One tiny issue https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-is-a-toolscheck_min_cppstd-call-not-enough

2021-11-13 19:22 UTC, prince-chrismc commented on recipes/inversify-cpp/all/conanfile.py
> +        tools.check_min_cppstd(self, 17)
```suggestion
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, 17)
```

2021-11-13 23:02 UTC, mosure commented
Hello, I am reviewing [args-parser/all/test_package/conanfile.py](https://github.com/conan-io/conan-center-index/blob/master/recipes/args-parser/all/test_package/conanfile.py). Given [`args-parser`'s `cppstd` validation](https://github.com/conan-io/conan-center-index/blob/master/recipes/args-parser/all/conanfile.py#L30), I would expect `inversify-cpp`'s test package to behave similarly, however, the `test_package` does not seem to be running with correct `cppstd >= 17` after incorporating `cppstd` guard.

2021-11-16 04:08 UTC, prince-chrismc commented
ahh excellent pitfal... You are missing this little bit of magic

https://github.com/conan-io/conan-center-index/blob/e6b59d950aac0909e777f962d1fda9ab428c1995/recipes/args-parser/all/test_package/CMakeLists.txt#L15-L18

***

So with the change (adding the `if` statement) we are never hitting the "check min" because CCI infra currently does not handle the `cppstd` setting. Previously it was using the compiler default (and block compilers that support it with that setting). So now we need to make sure that is set in the test_package in the cmake

2021-11-19 03:48 UTC, prince-chrismc commented
You can block windows MT since it's the only failure

2021-12-04 04:39 UTC, prince-chrismc commented on recipes/inversify-cpp/all/conanfile.py
> +        return os.path.join(self.source_folder, "source_subfolder")
This should not be required (the default relative path always starts from here

2021-12-04 04:39 UTC, prince-chrismc commented on recipes/inversify-cpp/all/conanfile.py
> +        self.cpp_info.names["pkg_config"] = "inversify-cpp"
I did not find these defined in your project + they are the default from Conan
We only explicit set the ones defined in the project. 

I think these can be removed

2021-12-05 16:40 UTC, prince-chrismc approved these changes

2021-12-09 10:46 UTC, ericLemanissier approved these changes

2021-12-10 11:30 UTC, uilianries approved these changes

2021-12-10 12:05 UTC, merged