nvtx: New NVTX package.
conan-io/conan-center-index pull request #7977
Opened 2021-11-06 14:49 UTC by sh0

Specify library name and version:  **nvtx/3.0.1**

Add NVIDIA Tools Extension SDK (NVTX) header-only library.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-11-06 15:16 UTC, sh0 commented
There is a slight issue with CI. Because this library is header only and has `settings = "os"` only one package is built per platform. This is fine, but the test package should really still be built for all targets to truly test if everything works correctly. Reason is that the library has bunch of inline header functions that do non-trivial things.

There probably isn't any way to force CI to test all platforms without expanding recipe `settings` variable?

2021-11-07 13:28 UTC, SpaceIm commented
It's tested for all os/arch/compiler, but only one compiler version, libcxx/msvc runtime, and always Release.

2021-11-07 13:37 UTC, SpaceIm requested changes

2021-11-07 13:37 UTC, SpaceIm commented on recipes/nvtx/all/conanfile.py
> +required_conan_version = ">=1.35.0"
```suggestion
required_conan_version = ">=1.33.0"
```

2021-11-07 13:37 UTC, SpaceIm commented on recipes/nvtx/all/conanfile.py
> +    settings = "os"
```suggestion
    settings = "os", "arch", "compiler", "build_type"
```

Not sure, butI think it will be required for conan v2

2021-11-07 13:37 UTC, SpaceIm commented on recipes/nvtx/all/conanfile.py
> +        if self.settings.os == "Linux":
```suggestion
        if self.settings.os in ["Linux", "FreeBSD"]:
```

2021-11-07 13:46 UTC, SpaceIm approved these changes

2021-11-08 06:30 UTC, SSE4 approved these changes

2021-11-08 18:52 UTC, uilianries approved these changes

2021-11-08 19:35 UTC, merged