Use absolute target names in glew
conan-io/conan-center-index pull request #8264
Opened 2021-12-01 12:31 UTC by tapia

2021-12-01 12:47 UTC, czoido commented on recipes/glew/all/conanfile.py
> +        self.cpp_info.components["glewlib"].set_property("cmake_target_name", "GLEW::GLEW", "cmake_find_package")
```suggestion
        self.cpp_info.components["glewlib"].set_property("cmake_module_target_name", "GLEW::GLEW")
```

2021-12-01 22:08 UTC, SpaceIm requested changes

2021-12-01 22:08 UTC, SpaceIm commented on recipes/glew/all/conanfile.py
> +
```suggestion
        self.cpp_info.set_property("cmake_find_mode", "both")
        self.cpp_info.set_property("cmake_module_file_name", "GLEW")
        self.cpp_info.set_property("cmake_file_name", "glew")
        self.cpp_info.set_property("cmake_module_target_name", "GLEW::GLEW")
```

2021-12-01 22:08 UTC, SpaceIm commented on recipes/glew/all/conanfile.py
> +        self.cpp_info.components["glewlib"].set_property("cmake_target_name", "GLEW::{}".format(glewlib_target_name))
```suggestion
        self.cpp_info.set_property("cmake_target_name", "GLEW::{}".format(glewlib_target_name))
```

2021-12-22 18:28 UTC, czoido approved these changes

2021-12-22 23:06 UTC, SpaceIm approved these changes

2021-12-23 01:07 UTC, prince-chrismc approved these changes

2021-12-23 02:34 UTC, merged