Use absolute target names in glfw
conan-io/conan-center-index pull request #8268
Opened 2021-12-01 14:48 UTC by tapia

2021-12-01 15:07 UTC, SpaceIm requested changes
transition will be funny ^^

(glfw imported target is not namespaced, so we want `glfw` for `cmake_target_name` with the new model, and we don't want to add the custom module in `CMakeDeps` because it's a workaround to provide non-namespaced imported target to `cmake_find_package_*`)

2021-12-01 15:07 UTC, SpaceIm commented on recipes/glfw/all/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "glfw::glfw")
```suggestion
        self.cpp_info.set_property("cmake_target_name", "glfw")
```

2021-12-01 15:07 UTC, SpaceIm commented on recipes/glfw/all/conanfile.py
>          self.cpp_info.set_property("cmake_build_modules", [self._module_file_rel_path])
```suggestion
```

2021-12-01 17:17 UTC, tapia commented on recipes/glfw/all/conanfile.py
>          self.cpp_info.set_property("cmake_build_modules", [self._module_file_rel_path])
Fixed (?)

2021-12-01 18:23 UTC, SpaceIm submitted a review, later dismissed

2021-12-14 11:59 UTC, SSE4 commented
@tapia there are conflicts, please resolve

2021-12-14 14:56 UTC, SpaceIm commented
Just bump required_conan_version and remove TODO above

2021-12-28 16:41 UTC, czoido approved these changes

2021-12-28 17:41 UTC, closed without merging