Use absolute target names in fftw
conan-io/conan-center-index pull request #8273
Opened 2021-12-01 16:45 UTC by tapia

2021-12-01 21:57 UTC, SpaceIm requested changes

2021-12-01 21:57 UTC, SpaceIm commented on recipes/fftw/all/conanfile.py
> +        self.cpp_info.set_property("cmake_file_name", "{}::{}".format(cmake_namespace, cmake_namespace))
```suggestion
        self.cpp_info.set_property("cmake_file_name", cmake_config_name)
        self.cpp_info.set_property("cmake_target_name", "{}::{}".format(cmake_namespace, cmake_target_name))
        self.cpp_info.set_property("pkg_config_name", pkgconfig_name)

```

2021-12-01 21:57 UTC, SpaceIm commented on recipes/fftw/all/conanfile.py
> +        self.cpp_info.components["fftwlib"].set_property("cmake_file_name", "{}::{}".format(cmake_namespace, cmake_target_name))
```suggestion
```

2021-12-02 11:05 UTC, czoido commented on recipes/fftw/all/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "{}::{}".format(cmake_namespace, cmake_target_name))
```suggestion
```
I think we can remove this and leave the component one but adding a #FIXME explaining that in Conan 2.0 we should undo the workaround and move that component to be the root cpp_info.

2021-12-28 17:22 UTC, czoido approved these changes

2021-12-28 17:58 UTC, SpaceIm approved these changes

2021-12-29 05:10 UTC, prince-chrismc approved these changes

2021-12-29 05:34 UTC, merged