isl 0.24
conan-io/conan-center-index pull request #8290
Opened 2021-12-02 08:33 UTC by ericLemanissier

Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2021-12-02 10:25 UTC, SpaceIm requested changes

2021-12-02 10:25 UTC, SpaceIm commented on recipes/isl/all/conanfile.py
>  class IslConan(ConanFile):
```suggestion

required_conan_version = ">=1.33.0"


class IslConan(ConanFile):
```

2021-12-02 11:58 UTC, SpaceIm commented
Add this in autotools configuration:

```python
        if self.settings.compiler == "Visual Studio" and tools.Version(self.settings.compiler.version) >= 12:
            self._autotools.flags.append("-FS")
```

2021-12-02 11:59 UTC, SpaceIm submitted a review, later dismissed

2021-12-03 08:29 UTC, ericLemanissier commented
`gmp.lib(bdiv_dbm1c.obj) : fatal error LNK1318: Unexpected PDB error; OK (0) 'C:\j\w\buildsinglereference@3\.conan\data\isl\0.22\_\_\build\048083ccb84e0809ad51b2a4017a45b658567c51\vc140.pdb'
`
`gmp.lib(tdiv_q_2exp.obj) : fatal error LNK1318: Unexpected PDB error; OK (0) 'C:\j\w\buildsinglereference@3\.conan\data\isl\0.22\_\_\build\048083ccb84e0809ad51b2a4017a45b658567c51\vc140.pdb'`

WAT ?

2021-12-07 18:08 UTC, ericLemanissier commented
so same error as https://github.com/conan-io/conan-center-index/pull/7012. Does anyone have a clue ?

2021-12-18 06:33 UTC, SSE4 approved these changes

2021-12-20 17:39 UTC, uilianries approved these changes
LGTM

2021-12-21 17:01 UTC, prince-chrismc approved these changes

2021-12-21 17:34 UTC, merged