aws-c-event-stream: Use absolute target names
conan-io/conan-center-index pull request #8292
Opened 2021-12-02 08:59 UTC by franramirez688

This PR updates the target names for CMakeDeps via set_property.
Conan version required: 1.43
Conan feature related: conan-io/conan#10099

2021-12-02 09:45 UTC, SpaceIm requested changes

2021-12-02 09:45 UTC, SpaceIm commented on recipes/aws-c-event-stream/all/conanfile.py
> +        self.cpp_info.set_property("cmake_target_name", "AWS::AWS")
```suggestion
        self.cpp_info.set_property("cmake_target_name", "AWS::aws-c-event-stream")
```

Like `vulkan-headers` recipe, very important to not define `AWS::AWS` target. It was a tedious issue of previous mechanism.

2021-12-02 09:45 UTC, SpaceIm commented on recipes/aws-c-event-stream/all/conanfile.py
> +        self.cpp_info.components["aws-c-event-stream-lib"].set_property("cmake_target_name", "AWS::aws-c-event-stream")
```suggestion
```

2021-12-07 09:57 UTC, franramirez688 commented
@SpaceIm I think we have several PRs with the same conditions as https://github.com/conan-io/conan-center-index/pull/8291#discussion_r760918490
Deleting the component as suggested, we should add all the requires and libs from that one to the root ``cpp_info``, shouldn't we?

2021-12-10 13:30 UTC, franramirez688 commented
> @SpaceIm I think we have several PRs with the same conditions as [#8291 (comment)](https://github.com/conan-io/conan-center-index/pull/8291#discussion_r760918490) Deleting the component as suggested, we should add all the requires and libs from that one to the root `cpp_info`, shouldn't we?

Checked locally and it's working as it is with legacy and new generators. So it's enough for now.

2021-12-12 09:58 UTC, SpaceIm commented
> @SpaceIm I think we have several PRs with the same conditions as [#8291 (comment)](https://github.com/conan-io/conan-center-index/pull/8291#discussion_r760918490)
> Deleting the component as suggested, we should add all the requires and libs from that one to the root `cpp_info`, shouldn't we?

component is not deleted, it's still there as a side effect of cmake_find_package support.

2021-12-12 09:59 UTC, SpaceIm approved these changes

2021-12-14 16:19 UTC, czoido approved these changes

2021-12-17 02:35 UTC, prince-chrismc approved these changes

2021-12-17 04:05 UTC, merged