rename package co to cocoyaxi
conan-io/conan-center-index pull request #8729
Opened 2022-01-09 15:25 UTC by idealvin

Specify library name and version:  **cocoyaxi/v2.0.3**

- Rename package co to [cocoyaxi](https://github.com/idealvin/cocoyaxi).
- Add cocoyaxi v2.0.3
---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-01-09 16:00 UTC, idealvin commented
Could someone help? Thanks!
```sh
-- Found cocoyaxi: 2.0.3 (found version "2.0.3") 
-- Library co found /home/conan/w/BuildSingleReference/.conan/data/cocoyaxi/2.0.3/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libco.a
-- Skipping already existing target: CONAN_LIB::cocoyaxi_co
-- Found: /home/conan/w/BuildSingleReference/.conan/data/cocoyaxi/2.0.3/_/_/package/053ea29eb0edc6b1695c893b738a971110c756fd/lib/libco.a
-- Configuring done
-- Generating done
CMake Error at CMakeLists.txt:10 (add_executable):
  Target "test_package" links to target "cocoyaxi::co" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

2022-01-09 16:09 UTC, SpaceIm requested changes

2022-01-09 16:09 UTC, SpaceIm commented on recipes/cocoyaxi/all/conanfile.py
> +        self.cpp_info.names["cmake_find_package_multi"] = "cocoyaxi"
```suggestion
```

your library doesn't export CMake config files, so do not suggest in `package_info()` that it does. But I would recommend to add this feature in your CMakeLists, it's very useful for consumers.

2022-01-09 16:09 UTC, SpaceIm commented on recipes/cocoyaxi/all/test_package/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} cocoyaxi::co)
```suggestion
target_link_libraries(${PROJECT_NAME} cocoyaxi::cocoyaxi)
```

2022-01-09 16:27 UTC, SpaceIm commented
You should open 2 PRs:
- one PR which add deprecated = "cocoyaxi" attribute to `co` recipe
- one PR adding `cocoyaxi` recipe

2022-01-10 04:43 UTC, idealvin commented
> * deprecated

I'm sorry. But I don't know how to make a package deprecated in Conan.

2022-01-14 11:49 UTC, closed without merging

2022-01-14 11:51 UTC, SpaceIm commented
> I'm sorry. But I don't know how to deprecate a recipe in Conan.

see my comment above, it's just one line.

2022-01-14 11:55 UTC, idealvin commented
> > I'm sorry. But I don't know how to deprecate a recipe in Conan.
> 
> see my comment above, it's just one line.

@SpaceIm  ok, thanks. Another question, should I remove old versions in cocoyaxi?