- [mpir] enable M1 builds
conan-io/conan-center-index pull request #8811
Opened 2022-01-11 06:08 UTC by SSE4

closes: #8772

Specify library name and version:  **mpir/all**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-01-11 09:58 UTC, jgsogo requested changes

2022-01-11 09:58 UTC, jgsogo commented on recipes/mpir/all/conanfile.py
> +    def validate2(self):
Just remove if it is not needed.

2022-01-11 10:00 UTC, jgsogo commented
... love to see when a PR adds configurations 🚀

2022-01-11 21:28 UTC, prince-chrismc approved these changes

2022-01-12 07:47 UTC, jgsogo approved these changes
💯

2022-01-13 00:10 UTC, SpaceIm commented on recipes/mpir/all/conanfile.py
> +                env_build["CXX_FOR_BUILD"] = xcrun.cxx + flags
Wouldn't it be more elegant and robust to get `self._autotools.flags` and `self._autotools.cxxflags` in `_configure_autotools()`, then inject those values in `CC_FOR_BUILD` and `CXX_FOR_BUILD` if cross-building (I guess those values are required for some reason in this case)?

2022-02-02 11:58 UTC, uilianries approved these changes

2022-02-02 12:37 UTC, merged