[cereal] rename using conan tools
conan-io/conan-center-index pull request #8976
Opened 2022-01-19 10:43 UTC by lkotsonis

Specify library name and version:  **cereal/1.3.0**

Fixes a couple of warning in the current recipe and test package.

---

- [ x ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-01-19 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=8976) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan-center-index?pullRequest=8976) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=8976) it.</sub>

2022-01-19 14:00 UTC, SSE4 approved these changes

2022-01-19 16:53 UTC, uilianries approved these changes
LGTM

2022-01-21 07:03 UTC, ericLemanissier approved these changes

2022-01-21 10:58 UTC, SpaceIm requested changes

2022-01-21 10:58 UTC, SpaceIm commented on recipes/cereal/all/conanfile.py
>          tools.get(**self.conan_data["sources"][self.version])
```suggestion
        tools.get(**self.conan_data["sources"][self.version],
                  destination=self._source_subfolder, strip_root=True)
```

2022-01-21 10:58 UTC, SpaceIm commented on recipes/cereal/all/conanfile.py
> +        rename(self, self.name + "-" + self.version, self._source_subfolder)
```suggestion
```

2022-01-21 10:58 UTC, SpaceIm commented on recipes/cereal/all/conanfile.py
> +from conan.tools.files import rename
```suggestion
```

2022-01-21 14:08 UTC, merged