Add hunspell/1.7.0
conan-io/conan-center-index pull request #9203
Opened 2022-01-31 17:49 UTC by friendlyanon

Specify library name and version:  **hunspell/1.7.0**

Issue: #8618

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-01-31 18:12 UTC, intelligide requested changes

2022-01-31 18:12 UTC, intelligide commented on recipes/hunspell/all/conanfile.py
> +        os.remove(h)
```suggestion
      os.remove(os.path.join(self.source_folder, "src", "hunspell", "hunvisapi.h"))
```

2022-01-31 18:17 UTC, friendlyanon commented on recipes/hunspell/all/conanfile.py
> +        os.remove(h)
PEP 8 requires 79 long lines.

2022-01-31 18:19 UTC, friendlyanon commented on recipes/hunspell/all/conanfile.py
> +    license = "???"
I was going to start a discussion on the license. The project has 3 licenses. What's the most appropriate to select in these cases? What's the rationale that you used to select LGPL?

2022-01-31 18:21 UTC, friendlyanon commented on recipes/hunspell/all/conanfile.py
> +    generators = ("cmake",)
What's the significance of this?

2022-01-31 18:22 UTC, intelligide commented on recipes/hunspell/all/conanfile.py
> +    license = "???"
`license` can be a tuple. :wink:

2022-01-31 23:09 UTC, intelligide commented on recipes/hunspell/all/conanfile.py
> +    generators = ("cmake",)
`generators` can be a tuple or a simple string. It is for more simplicity and readability if there is only one generator.

2022-01-31 23:15 UTC, intelligide commented on recipes/hunspell/all/test_package/conanfile.py
> +    generators = ("cmake", "cmake_find_package_multi")
conanfile attributes that are tuples also support simple elements without having to be in a tuple. So, `generators = ("cmake",)` and `generators = "cmake"` produce the same result. We use as few parentheses as possible to keep the recipes as simple and readable as possible.

2022-02-04 14:16 UTC, toge approved these changes

2022-02-21 09:28 UTC, SSE4 approved these changes

2022-03-02 09:26 UTC, uilianries commented on recipes/hunspell/all/conanfile.py
> +from conans.errors import ConanInvalidConfiguration
```suggestion
```

Ununsed

2022-03-02 09:26 UTC, uilianries approved these changes

2022-03-03 05:06 UTC, merged