Add freeimage/3.18.0
conan-io/conan-center-index pull request #9243
Opened 2022-02-03 07:31 UTC by pbreaux

Specify library name and version:  **freeimage/3.18.0**

This is a new addition to the ConanCenter.

Issue: #3027
---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-02-03 19:23 UTC, intelligide requested changes

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/test_package/conanfile.py
> +        if not tools.cross_building(self.settings):
```suggestion
        if not tools.cross_building(self):
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/test_package/conanfile.py
> +    settings = "os", "compiler", "build_type", "arch"
```suggestion
     settings = "os", "arch", "compiler", "build_type"
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +    license = "FreeImage", "GPL-3.0-or-later", "GPL-2.0-or-later", "FreeImage"
```suggestion
    license = "FreeImage", "GPL-3.0-or-later", "GPL-2.0-or-later"
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +        if bool(self.options.with_jpeg):
```suggestion
        if self.options.with_jpeg is not None:
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +        os.rename(extracted_dir, self._source_subfolder)
```suggestion
        tools.get(**self.conan_data["sources"][self.version],
                  destination=self._source_subfolder, strip_root=True)
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +
```suggestion

required_conan_version = ">=1.43.0"


```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +    topics = ("conan", "freeimage", "image", "decoding", "graphics")
```suggestion
    topics = ("freeimage", "image", "decoding", "graphics")
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +    exports_sources = ["CMakeLists.txt", "patches/*"]
```suggestion
```

2022-02-03 19:23 UTC, intelligide commented on recipes/freeimage/all/conanfile.py
> +
```suggestion

    def export_sources(self):
        self.copy("CMakeLists.txt")
        for patch in self.conan_data.get("patches", {}).get(self.version, []):
            self.copy(patch["patch_file"])

```

2022-02-09 11:05 UTC, uilianries approved these changes
- FreeImage does not have an official cmake file, but it refers the project as FreeImage, so I'm fine accepting it as cmake target
- The upstream offers a Makefile, which didn't work to me at first try with GCC11. So I'm fine accepting this cmake wrapper
- I see a big number of patches, and they are related to external dependencies only, so I'm fine with it.

LGTM

2022-02-15 00:26 UTC, pbreaux reviewed
Changes applied.

2022-02-16 08:38 UTC, uilianries approved these changes

2022-02-21 07:31 UTC, SSE4 approved these changes

2022-03-02 20:36 UTC, prince-chrismc commented on recipes/freeimage/all/conanfile.py
> +        self.cpp_info.names["pkg_config"] = "freeimage"
Missing new generators 🤷

2022-03-02 20:36 UTC, prince-chrismc approved these changes
Great work !!

2022-03-02 21:05 UTC, intelligide approved these changes

2022-03-03 05:26 UTC, merged