libschrift: add recipe
conan-io/conan-center-index pull request #9295
Opened 2022-02-07 18:57 UTC by toge

Specify library name and version:  **libschrift/0.10.1**

libschrift is true type font rendering library, alternatvie of freetype.

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-02-07 20:13 UTC, madebr approved these changes

2022-02-08 23:48 UTC, SpaceIm requested changes

2022-02-08 23:48 UTC, SpaceIm commented on recipes/libschrift/all/CMakeLists.txt
> +add_library(schrift source_subfolder/schrift.c)
```suggestion
cmake_minimum_required(VERSION 3.8)
project(schrift LANGUAGES C)

include(conanbuildinfo.cmake)
conan_basic_setup(KEEP_RPATHS)

include(GNUInstallDirs)

add_library(schrift source_subfolder/schrift.c)
target_compile_features(schrift PRIVATE c_std_99)
set_target_properties(schrift PROPERTIES
    PUBLIC_HEADER source_subfolder/schrift.h
    WINDOWS_EXPORT_ALL_SYMBOLS ON
)

install(
  TARGETS schrift
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
```

2022-02-08 23:48 UTC, SpaceIm commented on recipes/libschrift/all/conanfile.py
> +        self.copy(pattern="*.dylib", dst="lib", src="lib", keep_path=False)
```suggestion
        cmake = self._configure_cmake()
        cmake.install()
```

2022-02-09 15:39 UTC, SpaceIm commented
Opps, maybe restore `set(CMAKE_C_EXTENSIONS OFF)`?

2022-02-10 00:07 UTC, toge commented
@SpaceIm 
Oh, I forget it. 
I will fix later.

2022-02-10 07:58 UTC, SpaceIm approved these changes

2022-02-10 12:22 UTC, madebr approved these changes

2022-02-11 07:26 UTC, merged