bump xxsds-sdsl-lite version
conan-io/conan-center-index pull request #9444
Opened 2022-02-20 20:30 UTC by wolfee001

**xxsds-sdsl-lite/3.0.0**

add new version

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-02-21 07:06 UTC, SSE4 approved these changes

2022-02-25 17:23 UTC, wolfee001 commented
someone, please?

2022-03-02 12:51 UTC, uilianries submitted a review, later dismissed

2022-03-04 22:30 UTC, SpaceIm requested changes
simplify

2022-03-04 22:30 UTC, SpaceIm commented on recipes/xxsds-sdsl-lite/all/conanfile.py
>          tools.get(**source)
```suggestion
        tools.get(**self.conan_data["sources"][self.version],
                  destination=self._source_subfolder, strip_root=True)
```

2022-03-04 22:30 UTC, SpaceIm commented on recipes/xxsds-sdsl-lite/all/conanfile.py
> +            extracted_folder += self.version
```suggestion
```

2022-03-05 12:36 UTC, wolfee001 commented on recipes/xxsds-sdsl-lite/all/conanfile.py
>          tools.get(**source)
done

2022-03-05 12:36 UTC, wolfee001 commented on recipes/xxsds-sdsl-lite/all/conanfile.py
> +            extracted_folder += self.version
done

2022-03-07 16:21 UTC, uilianries commented on recipes/xxsds-sdsl-lite/all/conanfile.py
>          source = self.conan_data["sources"][self.version]
```suggestion
```

not used

2022-03-07 16:45 UTC, SpaceIm commented
add `required_conan_version = ">=1.33.0"` please

2022-03-08 08:30 UTC, uilianries approved these changes

2022-03-11 08:10 UTC, SSE4 approved these changes

2022-03-11 09:49 UTC, SpaceIm approved these changes

2022-03-11 10:09 UTC, merged