[approvaltests.cpp] Simplify test_package without extra requirements
conan-io/conan-center-index pull request #9586
Opened 2022-03-03 12:04 UTC by uilianries

Specify library name and version:  **ApprovalTests.CPP/any**

* Remove default_options from test_package
* Simplify test_package execution, no longer install extra dependencies
* Check compiler version under validate method

Related to https://github.com/conan-io/hooks/issues/287
---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-03-04 08:35 UTC, SSE4 commented
there are many changes... and we are no longer testing all the backends... I am tentative

2022-03-04 09:02 UTC, ericLemanissier commented on recipes/approvaltests.cpp/all/test_package/test_package.cpp
> +    std::cout << ApprovalTests::StringMaker::toString(42) << " is the answer."<< std::endl;
this is risky. We would better use a symbol from ApprovalTests library, or the linker will discard the object file, and we have no chance of detecting missing requirements/system requirements.

2022-03-04 09:07 UTC, uilianries commented
> there are many changes... and we are no longer testing all the backends... I am tentative

We are not testing the default package

2022-03-04 09:10 UTC, ericLemanissier reviewed
ApprovalTests::Grid::print is not inline so

2022-03-04 09:10 UTC, ericLemanissier commented on recipes/approvaltests.cpp/all/test_package/test_package.cpp
> +
```suggestion
#include "utilities/Grid.h"

```

2022-03-04 09:10 UTC, ericLemanissier commented on recipes/approvaltests.cpp/all/test_package/test_package.cpp
> +    std::cout << ApprovalTests::StringMaker::toString(42) << " is the answer."<< std::endl;
```suggestion
    std::cout << ApprovalTests::StringMaker::toString(42) << ApprovalTests::Grid::print(1, 1, " is the answer.")<< std::endl;
```
ApprovalTests::Grid::print is not inline, so we are sure that the library is not discarded

2022-03-04 09:28 UTC, uilianries commented
@ericLemanissier Thank you! Well observed!

2022-03-04 11:48 UTC, ericLemanissier commented on recipes/approvaltests.cpp/all/test_package/test_package.cpp
> +#include "utilities/Grid.h"
```suggestion
#include "ApprovalTests/utilities/Grid.h"
```

2022-03-07 18:23 UTC, uilianries commented
@ericLemanissier I needed to revert that change. `Grid` is a new feature, not available on previous versions

2022-03-07 18:24 UTC, ericLemanissier commented
Yes, I saw that. Approval was header only in early versions anyway

2022-03-15 03:23 UTC, prince-chrismc commented
CI looks stuck

2022-03-15 07:40 UTC, SSE4 commented
> CI looks stuck

it shouldn't block, it is just a secondary notification didn't arrive

2022-03-16 04:10 UTC, prince-chrismc approved these changes

2022-03-18 10:38 UTC, ericLemanissier approved these changes

2022-03-22 11:53 UTC, ericLemanissier approved these changes

2022-03-22 11:55 UTC, ericLemanissier requested changes
no test is actually run with this version of the PR. You may simply want to add back the small test you had in a previous version of this PR ?

2022-03-23 15:58 UTC, prince-chrismc approved these changes

2022-03-23 16:57 UTC, SSE4 approved these changes

2022-03-23 17:04 UTC, merged