backport s2n fix
conan-io/conan-center-index pull request #9677
Opened 2022-03-09 14:29 UTC by dvirtz

Specify library name and version:  **s2n/1.1.0** and **s2n/1.0.11**

backport upstream fix from https://github.com/aws/s2n-tls/pull/3219 to solve #8876

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

2022-03-09 14:37 UTC, uilianries commented
@dvirtz Github says this branch has a conflict. Could you rebase, please.

2022-03-09 17:12 UTC, SpaceIm requested changes

2022-03-09 17:12 UTC, SpaceIm commented on recipes/s2n/all/conandata.yml
> +
```suggestion
```

2022-03-09 17:12 UTC, SpaceIm commented on recipes/s2n/all/conanfile.py
> +    exports_sources = "CMakeLists.txt", "patches/**"
Prefer this pattern: https://github.com/conan-io/conan-center-index/blob/fe837d4775b00e8c1bf4372d0508db941aa0ba5b/recipes/aaplus/all/conanfile.py#L36-L39

2022-03-11 16:35 UTC, uilianries approved these changes
LGTM

2022-03-14 10:53 UTC, SSE4 approved these changes

2022-03-15 03:28 UTC, prince-chrismc approved these changes

2022-03-15 07:46 UTC, merged