detools: Binary delta encoding in C
conan-io/conan-center-index pull request #9734
Opened 2022-03-12 09:58 UTC by eerimoq

Add version 0.51.0.

Based on http://www.daemonology.net/bsdiff/ and HDiffPatch, with the following features:

* bsdiff algorithm.

* sequential or in-place (resumable) patch types.

* LZ4, LZMA, heatshrink or CRLE compression.

* Sequential patches allow streaming.

* Incremental apply patch, suitable for memory constrained embedded
  devices. Only the sequential patch type is supported.

* SA-IS or divsufsort instead of qsufsort for bsdiff.

2022-03-21 14:00 UTC, intelligide requested changes

2022-03-21 14:11 UTC, uilianries reviewed
It looks good, only need to shape the package ID

2022-03-21 18:49 UTC, eerimoq commented on recipes/detools/all/test_package/conanfile.py
> +            raise Exception("Patched file does not match new")
Why should the check be removed?

2022-03-21 18:56 UTC, intelligide commented on recipes/detools/all/test_package/conanfile.py
> +            raise Exception("Patched file does not match new")
the `test_package` is just there to validate that the package is correctly created, and that package consumers will be able to link against it. This is not meant to test if the library is working properly. It needs to be able to be built and run without link errors.

2022-03-21 20:01 UTC, intelligide submitted a review, later dismissed

2022-03-22 06:17 UTC, SSE4 submitted a review, later dismissed

2022-03-22 06:17 UTC, SSE4 commented on recipes/detools/all/test_package/test_package.c
> +    if (res == 2780) {
what is 2780? some constant, or comment could help to understand over the magic number

2022-03-22 08:49 UTC, uilianries approved these changes

2022-03-22 12:14 UTC, intelligide approved these changes

2022-03-23 16:58 UTC, SSE4 approved these changes

2022-03-23 17:24 UTC, merged